### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventHandler
  id: UnhandledExceptionEventHandler
  langs:
  - csharp
  name: UnhandledExceptionEventHandler
  nameWithType: UnhandledExceptionEventHandler
  fullName: Microsoft.VisualBasic.ApplicationServices.UnhandledExceptionEventHandler
  type: Delegate
  summary: "A kezelő mód a <xref uid=&quot;langword_csharp_My.Application.UnhandledException&quot; name=&quot;My.Application.UnhandledException&quot; href=&quot;&quot;> </xref> esemény."
  remarks: "A Visual Basic nem kell explicit módon használható ez a delegált. További információkért lásd: <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException>.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException>"
  example:
  - "<xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.UnhandledException?displayProperty=fullName>  \n  \n [Overview of the Visual Basic Application Model](~/add/includes/ajax-current-ext-md.md)"
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public delegate void UnhandledExceptionEventHandler(object sender, UnhandledExceptionEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
