### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  id: AssemblyReferenceType
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
  langs:
  - csharp
  name: AssemblyReferenceType
  nameWithType: AssemblyReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  type: Enum
  summary: "Ez az osztály egy szerelvényre mutató hivatkozás típusát jelöli."
  syntax:
    content: public enum AssemblyReferenceType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
  id: ClickOnceManifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  langs:
  - csharp
  name: ClickOnceManifest
  nameWithType: AssemblyReferenceType.ClickOnceManifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Megadja a ClickOnce jegyzék."
  syntax:
    content: ClickOnceManifest
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
  id: ManagedAssembly
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  langs:
  - csharp
  name: ManagedAssembly
  nameWithType: AssemblyReferenceType.ManagedAssembly
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Megadja a .NET-keretrendszer szerelvény."
  syntax:
    content: ManagedAssembly
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
  id: NativeAssembly
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  langs:
  - csharp
  name: NativeAssembly
  nameWithType: AssemblyReferenceType.NativeAssembly
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Megadja egy Win32 natív szerelvény."
  syntax:
    content: NativeAssembly
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
  id: Unspecified
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  langs:
  - csharp
  name: Unspecified
  nameWithType: AssemblyReferenceType.Unspecified
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
  type: Field
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Szerelvény típus nincs megadva, és határozza meg a <xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.UpdateFileInfo*>metódus.</xref:Microsoft.Build.Tasks.Deployment.ManifestUtilities.Manifest.UpdateFileInfo*>"
  syntax:
    content: Unspecified
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  isExternal: false
  name: ClickOnceManifest
  nameWithType: AssemblyReferenceType.ClickOnceManifest
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ClickOnceManifest
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: AssemblyReferenceType
  nameWithType: AssemblyReferenceType
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  isExternal: false
  name: ManagedAssembly
  nameWithType: AssemblyReferenceType.ManagedAssembly
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.ManagedAssembly
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  isExternal: false
  name: NativeAssembly
  nameWithType: AssemblyReferenceType.NativeAssembly
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.NativeAssembly
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType
  isExternal: false
  name: Unspecified
  nameWithType: AssemblyReferenceType.Unspecified
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.AssemblyReferenceType.Unspecified
