### YamlMime:ManagedReference
items:
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  id: StartupNextInstanceEventArgs
  children:
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  - Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  langs:
  - csharp
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  type: Class
  summary: "Adja meg az adatait a <xref uid=&quot;langword_csharp_My.Application.StartupNextInstance&quot; name=&quot;My.Application.StartupNextInstance&quot; href=&quot;&quot;> </xref> esemény."
  remarks: "A <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>esemény akkor következik be, amikor egy további példányt egy egypéldányos alkalmazás elindul, a Visual Basic alkalmazás modell használatával.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> További információkért lásd: [a Visual Basic alkalmazás modell áttekintése](~/add/includes/ajax-current-ext-md.md).       StartupNextInstanceEventArgs későbbi alkalmazáspéldány parancssori argumentumokat tartalmaz, és azt jelzi, hogy az első alkalmazáspéldány kell hozni az előtérben a kivételkezelő kiürítése."
  syntax:
    content: >-
      [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]

      public class StartupNextInstanceEventArgs : EventArgs
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  id: '#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)'
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  type: Constructor
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Egy új példányát inicializálja a <xref href=&quot;Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs&quot;> </xref> osztály."
  remarks: "A <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>esemény akkor következik be, amikor egy további példányt egy egypéldányos alkalmazás elindul, a Visual Basic alkalmazás modell használatával.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> További információkért lásd: [a Visual Basic alkalmazás modell áttekintése](~/add/includes/ajax-current-ext-md.md).       <xref:Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs>az ezt követő alkalmazáspéldány parancssori argumentumokat tartalmaz, és azt jelzi, hogy az első alkalmazáspéldány kell hozni az előtérben a kivételkezelő kiürítése.</xref:Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs>"
  syntax:
    content: public StartupNextInstanceEventArgs (System.Collections.ObjectModel.ReadOnlyCollection<string> args, bool bringToForegroundFlag);
    parameters:
    - id: args
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; objektum, amely tartalmazza az ezt követő alkalmazáspéldány parancssori argumentumokat."
    - id: bringToForegroundFlag
      type: System.Boolean
      description: "A <xref:System.Boolean>, amely azt jelzi, hogy az első alkalmazáspéldány kell hozni az előtérben a kivételkezelő kiürítése.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  id: BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Azt jelzi, hogy az első alkalmazáspéldány kell hozni az előtérben a kivételkezelő kiürítése."
  remarks: "A Visual Basic Alkalmazásmodellt. Ez a tulajdonság értékének ellenőrzi a kezelők futtatása után a <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>esemény.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> Ha a BringToForeground tulajdonság `True`, az első alkalmazáspéldány kerüléséig az előtérbe. Ellenkező esetben az első alkalmazáspéldány marad, ha volt. További információkért lásd: [a Visual Basic alkalmazás modell áttekintése](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public bool BringToForeground { get; set; }
    return:
      type: System.Boolean
      description: "A <xref:System.Boolean>, amely azt jelzi, hogy az első alkalmazáspéldány kell hozni az előtérben a kivételkezelő kiürítése.</xref:System.Boolean>"
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  id: CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  langs:
  - csharp
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  type: Property
  assemblies:
  - Microsoft.VisualBasic
  namespace: Microsoft.VisualBasic.ApplicationServices
  summary: "Lekérdezi az ezt követő alkalmazáspéldány parancssori argumentumokat."
  remarks: "A <xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance>esemény akkor következik be, amikor egy további példányt egy egypéldányos alkalmazás elindul, a Visual Basic alkalmazás modell használatával.</xref:Microsoft.VisualBasic.ApplicationServices.WindowsFormsApplicationBase.StartupNextInstance> További információkért lásd: [a Visual Basic alkalmazás modell áttekintése](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public System.Collections.ObjectModel.ReadOnlyCollection<string> CommandLine { get; }
    return:
      type: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
      description: "A &lt;xref:System.Collections.ObjectModel.ReadOnlyCollection%601&gt; objektum, amely tartalmazza az ezt követő alkalmazáspéldány parancssori argumentumokat."
  overload: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor(System.Collections.ObjectModel.ReadOnlyCollection{System.String},System.Boolean)
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.StartupNextInstanceEventArgs(ReadOnlyCollection<String>,Boolean)
- uid: System.Collections.ObjectModel.ReadOnlyCollection{System.String}
  parent: System.Collections.ObjectModel
  isExternal: true
  name: ReadOnlyCollection<String>
  nameWithType: ReadOnlyCollection<String>
  fullName: System.Collections.ObjectModel.ReadOnlyCollection<System.String>
  spec.csharp:
  - uid: System.Collections.ObjectModel.ReadOnlyCollection`1
    name: ReadOnlyCollection
    nameWithType: ReadOnlyCollection
    fullName: ReadOnlyCollection<System.String>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
  fullName: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.#ctor*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: StartupNextInstanceEventArgs
  nameWithType: StartupNextInstanceEventArgs.StartupNextInstanceEventArgs
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.BringToForeground*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: BringToForeground
  nameWithType: StartupNextInstanceEventArgs.BringToForeground
- uid: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs.CommandLine*
  parent: Microsoft.VisualBasic.ApplicationServices.StartupNextInstanceEventArgs
  isExternal: false
  name: CommandLine
  nameWithType: StartupNextInstanceEventArgs.CommandLine
