### YamlMime:ManagedReference
items:
- uid: System.Configuration.ContextInformation
  id: ContextInformation
  children:
  - System.Configuration.ContextInformation.GetSection(System.String)
  - System.Configuration.ContextInformation.HostingContext
  - System.Configuration.ContextInformation.IsMachineLevel
  langs:
  - csharp
  name: ContextInformation
  nameWithType: ContextInformation
  fullName: System.Configuration.ContextInformation
  type: Class
  summary: "Magában foglalja a környezet adatainak, amelyhez társítva van egy <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> objektum. Ez az osztály nem örökölhető."
  remarks: "A ContextInformation objektum részletesen bemutatja a környezetben a konfigurációt az elemre vonatkozó. Használhatja például a <xref:System.Configuration.ContextInformation.IsMachineLevel%2A>tulajdonság határozza meg hogy a <xref:System.Configuration.ConfigurationElement>volt a Machine.config fájlban állítsa be, illetve azt is meghatározhatja, melyik hierarchiába egy <xref:System.Configuration.ConfigurationElement>használatával tartozik a <xref:System.Configuration.ContextInformation.HostingContext%2A>tulajdonság.</xref:System.Configuration.ContextInformation.HostingContext%2A> </xref:System.Configuration.ConfigurationElement> </xref:System.Configuration.ConfigurationElement> </xref:System.Configuration.ContextInformation.IsMachineLevel%2A>"
  example:
  - "The following code example demonstrates how to use the ContextInformation type.  \n  \n [!code-vb[System.Configuration.ContextInformation#1](~/add/codesnippet/visualbasic/t-system.configuration.c_0_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#1](~/add/codesnippet/csharp/t-system.configuration.c_0_1.cs)]"
  syntax:
    content: public sealed class ContextInformation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  id: GetSection(System.String)
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "A megadott szakasz neve alapján a szakasz konfigurációs információkat tartalmazó objektum biztosít."
  remarks: "Belül a konfigurációs szakasz meghatározásakor vegye figyelembe, hogy a konfigurációs szakasz neve kis-és nagybetűket."
  syntax:
    content: public object GetSection (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "A konfigurációs szakasz neve."
    return:
      type: System.Object
      description: "A megadott szakasz konfigurációját belül tartalmazó objektum."
  overload: System.Configuration.ContextInformation.GetSection*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.HostingContext
  id: HostingContext
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi a környezetben, ahol a konfigurációs tulajdonságának kiértékelése megtörténik a környezetében."
  remarks: "A lehetséges HostingContext érték <xref:System.Web.Configuration.WebContext>, <xref:System.Configuration.ExeContext>, vagy `null`.</xref:System.Configuration.ExeContext> </xref:System.Web.Configuration.WebContext>"
  example:
  - "The following code example demonstrates how to use the HostingContext property.  \n  \n [!code-vb[System.Configuration.ContextInformation#3](~/add/codesnippet/visualbasic/p-system.configuration.c_46_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#3](~/add/codesnippet/csharp/p-system.configuration.c_46_1.cs)]"
  syntax:
    content: public object HostingContext { get; }
    return:
      type: System.Object
      description: "Adja meg a környezetben, ahol a konfigurációs tulajdonságának kiértékelése megtörténik objektum."
  overload: System.Configuration.ContextInformation.HostingContext*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ContextInformation.IsMachineLevel
  id: IsMachineLevel
  parent: System.Configuration.ContextInformation
  langs:
  - csharp
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Adja meg, hogy a konfigurációs tulajdonságának kiértékelése megtörténik a számítógép konfigurációs szintjén érték beolvasása."
  remarks: "Ha visszaadott IsMachineLevel értéke `false`, használja a <xref:System.Configuration.ContextInformation.HostingContext%2A>tulajdonság a konfigurációs hierarchiában szintjének.</xref:System.Configuration.ContextInformation.HostingContext%2A>"
  example:
  - "The following code example demonstrates how to use the <xref:System.Configuration.ContextInformation.HostingContext%2A> property.  \n  \n [!code-vb[System.Configuration.ContextInformation#2](~/add/codesnippet/visualbasic/p-system.configuration.c_7_1.vb)]\n [!code-cs[System.Configuration.ContextInformation#2](~/add/codesnippet/csharp/p-system.configuration.c_7_1.cs)]"
  syntax:
    content: public bool IsMachineLevel { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a konfigurációs tulajdonságának kiértékelése megtörténik a számítógép konfigurációs szintjén; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ContextInformation.IsMachineLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ContextInformation.GetSection(System.String)
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection(String)
  nameWithType: ContextInformation.GetSection(String)
  fullName: System.Configuration.ContextInformation.GetSection(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ContextInformation.HostingContext
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
  fullName: System.Configuration.ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
  fullName: System.Configuration.ContextInformation.IsMachineLevel
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.ContextInformation.GetSection*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: GetSection
  nameWithType: ContextInformation.GetSection
- uid: System.Configuration.ContextInformation.HostingContext*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: HostingContext
  nameWithType: ContextInformation.HostingContext
- uid: System.Configuration.ContextInformation.IsMachineLevel*
  parent: System.Configuration.ContextInformation
  isExternal: false
  name: IsMachineLevel
  nameWithType: ContextInformation.IsMachineLevel
