### YamlMime:ManagedReference
items:
- uid: System.Configuration.ProtectedConfigurationProviderCollection
  id: ProtectedConfigurationProviderCollection
  children:
  - System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  - System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  - System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  langs:
  - csharp
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection
  fullName: System.Configuration.ProtectedConfigurationProviderCollection
  type: Class
  summary: "Egy gyűjteményét biztosítja <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objektumok."
  remarks: "A <xref:System.Configuration.ProtectedConfiguration.Providers%2A>tulajdonsága a <xref:System.Configuration.ProtectedConfiguration>osztály gyűjteményei ProtectedConfigurationProviderCollection, az alkalmazás számára elérhető összes védett konfigurációs szolgáltató.</xref:System.Configuration.ProtectedConfiguration> </xref:System.Configuration.ProtectedConfiguration.Providers%2A>       A szakaszok egy konfigurációs fájl, amelyet az alkalmazás bizalmas információk védelme érdekében titkosíthatók. Ez növeli a biztonsági azáltal, hogy jogosulatlan hozzáférés nehéz, még akkor is, ha egy támadó hozzáfér a konfigurációs fájlban.       A .NET-keretrendszer két védett konfigurációszolgáltatók a konfigurációs fájlok titkosítására használható tartalmaz: a <xref:System.Configuration.RsaProtectedConfigurationProvider>osztály, amely használja a <xref:System.Security.Cryptography.RSACryptoServiceProvider>osztály konfigurációs szakasz titkosítása és a <xref:System.Configuration.DpapiProtectedConfigurationProvider>osztály, amely a Windows Data Protection API (DPAPI) használja a konfigurációs szakasz titkosítása.</xref:System.Configuration.DpapiProtectedConfigurationProvider> </xref:System.Security.Cryptography.RSACryptoServiceProvider> </xref:System.Configuration.RsaProtectedConfigurationProvider>       Lehetséges, hogy a követelmény, hogy titkosítsa a bizalmas adatokat az RSA vagy a DPAPI-t szolgáltató eltérő algoritmus használatával. Ebben az esetben a saját egyéni védett konfigurációs szolgáltatója hozhat létre. A <xref:System.Configuration.ProtectedConfigurationProvider>osztály egy absztrakt alaposztály öröklő meg kell létrehozni a saját védett konfigurációszolgáltatót.</xref:System.Configuration.ProtectedConfigurationProvider>       Védett konfigurációjával kapcsolatos további információkért lásd: [titkosított konfigurációs információt használatával védett konfigurációs](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: 'public class ProtectedConfigurationProviderCollection : System.Configuration.Provider.ProviderCollection'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderCollection
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderCollection.Clear
  - System.Configuration.Provider.ProviderCollection.CopyTo(System.Configuration.Provider.ProviderBase[],System.Int32)
  - System.Configuration.Provider.ProviderCollection.Count
  - System.Configuration.Provider.ProviderCollection.GetEnumerator
  - System.Configuration.Provider.ProviderCollection.IsSynchronized
  - System.Configuration.Provider.ProviderCollection.Remove(System.String)
  - System.Configuration.Provider.ProviderCollection.SetReadOnly
  - System.Configuration.Provider.ProviderCollection.SyncRoot
  - System.Configuration.Provider.ProviderCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  id: '#ctor'
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: ProtectedConfigurationProviderCollection()
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.ProtectedConfigurationProviderCollection&quot;> </xref> osztály az alapértelmezett beállításokkal."
  remarks: "A ProtectedConfigurationProviderCollection konstruktor nem célja, hogy közvetlenül a kódból használni. Az ASP.NET konfigurációs rendszer nevezik. Az <xref:System.Configuration.ProtectedConfigurationProviderCollection>osztály <xref:System.Configuration.ProtectedConfiguration.Providers%2A>a <xref:System.Configuration.ProtectedConfiguration>osztály</xref:System.Configuration.ProtectedConfiguration> tulajdonságának</xref:System.Configuration.ProtectedConfiguration.Providers%2A> használatával</xref:System.Configuration.ProtectedConfigurationProviderCollection> kaphat"
  syntax:
    content: public ProtectedConfigurationProviderCollection ();
    parameters: []
  overload: System.Configuration.ProtectedConfigurationProviderCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  id: Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: Add(ProviderBase)
  nameWithType: ProtectedConfigurationProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add(ProviderBase)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Hozzáad egy <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objektum a gyűjteményhez."
  syntax:
    content: public override void Add (System.Configuration.Provider.ProviderBase provider);
    parameters:
    - id: provider
      type: System.Configuration.Provider.ProviderBase
      description: "A <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objektum hozzáadására a gyűjteményhez."
  overload: System.Configuration.ProtectedConfigurationProviderCollection.Add*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>provider</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "<code>provider</code>nem egy <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objektum."
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "The <xref href=\"System.Configuration.ProtectedConfigurationProvider\"></xref> object to add already exists in the collection.  \n  \n \\- or -  \n  \n The collection is read-only."
  platform:
  - net462
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  id: Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: ProtectedConfigurationProviderCollection.Item(String)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item(String)
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> a gyűjtemény a megadott nevű objektum."
  syntax:
    content: public System.Configuration.ProtectedConfigurationProvider this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "A neve egy <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objektum a gyűjteményben."
    return:
      type: System.Configuration.ProtectedConfigurationProvider
      description: "A <xref href=&quot;System.Configuration.ProtectedConfigurationProvider&quot;> </xref> objektum a megadott névvel vagy <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> Ha nincs ilyen nevű objektum."
  overload: System.Configuration.ProtectedConfigurationProviderCollection.Item*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderCollection
  isExternal: false
  name: System.Configuration.Provider.ProviderCollection
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: ProtectedConfigurationProviderCollection()
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection()
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add(System.Configuration.Provider.ProviderBase)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add(ProviderBase)
  nameWithType: ProtectedConfigurationProviderCollection.Add(ProviderBase)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Add(ProviderBase)
- uid: System.Configuration.Provider.ProviderBase
  parent: System.Configuration.Provider
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item(System.String)
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item(String)
  nameWithType: ProtectedConfigurationProviderCollection.Item(String)
  fullName: System.Configuration.ProtectedConfigurationProviderCollection.Item(String)
- uid: System.Configuration.ProtectedConfigurationProvider
  parent: System.Configuration
  isExternal: false
  name: ProtectedConfigurationProvider
  nameWithType: ProtectedConfigurationProvider
  fullName: System.Configuration.ProtectedConfigurationProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ProtectedConfigurationProviderCollection.#ctor*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: ProtectedConfigurationProviderCollection
  nameWithType: ProtectedConfigurationProviderCollection.ProtectedConfigurationProviderCollection
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Add*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Add
  nameWithType: ProtectedConfigurationProviderCollection.Add
- uid: System.Configuration.ProtectedConfigurationProviderCollection.Item*
  parent: System.Configuration.ProtectedConfigurationProviderCollection
  isExternal: false
  name: Item
  nameWithType: ProtectedConfigurationProviderCollection.Item
