### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory
  id: ApplicationServicesHostFactory
  children:
  - System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  - System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  langs:
  - csharp
  name: ApplicationServicesHostFactory
  nameWithType: ApplicationServicesHostFactory
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory
  type: Class
  summary: "A gyári osztály, amely létrehozza a hitelesítési szolgáltatás, a szerepkör-szolgáltatás és a profil szolgáltatás felügyelt üzemeltetési környezetben biztosít."
  remarks: "A gyári osztály példányainak létrehozásához lehetőséget biztosít a <xref:System.Web.ApplicationServices.AuthenticationService>, <xref:System.Web.ApplicationServices.ProfileService>, és <xref:System.Web.ApplicationServices.RoleService>osztályok.</xref:System.Web.ApplicationServices.RoleService> </xref:System.Web.ApplicationServices.ProfileService> </xref:System.Web.ApplicationServices.AuthenticationService>       A gyári osztály használatához hozzon létre egy WCF-szolgáltatások (.svc kiterjesztésű) fájlt, és adja meg a ApplicationServicesHostFactory a `ServiceHosting` attribútuma a `@ ServiceHost` direktívát."
  example:
  - "The following example shows how to specify ApplicationServicesHostFactory in the `@ ServiceHost` directive of a .svc file to configure the authentication service.  \n  \n```c#  \n<%@ ServiceHost   \n  Language=\"C#\"   \n  Service=\"System.Web.ApplicationServices.AuthenticationService\"   \n  Factory=\"System.Web.ApplicationServices.ApplicationServicesHostFactory\"   \n%>  \n  \n```  \n  \n```vb  \n<%@ ServiceHost   \n  Language=\"VB\"   \n  Service=\"System.Web.ApplicationServices.AuthenticationService\"   \n  Factory=\"System.Web.ApplicationServices.ApplicationServicesHostFactory\"   \n%>  \n```"
  syntax:
    content: 'public class ApplicationServicesHostFactory : System.ServiceModel.Activation.ServiceHostFactory'
  inheritance:
  - System.ServiceModel.Activation.ServiceHostFactory
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  id: '#ctor'
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  langs:
  - csharp
  name: ApplicationServicesHostFactory()
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.ApplicationServices.ApplicationServicesHostFactory&quot;> </xref> osztály."
  syntax:
    content: public ApplicationServicesHostFactory ();
    parameters: []
  overload: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  id: CreateServiceHost(System.Type,System.Uri[])
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  langs:
  - csharp
  name: CreateServiceHost(Type,Uri[])
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  type: Method
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Létrehoz egy új, a szolgáltatás osztály, amely rendelkezik a megadott alap-címeket."
  remarks: "Általában ez a metódus neve automatikusan [!INCLUDE[vsindigo](~/add/includes/vsindigo-md.md)] szolgáltatás részeként aktiválás, és nem kell manuálisan hívja meg a metódust."
  syntax:
    content: protected override System.ServiceModel.ServiceHost CreateServiceHost (Type serviceType, Uri[] baseAddresses);
    parameters:
    - id: serviceType
      type: System.Type
      description: "A szolgáltatásgazda létrehozása típusa."
    - id: baseAddresses
      type: System.Uri[]
      description: "A szolgáltatás alapcíme tömbjét."
    return:
      type: System.ServiceModel.ServiceHost
      description: "A <xref href=&quot;System.ServiceModel.ServiceHost&quot;> </xref> szolgáltatás, amely rendelkezik a megadott alap-címeket típusú példány."
  overload: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Activation.ServiceHostFactory
  isExternal: false
  name: System.ServiceModel.Activation.ServiceHostFactory
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: ApplicationServicesHostFactory()
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory()
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.ApplicationServicesHostFactory()
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(System.Type,System.Uri[])
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: CreateServiceHost(Type,Uri[])
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
  fullName: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost(Type,Uri[])
- uid: System.ServiceModel.ServiceHost
  parent: System.ServiceModel
  isExternal: false
  name: ServiceHost
  nameWithType: ServiceHost
  fullName: System.ServiceModel.ServiceHost
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Uri[]
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri[]
  spec.csharp:
  - uid: System.Uri
    name: Uri
    nameWithType: Uri
    fullName: Uri[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.#ctor*
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: ApplicationServicesHostFactory
  nameWithType: ApplicationServicesHostFactory.ApplicationServicesHostFactory
- uid: System.Web.ApplicationServices.ApplicationServicesHostFactory.CreateServiceHost*
  parent: System.Web.ApplicationServices.ApplicationServicesHostFactory
  isExternal: false
  name: CreateServiceHost
  nameWithType: ApplicationServicesHostFactory.CreateServiceHost
