### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.DiagnosticSection
  id: DiagnosticSection
  children:
  - System.ServiceModel.Configuration.DiagnosticSection.#ctor
  - System.ServiceModel.Configuration.DiagnosticSection.EndToEndTracing
  - System.ServiceModel.Configuration.DiagnosticSection.EtwProviderId
  - System.ServiceModel.Configuration.DiagnosticSection.MessageLogging
  - System.ServiceModel.Configuration.DiagnosticSection.PerformanceCounters
  - System.ServiceModel.Configuration.DiagnosticSection.Properties
  - System.ServiceModel.Configuration.DiagnosticSection.WmiProviderEnabled
  langs:
  - csharp
  name: DiagnosticSection
  nameWithType: DiagnosticSection
  fullName: System.ServiceModel.Configuration.DiagnosticSection
  type: Class
  summary: "A konfigurációs szakaszban határozza meg a beállításokat egy rendszergazda a futásidejű ellenőrzés és a vezérlés használható jelöli."
  syntax:
    content: 'public sealed class DiagnosticSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DiagnosticSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.DiagnosticSection
  langs:
  - csharp
  name: DiagnosticSection()
  nameWithType: DiagnosticSection.DiagnosticSection()
  fullName: System.ServiceModel.Configuration.DiagnosticSection.DiagnosticSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.DiagnosticSection&quot;> </xref> osztály."
  syntax:
    content: public DiagnosticSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.DiagnosticSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DiagnosticSection.EndToEndTracing
  id: EndToEndTracing
  parent: System.ServiceModel.Configuration.DiagnosticSection
  langs:
  - csharp
  name: EndToEndTracing
  nameWithType: DiagnosticSection.EndToEndTracing
  fullName: System.ServiceModel.Configuration.DiagnosticSection.EndToEndTracing
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi a megadott végpont nyomkövetés konfigurációs beállításokat egy <xref href=&quot;System.ServiceModel.Configuration.EndToEndTracingElement&quot;> </xref> példány."
  syntax:
    content: public System.ServiceModel.Configuration.EndToEndTracingElement EndToEndTracing { get; }
    return:
      type: System.ServiceModel.Configuration.EndToEndTracingElement
      description: "Beolvasása <xref href=&quot;System.ServiceModel.Configuration.EndToEndTracingElement&quot;> </xref>, amely végpont nyomkövetés-konfigurációs beállításait tartalmazza."
  overload: System.ServiceModel.Configuration.DiagnosticSection.EndToEndTracing*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DiagnosticSection.EtwProviderId
  id: EtwProviderId
  parent: System.ServiceModel.Configuration.DiagnosticSection
  langs:
  - csharp
  name: EtwProviderId
  nameWithType: DiagnosticSection.EtwProviderId
  fullName: System.ServiceModel.Configuration.DiagnosticSection.EtwProviderId
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekéri az esemény-nyomkövetési szolgáltató, amely beírja a ETW-munkamenet azonosítóját."
  syntax:
    content: public string EtwProviderId { get; set; }
    return:
      type: System.String
      description: "<xref:System.String>.</xref:System.String> Beolvasása"
  overload: System.ServiceModel.Configuration.DiagnosticSection.EtwProviderId*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DiagnosticSection.MessageLogging
  id: MessageLogging
  parent: System.ServiceModel.Configuration.DiagnosticSection
  langs:
  - csharp
  name: MessageLogging
  nameWithType: DiagnosticSection.MessageLogging
  fullName: System.ServiceModel.Configuration.DiagnosticSection.MessageLogging
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Bemutatja a beállításait [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] üzenetek naplózása."
  syntax:
    content: public System.ServiceModel.Configuration.MessageLoggingElement MessageLogging { get; }
    return:
      type: System.ServiceModel.Configuration.MessageLoggingElement
      description: "A <xref href=&quot;System.ServiceModel.Configuration.MessageLoggingElement&quot;> </xref> , amely bemutatja a beállításait [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] üzenetek naplózása."
  overload: System.ServiceModel.Configuration.DiagnosticSection.MessageLogging*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DiagnosticSection.PerformanceCounters
  id: PerformanceCounters
  parent: System.ServiceModel.Configuration.DiagnosticSection
  langs:
  - csharp
  name: PerformanceCounters
  nameWithType: DiagnosticSection.PerformanceCounters
  fullName: System.ServiceModel.Configuration.DiagnosticSection.PerformanceCounters
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely meghatározza, hogy engedélyezve vannak-e a teljesítményszámlálók a szerelvény."
  syntax:
    content: public System.ServiceModel.Diagnostics.PerformanceCounterScope PerformanceCounters { get; set; }
    return:
      type: System.ServiceModel.Diagnostics.PerformanceCounterScope
      description: "Egy érvényes <xref href=&quot;System.ServiceModel.Diagnostics.PerformanceCounterScope&quot;> </xref> érték, amely meghatározza, hogy milyen típusú teljesítmény teljesítményszámlálók a szerelvény engedélyezve vannak."
  overload: System.ServiceModel.Configuration.DiagnosticSection.PerformanceCounters*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DiagnosticSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.DiagnosticSection
  langs:
  - csharp
  name: Properties
  nameWithType: DiagnosticSection.Properties
  fullName: System.ServiceModel.Configuration.DiagnosticSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.DiagnosticSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.DiagnosticSection.WmiProviderEnabled
  id: WmiProviderEnabled
  parent: System.ServiceModel.Configuration.DiagnosticSection
  langs:
  - csharp
  name: WmiProviderEnabled
  nameWithType: DiagnosticSection.WmiProviderEnabled
  fullName: System.ServiceModel.Configuration.DiagnosticSection.WmiProviderEnabled
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely megadja, hogy engedélyezve van-e a szerelvény a WMI-szolgáltatótól."
  remarks: "A WMI-szolgáltató szükség a felhasználók számára a vizsgálati és ellenőrzési funkciók a futásidejű eléréséhez [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)]."
  syntax:
    content: public bool WmiProviderEnabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha engedélyezve van a szerelvényben a WMI-szolgáltatótól; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.DiagnosticSection.WmiProviderEnabled*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.DiagnosticSection.#ctor
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: DiagnosticSection()
  nameWithType: DiagnosticSection.DiagnosticSection()
  fullName: System.ServiceModel.Configuration.DiagnosticSection.DiagnosticSection()
- uid: System.ServiceModel.Configuration.DiagnosticSection.EndToEndTracing
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: EndToEndTracing
  nameWithType: DiagnosticSection.EndToEndTracing
  fullName: System.ServiceModel.Configuration.DiagnosticSection.EndToEndTracing
- uid: System.ServiceModel.Configuration.EndToEndTracingElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: EndToEndTracingElement
  nameWithType: EndToEndTracingElement
  fullName: System.ServiceModel.Configuration.EndToEndTracingElement
- uid: System.ServiceModel.Configuration.DiagnosticSection.EtwProviderId
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: EtwProviderId
  nameWithType: DiagnosticSection.EtwProviderId
  fullName: System.ServiceModel.Configuration.DiagnosticSection.EtwProviderId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.DiagnosticSection.MessageLogging
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: MessageLogging
  nameWithType: DiagnosticSection.MessageLogging
  fullName: System.ServiceModel.Configuration.DiagnosticSection.MessageLogging
- uid: System.ServiceModel.Configuration.MessageLoggingElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: MessageLoggingElement
  nameWithType: MessageLoggingElement
  fullName: System.ServiceModel.Configuration.MessageLoggingElement
- uid: System.ServiceModel.Configuration.DiagnosticSection.PerformanceCounters
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: PerformanceCounters
  nameWithType: DiagnosticSection.PerformanceCounters
  fullName: System.ServiceModel.Configuration.DiagnosticSection.PerformanceCounters
- uid: System.ServiceModel.Diagnostics.PerformanceCounterScope
  parent: System.ServiceModel.Diagnostics
  isExternal: false
  name: PerformanceCounterScope
  nameWithType: PerformanceCounterScope
  fullName: System.ServiceModel.Diagnostics.PerformanceCounterScope
- uid: System.ServiceModel.Configuration.DiagnosticSection.Properties
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: Properties
  nameWithType: DiagnosticSection.Properties
  fullName: System.ServiceModel.Configuration.DiagnosticSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.DiagnosticSection.WmiProviderEnabled
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: WmiProviderEnabled
  nameWithType: DiagnosticSection.WmiProviderEnabled
  fullName: System.ServiceModel.Configuration.DiagnosticSection.WmiProviderEnabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.DiagnosticSection.#ctor*
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: DiagnosticSection
  nameWithType: DiagnosticSection.DiagnosticSection
- uid: System.ServiceModel.Configuration.DiagnosticSection.EndToEndTracing*
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: EndToEndTracing
  nameWithType: DiagnosticSection.EndToEndTracing
- uid: System.ServiceModel.Configuration.DiagnosticSection.EtwProviderId*
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: EtwProviderId
  nameWithType: DiagnosticSection.EtwProviderId
- uid: System.ServiceModel.Configuration.DiagnosticSection.MessageLogging*
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: MessageLogging
  nameWithType: DiagnosticSection.MessageLogging
- uid: System.ServiceModel.Configuration.DiagnosticSection.PerformanceCounters*
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: PerformanceCounters
  nameWithType: DiagnosticSection.PerformanceCounters
- uid: System.ServiceModel.Configuration.DiagnosticSection.Properties*
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: Properties
  nameWithType: DiagnosticSection.Properties
- uid: System.ServiceModel.Configuration.DiagnosticSection.WmiProviderEnabled*
  parent: System.ServiceModel.Configuration.DiagnosticSection
  isExternal: false
  name: WmiProviderEnabled
  nameWithType: DiagnosticSection.WmiProviderEnabled
