### YamlMime:ManagedReference
items:
- uid: System.Web.PreApplicationStartMethodAttribute
  id: PreApplicationStartMethodAttribute
  children:
  - System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  - System.Web.PreApplicationStartMethodAttribute.MethodName
  - System.Web.PreApplicationStartMethodAttribute.Type
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute
  fullName: System.Web.PreApplicationStartMethodAttribute
  type: Class
  summary: "Bővített támogatást nyújt az alkalmazás indításakor."
  remarks: "-Nincs garancia a rendelés, amelyben az alkalmazás szerelvényben definiált start módszerek nevezzük. Ennek eredményeképpen minden egyes regisztrált start metódus elkülönítve fusson kell megírni, és hatásai más regisztrált start módszer nem függ.       Attribútumok használatával kapcsolatos további információkért lásd: [attribútumok](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Assembly, AllowMultiple=true)]

      public sealed class PreApplicationStartMethodAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  id: '#ctor(System.Type,System.String)'
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.PreApplicationStartMethodAttribute&quot;> </xref> osztály."
  remarks: "A metódus által hivatkozott a `methodName` paraméter nyilvánosnak kell lennie, és egy példánymetódus vagy a statikus metódus lehet."
  syntax:
    content: public PreApplicationStartMethodAttribute (Type type, string methodName);
    parameters:
    - id: type
      type: System.Type
      description: "Az indítási metódus típusú leíró objektum..."
    - id: methodName
      type: System.String
      description: "Nincs visszatérési értéke üres paraméter aláírás."
  overload: System.Web.PreApplicationStartMethodAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  id: MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Lekérdezi a társított indítási módszert."
  syntax:
    content: public string MethodName { get; }
    return:
      type: System.String
      description: "A társított indítási metódus nevét tartalmazó karakterlánc."
  overload: System.Web.PreApplicationStartMethodAttribute.MethodName*
  exceptions: []
  platform:
  - net462
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  id: Type
  parent: System.Web.PreApplicationStartMethodAttribute
  langs:
  - csharp
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web
  summary: "Lekérdezi a társított indítási metódus által visszaadott típus."
  syntax:
    content: public Type Type { get; }
    return:
      type: System.Type
      description: "Ismerteti az indítási metódus típusú objektum."
  overload: System.Web.PreApplicationStartMethodAttribute.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor(System.Type,System.String)
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute(Type,String)
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
  fullName: System.Web.PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute(Type,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
  fullName: System.Web.PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
  fullName: System.Web.PreApplicationStartMethodAttribute.Type
- uid: System.Web.PreApplicationStartMethodAttribute.#ctor*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: PreApplicationStartMethodAttribute
  nameWithType: PreApplicationStartMethodAttribute.PreApplicationStartMethodAttribute
- uid: System.Web.PreApplicationStartMethodAttribute.MethodName*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: MethodName
  nameWithType: PreApplicationStartMethodAttribute.MethodName
- uid: System.Web.PreApplicationStartMethodAttribute.Type*
  parent: System.Web.PreApplicationStartMethodAttribute
  isExternal: false
  name: Type
  nameWithType: PreApplicationStartMethodAttribute.Type
