### YamlMime:ManagedReference
items:
- uid: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  id: DataServicesReplaceFunctionFeature
  children:
  - System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.#ctor
  - System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.Enable
  langs:
  - csharp
  name: DataServicesReplaceFunctionFeature
  nameWithType: DataServicesReplaceFunctionFeature
  fullName: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  type: Class
  summary: "Egy konfigurációs elem, amely lehetővé teszi, hogy engedélyezi vagy letiltja a szolgáltatás funkcióinak helyett."
  syntax:
    content: 'public class DataServicesReplaceFunctionFeature : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.#ctor
  id: '#ctor'
  parent: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  langs:
  - csharp
  name: DataServicesReplaceFunctionFeature()
  nameWithType: DataServicesReplaceFunctionFeature.DataServicesReplaceFunctionFeature()
  fullName: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.DataServicesReplaceFunctionFeature()
  type: Constructor
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Data.Services.Configuration.DataServicesReplaceFunctionFeature&quot;> </xref> osztály."
  syntax:
    content: public DataServicesReplaceFunctionFeature ();
    parameters: []
  overload: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.Enable
  id: Enable
  parent: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  langs:
  - csharp
  name: Enable
  nameWithType: DataServicesReplaceFunctionFeature.Enable
  fullName: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.Enable
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services.Configuration
  summary: "Lekérdezi vagy beállítja a logikai értéket, amely meghatározza, hogy engedélyezve van-e a név felülírandó funkció."
  syntax:
    content: public bool Enable { get; set; }
    return:
      type: System.Boolean
      description: "Értéke TRUE, ha a név felülírandó funkció engedélyezve, egyébként hamis értéket."
  overload: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.Enable*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.#ctor
  parent: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  isExternal: false
  name: DataServicesReplaceFunctionFeature()
  nameWithType: DataServicesReplaceFunctionFeature.DataServicesReplaceFunctionFeature()
  fullName: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.DataServicesReplaceFunctionFeature()
- uid: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.Enable
  parent: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  isExternal: false
  name: Enable
  nameWithType: DataServicesReplaceFunctionFeature.Enable
  fullName: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.Enable
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.#ctor*
  parent: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  isExternal: false
  name: DataServicesReplaceFunctionFeature
  nameWithType: DataServicesReplaceFunctionFeature.DataServicesReplaceFunctionFeature
- uid: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature.Enable*
  parent: System.Data.Services.Configuration.DataServicesReplaceFunctionFeature
  isExternal: false
  name: Enable
  nameWithType: DataServicesReplaceFunctionFeature.Enable
