### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.TrustNotGrantedException
  id: TrustNotGrantedException
  children:
  - System.Deployment.Application.TrustNotGrantedException.#ctor
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException
  fullName: System.Deployment.Application.TrustNotGrantedException
  type: Class
  summary: "Azt jelzi, hogy az alkalmazás nem rendelkezik a megfelelő szintű megbízhatóság futtathatja a helyi számítógépen."
  remarks: "Alapértelmezés szerint [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] alkalmazások kap egy az ügyfélszámítógépeken, amely megakadályozza, hogy a potenciálisan rosszindulatú tevékenységek, például a merevlemez-meghajtóról adatok törlése vagy a hálózathoz hozzáférő személyesen megbízhatósági szintet. A [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] alkalmazás segítségével engedély jogosultságszint-emelés vagy a megbízható alkalmazások központi telepítése egy magasabb szintű bizalmi kapcsolat kérése:-engedély jogosultságszint-emelési kéri a felhasználót, hogy adja meg az alkalmazás egy magasabb szintű biztonságot.      – Alkalmazástelepítés megbízható digitális aláírása megegyezik a [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] alkalmazás a helyi számítógép megbízható közzétevők listájának ellen.       TrustNotGrantedException fog jelezni, ha: - az alkalmazás engedélyt jogosultságszint-emelés használja, és a felhasználó megtagadja a kérelmet az emelt szintű megbízhatóság; Az alkalmazás használja a megbízható alkalmazások központi telepítése, illetve az alkalmazás aláírásához használt digitális tanúsítvány nem szerepel a helyi számítógép megbízható közzétevő. Ha egy alkalmazás egy frissítés legyen telepítve, és a frissítés több jogosultsággal, mint a korábbi verziót használja, és [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] jelez a TrustNotGrantedException, az új verzió nem telepíthető."
  syntax:
    content: 'public class TrustNotGrantedException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> osztály rendszer által megadott üzenetet, amely leírja a hibát."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonság egy rendszer által megadott üzenetet, amely leírja a hibát, például a &quot;DefaultMessageDisplayedByParameterlessCtorWriterMustSupply&quot; ezt az üzenetet az új példány veszi figyelembe a rendszer aktuális kulturális környezetének.</xref:System.Exception.Message%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.InsufficientMemoryException>.</xref:System.InsufficientMemoryException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Az üzenet honosított hibakarakterlánc. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public TrustNotGrantedException ();
    parameters: []
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> osztály egy adott üzenet, amely leírja a hibát."
  remarks: "Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Deployment.Application.TrustNotGrantedException>.</xref:System.Deployment.Application.TrustNotGrantedException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A hiba üzenet mezőben megadott karakterlánc `message`. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public TrustNotGrantedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> a szerializált adatok osztályt."
  syntax:
    content: protected TrustNotGrantedException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.TrustNotGrantedException
  langs:
  - csharp
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.TrustNotGrantedException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  syntax:
    content: public TrustNotGrantedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.Deployment.Application.TrustNotGrantedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException()
  nameWithType: TrustNotGrantedException.TrustNotGrantedException()
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException()
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(SerializationInfo,StreamingContext)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException(String,Exception)
  nameWithType: TrustNotGrantedException.TrustNotGrantedException(String,Exception)
  fullName: System.Deployment.Application.TrustNotGrantedException.TrustNotGrantedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.TrustNotGrantedException.#ctor*
  parent: System.Deployment.Application.TrustNotGrantedException
  isExternal: false
  name: TrustNotGrantedException
  nameWithType: TrustNotGrantedException.TrustNotGrantedException
