### YamlMime:ManagedReference
items:
- uid: System.ApplicationIdentity
  id: ApplicationIdentity
  children:
  - System.ApplicationIdentity.#ctor(System.String)
  - System.ApplicationIdentity.CodeBase
  - System.ApplicationIdentity.FullName
  - System.ApplicationIdentity.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.ApplicationIdentity.ToString
  langs:
  - csharp
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity
  fullName: System.ApplicationIdentity
  type: Class
  summary: "Lehetővé teszi a jegyzék által aktivált alkalmazások egyedi azonosításához. Ez az osztály nem örökölhető."
  remarks: "Az aktiválás jegyzékfájl-alapú alkalmazások a ApplicationIdentity osztály használatos."
  example:
  - "The following code example demonstrates the use of an <xref:System.ActivationContext> object to obtain the ApplicationIdentity for a manifest-based application. This code example is part of a larger example provided for the <xref:System.ActivationContext> class.  \n  \n [!code-vb[System.ActivationContext#2](~/add/codesnippet/visualbasic/t-system.applicationiden_1.vb)]\n [!code-cs[System.ActivationContext#2](~/add/codesnippet/csharp/t-system.applicationiden_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class ApplicationIdentity : System.Runtime.Serialization.ISerializable
  inheritance:
  - System.Object
  implements:
  - System.Runtime.Serialization.ISerializable
  inheritedMembers: []
  platform:
  - net462
- uid: System.ApplicationIdentity.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ApplicationIdentity
  langs:
  - csharp
  name: ApplicationIdentity(String)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String)
  fullName: System.ApplicationIdentity.ApplicationIdentity(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ApplicationIdentity&quot;> </xref> osztály."
  remarks: "The format of the `applicationIdentityFullName` parameter is a comma-delimited Unicode string that begins with the name, as follows:  \n  \n```  \n  \napplicationURL  \n#  \ndeploymentIdentity  \n\\  \napplicationIdentity  \n  \n```  \n  \n Where *deploymentIdentity* =  \n  \n```  \n  \ndeploymentManifest  \n, Version =   \nMajor.Minor.Build.Revision  \n, Culture =   \nCultureInfo  \n, PublicKeyToken=  \nTokenNumber  \n, processorArchitecture=  \nprocessorArchitecture  \n  \n```  \n  \n And *applicationIdentity* =  \n  \n```  \n  \napplicationName  \n, Version =   \nMajor.Minor.Build.Revision  \n, Culture =   \nCultureInfo  \n, PublicKeyToken=  \nTokenNumber  \n, processorArchitecture=  \nprocessorArchitecture  \n, type=  \nOsType  \n  \n```  \n  \n The following is an example of the full name for an application named ActivationContext:  \n  \n```  \nhttp://testserver/ActivationContext/ActivationContext.application  \n#ActivationContext.application, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ae13aad84c1a3490, processorArchitecture=msil  \n\\ActivationContext.exe, Version=1.0.0.0, Culture=neutral, PublicKeyToken=ae13aad84c1a3490, processorArchitecture=msil, type=win32  \n```  \n  \n The default value for processor architecture is \"msil\", and the default value for type is \"win32\"."
  syntax:
    content: public ApplicationIdentity (string applicationIdentityFullName);
    parameters:
    - id: applicationIdentityFullName
      type: System.String
      description: "Az alkalmazás teljes nevét."
  overload: System.ApplicationIdentity.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>applicationIdentityFullName</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ApplicationIdentity.CodeBase
  id: CodeBase
  parent: System.ApplicationIdentity
  langs:
  - csharp
  name: CodeBase
  nameWithType: ApplicationIdentity.CodeBase
  fullName: System.ApplicationIdentity.CodeBase
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  summary: "Az üzembe helyezési jegyzék helyét egy URL-címet kap."
  remarks: "A következő két példákban a CodeBase tulajdonságértékek ActivationContext nevű alkalmazás: - http://testserver/ActivationContext/ActivationContext.application - file://C:/UserFiles/UserName/SolutionName/ActivationContext/publish/ActivationContext.application."
  example:
  - "The following code example demonstrates the use of an <xref:System.ApplicationIdentity> object to obtain the value of the CodeBase property for a manifest-based application. This code example is part of a larger example provided for the <xref:System.ActivationContext> class.  \n  \n [!code-vb[System.ActivationContext#3](~/add/codesnippet/visualbasic/p-system.applicationiden_1_1.vb)]\n [!code-cs[System.ActivationContext#3](~/add/codesnippet/csharp/p-system.applicationiden_1_1.cs)]"
  syntax:
    content: public string CodeBase { get; }
    return:
      type: System.String
      description: "Az üzembe helyezési jegyzék URL-CÍMÉT."
  overload: System.ApplicationIdentity.CodeBase*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationIdentity.FullName
  id: FullName
  parent: System.ApplicationIdentity
  langs:
  - csharp
  name: FullName
  nameWithType: ApplicationIdentity.FullName
  fullName: System.ApplicationIdentity.FullName
  type: Property
  assemblies:
  - mscorlib
  namespace: System
  summary: "Lekérdezi az alkalmazás teljes nevét."
  remarks: "A FullName tulajdonság formátumban, olvassa el a <xref:System.ApplicationIdentity.%23ctor%2A>konstruktor.</xref:System.ApplicationIdentity.%23ctor%2A>"
  example:
  - "The following code example demonstrates the use of an <xref:System.ApplicationIdentity> object to obtain the value of the FullName property for a manifest-based application. This code example is part of a larger example provided for the <xref:System.ActivationContext> class.  \n  \n [!code-vb[System.ActivationContext#3](~/add/codesnippet/visualbasic/p-system.applicationiden_0_1.vb)]\n [!code-cs[System.ActivationContext#3](~/add/codesnippet/csharp/p-system.applicationiden_0_1.cs)]"
  syntax:
    content: public string FullName { get; }
    return:
      type: System.String
      description: "Az alkalmazás, más néven a megjelenített név teljes neve."
  overload: System.ApplicationIdentity.FullName*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationIdentity.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  isEii: true
  parent: System.ApplicationIdentity
  langs:
  - csharp
  name: System.Runtime.Serialization.ISerializable.GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  summary: "Kitölti egy <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> objektum szerializálása a célobjektum szükséges adatokat."
  syntax:
    content: void ISerializable.GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> adatokkal feltölteni."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>) a szerializálási-struktúrája.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.ApplicationIdentity.System#Runtime#Serialization#ISerializable#GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationIdentity.ToString
  id: ToString
  parent: System.ApplicationIdentity
  langs:
  - csharp
  name: ToString()
  nameWithType: ApplicationIdentity.ToString()
  fullName: System.ApplicationIdentity.ToString()
  type: Method
  assemblies:
  - mscorlib
  namespace: System
  summary: "A jegyzékfájl által aktivált alkalmazások teljes nevét adja vissza."
  remarks: "A jegyzék aktivált alkalmazás teljes nevét formátumban, olvassa el a <xref:System.ApplicationIdentity.%23ctor%2A>konstruktor.</xref:System.ApplicationIdentity.%23ctor%2A>"
  syntax:
    content: public override string ToString ();
    parameters: []
    return:
      type: System.String
      description: "A jegyzékfájl által aktivált alkalmazások teljes neve."
  overload: System.ApplicationIdentity.ToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ApplicationIdentity.#ctor(System.String)
  parent: System.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity(String)
  nameWithType: ApplicationIdentity.ApplicationIdentity(String)
  fullName: System.ApplicationIdentity.ApplicationIdentity(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationIdentity.CodeBase
  parent: System.ApplicationIdentity
  isExternal: false
  name: CodeBase
  nameWithType: ApplicationIdentity.CodeBase
  fullName: System.ApplicationIdentity.CodeBase
- uid: System.ApplicationIdentity.FullName
  parent: System.ApplicationIdentity
  isExternal: false
  name: FullName
  nameWithType: ApplicationIdentity.FullName
  fullName: System.ApplicationIdentity.FullName
- uid: System.ApplicationIdentity.System#Runtime#Serialization#ISerializable#GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.ApplicationIdentity
  isExternal: false
  name: System.Runtime.Serialization.ISerializable.GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.ApplicationIdentity.ToString
  parent: System.ApplicationIdentity
  isExternal: false
  name: ToString()
  nameWithType: ApplicationIdentity.ToString()
  fullName: System.ApplicationIdentity.ToString()
- uid: System.ApplicationIdentity.#ctor*
  parent: System.ApplicationIdentity
  isExternal: false
  name: ApplicationIdentity
  nameWithType: ApplicationIdentity.ApplicationIdentity
- uid: System.ApplicationIdentity.CodeBase*
  parent: System.ApplicationIdentity
  isExternal: false
  name: CodeBase
  nameWithType: ApplicationIdentity.CodeBase
- uid: System.ApplicationIdentity.FullName*
  parent: System.ApplicationIdentity
  isExternal: false
  name: FullName
  nameWithType: ApplicationIdentity.FullName
- uid: System.ApplicationIdentity.System#Runtime#Serialization#ISerializable#GetObjectData*
  parent: System.ApplicationIdentity
  isExternal: false
  name: System.Runtime.Serialization.ISerializable.GetObjectData
  nameWithType: ApplicationIdentity.System.Runtime.Serialization.ISerializable.GetObjectData
- uid: System.ApplicationIdentity.ToString*
  parent: System.ApplicationIdentity
  isExternal: false
  name: ToString
  nameWithType: ApplicationIdentity.ToString
