### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IdentityModelCaches
  id: IdentityModelCaches
  children:
  - System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  - System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  - System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  langs:
  - csharp
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches
  fullName: System.IdentityModel.Configuration.IdentityModelCaches
  type: Class
  summary: "Meghatározza a gyorsítótárak megismételt jogkivonatok és gyorsítótárazza a munkamenet-jogkivonatokat konfigurált. Ez az osztály nem örökölhető."
  remarks: "Lekérdezi vagy beállítja a konfigurált <xref:System.IdentityModel.Tokens.TokenReplayCache>és <xref:System.IdentityModel.Tokens.SessionSecurityTokenCache>.</xref:System.IdentityModel.Tokens.SessionSecurityTokenCache> </xref:System.IdentityModel.Tokens.TokenReplayCache> A `Caches` tulajdonsága a <xref:System.IdentityModel.Configuration.IdentityConfiguration>osztály és a <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfiguration>osztály a példánya: IdentityModelCaches.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfiguration> </xref:System.IdentityModel.Configuration.IdentityConfiguration>"
  syntax:
    content: public sealed class IdentityModelCaches
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.Configuration.IdentityModelCaches&quot;> </xref> osztály."
  syntax:
    content: public IdentityModelCaches ();
    parameters: []
  overload: System.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  id: SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.IdentityModel.Tokens.SessionSecurityTokenCache&quot;> </xref> gyorsítótár használandó a <xref href=&quot;System.IdentityModel.Tokens.SessionSecurityToken&quot;> </xref>."
  syntax:
    content: public System.IdentityModel.Tokens.SessionSecurityTokenCache SessionSecurityTokenCache { get; set; }
    return:
      type: System.IdentityModel.Tokens.SessionSecurityTokenCache
      description: "A megadott lexikális elem gyorsítótárában."
  overload: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "A tulajdonság beállítása <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> következik be."
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  id: TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  langs:
  - csharp
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.IdentityModel.Tokens.TokenReplayCache&quot;> </xref> , amely azt határozza meg, hogy visszajátszani vannak-e a jogkivonatokat."
  syntax:
    content: public System.IdentityModel.Tokens.TokenReplayCache TokenReplayCache { get; set; }
    return:
      type: System.IdentityModel.Tokens.TokenReplayCache
      description: "A beállított ismétlésészlelési gyorsítótár."
  overload: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "A tulajdonság beállítása <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> következik be."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: IdentityModelCaches()
  nameWithType: IdentityModelCaches.IdentityModelCaches()
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.IdentityModelCaches()
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache
- uid: System.IdentityModel.Tokens.SessionSecurityTokenCache
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: SessionSecurityTokenCache
  fullName: System.IdentityModel.Tokens.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache
- uid: System.IdentityModel.Tokens.TokenReplayCache
  parent: System.IdentityModel.Tokens
  isExternal: false
  name: TokenReplayCache
  nameWithType: TokenReplayCache
  fullName: System.IdentityModel.Tokens.TokenReplayCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.#ctor*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: IdentityModelCaches
  nameWithType: IdentityModelCaches.IdentityModelCaches
- uid: System.IdentityModel.Configuration.IdentityModelCaches.SessionSecurityTokenCache*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCaches.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCaches.TokenReplayCache*
  parent: System.IdentityModel.Configuration.IdentityModelCaches
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCaches.TokenReplayCache
