### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ComUdtElement
  id: ComUdtElement
  children:
  - System.ServiceModel.Configuration.ComUdtElement.#ctor
  - System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  - System.ServiceModel.Configuration.ComUdtElement.Name
  - System.ServiceModel.Configuration.ComUdtElement.Properties
  - System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  - System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  langs:
  - csharp
  name: ComUdtElement
  nameWithType: ComUdtElement
  fullName: System.ServiceModel.Configuration.ComUdtElement
  type: Class
  summary: "A felhasználó definiált típusa (UDT), amely a szolgáltatási szerződés szereplő jelöli. Ez az osztály nem örökölhető."
  remarks: "A COM + integrációs futásidejű szolgáltatások típustár vizsgálatával hoz létre. Ha egy COM + összetevőt tartalmaz módszereket, amelyek megfelelnek egy `VARIANT`, a rendszer nem tudja megállapítani a tényleges típusok előtt futásidejű átadni. Ezért, amikor megpróbál adjon át egy felhasználó definiált típusa (UDT) belül egy `VARIANT`, mert nincs olyan ismert típusnak a szerializálás sikertelen.       Ez a probléma megkerülése, adhat hozzá a UDTs a konfigurációs fájlt, hogy akkor is meg lehet adni a megfelelő szolgáltatási szerződés ismert típusként. Ehhez ki kell egyedi módon azonosítja az UDT és a szerződés(ek), ez azt jelenti, hogy az eredeti COM adaptert, amely használja ezt a szolgáltatást.       A következő példa bemutatja, hogy a két meghatározott UDTs hozzáadása a `userDefinedTypes`> erre a célra a konfigurációs fájl részét.       [!code-cs[XpsCreate #XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent) ] attribútumait a `userDefinedType`> elem a következők:- `typeName`: egy nem kötelező attribútum adatbázisok olvasható típusának nevét. A futtatókörnyezet nem használja, de a segítségével egy olvasó segítségével különböztetheti meg egymástól a típusok.      - `typeLibID`: a regisztrált típustár típusát meghatározó GUID karakterlánc.      - `typeLibVersion`: a típus könyvtárverzió típusát meghatározó karakterlánc.      - `typeDefID`: a regisztrált típus könyvtárból UDT típusát GUID karakterlánc.       A szolgáltatás inicializálásakor a COM + integrációs futásidejű megkeresi a megadott típusoknak, és hozzáadja őket a megadott szerződések ismert típusokat tartalmazó gyűjteményéhez."
  example:
  - "The following example demonstrates adding two specific UDTs to the <`userDefinedTypes`> section of the configuration file for this purpose.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: 'public sealed class ComUdtElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref> osztály."
  syntax:
    content: public ComUdtElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.ComUdtElement&quot;> </xref> osztály a megadott GUID-karakterláncot."
  syntax:
    content: public ComUdtElement (string typeDefID);
    parameters:
    - id: typeDefID
      type: System.String
      description: "A GUID karakterlánc, amely azonosítja a regisztrált típus könyvtárból UDT típusát."
  overload: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  id: Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja az adatbázisok olvasható típusának neve."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "Az adatbázisok olvasható típusának neve."
  overload: System.ServiceModel.Configuration.ComUdtElement.Name*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.ComUdtElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  id: TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a GUID karakterlánc, amely azonosítja a regisztrált típus könyvtárból UDT típusát."
  syntax:
    content: public string TypeDefID { get; set; }
    return:
      type: System.String
      description: "A meghatározott UDT típust a regisztrált típus könyvtárból."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  id: TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a GUID karakterlánc, amely azonosítja a regisztrált típus könyvtárban, amely meghatározza a típusát."
  syntax:
    content: public string TypeLibID { get; set; }
    return:
      type: System.String
      description: "A regisztrált típus könyvtárban, amely meghatározza a típusát."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  id: TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  langs:
  - csharp
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja, amely azonosítja a típus könyvtárverzió típusát meghatározó karakterlánc."
  syntax:
    content: public string TypeLibVersion { get; set; }
    return:
      type: System.String
      description: "A típus könyvtárverzió típusát meghatározó."
  overload: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement()
  nameWithType: ComUdtElement.ComUdtElement()
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement()
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement(String)
  nameWithType: ComUdtElement.ComUdtElement(String)
  fullName: System.ServiceModel.Configuration.ComUdtElement.ComUdtElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.ComUdtElement.Name
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
  fullName: System.ServiceModel.Configuration.ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
  fullName: System.ServiceModel.Configuration.ComUdtElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
  fullName: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion
- uid: System.ServiceModel.Configuration.ComUdtElement.#ctor*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: ComUdtElement
  nameWithType: ComUdtElement.ComUdtElement
- uid: System.ServiceModel.Configuration.ComUdtElement.Name*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Name
  nameWithType: ComUdtElement.Name
- uid: System.ServiceModel.Configuration.ComUdtElement.Properties*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: Properties
  nameWithType: ComUdtElement.Properties
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeDefID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeDefID
  nameWithType: ComUdtElement.TypeDefID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibID*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibID
  nameWithType: ComUdtElement.TypeLibID
- uid: System.ServiceModel.Configuration.ComUdtElement.TypeLibVersion*
  parent: System.ServiceModel.Configuration.ComUdtElement
  isExternal: false
  name: TypeLibVersion
  nameWithType: ComUdtElement.TypeLibVersion
