### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallEventHandler
  id: InstallEventHandler
  langs:
  - csharp
  name: InstallEventHandler
  nameWithType: InstallEventHandler
  fullName: System.Configuration.Install.InstallEventHandler
  type: Delegate
  summary: "Represents the method that will handle the <xref href=&quot;System.Configuration.Install.Installer.BeforeInstall&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.AfterInstall&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.Committing&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.Committed&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.BeforeRollback&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.AfterRollback&quot;></xref>, <xref href=&quot;System.Configuration.Install.Installer.BeforeUninstall&quot;></xref>, or <xref href=&quot;System.Configuration.Install.Installer.AfterUninstall&quot;></xref> event of an <xref href=&quot;System.Configuration.Install.Installer&quot;></xref>."
  remarks: "Amikor létrehoz egy InstallEventHandler delegált, meg kell adnia a módszert, amelyet az esemény fogja kezelni. Az esemény társítja a eseménykezelő, vegye fel a küldött példányának az esemény. Az eseménykezelő nevezzük az esemény akkor következik be, amikor, ha nem távolítja el a delegált. Esemény kezelő delegáltak kapcsolatos további információkért lásd: [események](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public delegate void InstallEventHandler(object sender, InstallEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
