### YamlMime:ManagedReference
items:
- uid: System.Configuration.StringValidatorAttribute
  id: StringValidatorAttribute
  children:
  - System.Configuration.StringValidatorAttribute.#ctor
  - System.Configuration.StringValidatorAttribute.InvalidCharacters
  - System.Configuration.StringValidatorAttribute.MaxLength
  - System.Configuration.StringValidatorAttribute.MinLength
  - System.Configuration.StringValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute
  fullName: System.Configuration.StringValidatorAttribute
  type: Class
  summary: "Deklaratív módon arra utasítja a .NET-keretrendszer karakterlánc érvényesítést hajt végre egy konfigurációs tulajdonság. Ez az osztály nem örökölhető."
  remarks: "A StringValidatorAttribute használatával adja meg egy konfigurációs tulajdonság. Ez az ellenőrzése, hogy a tulajdonság használatával a .NET-keretrendszer utasítja a <xref:System.Configuration.StringValidator>, és adja át azt az decorating paraméterek értékét.</xref:System.Configuration.StringValidator>       Csak a Tulajdonságok típusa StringValidatorAttribute objektumok alkalmazhat."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the StringValidatorAttribute object.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/t-system.configuration.s_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/t-system.configuration.s_1_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class StringValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.StringValidatorAttribute&quot;> </xref> osztály."
  remarks: "Ez a konstruktor a kiadott modell használható annak biztosításához, hogy a konfigurációs elemhez tulajdonsághoz hozzárendelt érték karakterlánc típusú."
  example:
  - "The following example shows how to use the StringValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/visualbasic/m-system.configuration.s_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#3](~/add/codesnippet/csharp/m-system.configuration.s_2_1.cs)]"
  syntax:
    content: public StringValidatorAttribute ();
    parameters: []
  overload: System.Configuration.StringValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  id: InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi vagy beállítja a tulajdonság érvénytelen karaktereket."
  remarks: ''
  example:
  - "The following example shows how to use the InvalidCharacters property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_15_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_15_1.cs)]"
  syntax:
    content: public string InvalidCharacters { get; set; }
    return:
      type: System.String
      description: "A karakterlánc, amely a tulajdonság nem megengedett karaktereket tartalmaz."
  overload: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  id: MaxLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi vagy beállítja azt a karakterláncot kell megadnia a tulajdonság hozzárendelése az engedélyezett maximális hosszt."
  remarks: ''
  example:
  - "The following example shows how to use the MaxLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_8_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_8_1.cs)]"
  syntax:
    content: public int MaxLength { get; set; }
    return:
      type: System.Int32
      description: "A karakterlánc a tulajdonság hozzárendelése a maximális engedélyezett hosszához jelző egész számot."
  overload: System.Configuration.StringValidatorAttribute.MaxLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "A kijelölt érték kisebb, mint <xref:System.Configuration.StringValidatorAttribute.MinLength*>.</xref:System.Configuration.StringValidatorAttribute.MinLength*>"
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.MinLength
  id: MinLength
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi vagy beállítja a minimális megengedett érték a karakterláncot kell megadnia a tulajdonság hozzárendelése."
  remarks: ''
  example:
  - "The following example shows how to use the MinLength property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/visualbasic/p-system.configuration.s_12_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#2](~/add/codesnippet/csharp/p-system.configuration.s_12_1.cs)]"
  syntax:
    content: public int MinLength { get; set; }
    return:
      type: System.Int32
      description: "A tulajdonság hozzárendelése a karakterlánc minimális hosszának jelző egész számot."
  overload: System.Configuration.StringValidatorAttribute.MinLength*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "A kijelölt érték nagyobb, mint <xref:System.Configuration.StringValidatorAttribute.MaxLength*>.</xref:System.Configuration.StringValidatorAttribute.MaxLength*>"
  platform:
  - net462
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi egy példányát a <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> osztály."
  remarks: "A ValidatorInstance tulajdonsággal meghívásával karakterlánc érvényességi végrehajtásához a <xref:System.Configuration.StringValidator.Validate%2A>metódus.</xref:System.Configuration.StringValidator.Validate%2A>"
  example:
  - "The following example shows how to use the ValidatorInstance property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/visualbasic/p-system.configuration.s_4_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#14](~/add/codesnippet/csharp/p-system.configuration.s_4_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "A jelenlegi <xref href=&quot;System.Configuration.StringValidator&quot;> </xref> beállításait egy <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> érvényesítő példány."
  overload: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.StringValidatorAttribute.#ctor
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute()
  nameWithType: StringValidatorAttribute.StringValidatorAttribute()
  fullName: System.Configuration.StringValidatorAttribute.StringValidatorAttribute()
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
  fullName: System.Configuration.StringValidatorAttribute.InvalidCharacters
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.StringValidatorAttribute.MaxLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
  fullName: System.Configuration.StringValidatorAttribute.MaxLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Configuration.StringValidatorAttribute.MinLength
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
  fullName: System.Configuration.StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.StringValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.StringValidatorAttribute.#ctor*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: StringValidatorAttribute
  nameWithType: StringValidatorAttribute.StringValidatorAttribute
- uid: System.Configuration.StringValidatorAttribute.InvalidCharacters*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: InvalidCharacters
  nameWithType: StringValidatorAttribute.InvalidCharacters
- uid: System.Configuration.StringValidatorAttribute.MaxLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MaxLength
  nameWithType: StringValidatorAttribute.MaxLength
- uid: System.Configuration.StringValidatorAttribute.MinLength*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: MinLength
  nameWithType: StringValidatorAttribute.MinLength
- uid: System.Configuration.StringValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.StringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: StringValidatorAttribute.ValidatorInstance
