### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationValidatorBase
  id: ConfigurationValidatorBase
  children:
  - System.Configuration.ConfigurationValidatorBase.#ctor
  - System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  - System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  langs:
  - csharp
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
  type: Class
  summary: "Egy alaposztály való származtatás érvényesítési osztályra, hogy az objektum érték ellenőrizhető funkcionál."
  remarks: "A ConfigurationValidatorBase osztály egy egyéni érvényesítési létrehozására szolgál. Egy egyéni érvényesítési segítségével ellenőrizze objektumra értékeket."
  syntax:
    content: public abstract class ConfigurationValidatorBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  id: '#ctor'
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy példányát inicializálja a <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> osztály."
  syntax:
    content: protected ConfigurationValidatorBase ();
    parameters: []
  overload: System.Configuration.ConfigurationValidatorBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Meghatározza, hogy az objektum érvényesíteni lehessen típusától függően."
  syntax:
    content: public virtual bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Az objektumtípus."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a <code> type </code> paraméter értéke megegyezik a várt <xref uid=&quot;langword_csharp_type&quot; name=&quot;type&quot; href=&quot;&quot;> </xref>; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.ConfigurationValidatorBase.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Meghatározza, hogy az objektum értéke érvénytelen."
  remarks: "Az objektum származik a <xref:System.Configuration.ConfigurationValidatorBase>osztály tartalmaz egy objektum ellenőrizni a feltételeket.</xref:System.Configuration.ConfigurationValidatorBase> A feltételek jönnek létre, amikor a származtatott osztály létrejön. Az objektum ellenőrzése paraméterként a Validate metódus."
  syntax:
    content: public abstract void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Az objektum értéke."
  overload: System.Configuration.ConfigurationValidatorBase.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationValidatorBase.#ctor
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase()
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase()
  fullName: System.Configuration.ConfigurationValidatorBase.ConfigurationValidatorBase()
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate(System.Type)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate(Type)
  nameWithType: ConfigurationValidatorBase.CanValidate(Type)
  fullName: System.Configuration.ConfigurationValidatorBase.CanValidate(Type)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.ConfigurationValidatorBase.Validate(System.Object)
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate(Object)
  nameWithType: ConfigurationValidatorBase.Validate(Object)
  fullName: System.Configuration.ConfigurationValidatorBase.Validate(Object)
- uid: System.Configuration.ConfigurationValidatorBase.#ctor*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase.ConfigurationValidatorBase
- uid: System.Configuration.ConfigurationValidatorBase.CanValidate*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: CanValidate
  nameWithType: ConfigurationValidatorBase.CanValidate
- uid: System.Configuration.ConfigurationValidatorBase.Validate*
  parent: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: Validate
  nameWithType: ConfigurationValidatorBase.Validate
