### YamlMime:ManagedReference
items:
- uid: System.Activities.WorkflowApplicationAbortedException
  id: WorkflowApplicationAbortedException
  children:
  - System.Activities.WorkflowApplicationAbortedException.#ctor
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  - System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  langs:
  - csharp
  name: WorkflowApplicationAbortedException
  nameWithType: WorkflowApplicationAbortedException
  fullName: System.Activities.WorkflowApplicationAbortedException
  type: Class
  summary: "Jelöli, amelyek fordul elő, amikor egy műveletet a munkafolyamat-példány érvénytelen, mert a példány meg lett szakítva."
  syntax:
    content: 'public class WorkflowApplicationAbortedException : System.Activities.WorkflowApplicationException'
  inheritance:
  - System.Exception
  - System.Activities.WorkflowApplicationException
  implements: []
  inheritedMembers:
  - System.Activities.WorkflowApplicationException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Activities.WorkflowApplicationException.InstanceId
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor
  id: '#ctor'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException()
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.Activities.WorkflowApplicationAbortedException&quot;> </xref> osztály."
  syntax:
    content: public WorkflowApplicationAbortedException ();
    parameters: []
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.Activities.WorkflowApplicationAbortedException&quot;> </xref> osztály egy szöveges karakterlánc leírás a kivétel."
  syntax:
    content: public WorkflowApplicationAbortedException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A megszakítási kivétel leírása."
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.Activities.WorkflowApplicationAbortedException&quot;> </xref> a szerializált adatfolyamból ehhez a kivételhez vonatkozó adatok beolvasásához szükséges környezet és a szerializálási adatokat osztályt."
  syntax:
    content: protected WorkflowApplicationAbortedException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Minden szükséges információt szerializálni, vagy a megszakításhoz kivétel objektum deszerializálása."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A forrás- és egy adott szerializált folyamban, és egy további, a hívó által megadott környezetben."
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String,Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.Activities.WorkflowApplicationAbortedException&quot;> </xref> osztály egy szöveges karakterlánc leírás a kivétel és okozza-e a megszakítási kivétel további kivételt."
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A megszakítási kivétel leírása."
    - id: innerException
      type: System.Exception
      description: "Az alkalmazás oksági kapcsolattal rendelkező kivétel kivétel meg lett szakítva. A megszakított Alkalmazáskivétel válaszként a belső kivétel történt, és megfelelően kezeli a hiba adatait a belső kivétel üzenetében használhatja."
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  id: '#ctor(System.String,System.Guid)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String,Guid)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.Activities.WorkflowApplicationAbortedException&quot;> </xref> osztály a megszakítási kivétel szöveges karakterlánc leírását és az egyedi azonosítója."
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Guid instanceId);
    parameters:
    - id: message
      type: System.String
      description: "A megszakítási kivétel leírása."
    - id: instanceId
      type: System.Guid
      description: "A globálisan egyedi azonosítóját."
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  id: '#ctor(System.String,System.Guid,System.Exception)'
  parent: System.Activities.WorkflowApplicationAbortedException
  langs:
  - csharp
  name: WorkflowApplicationAbortedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid,Exception)
  type: Constructor
  assemblies:
  - System.Activities
  namespace: System.Activities
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.Activities.WorkflowApplicationAbortedException&quot;> </xref> osztály egy szöveges karakterlánc leírás a megszakítási kivétel, az egyedi azonosító és okozza-e a megszakítási kivétel további kivételt."
  syntax:
    content: public WorkflowApplicationAbortedException (string message, Guid instanceId, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A megszakítási kivétel leírása."
    - id: instanceId
      type: System.Guid
      description: "A globálisan egyedi azonosítóját."
    - id: innerException
      type: System.Exception
      description: "Az alkalmazás oksági kapcsolattal rendelkező kivétel kivétel meg lett szakítva. A megszakított Alkalmazáskivétel válaszként a belső kivétel történt, és megfelelően kezeli a hiba adatait a belső kivétel üzenetében használhatja."
  overload: System.Activities.WorkflowApplicationAbortedException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Activities.WorkflowApplicationException
  isExternal: false
  name: System.Activities.WorkflowApplicationException
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException()
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException()
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Exception)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String,Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Exception)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String,Guid)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid)
- uid: System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor(System.String,System.Guid,System.Exception)
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException(String,Guid,Exception)
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid,Exception)
  fullName: System.Activities.WorkflowApplicationAbortedException.WorkflowApplicationAbortedException(String,Guid,Exception)
- uid: System.Activities.WorkflowApplicationAbortedException.#ctor*
  parent: System.Activities.WorkflowApplicationAbortedException
  isExternal: false
  name: WorkflowApplicationAbortedException
  nameWithType: WorkflowApplicationAbortedException.WorkflowApplicationAbortedException
