### YamlMime:ManagedReference
items:
- uid: System.EnvironmentVariableTarget
  id: EnvironmentVariableTarget
  children:
  - System.EnvironmentVariableTarget.Machine
  - System.EnvironmentVariableTarget.Process
  - System.EnvironmentVariableTarget.User
  langs:
  - csharp
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
  type: Enum
  summary: "Adja meg a helyet, ahol egy környezeti változó tárolja, vagy lekérése készlet vagy a get műveletet."
  remarks: "A EnvironmentVariableTarget számbavétel használják az egyes túlterhelés a <xref:System.Environment.SetEnvironmentVariable%2A>, <xref:System.Environment.GetEnvironmentVariable%2A>, és <xref:System.Environment.GetEnvironmentVariables%2A>módszerek adja meg a helyet, vagy a cél, ahol a név- és környezeti változó tárolja vagy lekérése.</xref:System.Environment.GetEnvironmentVariables%2A> </xref:System.Environment.GetEnvironmentVariable%2A> </xref:System.Environment.SetEnvironmentVariable%2A>       A cél három hely egyike lehet: az aktuális folyamat, a Windows operációs rendszer beállításkulcs fenntartott az aktuális felhasználóhoz társított környezeti változók vagy a környezeti változók társított a helyi számítógép összes felhasználója számára fenntartott beállításkulcs társított környezeti blokk."
  example:
  - "The following code example demonstrates the EnvironmentVariableTarget enumeration in methods that create, modify, and delete environment variables.  \n  \n [!code-cpp[environment.getsetenvar#1](~/add/codesnippet/cpp/t-system.environmentvari_1.cpp)]\n [!code-vb[environment.getsetenvar#1](~/add/codesnippet/visualbasic/t-system.environmentvari_1.vb)]\n [!code-cs[environment.getsetenvar#1](~/add/codesnippet/csharp/t-system.environmentvari_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public enum EnvironmentVariableTarget
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Machine
  id: Machine
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "A környezeti változó tárolja, vagy a lekérése a <xref uid=&quot;langword_csharp_HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; name=&quot;HKEY_LOCAL_MACHINE\\System\\CurrentControlSet\\Control\\Session Manager\\Environment&quot; href=&quot;&quot;> </xref> kulcs a Windows operációs rendszer beállításjegyzékében."
  remarks: "Amikor egy felhasználó a beállítási művelet hoz létre a következő környezeti változó, az operációs rendszer a következő környezeti változó tárolja, a beállításjegyzék, de nem a jelenlegi folyamatban. Ha bármely felhasználó a helyi számítógépen elindul egy új folyamatot, az operációs rendszer átmásolja a környezeti változó a beállításjegyzék folyamat.       Amikor a folyamat leáll, az operációs rendszer megsemmisít a környezeti változó a folyamatba. Azonban a beállításjegyzékben a környezeti változó tartósan fennáll, addig, amíg a felhasználó eltávolítja azt a programozott módon, vagy az operációs rendszer eszköz segítségével."
  syntax:
    content: Machine
    return:
      type: System.EnvironmentVariableTarget
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.Process
  id: Process
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "A környezeti változó tárolja, vagy a jelenlegi folyamathoz tartozó környezeti blokk lekért."
  remarks: "A felhasználó a környezeti változó beállítási művelet hoz létre.       Amikor a folyamat leáll, az operációs rendszer megsemmisít a környezeti változó a folyamatba."
  syntax:
    content: Process
    return:
      type: System.EnvironmentVariableTarget
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.EnvironmentVariableTarget.User
  id: User
  parent: System.EnvironmentVariableTarget
  langs:
  - csharp
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
  type: Field
  assemblies:
  - mscorlib
  namespace: System
  summary: "A környezeti változó tárolja, vagy a lekérése a <xref uid=&quot;langword_csharp_HKEY_CURRENT_USER\\Environment&quot; name=&quot;HKEY_CURRENT_USER\\Environment&quot; href=&quot;&quot;> </xref> kulcs a Windows operációs rendszer beállításjegyzékében."
  remarks: "Ha a felhasználó a beállítási művelet hoz létre a környezeti változó, az operációs rendszer a következő környezeti változó tárolja, a beállításjegyzék, de nem a jelenlegi folyamatban. Ha a felhasználó egy új folyamat elindul, az operációs rendszer átmásolja a környezeti változó a beállításjegyzék adott folyamatot.       Amikor a folyamat leáll, az operációs rendszer megsemmisít a környezeti változó a folyamatba. Azonban a beállításjegyzékben a környezeti változó tartósan fennáll, addig, amíg a felhasználó eltávolítja azt a programozott módon, vagy az operációs rendszer eszköz segítségével."
  syntax:
    content: User
    return:
      type: System.EnvironmentVariableTarget
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.EnvironmentVariableTarget.Machine
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Machine
  nameWithType: EnvironmentVariableTarget.Machine
  fullName: System.EnvironmentVariableTarget.Machine
- uid: System.EnvironmentVariableTarget
  parent: System
  isExternal: false
  name: EnvironmentVariableTarget
  nameWithType: EnvironmentVariableTarget
  fullName: System.EnvironmentVariableTarget
- uid: System.EnvironmentVariableTarget.Process
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: Process
  nameWithType: EnvironmentVariableTarget.Process
  fullName: System.EnvironmentVariableTarget.Process
- uid: System.EnvironmentVariableTarget.User
  parent: System.EnvironmentVariableTarget
  isExternal: false
  name: User
  nameWithType: EnvironmentVariableTarget.User
  fullName: System.EnvironmentVariableTarget.User
