### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  id: FilterTableEntryElement
  children:
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
  - System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
  langs:
  - csharp
  name: FilterTableEntryElement
  nameWithType: FilterTableEntryElement
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  type: Class
  summary: "Egy konfigurációs elem, amely meghatározza egy szűrő bejegyzés elemet jelképezi. Ez az elem tartalmaz szűrők, a végpontok és a biztonsági mentési végpontok közötti társítás, és határozza meg, amelynek szűrőértékeit szolgál az üzenet."
  syntax:
    content: 'public class FilterTableEntryElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: FilterTableEntryElement()
  nameWithType: FilterTableEntryElement.FilterTableEntryElement()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterTableEntryElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.ServiceModel.Routing.Configuration.FilterTableEntryElement&quot;> </xref> osztály."
  syntax:
    content: public FilterTableEntryElement ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
  id: BackupList
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: BackupList
  nameWithType: FilterTableEntryElement.BackupList
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely meghatározza egy hivatkozás egy biztonsági mentési végpontok elemre."
  syntax:
    content: public string BackupList { get; set; }
    return:
      type: System.String
      description: "A biztonsági mentési végpontok elem mutató hivatkozás."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
  id: EndpointName
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: EndpointName
  nameWithType: FilterTableEntryElement.EndpointName
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely meghatározza egy hivatkozást egy ügyfél-végpontot, amely üzeneteket küld, ha a kapcsolódó üzenetszűrő megegyezik az üzenetet."
  syntax:
    content: public string EndpointName { get; set; }
    return:
      type: System.String
      description: "Egy kulccsal, hogy egy ügyfél végpont."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
  id: FilterName
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: FilterName
  nameWithType: FilterTableEntryElement.FilterName
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Lekérdezi vagy beállítja a hivatkozni kell a szűrő elem értéke."
  syntax:
    content: public string FilterName { get; set; }
    return:
      type: System.String
      description: "A szűrő elem billentyűt."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
  id: Priority
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  langs:
  - csharp
  name: Priority
  nameWithType: FilterTableEntryElement.Priority
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely meghatározza a bejegyzés prioritását."
  remarks: "A bejegyzések a szűrőtáblában prioritás, a legalacsonyabb prioritású alatt 0-val alapján értékeli ki. Összes bejegyzés az adott prioritással egy időben értékeli ki, ha nincs megfelelő bejegyzés található az aktuális prioritás, a következő prioritási szintet ki lesz értékelve.       Ezt az értéket nem kötelező megadni."
  syntax:
    content: public int Priority { get; set; }
    return:
      type: System.Int32
      description: "Ez a bejegyzés prioritását. Az alapértelmezett érték a 0."
  overload: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: FilterTableEntryElement()
  nameWithType: FilterTableEntryElement.FilterTableEntryElement()
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterTableEntryElement()
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: BackupList
  nameWithType: FilterTableEntryElement.BackupList
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: EndpointName
  nameWithType: FilterTableEntryElement.EndpointName
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: FilterName
  nameWithType: FilterTableEntryElement.FilterName
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: Priority
  nameWithType: FilterTableEntryElement.Priority
  fullName: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.#ctor*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: FilterTableEntryElement
  nameWithType: FilterTableEntryElement.FilterTableEntryElement
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.BackupList*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: BackupList
  nameWithType: FilterTableEntryElement.BackupList
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.EndpointName*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: EndpointName
  nameWithType: FilterTableEntryElement.EndpointName
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.FilterName*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: FilterName
  nameWithType: FilterTableEntryElement.FilterName
- uid: System.ServiceModel.Routing.Configuration.FilterTableEntryElement.Priority*
  parent: System.ServiceModel.Routing.Configuration.FilterTableEntryElement
  isExternal: false
  name: Priority
  nameWithType: FilterTableEntryElement.Priority
