### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs
  id: DeploymentProgressChangedEventArgs
  children:
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  - System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  langs:
  - csharp
  name: DeploymentProgressChangedEventArgs
  nameWithType: DeploymentProgressChangedEventArgs
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs
  type: Class
  summary: "Folyamatban lévő adatokat egy aszinkron művelet jelentett képvisel."
  remarks: "Ez az osztály tulajdonságait, a folyamatban lévő leíró tartalmazza a <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, és <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>események.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged> </xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> Ez az osztály nem minden tulajdonságot minden esemény vonatkozik.       <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A>és <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A>jelentik a teljes adatmennyiség bájtban rendre letöltött dátumát és a letöltési műveletben bájtok teljes száma; az összes három esemény alkalmazza őket.</xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal%2A></xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted%2A> <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A>az aktuális megfelelő Fájlcsoport neve <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>esemény, és <xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A>az aktuális szakasza a letöltési művelet által adott jelentéseket tükrözik.</xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.State%2A> </xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged></xref:System.Deployment.Application.DeploymentProgressChangedEventArgs.Group%2A>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/t-system.deployment.appl_5_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: 'public class DeploymentProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  id: BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a művelet már letöltött bájtok száma."
  remarks: "A <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, a BytesCompleted tulajdonság hivatkozik az üzembe helyezési jegyzék letöltése.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> A <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, a tulajdonság része teljes frissítés letöltés előrehaladását a jegyzékfájlban, a szerelvények és az adatok fájlok hivatkozik.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> A <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, a tulajdonság hivatkozik a nevesített csoport részét képező fájlok teljes készlete letöltés előrehaladását.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/c5260b60-c259-429d-9763-_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public long BytesCompleted { get; }
    return:
      type: System.Int64
      description: "Egy <xref:System.Int64>az adatok már képviselő át, bájtban.</xref:System.Int64>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  id: BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "A letöltési művelet lekérdezi a bájtok teljes száma."
  remarks: "A <xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged>, a BytesTotal tulajdonság hivatkozik az üzembe helyezési jegyzék letöltése.</xref:System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged> A <xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged>, a tulajdonság része teljes frissítés letöltés előrehaladását a jegyzékfájlban, a szerelvények és az adatok fájlok hivatkozik.</xref:System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged> A <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>, a tulajdonság hivatkozik a nevesített csoport részét képező fájlok teljes készlete letöltés előrehaladását.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged>"
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_3_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public long BytesTotal { get; }
    return:
      type: System.Int64
      description: "Egy <xref:System.Int64>jelölő teljes mérete bájtban a letöltés.</xref:System.Int64>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  id: Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a letöltött fájl csoport nevét."
  remarks: "Több hívások is kezdeményezhető <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A>, és töltse le egyszerre több fájlcsoportok.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync%2A> Csoport használatával meghatározni, melyik esemény visszahívások melyik csoport felelnek meg."
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_4_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public string Group { get; }
    return:
      type: System.String
      description: "A <xref:System.String>tartalmazó fájl csoport nevét, ha az esemény történt hívása miatt <xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync*>; ellenkező esetben a nulla hosszúságú karakterlánc.</xref:System.Deployment.Application.ApplicationDeployment.DownloadFileGroupAsync*> </xref:System.String>"
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a végrehajtandó műveletet a folyamat éppen végrehajtás alatt áll."
  remarks: ''
  example:
  - "The following code example downloads a file group named `HelpFiles`, and displays download progress in a status bar. This example requires that you deploy a Windows Forms application, and that your main form has a <xref:System.Windows.Forms.StatusStrip> control, and a <xref:System.Windows.Forms.ToolStripStatusLabel> control named `downloadStatus`.  \n  \n [!code-cs[ClickOnceAPI#8](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#8)]\n [!code-cpp[ClickOnceAPI#8](~/add/codesnippet/cpp/p-system.deployment.appl_11_1.cpp)]\n [!code-vb[ClickOnceAPI#8](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#8)]"
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "A <xref href=&quot;System.Deployment.Application.DeploymentProgressState&quot;> </xref> érték, amely meghatározza, hogy milyen elemet vagy elemeket a művelet letöltés folyamatban van."
  overload: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DeploymentProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesCompleted*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesCompleted
  nameWithType: DeploymentProgressChangedEventArgs.BytesCompleted
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.BytesTotal*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: BytesTotal
  nameWithType: DeploymentProgressChangedEventArgs.BytesTotal
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.Group*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: Group
  nameWithType: DeploymentProgressChangedEventArgs.Group
- uid: System.Deployment.Application.DeploymentProgressChangedEventArgs.State*
  parent: System.Deployment.Application.DeploymentProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DeploymentProgressChangedEventArgs.State
