### YamlMime:ManagedReference
items:
- uid: System.Configuration.Install.InstallException
  id: InstallException
  children:
  - System.Configuration.Install.InstallException.#ctor
  - System.Configuration.Install.InstallException.#ctor(System.String)
  - System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: InstallException
  nameWithType: InstallException
  fullName: System.Configuration.Install.InstallException
  type: Class
  summary: "A kivétellel, hogy hiba esetén a véglegesítés során történt visszaállítás, vagy távolítsa el a telepítési fázis."
  remarks: ''
  example:
  - "The following example, plus the examples in the <xref:System.Configuration.Install.InstallException.%23ctor%2A> constructors, together make up an example showing an assembly having its own installer. The installer is named `MyInstaller`, which has an attribute `RunInstallerAttribute`, indicating that this installer will be invoked by [Installutil.exe (Installer Tool)](~/add/includes/ajax-current-ext-md.md). [Installutil.exe (Installer Tool)](../Topic/Installutil.exe%20\\(Installer%20Tool\\).md) calls the methods <xref:System.Configuration.Install.Installer.Commit%2A>, <xref:System.Configuration.Install.Installer.Rollback%2A>, <xref:System.Configuration.Install.Installer.Install%2A> and <xref:System.Configuration.Install.Installer.Uninstall%2A>. The code in <xref:System.Configuration.Install.Installer.Commit%2A> presumes that a file named `FileDoesNotExist.txt` exists before the installation of the assembly can be committed. If the file `FileDoesNotExist.txt` does not exist, <xref:System.Configuration.Install.Installer.Commit%2A> raises an InstallException. The same is the case with <xref:System.Configuration.Install.Installer.Uninstall%2A> in which an uninstallation will only happen if a file named `FileDoesNotExist.txt` exists. Otherwise it raises an InstallException. In <xref:System.Configuration.Install.Installer.Rollback%2A>, a code fragment is executed, which might raise an exception. If the exception is raised, it is caught and an InstallException is raised with that exception being passed to it.  \n  \n> [!NOTE]\n>  Run this example with the help of Installutil.exe. Type this in the command prompt:  \n  \n `Installutil InstallException.exe`  \n  \n -or-  \n  \n `Installutil /u InstallException.exe`  \n  \n [!code-cs[InstallException#1](~/add/codesnippet/csharp/t-system.configuration.i_1_1.cs)]\n [!code-cpp[InstallException#1](~/add/codesnippet/cpp/t-system.configuration.i_1_1.cpp)]\n [!code-vb[InstallException#1](~/add/codesnippet/visualbasic/t-system.configuration.i_1_1.vb)]"
  syntax:
    content: 'public class InstallException : SystemException'
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.Install.InstallException.#ctor
  id: '#ctor'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException()
  nameWithType: InstallException.InstallException()
  fullName: System.Configuration.Install.InstallException.InstallException()
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.Install.InstallException&quot;> </xref> osztály."
  remarks: ''
  example:
  - "The following example demonstrates the InstallException constructor. It is a part of the example of the <xref:System.Configuration.Install.InstallException> class.  \n  \n In this example, Installutil.exe calls the <xref:System.Configuration.Install.Installer.Commit%2A> method. The code in <xref:System.Configuration.Install.Installer.Commit%2A> presumes that a file named `FileDoesNotExist.txt` exists before the installation of the assembly can be committed. If the file `FileDoesNotExist.txt` does not exist, <xref:System.Configuration.Install.Installer.Commit%2A> raises an <xref:System.Configuration.Install.InstallException>.  \n  \n> [!NOTE]\n>  This example shows how to use one of the overloaded versions of the <xref:System.Configuration.Install.InstallException> constructor. For other examples that might be available, see the individual overload topics.  \n  \n [!code-cs[InstallException#2](~/add/codesnippet/csharp/m-system.configuration.i_8_1.cs)]\n [!code-cpp[InstallException#2](~/add/codesnippet/cpp/m-system.configuration.i_8_1.cpp)]\n [!code-vb[InstallException#2](~/add/codesnippet/visualbasic/m-system.configuration.i_8_1.vb)]"
  syntax:
    content: public InstallException ();
    parameters: []
  overload: System.Configuration.Install.InstallException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Install.InstallException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(String)
  nameWithType: InstallException.InstallException(String)
  fullName: System.Configuration.Install.InstallException.InstallException(String)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.Install.InstallException&quot;> </xref> osztály, és a felhasználó számára megjelenített üzenetet adja meg."
  remarks: ''
  example:
  - "The following example demonstrates the <xref:System.Configuration.Install.InstallException.%23ctor%2A> constructor. It is a part of the example of the <xref:System.Configuration.Install.InstallException> class.  \n  \n In this example, Installutil.exe calls the <xref:System.Configuration.Install.Installer.Uninstall%2A> method. Uninstallation will only happen if a file named `FileDoesNotExist.txt` exists. Otherwise it raises an <xref:System.Configuration.Install.InstallException>.  \n  \n> [!NOTE]\n>  This example shows how to use one of the overloaded versions of the <xref:System.Configuration.Install.InstallException> constructor. For other examples that might be available, see the individual overload topics.  \n  \n [!code-cs[InstallException#4](~/add/codesnippet/csharp/m-system.configuration.i_11_1.cs)]\n [!code-cpp[InstallException#4](~/add/codesnippet/cpp/m-system.configuration.i_11_1.cpp)]\n [!code-vb[InstallException#4](~/add/codesnippet/visualbasic/m-system.configuration.i_11_1.vb)]"
  syntax:
    content: public InstallException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A felhasználó számára megjelenített üzenet."
  overload: System.Configuration.Install.InstallException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(SerializationInfo,StreamingContext)
  nameWithType: InstallException.InstallException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.Install.InstallException.InstallException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.Install.InstallException&quot;> </xref> a szerializált adatok osztályt."
  syntax:
    content: protected InstallException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A <xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> , amely tartalmazza a kivétel lépett fel az éppen szerializált objektum adatait."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A <xref:System.Runtime.Serialization.StreamingContext>, amely a cél- és környezeti információkat tartalmaz.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Configuration.Install.InstallException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Configuration.Install.InstallException
  langs:
  - csharp
  name: InstallException(String,Exception)
  nameWithType: InstallException.InstallException(String,Exception)
  fullName: System.Configuration.Install.InstallException.InstallException(String,Exception)
  type: Constructor
  assemblies:
  - System.Configuration.Install
  namespace: System.Configuration.Install
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.Install.InstallException&quot;> </xref> osztály, és megadja a felhasználó, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, megjelenítendő üzenetet."
  syntax:
    content: public InstallException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A felhasználó számára megjelenített üzenet."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.Configuration.Install.InstallException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.Configuration.Install.InstallException.#ctor
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException()
  nameWithType: InstallException.InstallException()
  fullName: System.Configuration.Install.InstallException.InstallException()
- uid: System.Configuration.Install.InstallException.#ctor(System.String)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(String)
  nameWithType: InstallException.InstallException(String)
  fullName: System.Configuration.Install.InstallException.InstallException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Install.InstallException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(SerializationInfo,StreamingContext)
  nameWithType: InstallException.InstallException(SerializationInfo,StreamingContext)
  fullName: System.Configuration.Install.InstallException.InstallException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Configuration.Install.InstallException.#ctor(System.String,System.Exception)
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException(String,Exception)
  nameWithType: InstallException.InstallException(String,Exception)
  fullName: System.Configuration.Install.InstallException.InstallException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Configuration.Install.InstallException.#ctor*
  parent: System.Configuration.Install.InstallException
  isExternal: false
  name: InstallException
  nameWithType: InstallException.InstallException
