### YamlMime:ManagedReference
items:
- uid: System.Configuration.RegexStringValidatorAttribute
  id: RegexStringValidatorAttribute
  children:
  - System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  - System.Configuration.RegexStringValidatorAttribute.Regex
  - System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: RegexStringValidatorAttribute
  nameWithType: RegexStringValidatorAttribute
  fullName: System.Configuration.RegexStringValidatorAttribute
  type: Class
  summary: "Deklaratív módon arra utasítja a .NET-keretrendszer karakterlánc érvényesítést hajt végre egy konfigurációs tulajdonság reguláris kifejezéssel. Ez az osztály nem örökölhető."
  remarks: "A RegexStringValidatorAttribute segítségével egy konfigurációs tulajdonság, amely arra utasítja a .NET-keretrendszer ellenőrzése, hogy a tulajdonság használatával adja a <xref:System.Configuration.RegexStringValidator>, és adja át azt az decorating paraméterek értékét.</xref:System.Configuration.RegexStringValidator>       Csak a Tulajdonságok típusa RegexStringValidatorAttribute objektumok is vonatkozik."
  example:
  - "The following example shows how to decorate the properties of a custom <xref:System.Configuration.ConfigurationSection> object using the RegexStringValidatorAttribute object.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/visualbasic/t-system.configuration.r_2_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/csharp/t-system.configuration.r_2_1.cs)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class RegexStringValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: RegexStringValidatorAttribute(String)
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  fullName: System.Configuration.RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.RegexStringValidatorAttribute&quot;> </xref> objektum."
  remarks: "A `regex` paramétert tartalmaz, amely egy karakterlánc meg kell egyeznie a reguláris kifejezési minta rendelhető hozzá a leírással ellátott konfigurációs-elem tulajdonság előtt.       Ez a konstruktor a kiadott modell használható annak érdekében, hogy a karakterlánc a kapcsolódó tulajdonsághoz hozzárendelt érték csak az engedélyezett karaktereket tartalmaz."
  example:
  - "The following example shows how to use the RegexStringValidatorAttribute constructor.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/visualbasic/m-system.configuration.r_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#4](~/add/codesnippet/csharp/m-system.configuration.r_0_1.cs)]"
  syntax:
    content: public RegexStringValidatorAttribute (string regex);
    parameters:
    - id: regex
      type: System.String
      description: "A reguláris kifejezés érvényesítéshez használt karakterlánc."
  overload: System.Configuration.RegexStringValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.RegexStringValidatorAttribute.Regex
  id: Regex
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
  fullName: System.Configuration.RegexStringValidatorAttribute.Regex
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi a szabályos kifejezés ellenőrzéshez használt karakterlánc."
  remarks: ''
  example:
  - "The following example shows how to use the Regex property.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#16](~/add/codesnippet/visualbasic/p-system.configuration.r_1_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#16](~/add/codesnippet/csharp/p-system.configuration.r_1_1.cs)]"
  syntax:
    content: public string Regex { get; }
    return:
      type: System.String
      description: "A reguláris kifejezés használatával szűrhetők a leírással ellátott konfigurációs-elem tulajdonság hozzárendelt szöveget tartalmazó karakterlánc."
  overload: System.Configuration.RegexStringValidatorAttribute.Regex*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.RegexStringValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi egy példányát a <xref href=&quot;System.Configuration.RegexStringValidator&quot;> </xref> osztály."
  remarks: "A ValidatorInstance tulajdonsággal meghívásával karakterlánc érvényességi végrehajtásához a <xref:System.Configuration.StringValidator.Validate%2A>metódus.</xref:System.Configuration.StringValidator.Validate%2A>"
  example:
  - "The following example shows how to use the ValidatorInstance method.  \n  \n [!code-vb[System.Configuration.ConfigurationValidatorAttributes#15](~/add/codesnippet/visualbasic/p-system.configuration.r_0_1.vb)]\n [!code-cs[System.Configuration.ConfigurationValidatorAttributes#15](~/add/codesnippet/csharp/p-system.configuration.r_0_1.cs)]"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "A <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> érvényesítő példány."
  overload: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor(System.String)
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: RegexStringValidatorAttribute(String)
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
  fullName: System.Configuration.RegexStringValidatorAttribute.RegexStringValidatorAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.RegexStringValidatorAttribute.Regex
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
  fullName: System.Configuration.RegexStringValidatorAttribute.Regex
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.RegexStringValidatorAttribute.#ctor*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: RegexStringValidatorAttribute
  nameWithType: RegexStringValidatorAttribute.RegexStringValidatorAttribute
- uid: System.Configuration.RegexStringValidatorAttribute.Regex*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: Regex
  nameWithType: RegexStringValidatorAttribute.Regex
- uid: System.Configuration.RegexStringValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.RegexStringValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: RegexStringValidatorAttribute.ValidatorInstance
