### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  id: TcpConnectionPoolSettingsElement
  children:
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  - System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  type: Class
  summary: "Egy konfigurációs elem, amely meghatározza egy TCP átviteli tartozó kapcsolat további beállításainak jelöli. Ez az osztály nem örökölhető."
  syntax:
    content: 'public sealed class TcpConnectionPoolSettingsElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement&quot;> </xref> osztály."
  syntax:
    content: public TcpConnectionPoolSettingsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  id: GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a karakterlánc, amely meghatározza a kimenő csatornák használt kapcsolatkészlet nevét."
  remarks: "Adatfolyamként továbbított módban kapcsolatok nincsenek megosztva, ami azt jelenti, hogy kapcsolatkészletezést le van tiltva. Az alapértelmezett érték egy &quot;alapértelmezett&quot; karakterláncot. Ez az érték egy adott ügyfél különálló csoportokba kapcsolatainak elkülönítése módosíthatja."
  syntax:
    content: public string GroupName { get; set; }
    return:
      type: System.String
      description: "A kimenő csatornák használt kapcsolatkészlet neve."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  id: IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja azt a maximális időtartamot, a kapcsolat bontásra kerül üresjáratban lehet."
  syntax:
    content: public TimeSpan IdleTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "Egy pozitív <xref:System.TimeSpan>, amely megadja, hogy a kapcsolat bontásra kerül üresjáratban lehet maximális időtartamot.</xref:System.TimeSpan> Az alapértelmezett érték 00:02:00."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  id: LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja az időtartam, mely után az aktív kapcsolat le van zárva."
  remarks: "A kapcsolat le van zárva, után a kapcsolat gyorsítótárba, és nem aktív átvitel közben adja vissza. A kapcsolat gyorsítótár, a TCP átviteli által használt végpontok, akár a gyorsítótárméretének korlátját <xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A>.</xref:System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint%2A> beállított szükség szerint új kapcsolatot hoz létre."
  syntax:
    content: public TimeSpan LeaseTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>struktúra, amely jelzi az időtartam, amely után a TCP-kapcsolat le van zárva.</xref:System.TimeSpan>"
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  id: MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a kapcsolatok maximális száma a szolgáltatás által kezdeményezett a távoli végpontnak."
  remarks: "Kapcsolatok száma, amelyek átlépik ezt a korlátot várólistára kerülnek, amíg a szabad terület meghaladja az lesz elérhető. Ez a tulajdonság korlátozza az időtartam, amelyen kapcsolatok maradnak előtt a rendszer kivételt hoz létre.       Ez a tulajdonság egy adott szolgáltatáshoz végpontot az ügyfél egyidejű aktív kapcsolatok számának korlátozása. Azzal, hogy az ügyfél több aktív kapcsolat túllépi ezt az értéket, ha a szolgáltatás nem válaszol, az ügyfél jelenhetnek meg. Ebben az esetben ezt az értéket be kell állítani haladhatja meg az adott végponti várt egyidejű ügyfélkapcsolatok maximális számát.       Ez a beállítás is megadható a szolgáltatás oldalon, amelyek esetében az érték használják való beállítására a következő <xref:System.ServiceModel.Channels.MaxPooledConnections%2A> <xref:System.ServiceModel.Channels.TcpChannelListener>.</xref:System.ServiceModel.Channels.TcpChannelListener> </xref:System.ServiceModel.Channels.MaxPooledConnections%2A>"
  syntax:
    content: public int MaxOutboundConnectionsPerEndpoint { get; set; }
    return:
      type: System.Int32
      description: "A távoli végpont a szolgáltatás által indított kapcsolatok maximális száma. Az alapértelmezett érték 10."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  langs:
  - csharp
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement()
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement()
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
  fullName: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.#ctor*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: TcpConnectionPoolSettingsElement
  nameWithType: TcpConnectionPoolSettingsElement.TcpConnectionPoolSettingsElement
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.GroupName*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: GroupName
  nameWithType: TcpConnectionPoolSettingsElement.GroupName
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.IdleTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: IdleTimeout
  nameWithType: TcpConnectionPoolSettingsElement.IdleTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.LeaseTimeout*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: LeaseTimeout
  nameWithType: TcpConnectionPoolSettingsElement.LeaseTimeout
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: MaxOutboundConnectionsPerEndpoint
  nameWithType: TcpConnectionPoolSettingsElement.MaxOutboundConnectionsPerEndpoint
- uid: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement.Properties*
  parent: System.ServiceModel.Configuration.TcpConnectionPoolSettingsElement
  isExternal: false
  name: Properties
  nameWithType: TcpConnectionPoolSettingsElement.Properties
