### YamlMime:ManagedReference
items:
- uid: System.AddIn.Hosting.AddInEnvironment
  id: AddInEnvironment
  children:
  - System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  - System.AddIn.Hosting.AddInEnvironment.Process
  langs:
  - csharp
  name: AddInEnvironment
  nameWithType: AddInEnvironment
  fullName: System.AddIn.Hosting.AddInEnvironment
  type: Class
  summary: "Hozzáférést biztosít az alkalmazástartomány-bővítmény folyamatán."
  remarks: "Az osztály használatával beépülő moduljainak betöltése a kívánt környezetbe, amely a következők egyike lehet:-alkalmazás meglévő tartományhoz, amely rendelkezik a <xref:System.AppDomain>objektum.</xref:System.AppDomain>      – Egy alkalmazástartomány bővítmény aktiválása automatikusan lett létrehozva.      -A meglévő külső folyamat.       Az AddInEnvironment objektumok bővítmény beszerzéséhez át a bővítmény alkalmazástartomány AddInEnvironment osztálykonstruktor. Másik lehetőségként használhatja a <xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>tulajdonsága a <xref:System.AddIn.Hosting.AddInController>osztály AddInEnvironment objektum a bővítményt.</xref:System.AddIn.Hosting.AddInController> </xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>       Miután beszerezte a AddInEnvironment objektum, a következőket teheti:-az AddInEnvironment objektum átadása a megfelelő <xref:System.AddIn.Hosting.AddInToken.Activate%2A>metódus túlterhelési.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> A szolgáltatás aktiválódik alkalmazás tartományban és az AddInEnvironment objektum által képviselt folyamat.      – Használja a <xref:System.AddIn.Hosting.AddInEnvironment.Process%2A>tulajdonságnak egy <xref:System.AddIn.Hosting.AddInProcess>objektum.</xref:System.AddIn.Hosting.AddInProcess> </xref:System.AddIn.Hosting.AddInEnvironment.Process%2A> Akkor továbbítja a megfelelő objektumokat, amelyek <xref:System.AddIn.Hosting.AddInToken.Activate%2A>metódus túlterhelési.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> A szolgáltatás aktiválódik a folyamat által képviselt a <xref:System.AddIn.Hosting.AddInProcess>objektum, de egy új alkalmazás tartományban.</xref:System.AddIn.Hosting.AddInProcess>"
  syntax:
    content: public sealed class AddInEnvironment
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  id: '#ctor(System.AppDomain)'
  parent: System.AddIn.Hosting.AddInEnvironment
  langs:
  - csharp
  name: AddInEnvironment(AppDomain)
  nameWithType: AddInEnvironment.AddInEnvironment(AppDomain)
  fullName: System.AddIn.Hosting.AddInEnvironment.AddInEnvironment(AppDomain)
  type: Constructor
  assemblies:
  - System.AddIn
  namespace: System.AddIn.Hosting
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.AddIn.Hosting.AddInEnvironment&quot;> </xref> osztály."
  remarks: "Van szüksége a bővítményt tartalmazó alkalmazás tartomány elérhető lesz, ha ez a konstruktor a bővítmény beszerzése használhatja <xref:System.AddIn.Hosting.AddInEnvironment>objektum.</xref:System.AddIn.Hosting.AddInEnvironment> Ellenkező esetben használhatja a <xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>tulajdonsága a <xref:System.AddIn.Hosting.AddInController>osztályt az beszerzése a <xref:System.AddIn.Hosting.AddInEnvironment>objektum.</xref:System.AddIn.Hosting.AddInEnvironment> </xref:System.AddIn.Hosting.AddInController> </xref:System.AddIn.Hosting.AddInController.AddInEnvironment%2A>"
  syntax:
    content: public AddInEnvironment (AppDomain appDomain);
    parameters:
    - id: appDomain
      type: System.AppDomain
      description: "A bővítményt tartalmazó alkalmazás tartomány."
  overload: System.AddIn.Hosting.AddInEnvironment.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>appDomain</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Security.SecurityException
    commentId: T:System.Security.SecurityException
    description: "Az igényelt a teljesen megbízható engedéllyel. A kivételhívási láncban a hívó nem rendelkezik megfelelő engedéllyel."
  platform:
  - net462
- uid: System.AddIn.Hosting.AddInEnvironment.Process
  id: Process
  parent: System.AddIn.Hosting.AddInEnvironment
  langs:
  - csharp
  name: Process
  nameWithType: AddInEnvironment.Process
  fullName: System.AddIn.Hosting.AddInEnvironment.Process
  type: Property
  assemblies:
  - System.AddIn
  namespace: System.AddIn.Hosting
  summary: "Lekérdezi a <xref href=&quot;System.AddIn.Hosting.AddInProcess&quot;> </xref> a folyamat, amelyben a fut. képviselő objektum."
  remarks: "Ez a tulajdonság segítségével több beépülő modulok ugyanazt a folyamatot, de eltérő tartományokban aktiválása.       Továbbítsa a <xref:System.AddIn.Hosting.AddInProcess>ezt a tulajdonságot a megfelelő objektumot kapott <xref:System.AddIn.Hosting.AddInToken.Activate%2A>metódus túlterhelési.</xref:System.AddIn.Hosting.AddInToken.Activate%2A> </xref:System.AddIn.Hosting.AddInProcess>       Ha szeretné aktiválni azokat egy külső folyamatban ugyanabban a tartományban, adja át a <xref:System.AddIn.Hosting.AddInEnvironment>objektumot közvetlenül a <xref:System.AddIn.Hosting.AddInToken.Activate%60%601%28System.AddIn.Hosting.AddInEnvironment%29?displayProperty=fullName>metódus túlterhelési.</xref:System.AddIn.Hosting.AddInToken.Activate%60%601%28System.AddIn.Hosting.AddInEnvironment%29?displayProperty=fullName> </xref:System.AddIn.Hosting.AddInEnvironment>"
  syntax:
    content: public System.AddIn.Hosting.AddInProcess Process { get; }
    return:
      type: System.AddIn.Hosting.AddInProcess
      description: "A folyamat, amelyben a fut.."
  overload: System.AddIn.Hosting.AddInEnvironment.Process*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Security.SecurityException
  isExternal: true
  name: System.Security.SecurityException
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor(System.AppDomain)
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: AddInEnvironment(AppDomain)
  nameWithType: AddInEnvironment.AddInEnvironment(AppDomain)
  fullName: System.AddIn.Hosting.AddInEnvironment.AddInEnvironment(AppDomain)
- uid: System.AppDomain
  parent: System
  isExternal: false
  name: AppDomain
  nameWithType: AppDomain
  fullName: System.AppDomain
- uid: System.AddIn.Hosting.AddInEnvironment.Process
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: Process
  nameWithType: AddInEnvironment.Process
  fullName: System.AddIn.Hosting.AddInEnvironment.Process
- uid: System.AddIn.Hosting.AddInProcess
  parent: System.AddIn.Hosting
  isExternal: false
  name: AddInProcess
  nameWithType: AddInProcess
  fullName: System.AddIn.Hosting.AddInProcess
- uid: System.AddIn.Hosting.AddInEnvironment.#ctor*
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: AddInEnvironment
  nameWithType: AddInEnvironment.AddInEnvironment
- uid: System.AddIn.Hosting.AddInEnvironment.Process*
  parent: System.AddIn.Hosting.AddInEnvironment
  isExternal: false
  name: Process
  nameWithType: AddInEnvironment.Process
