### YamlMime:ManagedReference
items:
- uid: System.Configuration.TimeSpanValidator
  id: TimeSpanValidator
  children:
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  - System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  - System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  - System.Configuration.TimeSpanValidator.Validate(System.Object)
  langs:
  - csharp
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator
  fullName: System.Configuration.TimeSpanValidator
  type: Class
  summary: "Érvényesítése biztosít egy <xref:System.TimeSpan>objektum.</xref:System.TimeSpan>"
  remarks: "A TimeSpanValidator osztály annak biztosítására szolgál, amely egy <xref:System.TimeSpan>adott feltételeknek megfelelő objektum.</xref:System.TimeSpan> A <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>két paraméterekkel rendelkező konstruktor biztosítja, hogy a minimum és maximum <xref:System.TimeSpan>érték betartása.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A> A <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>három paraméterekkel rendelkező konstruktor ellenőrzi a minimális és maximális <xref:System.TimeSpan>értékeket, valamint kizárólagos-e az érvényesítési tartomány.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A> A <xref:System.Configuration.TimeSpanValidator.%23ctor%2A>négy paraméterekkel rendelkező konstruktor ellenőrzi az előző három paramétert, valamint a ellenőrzések e a <xref:System.TimeSpan>értéke megegyezik egy bizonyos számú másodperc.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator.%23ctor%2A>       A <xref:System.Configuration.TimeSpanValidator.CanValidate%2A>módszer határozza meg, hogy az objektum típusának érvényesített megegyezik-e a várt típusú.</xref:System.Configuration.TimeSpanValidator.CanValidate%2A> Az objektum az érvényesített paramétereként átadása a <xref:System.Configuration.TimeSpanValidator.Validate%2A>metódus.</xref:System.Configuration.TimeSpanValidator.Validate%2A>"
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator type.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#1](~/add/codesnippet/csharp/t-system.configuration.t_2_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#1](~/add/codesnippet/visualbasic/t-system.configuration.t_2_1.vb)]"
  syntax:
    content: 'public class TimeSpanValidator : System.Configuration.ConfigurationValidatorBase'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationValidatorBase
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  id: '#ctor(System.TimeSpan,System.TimeSpan)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> osztály, a megadott paraméterek alapján."
  remarks: "A két paraméter TimeSpanValidator konstruktor használata esetén a <xref:System.Configuration.TimeSpanValidator>objektum azt ellenőrzi, hogy egy <xref:System.TimeSpan>megadott tartományra megfelelő érték.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator>"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>objektum, amely megadja azt a minimális időtartamot lehet érvényesíteni.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>objektum, amely megadja, hogy legfeljebb mennyi ideig lehet érvényesíteni.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> osztály, a megadott paraméterek alapján."
  remarks: "A TimeSpanValidator konstruktor ellenőrzi a minimális és maximális <xref:System.TimeSpan>értékeket, valamint kizárólagos-e az érvényesítési tartomány.</xref:System.TimeSpan> Ha a `rangeIsExclusive` paraméter értéke `true`, a <xref:System.TimeSpan>érték között nem lehet a `minValue` és `maxValue` értékek.</xref:System.TimeSpan>"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>objektum, amely megadja azt a minimális időtartamot lehet érvényesíteni.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>objektum, amely megadja, hogy legfeljebb mennyi ideig lehet érvényesíteni.</xref:System.TimeSpan>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "A <xref:System.Boolean>érték, amely megadja, hogy az érvényesítés tartomány kizárólagos.</xref:System.Boolean>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  id: '#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)'
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.TimeSpanValidator&quot;> </xref> osztály, a megadott paraméterek alapján."
  remarks: "Ha a `resolutionInSeconds` paraméter van megadva, a <xref:System.TimeSpan>objektum érvényesített egyenlőnek kell lennie ennek az értéknek ahhoz, hogy teljesíti az ellenőrző.</xref:System.TimeSpan>"
  example:
  - "The following code example demonstrates how to use the TimeSpanValidator constructor. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#2](~/add/codesnippet/csharp/5fd5fd48-b5cd-41a3-9e7a-_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#2](~/add/codesnippet/visualbasic/5fd5fd48-b5cd-41a3-9e7a-_1.vb)]"
  syntax:
    content: public TimeSpanValidator (TimeSpan minValue, TimeSpan maxValue, bool rangeIsExclusive, long resolutionInSeconds);
    parameters:
    - id: minValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>objektum, amely megadja azt a minimális időtartamot lehet érvényesíteni.</xref:System.TimeSpan>"
    - id: maxValue
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>objektum, amely megadja, hogy legfeljebb mennyi ideig lehet érvényesíteni.</xref:System.TimeSpan>"
    - id: rangeIsExclusive
      type: System.Boolean
      description: "A <xref:System.Boolean>érték, amely megadja, hogy az érvényesítés tartomány kizárólagos.</xref:System.Boolean>"
    - id: resolutionInSeconds
      type: System.Int64
      description: "Egy <xref:System.Int64>érték, amely megadja a másodpercek száma.</xref:System.Int64>"
  overload: System.Configuration.TimeSpanValidator.#ctor*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "<code>resolutionInSeconds</code> is less than <xref uid=\"langword_csharp_0\" name=\"0\" href=\"\"></xref>.  \n  \n \\- or -  \n  \n <code>minValue</code> is greater than <code>maxValue</code>."
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  id: CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Meghatározza, hogy az objektum típusa érvényesíteni lehessen."
  remarks: ''
  example:
  - "The following code example demonstrates how to use the CanValidate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#3](~/add/codesnippet/csharp/m-system.configuration.t_1_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#3](~/add/codesnippet/visualbasic/m-system.configuration.t_1_1.vb)]"
  syntax:
    content: public override bool CanValidate (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Az objektum típusa."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a <code> type </code> paraméter megegyezik egy <xref:System.TimeSpan>érték; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.TimeSpan>"
  overload: System.Configuration.TimeSpanValidator.CanValidate*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  id: Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  langs:
  - csharp
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Meghatározza, hogy az objektum értéke érvénytelen."
  remarks: "A <xref:System.Configuration.TimeSpanValidator>objektum tartalmazza a szabályok ellenőrizni egy <xref:System.TimeSpan>objektum.</xref:System.TimeSpan> </xref:System.Configuration.TimeSpanValidator> A szabályok jönnek létre, amikor egy példányát a <xref:System.Configuration.TimeSpanValidator>osztály jön létre.</xref:System.Configuration.TimeSpanValidator> Az objektum ellenőrzése paraméterként a Validate metódus."
  example:
  - "The following code example demonstrates how to use the Validate method. This code example is part of a larger example provided for the <xref:System.Configuration.TimeSpanValidator> class.  \n  \n [!code-cs[System.Configuration.TimeSpanValidator#4](~/add/codesnippet/csharp/m-system.configuration.t_2_1.cs)]\n [!code-vb[System.Configuration.TimeSpanValidator#4](~/add/codesnippet/visualbasic/m-system.configuration.t_2_1.vb)]"
  syntax:
    content: public override void Validate (object value);
    parameters:
    - id: value
      type: System.Object
      description: "Az objektum értéke."
  overload: System.Configuration.TimeSpanValidator.Validate*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorBase
  isExternal: false
  name: System.Configuration.ConfigurationValidatorBase
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan)
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.TimeSpanValidator.#ctor(System.TimeSpan,System.TimeSpan,System.Boolean,System.Int64)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  nameWithType: TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
  fullName: System.Configuration.TimeSpanValidator.TimeSpanValidator(TimeSpan,TimeSpan,Boolean,Int64)
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Configuration.TimeSpanValidator.CanValidate(System.Type)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate(Type)
  nameWithType: TimeSpanValidator.CanValidate(Type)
  fullName: System.Configuration.TimeSpanValidator.CanValidate(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.TimeSpanValidator.Validate(System.Object)
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate(Object)
  nameWithType: TimeSpanValidator.Validate(Object)
  fullName: System.Configuration.TimeSpanValidator.Validate(Object)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Configuration.TimeSpanValidator.#ctor*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: TimeSpanValidator
  nameWithType: TimeSpanValidator.TimeSpanValidator
- uid: System.Configuration.TimeSpanValidator.CanValidate*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: CanValidate
  nameWithType: TimeSpanValidator.CanValidate
- uid: System.Configuration.TimeSpanValidator.Validate*
  parent: System.Configuration.TimeSpanValidator
  isExternal: false
  name: Validate
  nameWithType: TimeSpanValidator.Validate
