### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProvider
  id: SettingsProvider
  children:
  - System.Configuration.SettingsProvider.#ctor
  - System.Configuration.SettingsProvider.ApplicationName
  - System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  - System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  langs:
  - csharp
  name: SettingsProvider
  nameWithType: SettingsProvider
  fullName: System.Configuration.SettingsProvider
  type: Class
  summary: "Az alkalmazás beállításainak architektúra egyéni beállítások szolgáltatók való származtatás alaposztályt funkcionál."
  remarks: "A beállítások szolgáltató meghatározza a mechanizmus az alkalmazás beállításainak architektúra használt konfigurációs adatainak tárolásához. A .NET-keretrendszer egy alapértelmezett beállítások szolgáltatót tartalmaz, <xref:System.Configuration.LocalFileSettingsProvider>, amely tárolja a konfigurációs adatokat a helyi fájlrendszerben.</xref:System.Configuration.LocalFileSettingsProvider> Azonban az absztrakt osztály SettingsProvider származó létrehozhatja alternatív tárolócsoport mechanizmusokat. A szolgáltató által használt egy burkoló osztály határozza meg a burkoló osztályt a <xref:System.Configuration.SettingsProviderAttribute>.</xref:System.Configuration.SettingsProviderAttribute> dekoráció Ha ez az attribútum nincs megadva, az alapértelmezett <xref:System.Configuration.LocalFileSettingsProvider>, szolgál.</xref:System.Configuration.LocalFileSettingsProvider>       Legalább egy egyéni beállítások szolgáltató létrehozásakor meg kell adnia ezt az osztályt a három módszer implementációja: <xref:System.Configuration.SettingsProvider.GetPropertyValues%2A>, <xref:System.Configuration.SettingsProvider.SetPropertyValues%2A>és <xref:System.Configuration.SettingsProvider.ApplicationName%2A>.</xref:System.Configuration.SettingsProvider.ApplicationName%2A> </xref:System.Configuration.SettingsProvider.SetPropertyValues%2A> </xref:System.Configuration.SettingsProvider.GetPropertyValues%2A>       Az ügyfélalkalmazások, adhat hozzá további szabványos funkciókat egyéni szolgáltatót is alkalmazásával a <xref:System.Configuration.IApplicationSettingsProvider>felületet.</xref:System.Configuration.IApplicationSettingsProvider> Ez az interfész található módszerek tükrözi a <xref:System.Configuration.ApplicationSettingsBase>osztályt, amely elsősorban az versioning támogassa.</xref:System.Configuration.ApplicationSettingsBase>       Általában akkor tervezzen beállítások szolgáltatók kell lennie, egyetlen instanced tárolási Erőforrásverseny elkerülése érdekében. Szolgáltatók is szálbiztos kell lennie, mert azok is meghívhatók egy alkalmazástartomány több burkoló-példány, illetve több alkalmazás eltérő tartományokban.       Legalább egy beállításszolgáltató fel kell ismernie az attribútumokat –<xref:System.Configuration.ApplicationScopedSettingAttribute>, <xref:System.Configuration.UserScopedSettingAttribute>, és <xref:System.Configuration.DefaultSettingValueAttribute>.</xref:System.Configuration.DefaultSettingValueAttribute> </xref:System.Configuration.UserScopedSettingAttribute> </xref:System.Configuration.ApplicationScopedSettingAttribute> Alkalmazásbeállítások alkalmazható attribútumok teljes listáját lásd: [alkalmazás beállítások attribútumok](~/add/includes/ajax-current-ext-md.md). Az egyéni beállításhoz szolgáltató oldja fel az attribútumok alkalmazott beállítások a következő módon: 1.  Ha a szolgáltató is teljesítése a kérelem attribútum implicit, nyilvánvalóan azt kell megtenni.      2.  A szolgáltató a kérelem nem teljesíthető, ha azt figyelmen kívül hagyja azt csendes módban.      3.  Ha két vagy több tulajdonságának ütközés lép fel; Ha például mindkét <xref:System.Configuration.ApplicationScopedSettingAttribute>és <xref:System.Configuration.UserScopedSettingAttribute>; a szolgáltató kell előidéznie <xref:System.Configuration.ConfigurationException>.</xref:System.Configuration.ConfigurationException> </xref:System.Configuration.UserScopedSettingAttribute> </xref:System.Configuration.ApplicationScopedSettingAttribute> alatt kitüntetett tulajdonság"
  syntax:
    content: 'public abstract class SettingsProvider : System.Configuration.Provider.ProviderBase'
  inheritance:
  - System.Object
  - System.Configuration.Provider.ProviderBase
  implements: []
  inheritedMembers:
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.Provider.ProviderBase.Name
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: SettingsProvider()
  nameWithType: SettingsProvider.SettingsProvider()
  fullName: System.Configuration.SettingsProvider.SettingsProvider()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy példányát inicializálja a <xref href=&quot;System.Configuration.SettingsProvider&quot;> </xref> osztály."
  remarks: "Ez az absztrakt osztály az alapértelmezett védett konstruktor. Származtatott egyéni beállítások szolgáltatók nem szükségesek a adjon meg egy explicit konstruktort, mert a <xref:System.Configuration.Provider.ProviderBase.Initialize%2A>metódus általában végzi el az összes inicializálási.</xref:System.Configuration.Provider.ProviderBase.Initialize%2A>       Ügyfélkód általában nem közvetlenül a beállítások szolgáltatója példányosítható; Ehelyett használhatja az alábbi eljárás egy beállításszolgáltató található az adott beállításokkal tulajdonság: 1.  A <xref:System.ComponentModel.Component.GetService%2A>módszer az aktuális <xref:System.ComponentModel.Component>, vagy <xref:System.ComponentModel.ISite>visszaállíthatja az aktuális <xref:System.Configuration.ISettingsProviderService>.</xref:System.Configuration.ISettingsProviderService> mutató hivatkozás</xref:System.ComponentModel.ISite> </xref:System.ComponentModel.Component> </xref:System.ComponentModel.Component.GetService%2A>      2.  Hívja a <xref:System.Configuration.ISettingsProviderService.GetSettingsProvider%2A>metódusában a <xref:System.Configuration.ISettingsProviderService>a beállításszolgáltató vissza az első lépésben lekért.</xref:System.Configuration.ISettingsProviderService> </xref:System.Configuration.ISettingsProviderService.GetSettingsProvider%2A>"
  syntax:
    content: protected SettingsProvider ();
    parameters: []
  overload: System.Configuration.SettingsProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.ApplicationName
  id: ApplicationName
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
  fullName: System.Configuration.SettingsProvider.ApplicationName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi vagy beállítja a jelenleg futó alkalmazás nevét."
  remarks: "Az ApplicationName és <xref:System.Configuration.Provider.ProviderBase.Name%2A>Tulajdonságok súgó hasonlóan elnevezett tulajdonságok megadása a különböző alkalmazások elem egyértelműségének biztosításához.</xref:System.Configuration.Provider.ProviderBase.Name%2A>"
  syntax:
    content: public abstract string ApplicationName { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>, amely tartalmazza az alkalmazás rövidített nevét, amely nem tartalmazza a teljes elérési útja vagy kiterjesztéssel, például, `SimpleAppSettings`.</xref:System.String>"
  overload: System.Configuration.SettingsProvider.ApplicationName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  id: GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  nameWithType: SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  fullName: System.Configuration.SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A megadott alkalmazás-példány és a beállítások tulajdonságcsoport tulajdonságértékek adja vissza a beállítások gyűjteménye."
  remarks: "Speciális beállítások kezelése a GetPropertyValues metódust kell megvalósítani, azok jelölésű <xref:System.Configuration.SpecialSettingAttribute>, illetve alkalmazás- és felhasználói beállítások összehangolandó.</xref:System.Configuration.SpecialSettingAttribute>"
  syntax:
    content: public abstract System.Configuration.SettingsPropertyValueCollection GetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection collection);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "A <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> leíró aktuális alkalmazás használatát."
    - id: collection
      type: System.Configuration.SettingsPropertyCollection
      description: "A <xref href=&quot;System.Configuration.SettingsPropertyCollection&quot;> </xref> tartalmazó a beállítások tulajdonságcsoport, amelynek értékei kérhető."
    return:
      type: System.Configuration.SettingsPropertyValueCollection
      description: "A <xref href=&quot;System.Configuration.SettingsPropertyValueCollection&quot;> </xref> az értékeket a megadott beállítások tulajdonság csoport tartalmazó."
  overload: System.Configuration.SettingsProvider.GetPropertyValues*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  id: SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  parent: System.Configuration.SettingsProvider
  langs:
  - csharp
  name: SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  nameWithType: SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  fullName: System.Configuration.SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Eszköztulajdonság-beállítások meghatározott csoportjára értékekre állítja."
  remarks: "<xref:System.Configuration.ApplicationSettingsBase>tartalmazza a <xref:System.Configuration.ApplicationSettingsBase.Save%2A>metódus, amely értékeinek minden beállítások tulajdonságot is nevezik.</xref:System.Configuration.ApplicationSettingsBase.Save%2A></xref:System.Configuration.ApplicationSettingsBase> Ez a módszer enumerálása összes a beállítások szolgáltatók társított a beállítások tulajdonságait, és SetPropertyValues metódus az egyes <xref:System.Configuration.SettingsProvider>a tényleges szerializálási művelet.</xref:System.Configuration.SettingsProvider>       A SetPropertyValues metódus a biztonságot szem előtt kell végrehajtani: - csak a teljesen megbízható kód engedélyezni kell az alkalmazásbeállítások frissítése. Csak a felhasználó Alkalmazásbeállítások frissítése részben megbízható kód engedélyezni kell. Nem megbízható kód általában nem engedélyezett alkalmazások beállításainak frissítése.      -Használati kvóták érdemes figyelembe venni, amelyek erőforrás támadások elleni védelmet részlegesen megbízható alkalmazások."
  syntax:
    content: public abstract void SetPropertyValues (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyValueCollection collection);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "A <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> az aktuális alkalmazás használati leíró."
    - id: collection
      type: System.Configuration.SettingsPropertyValueCollection
      description: "A <xref href=&quot;System.Configuration.SettingsPropertyValueCollection&quot;> </xref> jelölő beállítása beállítások csoportja."
  overload: System.Configuration.SettingsProvider.SetPropertyValues*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: System.Configuration.Provider.ProviderBase
- uid: System.Configuration.SettingsProvider.#ctor
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SettingsProvider()
  nameWithType: SettingsProvider.SettingsProvider()
  fullName: System.Configuration.SettingsProvider.SettingsProvider()
- uid: System.Configuration.SettingsProvider.ApplicationName
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
  fullName: System.Configuration.SettingsProvider.ApplicationName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProvider.GetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  nameWithType: SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
  fullName: System.Configuration.SettingsProvider.GetPropertyValues(SettingsContext,SettingsPropertyCollection)
- uid: System.Configuration.SettingsPropertyValueCollection
  parent: System.Configuration
  isExternal: false
  name: SettingsPropertyValueCollection
  nameWithType: SettingsPropertyValueCollection
  fullName: System.Configuration.SettingsPropertyValueCollection
- uid: System.Configuration.SettingsContext
  parent: System.Configuration
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
- uid: System.Configuration.SettingsPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: SettingsPropertyCollection
  nameWithType: SettingsPropertyCollection
  fullName: System.Configuration.SettingsPropertyCollection
- uid: System.Configuration.SettingsProvider.SetPropertyValues(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyValueCollection)
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  nameWithType: SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
  fullName: System.Configuration.SettingsProvider.SetPropertyValues(SettingsContext,SettingsPropertyValueCollection)
- uid: System.Configuration.SettingsProvider.#ctor*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SettingsProvider
  nameWithType: SettingsProvider.SettingsProvider
- uid: System.Configuration.SettingsProvider.ApplicationName*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: ApplicationName
  nameWithType: SettingsProvider.ApplicationName
- uid: System.Configuration.SettingsProvider.GetPropertyValues*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: GetPropertyValues
  nameWithType: SettingsProvider.GetPropertyValues
- uid: System.Configuration.SettingsProvider.SetPropertyValues*
  parent: System.Configuration.SettingsProvider
  isExternal: false
  name: SetPropertyValues
  nameWithType: SettingsProvider.SetPropertyValues
