### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AuthorizationRuleAction
  id: AuthorizationRuleAction
  children:
  - System.Web.Configuration.AuthorizationRuleAction.Allow
  - System.Web.Configuration.AuthorizationRuleAction.Deny
  langs:
  - csharp
  name: AuthorizationRuleAction
  nameWithType: AuthorizationRuleAction
  fullName: System.Web.Configuration.AuthorizationRuleAction
  type: Enum
  summary: "Határozza meg a engedély egy erőforráshoz történő hozzáféréskor."
  remarks: "Használja a <xref:System.Web.Configuration.AuthorizationRule.Action%2A>programozott módon konfigurálhatja az engedélyezési művelet a webes alkalmazás által használható tulajdonság.</xref:System.Web.Configuration.AuthorizationRule.Action%2A>"
  example:
  - "The following code example shows how use the <xref:System.Web.Configuration.AuthorizationRule.Action%2A> property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.AuthorizationRule> class.  \n  \n [!code-cs[System.Web.Configuration.Authorization#4](~/add/codesnippet/csharp/t-system.web.configurati_31_1.cs)]\n [!code-vb[System.Web.Configuration.Authorization#4](~/add/codesnippet/visualbasic/t-system.web.configurati_31_1.vb)]"
  syntax:
    content: public enum AuthorizationRuleAction
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationRuleAction.Allow
  id: Allow
  parent: System.Web.Configuration.AuthorizationRuleAction
  langs:
  - csharp
  name: Allow
  nameWithType: AuthorizationRuleAction.Allow
  fullName: System.Web.Configuration.AuthorizationRuleAction.Allow
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "A hitelesítési típus lehetővé teszi, hogy az erőforrás elérésére."
  syntax:
    content: Allow
    return:
      type: System.Web.Configuration.AuthorizationRuleAction
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthorizationRuleAction.Deny
  id: Deny
  parent: System.Web.Configuration.AuthorizationRuleAction
  langs:
  - csharp
  name: Deny
  nameWithType: AuthorizationRuleAction.Deny
  fullName: System.Web.Configuration.AuthorizationRuleAction.Deny
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "A hitelesítési típus megtagadja a hozzáférést az erőforráshoz."
  syntax:
    content: Deny
    return:
      type: System.Web.Configuration.AuthorizationRuleAction
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.AuthorizationRuleAction.Allow
  parent: System.Web.Configuration.AuthorizationRuleAction
  isExternal: false
  name: Allow
  nameWithType: AuthorizationRuleAction.Allow
  fullName: System.Web.Configuration.AuthorizationRuleAction.Allow
- uid: System.Web.Configuration.AuthorizationRuleAction
  parent: System.Web.Configuration
  isExternal: false
  name: AuthorizationRuleAction
  nameWithType: AuthorizationRuleAction
  fullName: System.Web.Configuration.AuthorizationRuleAction
- uid: System.Web.Configuration.AuthorizationRuleAction.Deny
  parent: System.Web.Configuration.AuthorizationRuleAction
  isExternal: false
  name: Deny
  nameWithType: AuthorizationRuleAction.Deny
  fullName: System.Web.Configuration.AuthorizationRuleAction.Deny
