### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode
  id: MembershipPasswordCompatibilityMode
  children:
  - System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
  - System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
  langs:
  - csharp
  name: MembershipPasswordCompatibilityMode
  nameWithType: MembershipPasswordCompatibilityMode
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode
  type: Enum
  summary: "Az ASP.NET tagság jelszó-kompatibilitási módjainak enumerálása."
  remarks: "Ez az enumerálás a jelszó-formátumairól az előző verziókkal való kompatibilitás biztosít."
  syntax:
    content: public enum MembershipPasswordCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
  id: Framework20
  parent: System.Web.Configuration.MembershipPasswordCompatibilityMode
  langs:
  - csharp
  name: Framework20
  nameWithType: MembershipPasswordCompatibilityMode.Framework20
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
  type: Field
  assemblies:
  - System.Web.ApplicationServices
  namespace: System.Web.Configuration
  summary: "Jelszavak ASP.NET 2.0 módban van."
  syntax:
    content: Framework20
    return:
      type: System.Web.Configuration.MembershipPasswordCompatibilityMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
  id: Framework40
  parent: System.Web.Configuration.MembershipPasswordCompatibilityMode
  langs:
  - csharp
  name: Framework40
  nameWithType: MembershipPasswordCompatibilityMode.Framework40
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
  type: Field
  assemblies:
  - System.Web.ApplicationServices
  namespace: System.Web.Configuration
  summary: "Jelszavak ASP.NET 4 módban van."
  syntax:
    content: Framework40
    return:
      type: System.Web.Configuration.MembershipPasswordCompatibilityMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
  parent: System.Web.Configuration.MembershipPasswordCompatibilityMode
  isExternal: false
  name: Framework20
  nameWithType: MembershipPasswordCompatibilityMode.Framework20
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework20
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: MembershipPasswordCompatibilityMode
  nameWithType: MembershipPasswordCompatibilityMode
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode
- uid: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
  parent: System.Web.Configuration.MembershipPasswordCompatibilityMode
  isExternal: false
  name: Framework40
  nameWithType: MembershipPasswordCompatibilityMode.Framework40
  fullName: System.Web.Configuration.MembershipPasswordCompatibilityMode.Framework40
