### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection
  id: SystemIdentityModelSection
  children:
  - System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  - System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  - System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  - System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  - System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  langs:
  - csharp
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection
  type: Class
  summary: "Jelzi a <xref uid=&quot;langword_csharp_&lt;system.identityModel&gt;&quot; name=&quot;&lt;system.identityModel&gt;&quot; href=&quot;&quot;> </xref> szakaszt egy konfigurációs fájlban. Ez az osztály nem örökölhető."
  remarks: "Belül a `<system.identityModel>` szakaszban, a konfiguráció adható meg, egyenként egyedi nevet és egy adott konfigurációs; meghatározása több identitás például `<identityConfiguration name=&quot;alternate&quot; >`. A gyűjtemény az identitás-modell szakaszban megadott azonosító konfigurációs elem használatával lehet beolvasni a <xref:System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements%2A>tulajdonság.</xref:System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements%2A>       Ha az identitás a konfigurációs elem nincs megadva a neve, az elem az alapértelmezett identitáskonfigurációs határozza meg. Az alapértelmezett identitáskonfigurációs mindig passzív összevonási esetekben használatos. Csak egy alapértelmezett konfiguráció előfordulhat, hogy létezik a modellben identitás konfigurációs szakaszban. Segítségével lekérhető a <xref:System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement%2A>tulajdonság.</xref:System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement%2A>"
  syntax:
    content: 'public sealed class SystemIdentityModelSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: SystemIdentityModelSection()
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection()
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SystemIdentityModelSection()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.Configuration.SystemIdentityModelSection&quot;> </xref> osztály."
  syntax:
    content: public SystemIdentityModelSection ();
    parameters: []
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  id: Current
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: Current
  nameWithType: SystemIdentityModelSection.Current
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi az aktuális <xref href=&quot;System.IdentityModel.Configuration.SystemIdentityModelSection&quot;> </xref> hivatkozás."
  syntax:
    content: public static System.IdentityModel.Configuration.SystemIdentityModelSection Current { get; }
    return:
      type: System.IdentityModel.Configuration.SystemIdentityModelSection
      description: "Az aktuális <xref href=&quot;System.IdentityModel.Configuration.SystemIdentityModelSection&quot;> </xref> hivatkozás."
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.Current*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  id: DefaultIdentityConfigurationElement
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi az alapértelmezett (névtelen) <xref href=&quot;System.IdentityModel.Configuration.IdentityConfigurationElement&quot;> </xref> a konfigurációs fájlból."
  remarks: "A `<system.identityModel>` szakasz csak egy alapértelmezett tartalmazhat `<identityConfiguration>` elemet. Az alapértelmezett identitáskonfigurációs mindig passzív összevonási esetekben használatos."
  syntax:
    content: public static System.IdentityModel.Configuration.IdentityConfigurationElement DefaultIdentityConfigurationElement { get; }
    return:
      type: System.IdentityModel.Configuration.IdentityConfigurationElement
      description: "Az alapértelmezett (névtelen) <xref uid=&quot;langword_csharp_&lt;identityConfiguration&gt;&quot; name=&quot;&lt;identityConfiguration&gt;&quot; href=&quot;&quot;> </xref> elemet."
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  id: IdentityConfigurationElements
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.IdentityModel.Configuration.IdentityConfigurationElementCollection&quot;> </xref> a konfigurációs fájlból."
  syntax:
    content: public System.IdentityModel.Configuration.IdentityConfigurationElementCollection IdentityConfigurationElements { get; }
    return:
      type: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
      description: "Egy gyűjteményt, amely tartalmazza az összes a <xref uid=&quot;langword_csharp_&lt;identityConfiguration&gt;&quot; name=&quot;&lt;identityConfiguration&gt;&quot; href=&quot;&quot;> </xref> elemeinek a <xref uid=&quot;langword_csharp_&lt;system.identityModel&gt;&quot; name=&quot;&lt;system.identityModel&gt;&quot; href=&quot;&quot;> </xref> szakasz."
  overload: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  id: SectionName
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  langs:
  - csharp
  name: SectionName
  nameWithType: SystemIdentityModelSection.SectionName
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  type: Field
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "A konfigurációs szakaszban meghatározottak szerint a Windows Identity Foundation (WIF); a neve system.identityModel."
  syntax:
    content: public const string SectionName;
    return:
      type: System.String
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SystemIdentityModelSection()
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection()
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SystemIdentityModelSection()
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelSection.Current
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.Current
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement
- uid: System.IdentityModel.Configuration.IdentityConfigurationElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: IdentityConfigurationElement
  nameWithType: IdentityConfigurationElement
  fullName: System.IdentityModel.Configuration.IdentityConfigurationElement
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements
- uid: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: IdentityConfigurationElementCollection
  nameWithType: IdentityConfigurationElementCollection
  fullName: System.IdentityModel.Configuration.IdentityConfigurationElementCollection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SectionName
  nameWithType: SystemIdentityModelSection.SectionName
  fullName: System.IdentityModel.Configuration.SystemIdentityModelSection.SectionName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.#ctor*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: SystemIdentityModelSection
  nameWithType: SystemIdentityModelSection.SystemIdentityModelSection
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.Current*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: Current
  nameWithType: SystemIdentityModelSection.Current
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.DefaultIdentityConfigurationElement*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: DefaultIdentityConfigurationElement
  nameWithType: SystemIdentityModelSection.DefaultIdentityConfigurationElement
- uid: System.IdentityModel.Configuration.SystemIdentityModelSection.IdentityConfigurationElements*
  parent: System.IdentityModel.Configuration.SystemIdentityModelSection
  isExternal: false
  name: IdentityConfigurationElements
  nameWithType: SystemIdentityModelSection.IdentityConfigurationElements
