### YamlMime:ManagedReference
items:
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute
  id: PositiveTimeSpanValidatorAttribute
  children:
  - System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  - System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute
  type: Class
  summary: "Deklaratív módon arra utasítja a .NET-keretrendszer idő érvényesítést hajt végre egy konfigurációs tulajdonság. Ez az osztály nem örökölhető."
  remarks: "A PositiveTimeSpanValidatorAttribute attribútum segítségével adja meg egy konfigurációs tulajdonság. Ez arra utasítja a .NET-keretrendszer ellenőrzése, hogy a tulajdonság használatával egy <xref:System.Configuration.PositiveTimeSpanValidator>objektumot, és adja át a decorating paraméterek értékét.</xref:System.Configuration.PositiveTimeSpanValidator>       PositiveTimeSpanValidatorAttribute objektumok csak tulajdonságtípus alkalmazható."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class PositiveTimeSpanValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.PositiveTimeSpanValidatorAttribute&quot;> </xref> osztály."
  remarks: "Ez a konstruktor használja annak biztosításához, hogy milyen típusú a kapcsolódó tulajdonsághoz hozzárendelt érték egy pozitív a kiadott modell <xref:System.TimeSpan>objektum.</xref:System.TimeSpan>"
  syntax:
    content: public PositiveTimeSpanValidatorAttribute ();
    parameters: []
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi egy példányát a <xref href=&quot;System.Configuration.PositiveTimeSpanValidator&quot;> </xref> osztály."
  remarks: "Használható a ValidatorInstance tulajdonság pozitív <xref:System.TimeSpan>érvényesítési objektum meghívásával a <xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName>metódus.</xref:System.Configuration.PositiveTimeSpanValidator.Validate%2A?displayProperty=fullName> </xref:System.TimeSpan>"
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "A <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> érvényesítő példány."
  overload: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute()
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute()
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.#ctor*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: PositiveTimeSpanValidatorAttribute
  nameWithType: PositiveTimeSpanValidatorAttribute.PositiveTimeSpanValidatorAttribute
- uid: System.Configuration.PositiveTimeSpanValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.PositiveTimeSpanValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: PositiveTimeSpanValidatorAttribute.ValidatorInstance
