### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SiteMapSection
  id: SiteMapSection
  children:
  - System.Web.Configuration.SiteMapSection.#ctor
  - System.Web.Configuration.SiteMapSection.DefaultProvider
  - System.Web.Configuration.SiteMapSection.Enabled
  - System.Web.Configuration.SiteMapSection.Properties
  - System.Web.Configuration.SiteMapSection.Providers
  langs:
  - csharp
  name: SiteMapSection
  nameWithType: SiteMapSection
  fullName: System.Web.Configuration.SiteMapSection
  type: Class
  summary: "Határozza meg a konfigurációs beállítások, amelyek támogatják az infrastruktúra konfigurálása, tárolására és webhely-navigáció megjelenítése. Ez az osztály nem örökölhető."
  remarks: "A SiteMapSection osztály programozott hozzáférés, és módosítsa a konfigurációs fájl tartalma módszert kínál a `siteMap` szakasz."
  example:
  - "This example demonstrates how to specify values declaratively for several attributes of the `siteMap` section, which can also be accessed as members of the SiteMapSection class.  \n  \n The following configuration file example shows how to specify values declaratively for the `siteMap` section.  \n  \n```  \n<system.web>  \n  <siteMap defaultProvider=\"XmlSiteMapReader\" enabled=\"true\">  \n    <providers>  \n      <clear />  \n      <add   \n        name=\"XmlSiteMapReader\"  \n        type=\"XmlSiteMapProvider, System.Web, Version=1.1.3300.0,  \n              Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a\"  \n        siteMapFile=\"my.sitemap\"   \n        description=\"XmlSiteMapProvider that loads my.sitemap\"/>  \n    </providers>  \n  </siteMap>  \n</system.web>  \n```  \n  \n The following code example demonstrates how to use the SiteMapSection class.  \n  \n [!code-vb[System.Web.Configuration.SiteMapSection#1](~/add/codesnippet/visualbasic/t-system.web.configurati_8_1.vb)]\n [!code-cs[System.Web.Configuration.SiteMapSection#1](~/add/codesnippet/csharp/t-system.web.configurati_8_1.cs)]"
  syntax:
    content: 'public sealed class SiteMapSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: SiteMapSection()
  nameWithType: SiteMapSection.SiteMapSection()
  fullName: System.Web.Configuration.SiteMapSection.SiteMapSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.SiteMapSection&quot;> </xref> osztály alapértelmezett beállításokkal."
  remarks: "A SiteMapSection konstruktor nem célja, hogy közvetlenül a kódból használni. Az ASP.NET konfigurációs rendszer nevezik. Példányának beszerezte a <xref:System.Web.Configuration.SiteMapSection>osztály használatával a <xref:System.Configuration.Configuration.GetSection%2A>metódus.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.SiteMapSection>"
  syntax:
    content: public SiteMapSection ();
    parameters: []
  overload: System.Web.Configuration.SiteMapSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.DefaultProvider
  id: DefaultProvider
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: DefaultProvider
  nameWithType: SiteMapSection.DefaultProvider
  fullName: System.Web.Configuration.SiteMapSection.DefaultProvider
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja az alapértelmezett navigációs szolgáltató nevét."
  remarks: "Navigációs szolgáltatók kezelésére szolgáló navigációs értékek a közös módon teszi közzé az API-k. A navigációs szolgáltatók is megadhat a `providers` az alszakasz a `siteMap` egy konfigurációs fájl részét."
  example:
  - "The following code example demonstrates how to use the DefaultProvider property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SiteMapSection> class.  \n  \n [!code-vb[System.Web.Configuration.SiteMapSection#2](~/add/codesnippet/visualbasic/p-system.web.configurati_66_1.vb)]\n [!code-cs[System.Web.Configuration.SiteMapSection#2](~/add/codesnippet/csharp/p-system.web.configurati_66_1.cs)]"
  syntax:
    content: public string DefaultProvider { get; set; }
    return:
      type: System.String
      description: "A szolgáltató neve a <xref:System.Web.Configuration.SiteMapSection.Providers*>tulajdonság vagy egy <xref:System.String.Empty>mező.</xref:System.String.Empty> </xref:System.Web.Configuration.SiteMapSection.Providers*> Az alapértelmezett érték <xref uid=&quot;langword_csharp_&quot;AspNetXmlSiteMapProvider&quot;&quot; name=&quot;&quot;AspNetXmlSiteMapProvider&quot;&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.SiteMapSection.DefaultProvider*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.Enabled
  id: Enabled
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: Enabled
  nameWithType: SiteMapSection.Enabled
  fullName: System.Web.Configuration.SiteMapSection.Enabled
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely jelzi, hogy engedélyezve van-e az ASP.NET hely térkép szolgáltatás."
  remarks: "Az Enabled tulajdonságot ad vissza, egy logikai érték, amely azt jelzi-e az ASP.NET navigációs szolgáltatás futási időben érhetők el."
  example:
  - "The following code example demonstrates how to use the Enabled property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SiteMapSection> class.  \n  \n [!code-vb[System.Web.Configuration.SiteMapSection#3](~/add/codesnippet/visualbasic/p-system.web.configurati_360_1.vb)]\n [!code-cs[System.Web.Configuration.SiteMapSection#3](~/add/codesnippet/csharp/p-system.web.configurati_360_1.cs)]"
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az ASP.NET webhely térkép engedélyezve van; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.SiteMapSection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.Properties
  id: Properties
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: Properties
  nameWithType: SiteMapSection.Properties
  fullName: System.Web.Configuration.SiteMapSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.SiteMapSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SiteMapSection.Providers
  id: Providers
  parent: System.Web.Configuration.SiteMapSection
  langs:
  - csharp
  name: Providers
  nameWithType: SiteMapSection.Providers
  fullName: System.Web.Configuration.SiteMapSection.Providers
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref> gyűjteményének <xref href=&quot;System.Configuration.ProviderSettings&quot;> </xref> objektumok."
  remarks: "Hely térkép szolgáltatók összetevői szerkezeti eléréséhez a helyhez. Megadhatja, hogy a hely térkép szolgáltatók a `providers` az alszakasz a `siteMap` egy konfigurációs fájl részét.       A <xref:System.Web.Configuration.SiteMapSection.DefaultProvider%2A>alapértelmezés szerint használt szolgáltató tulajdonságneveket.</xref:System.Web.Configuration.SiteMapSection.DefaultProvider%2A>"
  example:
  - "The following code example demonstrates how to use the Providers property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.SiteMapSection> class.  \n  \n [!code-vb[System.Web.Configuration.SiteMapSection#4](~/add/codesnippet/visualbasic/p-system.web.configurati_273_1.vb)]\n [!code-cs[System.Web.Configuration.SiteMapSection#4](~/add/codesnippet/csharp/p-system.web.configurati_273_1.cs)]"
  syntax:
    content: public System.Configuration.ProviderSettingsCollection Providers { get; }
    return:
      type: System.Configuration.ProviderSettingsCollection
      description: "A <xref href=&quot;System.Configuration.ProviderSettingsCollection&quot;> </xref> , amely tartalmazza a szolgáltatók beállítások vannak meghatározva a <xref uid=&quot;langword_csharp_providers&quot; name=&quot;providers&quot; href=&quot;&quot;> </xref> az alszakasz a <xref uid=&quot;langword_csharp_siteMap&quot; name=&quot;siteMap&quot; href=&quot;&quot;> </xref> a konfigurációs fájl részét."
  overload: System.Web.Configuration.SiteMapSection.Providers*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.SiteMapSection.#ctor
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: SiteMapSection()
  nameWithType: SiteMapSection.SiteMapSection()
  fullName: System.Web.Configuration.SiteMapSection.SiteMapSection()
- uid: System.Web.Configuration.SiteMapSection.DefaultProvider
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: DefaultProvider
  nameWithType: SiteMapSection.DefaultProvider
  fullName: System.Web.Configuration.SiteMapSection.DefaultProvider
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.SiteMapSection.Enabled
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Enabled
  nameWithType: SiteMapSection.Enabled
  fullName: System.Web.Configuration.SiteMapSection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.SiteMapSection.Properties
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Properties
  nameWithType: SiteMapSection.Properties
  fullName: System.Web.Configuration.SiteMapSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.SiteMapSection.Providers
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Providers
  nameWithType: SiteMapSection.Providers
  fullName: System.Web.Configuration.SiteMapSection.Providers
- uid: System.Configuration.ProviderSettingsCollection
  parent: System.Configuration
  isExternal: false
  name: ProviderSettingsCollection
  nameWithType: ProviderSettingsCollection
  fullName: System.Configuration.ProviderSettingsCollection
- uid: System.Web.Configuration.SiteMapSection.#ctor*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: SiteMapSection
  nameWithType: SiteMapSection.SiteMapSection
- uid: System.Web.Configuration.SiteMapSection.DefaultProvider*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: DefaultProvider
  nameWithType: SiteMapSection.DefaultProvider
- uid: System.Web.Configuration.SiteMapSection.Enabled*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Enabled
  nameWithType: SiteMapSection.Enabled
- uid: System.Web.Configuration.SiteMapSection.Properties*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Properties
  nameWithType: SiteMapSection.Properties
- uid: System.Web.Configuration.SiteMapSection.Providers*
  parent: System.Web.Configuration.SiteMapSection
  isExternal: false
  name: Providers
  nameWithType: SiteMapSection.Providers
