### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NetNamedPipeSecurity
  id: NetNamedPipeSecurity
  children:
  - System.ServiceModel.NetNamedPipeSecurity.#ctor
  - System.ServiceModel.NetNamedPipeSecurity.Mode
  - System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  - System.ServiceModel.NetNamedPipeSecurity.Transport
  langs:
  - csharp
  name: NetNamedPipeSecurity
  nameWithType: NetNamedPipeSecurity
  fullName: System.ServiceModel.NetNamedPipeSecurity
  type: Class
  summary: "Hozzáférést biztosít a nevesített cső kötéshez konfigurált biztonsági beállításait."
  remarks: ''
  example:
  - "The following code shows how to add a NetNamedPipeSecurity object to a <xref:System.ServiceModel.NetNamedPipeBinding> instance.  \n  \n [!code-cs[S_UENetNamedPipeSecurity#1](~/add/codesnippet/csharp/t-system.servicemodel.ne_2_1.cs)]"
  syntax:
    content: public sealed class NetNamedPipeSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: NetNamedPipeSecurity()
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity()
  fullName: System.ServiceModel.NetNamedPipeSecurity.NetNamedPipeSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.NetNamedPipeSecurity&quot;> </xref> osztály."
  syntax:
    content: public NetNamedPipeSecurity ();
    parameters: []
  overload: System.ServiceModel.NetNamedPipeSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode
  id: Mode
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
  fullName: System.ServiceModel.NetNamedPipeSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Lekérdezi vagy beállítja a biztonsági módot a nevesített cső kötés."
  remarks: "Ez a tulajdonság érvényes értékei: átviteli-alapú biztonság - átviteli - használata. Az alapértelmezett beállítás NTLM, amely nem biztosít a kiszolgáló hitelesítése használ.      -Nincs biztonsági none - használja."
  example:
  - "The following code shows how to set the Mode property:  \n  \n [!code-cs[S_UENetNamedPipeSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ne_3_1.cs)]"
  syntax:
    content: public System.ServiceModel.NetNamedPipeSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetNamedPipeSecurityMode
      description: "Értékét a <xref href=&quot;System.ServiceModel.NetNamedPipeSecurityMode&quot;> </xref> a nevesített cső kötés. Az alapértelmezett érték <xref href=&quot;System.ServiceModel.NetNamedPipeSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.NetNamedPipeSecurity.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Értéket ad vissza egy egy érték, amely azt jelzi, hogy a <xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>tulajdonság alapértelmezett értéke megváltozott, és kell szerializálni.</xref:System.ServiceModel.NetNamedPipeSecurity.Transport*> Ez használatos WCF által az XAML-integráció."
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a <xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>tulajdonság értéke kell lennie, mivel a szerializált; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.NetNamedPipeSecurity.Transport*>"
  overload: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport
  id: Transport
  parent: System.ServiceModel.NetNamedPipeSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
  fullName: System.ServiceModel.NetNamedPipeSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "A transport security lekérdezi a nevesített cső kötés."
  remarks: "Ez a módszer hozzáférést ad <xref:System.Net.Security.ProtectionLevel>a nevesített cső átvitel <xref:System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel%2A>.</xref:System.ServiceModel.NamedPipeTransportSecurity.ProtectionLevel%2A> keresztül</xref:System.Net.Security.ProtectionLevel>"
  example:
  - "The following code shows how to access the Transport property:  \n  \n [!code-cs[S_UENetNamedPipeSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ne_21_1.cs)]"
  syntax:
    content: public System.ServiceModel.NamedPipeTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.NamedPipeTransportSecurity
      description: "Értékét a <xref href=&quot;System.ServiceModel.NamedPipeTransportSecurity&quot;> </xref> a nevesített cső kötés."
  overload: System.ServiceModel.NetNamedPipeSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: NetNamedPipeSecurity()
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity()
  fullName: System.ServiceModel.NetNamedPipeSecurity.NetNamedPipeSecurity()
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
  fullName: System.ServiceModel.NetNamedPipeSecurity.Mode
- uid: System.ServiceModel.NetNamedPipeSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetNamedPipeSecurityMode
  nameWithType: NetNamedPipeSecurityMode
  fullName: System.ServiceModel.NetNamedPipeSecurityMode
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
  fullName: System.ServiceModel.NetNamedPipeSecurity.Transport
- uid: System.ServiceModel.NamedPipeTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: NamedPipeTransportSecurity
  nameWithType: NamedPipeTransportSecurity
  fullName: System.ServiceModel.NamedPipeTransportSecurity
- uid: System.ServiceModel.NetNamedPipeSecurity.#ctor*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: NetNamedPipeSecurity
  nameWithType: NetNamedPipeSecurity.NetNamedPipeSecurity
- uid: System.ServiceModel.NetNamedPipeSecurity.Mode*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Mode
  nameWithType: NetNamedPipeSecurity.Mode
- uid: System.ServiceModel.NetNamedPipeSecurity.ShouldSerializeTransport*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: NetNamedPipeSecurity.ShouldSerializeTransport
- uid: System.ServiceModel.NetNamedPipeSecurity.Transport*
  parent: System.ServiceModel.NetNamedPipeSecurity
  isExternal: false
  name: Transport
  nameWithType: NetNamedPipeSecurity.Transport
