### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ConnectionManagementElement
  id: ConnectionManagementElement
  children:
  - System.Net.Configuration.ConnectionManagementElement.#ctor
  - System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  - System.Net.Configuration.ConnectionManagementElement.Address
  - System.Net.Configuration.ConnectionManagementElement.MaxConnection
  - System.Net.Configuration.ConnectionManagementElement.Properties
  langs:
  - csharp
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement
  fullName: System.Net.Configuration.ConnectionManagementElement
  type: Class
  summary: "A távoli számítógéphez kapcsolatok maximális számát jelenti. Ez az osztály nem örökölhető."
  remarks: "This class corresponds to the [\\&lt;add\\&gt; Element for connectionManagement (Network Settings)](../Topic/%3Cadd%3E%20Element%20for%20connectionManagement%20\\(Network%20Settings\\).md) configuration element.  \n  \n This class is used to specify the maximum number of simultaneous connections to a remote computer.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ConnectionManagementElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Net.Configuration.ConnectionManagementElement&quot;> </xref> osztály."
  syntax:
    content: public ConnectionManagementElement ();
    parameters: []
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  id: '#ctor(System.String,System.Int32)'
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: ConnectionManagementElement(String,Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Net.Configuration.ConnectionManagementElement&quot;> </xref> osztály a megadott címmel és kapcsolatadatainak korlátot."
  remarks: "Ez a konstruktor beállítja a <xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>tulajdonságot `address` és a <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>tulajdonságot `maxConnection`.</xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A> </xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>"
  syntax:
    content: public ConnectionManagementElement (string address, int maxConnection);
    parameters:
    - id: address
      type: System.String
      description: "Egy karakterlánc, amely azonosítja az egy távoli számítógépre."
    - id: maxConnection
      type: System.Int32
      description: "Egész szám, amely azonosítja az engedélyezett kapcsolatok maximális számának `address` a helyi számítógépről."
  overload: System.Net.Configuration.ConnectionManagementElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  id: Address
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja a cím távoli számítógépeken."
  remarks: "Ez a tulajdonság az ismeretlen számítógépek kapcsolatok alapértelmezett számát beállítása a csillag (*) segítségével állíthatja be.       Ez a tulajdonság egy vagy több távoli számítógépet azonosít, és a <xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>tulajdonság határozza meg, hogy hány egyidejű kapcsolatok használata engedélyezett a helyi számítógép és a távoli számítógépek között.</xref:System.Net.Configuration.ConnectionManagementElement.MaxConnection%2A>"
  syntax:
    content: public string Address { get; set; }
    return:
      type: System.String
      description: "Egy karakterlánc, amely egy IP-cím vagy a DNS-név leíró reguláris kifejezést tartalmaz."
  overload: System.Net.Configuration.ConnectionManagementElement.Address*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  id: MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja a beállíthatja, hogy egy távoli számítógépre kapcsolatok maximális számát."
  remarks: "Ez a tulajdonság határozza meg, hány egyidejű kapcsolatainak engedélyezését a helyi számítógépen és a távoli számítógép között. A távoli számítógépet adott meg a <xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>tulajdonság.</xref:System.Net.Configuration.ConnectionManagementElement.Address%2A>       A MaxConnection tulajdonság <xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>.</xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName> száma Ha egy alkalmazás nem változik <xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName>az alapértelmezett, majd a MaxConnection tulajdonság alkalmazza a teljes alkalmazás tartományi.</xref:System.Net.WebRequest.ConnectionGroupName%2A?displayProperty=fullName> Ha csak egyetlen alkalmazástartományt az alkalmazás fut, majd a MaxConnection tulajdonság értéke alkalmazásszintű."
  syntax:
    content: public int MaxConnection { get; set; }
    return:
      type: System.Int32
      description: "A kapcsolatok maximális számát meghatározó egész szám."
  overload: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  id: Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  langs:
  - csharp
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Net.Configuration.ConnectionManagementElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement()
  nameWithType: ConnectionManagementElement.ConnectionManagementElement()
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement()
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor(System.String,System.Int32)
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement(String,Int32)
  nameWithType: ConnectionManagementElement.ConnectionManagementElement(String,Int32)
  fullName: System.Net.Configuration.ConnectionManagementElement.ConnectionManagementElement(String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Net.Configuration.ConnectionManagementElement.Address
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
  fullName: System.Net.Configuration.ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
  fullName: System.Net.Configuration.ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
  fullName: System.Net.Configuration.ConnectionManagementElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ConnectionManagementElement.#ctor*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: ConnectionManagementElement
  nameWithType: ConnectionManagementElement.ConnectionManagementElement
- uid: System.Net.Configuration.ConnectionManagementElement.Address*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Address
  nameWithType: ConnectionManagementElement.Address
- uid: System.Net.Configuration.ConnectionManagementElement.MaxConnection*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: MaxConnection
  nameWithType: ConnectionManagementElement.MaxConnection
- uid: System.Net.Configuration.ConnectionManagementElement.Properties*
  parent: System.Net.Configuration.ConnectionManagementElement
  isExternal: false
  name: Properties
  nameWithType: ConnectionManagementElement.Properties
