### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  id: StandardBindingReliableSessionElement
  children:
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(System.ServiceModel.ReliableSession)
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(System.ServiceModel.ReliableSession)
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  - System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
  langs:
  - csharp
  name: StandardBindingReliableSessionElement
  nameWithType: StandardBindingReliableSessionElement
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  type: Class
  summary: "A WS-Reliable üzenetküldést szabványos kötés definiált konfigurációs beállítást jelöli."
  syntax:
    content: 'public class StandardBindingReliableSessionElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: StandardBindingReliableSessionElement()
  nameWithType: StandardBindingReliableSessionElement.StandardBindingReliableSessionElement()
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.StandardBindingReliableSessionElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.StandardBindingReliableSessionElement&quot;> </xref> osztály."
  syntax:
    content: public StandardBindingReliableSessionElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(System.ServiceModel.ReliableSession)
  id: ApplyConfiguration(System.ServiceModel.ReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: ApplyConfiguration(ReliableSession)
  nameWithType: StandardBindingReliableSessionElement.ApplyConfiguration(ReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(ReliableSession)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "A megadott kötési elem tartalmának vonatkozik ez a konfigurációs szakasz."
  syntax:
    content: public void ApplyConfiguration (System.ServiceModel.ReliableSession reliableSession);
    parameters:
    - id: reliableSession
      type: System.ServiceModel.ReliableSession
      description: "A konfigurációs elem alkalmazni."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>reliableSession</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  id: InactivityTimeout
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: InactivityTimeout
  nameWithType: StandardBindingReliableSessionElement.InactivityTimeout
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a <xref:System.TimeSpan>érték, amely meghatározza a maximális időtartamot, a csatorna lehetővé teszi, hogy a többi kommunikációs fél további üzeneteire küldése előtt a csatornát hibásnak nyilvánítaná.</xref:System.TimeSpan>"
  remarks: "Tevékenység csatornán történt egy alkalmazás vagy infrastruktúra-üzenet fogadásakor típusúként van definiálva. Ez a tulajdonság szabja meg a maximális időt egy inaktív munkamenet életben tartása. Ha hosszabb ideig nem tevékenységet, a munkamenet megszakítása a infrastruktúra és a csatorna hibák."
  syntax:
    content: public TimeSpan InactivityTimeout { get; set; }
    return:
      type: System.TimeSpan
      description: "A <xref:System.TimeSpan>érték, amely meghatározza a maximális időtartamot, a csatorna lehetővé teszi, hogy a többi kommunikációs fél további üzeneteire küldése előtt a csatornát hibásnak nyilvánítaná.</xref:System.TimeSpan> Az alapértelmezett érték 00:10:00."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(System.ServiceModel.ReliableSession)
  id: InitializeFrom(System.ServiceModel.ReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: InitializeFrom(ReliableSession)
  nameWithType: StandardBindingReliableSessionElement.InitializeFrom(ReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(ReliableSession)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "A konfigurációs elem a megadott szakasz értékekkel inicializál."
  syntax:
    content: public void InitializeFrom (System.ServiceModel.ReliableSession reliableSession);
    parameters:
    - id: reliableSession
      type: System.ServiceModel.ReliableSession
      description: "A konfigurációs elem inicializálását."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>reliableSession</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  id: Ordered
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: Ordered
  nameWithType: StandardBindingReliableSessionElement.Ordered
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a logikai értéket, amely meghatározza, hogy az üzenetek kézbesítése garantáltan a küldés sorrendjében."
  syntax:
    content: public bool Ordered { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az üzenetek kézbesítése garantáltan a küldés; sorrendjében <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Ha üzenetek sorrendje nem is érkeznek. Az alapértelmezett érték <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  langs:
  - csharp
  name: Properties
  nameWithType: StandardBindingReliableSessionElement.Properties
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> gyűjteményét tartalmazó példány <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> objektumok, amelyek lehetnek attribútumok vagy <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> objektumokat a konfigurációs elem."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> gyűjteményét tartalmazó példány <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> objektumok, amelyek lehetnek attribútumok vagy <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> a konfigurációs elem objektumok."
  overload: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: StandardBindingReliableSessionElement()
  nameWithType: StandardBindingReliableSessionElement.StandardBindingReliableSessionElement()
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.StandardBindingReliableSessionElement()
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(System.ServiceModel.ReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: ApplyConfiguration(ReliableSession)
  nameWithType: StandardBindingReliableSessionElement.ApplyConfiguration(ReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration(ReliableSession)
- uid: System.ServiceModel.ReliableSession
  parent: System.ServiceModel
  isExternal: false
  name: ReliableSession
  nameWithType: ReliableSession
  fullName: System.ServiceModel.ReliableSession
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: InactivityTimeout
  nameWithType: StandardBindingReliableSessionElement.InactivityTimeout
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(System.ServiceModel.ReliableSession)
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: InitializeFrom(ReliableSession)
  nameWithType: StandardBindingReliableSessionElement.InitializeFrom(ReliableSession)
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom(ReliableSession)
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: Ordered
  nameWithType: StandardBindingReliableSessionElement.Ordered
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: Properties
  nameWithType: StandardBindingReliableSessionElement.Properties
  fullName: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.#ctor*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: StandardBindingReliableSessionElement
  nameWithType: StandardBindingReliableSessionElement.StandardBindingReliableSessionElement
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.ApplyConfiguration*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: ApplyConfiguration
  nameWithType: StandardBindingReliableSessionElement.ApplyConfiguration
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InactivityTimeout*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: InactivityTimeout
  nameWithType: StandardBindingReliableSessionElement.InactivityTimeout
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.InitializeFrom*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: InitializeFrom
  nameWithType: StandardBindingReliableSessionElement.InitializeFrom
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Ordered*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: Ordered
  nameWithType: StandardBindingReliableSessionElement.Ordered
- uid: System.ServiceModel.Configuration.StandardBindingReliableSessionElement.Properties*
  parent: System.ServiceModel.Configuration.StandardBindingReliableSessionElement
  isExternal: false
  name: Properties
  nameWithType: StandardBindingReliableSessionElement.Properties
