### YamlMime:ManagedReference
items:
- uid: System.Configuration.SubclassTypeValidatorAttribute
  id: SubclassTypeValidatorAttribute
  children:
  - System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  - System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  - System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  langs:
  - csharp
  name: SubclassTypeValidatorAttribute
  nameWithType: SubclassTypeValidatorAttribute
  fullName: System.Configuration.SubclassTypeValidatorAttribute
  type: Class
  summary: "Deklaratív módon arra utasítja a .NET-keretrendszer érvényesítést hajt végre egy konfigurációs tulajdonság. Ez az osztály nem örökölhető."
  remarks: "Használja a <xref:System.Configuration.IntegerValidatorAttribute>Adja meg egy konfigurációs tulajdonság attribútum.</xref:System.Configuration.IntegerValidatorAttribute> Ez a, kérje meg a .NET-keretrendszer ellenőrzése a tulajdonság egy SubclassTypeValidatorAttribute attribútum segítségével, és átadni a decorating paraméterek értékét.       Csak a Tulajdonságok típusa SubclassTypeValidatorAttribute attribútumok alkalmazhat."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SubclassTypeValidatorAttribute : System.Configuration.ConfigurationValidatorAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.ConfigurationValidatorAttribute
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationValidatorAttribute.ValidatorType
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: SubclassTypeValidatorAttribute(Type)
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  fullName: System.Configuration.SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.SubclassTypeValidatorAttribute&quot;> </xref> osztály."
  remarks: "Győződjön meg arról, hogy a kapcsolódó tulajdonsághoz hozzárendelt érték egy olyan alaposztályból Ez a konstruktor használja a kiadott modellben."
  syntax:
    content: public SubclassTypeValidatorAttribute (Type baseClass);
    parameters:
    - id: baseClass
      type: System.Type
      description: "Alaposztály típusa."
  overload: System.Configuration.SubclassTypeValidatorAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  id: BaseClass
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Az alaptípus a érvényesített objektum beolvasása."
  syntax:
    content: public Type BaseClass { get; }
    return:
      type: System.Type
      description: "Az objektum az érvényesített alaptípusa."
  overload: System.Configuration.SubclassTypeValidatorAttribute.BaseClass*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  id: ValidatorInstance
  parent: System.Configuration.SubclassTypeValidatorAttribute
  langs:
  - csharp
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Az érvényesítő attribútumpéldány lekérdezi."
  syntax:
    content: public override System.Configuration.ConfigurationValidatorBase ValidatorInstance { get; }
    return:
      type: System.Configuration.ConfigurationValidatorBase
      description: "Az aktuális <xref href=&quot;System.Configuration.ConfigurationValidatorBase&quot;> </xref> példány."
  overload: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationValidatorAttribute
  isExternal: false
  name: System.Configuration.ConfigurationValidatorAttribute
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor(System.Type)
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: SubclassTypeValidatorAttribute(Type)
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
  fullName: System.Configuration.SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
  fullName: System.Configuration.SubclassTypeValidatorAttribute.BaseClass
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
  fullName: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance
- uid: System.Configuration.ConfigurationValidatorBase
  parent: System.Configuration
  isExternal: false
  name: ConfigurationValidatorBase
  nameWithType: ConfigurationValidatorBase
  fullName: System.Configuration.ConfigurationValidatorBase
- uid: System.Configuration.SubclassTypeValidatorAttribute.#ctor*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: SubclassTypeValidatorAttribute
  nameWithType: SubclassTypeValidatorAttribute.SubclassTypeValidatorAttribute
- uid: System.Configuration.SubclassTypeValidatorAttribute.BaseClass*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: BaseClass
  nameWithType: SubclassTypeValidatorAttribute.BaseClass
- uid: System.Configuration.SubclassTypeValidatorAttribute.ValidatorInstance*
  parent: System.Configuration.SubclassTypeValidatorAttribute
  isExternal: false
  name: ValidatorInstance
  nameWithType: SubclassTypeValidatorAttribute.ValidatorInstance
