### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  id: ApplicationChangedEventArgs
  children:
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  - System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  langs:
  - csharp
  name: ApplicationChangedEventArgs
  nameWithType: ApplicationChangedEventArgs
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  type: Class
  summary: "A visszahívási metódus megfelelő információkkal amikor egy <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication.ApplicationChanged&quot;> </xref> esemény akkor következik be."
  remarks: "Egy <xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged>esemény jelenik meg, amikor: - társ elindít egy alkalmazást együttműködésén belül - társ karakterlánccal végződik-e egy alkalmazás egy együttműködés belül - a <xref:System.Net.PeerToPeer.Collaboration.PeerContact>együttműködés társ képviselő objektum tulajdonságainak módosítását rendelkezik, a társított becenév - az alkalmazási módosítja a társ partner számítógép - társ áthelyezése egy másik IP-címet a hálózati – például minden osztály az ApplicationChangedEventArgs osztályt használó megköveteli a <xref:System.Security.Permissions.PermissionState>pedig nem korlátozott.</xref:System.Security.Permissions.PermissionState> </xref:System.Net.PeerToPeer.Collaboration.PeerContact> </xref:System.Net.PeerToPeer.Collaboration.ContactManager.ApplicationChanged> Ebben az állapotban jön létre, amikor a <xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>objektum.</xref:System.Net.PeerToPeer.Collaboration.PeerCollaboration>"
  syntax:
    content: 'public class ApplicationChangedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Lekérdezi a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> az az esemény időpontja."
  remarks: "Amennyiben szerepel, az alapértelmezett érték a tulajdonság van `null`."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "A <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> frissített példány."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  id: PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "A módosítás típusa lekérdezi a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> , amely történt."
  remarks: "Amennyiben szerepel, az alapértelmezett érték a tulajdonság van `null`."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerChangeType PeerChangeType { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerChangeType
      description: "A <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerChangeType&quot;> </xref> számbavételi érték, amely meghatározza az olyan változást, amely végre lett a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Lekérdezi a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> társított a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "<xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;></xref>társított a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Lekérdezi a végpont, amelynek <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> adatai megváltoztak."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "A <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> , amely tartalmazza a végpont melyik alkalmazás adatai megváltoztak. Ha explicit módon megadott, alapértelmezett összes tulajdonságának értéke <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> referencia típusok és típusú tulajdonságok nulla (0) <xref uid=&quot;langword_csharp_int&quot; name=&quot;int&quot; href=&quot;&quot;> </xref>."
  overload: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.PeerChangeType
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerChangeType
  nameWithType: PeerChangeType
  fullName: System.Net.PeerToPeer.Collaboration.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerApplication
  nameWithType: ApplicationChangedEventArgs.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerChangeType*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerChangeType
  nameWithType: ApplicationChangedEventArgs.PeerChangeType
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerContact
  nameWithType: ApplicationChangedEventArgs.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.ApplicationChangedEventArgs
  isExternal: false
  name: PeerEndPoint
  nameWithType: ApplicationChangedEventArgs.PeerEndPoint
