### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  id: FindCriteriaElement
  children:
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  - System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  langs:
  - csharp
  name: FindCriteriaElement
  nameWithType: FindCriteriaElement
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  type: Class
  summary: "Egy konfigurációs elem által használt ügyfélalkalmazás kereséséhez munkafolyamat-szolgáltatásokat hálózaton vagy az interneten keresztül állítható tartalmazó kezeli."
  syntax:
    content: 'public sealed class FindCriteriaElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: FindCriteriaElement()
  nameWithType: FindCriteriaElement.FindCriteriaElement()
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.FindCriteriaElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;> </xref> osztály."
  syntax:
    content: public FindCriteriaElement ();
    parameters: []
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  id: ContractTypeNames
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Lekérdezi a munkafolyamat-szolgáltatás üzenetegyezmény-típusokat, a neveket tartalmazó konfigurációs elemek gyűjteménye."
  syntax:
    content: public System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection ContractTypeNames { get; }
    return:
      type: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
      description: "Elemek gyűjteménye."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  id: Duration
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Duration
  nameWithType: FindCriteriaElement.Duration
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Lekérdezi vagy beállítja azt a maximális várakozási idő a válaszokat a szolgáltatások a hálózati vagy az interneten."
  syntax:
    content: public TimeSpan Duration { get; set; }
    return:
      type: System.TimeSpan
      description: "A timespan objektum a határozza meg a várakozási időszakot."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  id: Extensions
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.ServiceModel.Configuration.XmlElementElementCollection&quot;> </xref> objektum, amely a bővítményeket biztosítanak egy <xref href=&quot;System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;> </xref>."
  syntax:
    content: public System.ServiceModel.Configuration.XmlElementElementCollection Extensions { get; }
    return:
      type: System.ServiceModel.Configuration.XmlElementElementCollection
      description: "Elemek gyűjteménye."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  id: MaxResults
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Lekérdezi vagy beállítja a várnia kell, a hálózaton vagy az internetes szolgáltatások válaszok maximális száma."
  remarks: "Ha MaxResults válaszok előtt fogadott <xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration%2A>lejárt, a keresési művelet véget ér.</xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration%2A>"
  syntax:
    content: public int MaxResults { get; set; }
    return:
      type: System.Int32
      description: "A maximális számát."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  id: Properties
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Properties
  nameWithType: FindCriteriaElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  id: ScopeMatchBy
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Lekérdezi vagy beállítja az URI, amely egy szolgáltatás, amelyben keres a, és mely tagjai elleni helyét és típusát jelöli meg a <xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*>gyűjtemény teljesül.</xref:System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*>"
  syntax:
    content: public Uri ScopeMatchBy { get; set; }
    return:
      type: System.Uri
      description: "Az URI-azonosítója egy szolgáltatásalkalmazást."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  id: Scopes
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  langs:
  - csharp
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery.Configuration
  summary: "Lekérdezi a gyűjteménye <xref href=&quot;System.ServiceModel.Discovery.Configuration.FindCriteriaElement&quot;> </xref> objektumokat, amelyek abszolút URI-k egy adott szolgáltatás vagy a szolgáltatások kereséséhez a keresési művelet során használt."
  remarks: "Ha az adott szolgáltatás megtalálható, a sikeres egyeztetés között a szolgáltatás URI-azonosítója és a hatókör URI-t, néha hatókör szabályok, amelyek kezelik az egyező komplikációk segítségével történt."
  syntax:
    content: public System.ServiceModel.Discovery.Configuration.ScopeElementCollection Scopes { get; }
    return:
      type: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
      description: "URI-azonosítók tartalmazó elemek gyűjteménye."
  overload: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: FindCriteriaElement()
  nameWithType: FindCriteriaElement.FindCriteriaElement()
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.FindCriteriaElement()
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames
- uid: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
  parent: System.ServiceModel.Discovery.Configuration
  isExternal: false
  name: ContractTypeNameElementCollection
  nameWithType: ContractTypeNameElementCollection
  fullName: System.ServiceModel.Discovery.Configuration.ContractTypeNameElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Duration
  nameWithType: FindCriteriaElement.Duration
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration
- uid: System.TimeSpan
  parent: System
  isExternal: true
  name: TimeSpan
  nameWithType: TimeSpan
  fullName: System.TimeSpan
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions
- uid: System.ServiceModel.Configuration.XmlElementElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: XmlElementElementCollection
  nameWithType: XmlElementElementCollection
  fullName: System.ServiceModel.Configuration.XmlElementElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Properties
  nameWithType: FindCriteriaElement.Properties
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
  fullName: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes
- uid: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
  parent: System.ServiceModel.Discovery.Configuration
  isExternal: false
  name: ScopeElementCollection
  nameWithType: ScopeElementCollection
  fullName: System.ServiceModel.Discovery.Configuration.ScopeElementCollection
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.#ctor*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: FindCriteriaElement
  nameWithType: FindCriteriaElement.FindCriteriaElement
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ContractTypeNames*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ContractTypeNames
  nameWithType: FindCriteriaElement.ContractTypeNames
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Duration*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Duration
  nameWithType: FindCriteriaElement.Duration
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Extensions*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Extensions
  nameWithType: FindCriteriaElement.Extensions
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.MaxResults*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: MaxResults
  nameWithType: FindCriteriaElement.MaxResults
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Properties*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Properties
  nameWithType: FindCriteriaElement.Properties
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.ScopeMatchBy*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: ScopeMatchBy
  nameWithType: FindCriteriaElement.ScopeMatchBy
- uid: System.ServiceModel.Discovery.Configuration.FindCriteriaElement.Scopes*
  parent: System.ServiceModel.Discovery.Configuration.FindCriteriaElement
  isExternal: false
  name: Scopes
  nameWithType: FindCriteriaElement.Scopes
