### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProtocolsConfigurationHandler
  id: ProtocolsConfigurationHandler
  children:
  - System.Web.Configuration.ProtocolsConfigurationHandler.#ctor
  - System.Web.Configuration.ProtocolsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: ProtocolsConfigurationHandler
  nameWithType: ProtocolsConfigurationHandler
  fullName: System.Web.Configuration.ProtocolsConfigurationHandler
  type: Class
  summary: "A konfigurációs kezelő protokollok jelöli."
  remarks: "A ProtocolsConfigurationHandler osztály a .NET-keretrendszer 3.5-ös verziója jelent meg. További információkért lásd: [verziója és a függőségek](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: 'public sealed class ProtocolsConfigurationHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.ProtocolsConfigurationHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ProtocolsConfigurationHandler
  langs:
  - csharp
  name: ProtocolsConfigurationHandler()
  nameWithType: ProtocolsConfigurationHandler.ProtocolsConfigurationHandler()
  fullName: System.Web.Configuration.ProtocolsConfigurationHandler.ProtocolsConfigurationHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.ProtocolsConfigurationHandler&quot;> </xref> osztály."
  syntax:
    content: public ProtocolsConfigurationHandler ();
    parameters: []
  overload: System.Web.Configuration.ProtocolsConfigurationHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProtocolsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.ProtocolsConfigurationHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: ProtocolsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.ProtocolsConfigurationHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Új objektumot hoz létre protokollok konfigurációs."
  syntax:
    content: public object Create (object parent, object configContextObj, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "A szülő konfigurációs szakasz."
    - id: configContextObj
      type: System.Object
      description: "A konfigurációs környezeti objektumot."
    - id: section
      type: System.Xml.XmlNode
      description: "A konfigurációs szakasz létrehozásához."
    return:
      type: System.Object
      description: "Az új protokollok konfigurációs objektum."
  overload: System.Web.Configuration.ProtocolsConfigurationHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.ProtocolsConfigurationHandler.#ctor
  parent: System.Web.Configuration.ProtocolsConfigurationHandler
  isExternal: false
  name: ProtocolsConfigurationHandler()
  nameWithType: ProtocolsConfigurationHandler.ProtocolsConfigurationHandler()
  fullName: System.Web.Configuration.ProtocolsConfigurationHandler.ProtocolsConfigurationHandler()
- uid: System.Web.Configuration.ProtocolsConfigurationHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.ProtocolsConfigurationHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: ProtocolsConfigurationHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.ProtocolsConfigurationHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.ProtocolsConfigurationHandler.#ctor*
  parent: System.Web.Configuration.ProtocolsConfigurationHandler
  isExternal: false
  name: ProtocolsConfigurationHandler
  nameWithType: ProtocolsConfigurationHandler.ProtocolsConfigurationHandler
- uid: System.Web.Configuration.ProtocolsConfigurationHandler.Create*
  parent: System.Web.Configuration.ProtocolsConfigurationHandler
  isExternal: false
  name: Create
  nameWithType: ProtocolsConfigurationHandler.Create
