### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  id: ServiceSettingsResponseInfo
  children:
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  - System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  langs:
  - csharp
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  type: Class
  summary: "Vissza, ha egy társ kérelmek egy társ feloldó szolgáltatás beállításait ismerteti."
  remarks: "Ez az osztály példányai elsősorban információkat ad át szolgáltatás beállításokat választ a feloldó szolgáltatás az adott szolgáltatás egy hálózati ügyfélhez."
  syntax:
    content: >-
      [System.ServiceModel.MessageContract(IsWrapped=false)]

      public class ServiceSettingsResponseInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Egy új alapértelmezett példányát inicializálja a <xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;> </xref> osztály."
  remarks: "Az alapértelmezett érték `control` értéke TRUE."
  syntax:
    content: public ServiceSettingsResponseInfo ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  id: '#ctor(System.Boolean)'
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo&quot;> </xref> osztály a megadott átirányítási házirend értékű."
  syntax:
    content: public ServiceSettingsResponseInfo (bool control);
    parameters:
    - id: control
      type: System.Boolean
      description: "<xref:System.Boolean>Ez azt jelzi, hogy hivatkozásokat a feloldó szolgáltatás által átadott.</xref:System.Boolean>"
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  id: ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Lekérdezi vagy beállítja, hogy hivatkozásokat a feloldó szolgáltatás által átadott."
  syntax:
    content: public bool ControlMeshShape { get; set; }
    return:
      type: System.Boolean
      description: "IGAZ, ha részt vesz a háló társaktól érkező átirányítások átadott; hamis, ha azok figyelmen kívül lesznek hagyva."
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  id: HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  langs:
  - csharp
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Azt jelzi, hogy a típus szerializált példányát tartalmazó üzenet törzsét formátuma megfelelő."
  syntax:
    content: public bool HasBody ();
    parameters: []
    return:
      type: System.Boolean
      description: "IGAZ, ha a szolgáltatás beállításainak információk választörzs megfelelően formázott a feladó; Ha nem FALSE."
  overload: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo()
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor(System.Boolean)
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo(Boolean)
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ServiceSettingsResponseInfo(Boolean)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody()
  nameWithType: ServiceSettingsResponseInfo.HasBody()
  fullName: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody()
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.#ctor*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ServiceSettingsResponseInfo
  nameWithType: ServiceSettingsResponseInfo.ServiceSettingsResponseInfo
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.ControlMeshShape*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: ControlMeshShape
  nameWithType: ServiceSettingsResponseInfo.ControlMeshShape
- uid: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo.HasBody*
  parent: System.ServiceModel.PeerResolvers.ServiceSettingsResponseInfo
  isExternal: false
  name: HasBody
  nameWithType: ServiceSettingsResponseInfo.HasBody
