### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WindowsServiceElement
  id: WindowsServiceElement
  children:
  - System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  - System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  - System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  - System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  - System.ServiceModel.Configuration.WindowsServiceElement.Properties
  langs:
  - csharp
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement
  fullName: System.ServiceModel.Configuration.WindowsServiceElement
  type: Class
  summary: "Egy konfigurációs elem, amely meghatározza egy Windows-szolgáltatás hitelesítő adat beállításainak jelöli. Ez az osztály nem örökölhető."
  remarks: ''
  example:
  - <xref:System.ServiceModel.Security.WindowsServiceCredential>
  syntax:
    content: 'public sealed class WindowsServiceElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: WindowsServiceElement()
  nameWithType: WindowsServiceElement.WindowsServiceElement()
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.WindowsServiceElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.WindowsServiceElement&quot;> </xref> osztály."
  syntax:
    content: public WindowsServiceElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WindowsServiceElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  id: AllowAnonymousLogons
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a logikai értéket, amely meghatározza, hogy a névtelen felhasználók bejelentkezhet."
  remarks: "Egy olyan kötésen használata a Windows szolgáltatás hitelesítő adatait, a rendszer nem engedélyezi a névtelen hozzáférést alapértelmezés szerint. Ez azt jelenti, hogy csak tartomány vagy munkacsoport hitelesített felhasználók férhetnek hozzá a rendszer. A névtelen, nem hitelesített felhasználó hozzáférhessen a szolgáltatáshoz használhatja ezt a tulajdonságot. Meg kell körültekintően járjon el ez a beállítás használata esetén."
  syntax:
    content: public bool AllowAnonymousLogons { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a névtelen felhasználók bejelentkezhet; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  id: Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: Copy(WindowsServiceElement)
  nameWithType: WindowsServiceElement.Copy(WindowsServiceElement)
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Copy(WindowsServiceElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Másolja a konfigurációs elem az adott konfigurációs elem tartalmát."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.WindowsServiceElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.WindowsServiceElement
      description: "A konfigurációs elem másolása."
  overload: System.ServiceModel.Configuration.WindowsServiceElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "A konfigurációs fájl csak olvasható."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  id: IncludeWindowsGroups
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy a Windows-csoportok a biztonsági környezet szerepel."
  remarks: "Ez a tulajdonság `true` van a teljesítményre gyakorolt hatás eredményezi egy teljes csoport kiterjesztése. Ez a tulajdonság beállítása `false` nem kell létesíteni a csoportokat, ha egy felhasználó tartozik."
  syntax:
    content: public bool IncludeWindowsGroups { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a Windows-csoportok tartoznak a biztonsági környezet; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  langs:
  - csharp
  name: Properties
  nameWithType: WindowsServiceElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.WindowsServiceElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: WindowsServiceElement()
  nameWithType: WindowsServiceElement.WindowsServiceElement()
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.WindowsServiceElement()
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy(System.ServiceModel.Configuration.WindowsServiceElement)
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Copy(WindowsServiceElement)
  nameWithType: WindowsServiceElement.Copy(WindowsServiceElement)
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Copy(WindowsServiceElement)
- uid: System.ServiceModel.Configuration.WindowsServiceElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement
  fullName: System.ServiceModel.Configuration.WindowsServiceElement
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Properties
  nameWithType: WindowsServiceElement.Properties
  fullName: System.ServiceModel.Configuration.WindowsServiceElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WindowsServiceElement.#ctor*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: WindowsServiceElement
  nameWithType: WindowsServiceElement.WindowsServiceElement
- uid: System.ServiceModel.Configuration.WindowsServiceElement.AllowAnonymousLogons*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: AllowAnonymousLogons
  nameWithType: WindowsServiceElement.AllowAnonymousLogons
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Copy*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Copy
  nameWithType: WindowsServiceElement.Copy
- uid: System.ServiceModel.Configuration.WindowsServiceElement.IncludeWindowsGroups*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: IncludeWindowsGroups
  nameWithType: WindowsServiceElement.IncludeWindowsGroups
- uid: System.ServiceModel.Configuration.WindowsServiceElement.Properties*
  parent: System.ServiceModel.Configuration.WindowsServiceElement
  isExternal: false
  name: Properties
  nameWithType: WindowsServiceElement.Properties
