### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection
  id: BackupListCollection
  children:
  - System.ServiceModel.Routing.Configuration.BackupListCollection.#ctor
  - System.ServiceModel.Routing.Configuration.BackupListCollection.Add(System.ServiceModel.Routing.Configuration.BackupEndpointCollection)
  - System.ServiceModel.Routing.Configuration.BackupListCollection.Clear
  - System.ServiceModel.Routing.Configuration.BackupListCollection.CreateNewElement
  - System.ServiceModel.Routing.Configuration.BackupListCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Routing.Configuration.BackupListCollection.Item(System.String)
  - System.ServiceModel.Routing.Configuration.BackupListCollection.Remove(System.ServiceModel.Routing.Configuration.BackupEndpointCollection)
  langs:
  - csharp
  name: BackupListCollection
  nameWithType: BackupListCollection
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection
  type: Class
  summary: "A konfigurációs elem, amely tartalmaz egy gyűjteményét jelenti <xref href=&quot;System.ServiceModel.Routing.Configuration.BackupEndpointCollection&quot;> </xref> példányok."
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.ServiceModel.Routing.Configuration.BackupEndpointCollection), AddItemName="backupList")]

      public class BackupListCollection : System.Configuration.ConfigurationElementCollection
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Properties
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CollectionType
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.ElementName
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  langs:
  - csharp
  name: BackupListCollection()
  nameWithType: BackupListCollection.BackupListCollection()
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.BackupListCollection()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.ServiceModel.Routing.Configuration.BackupListCollection&quot;> </xref> osztály."
  syntax:
    content: public BackupListCollection ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.BackupListCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Add(System.ServiceModel.Routing.Configuration.BackupEndpointCollection)
  id: Add(System.ServiceModel.Routing.Configuration.BackupEndpointCollection)
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  langs:
  - csharp
  name: Add(BackupEndpointCollection)
  nameWithType: BackupListCollection.Add(BackupEndpointCollection)
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.Add(BackupEndpointCollection)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Hozzáad egy új <xref href=&quot;System.ServiceModel.Routing.Configuration.BackupEndpointCollection&quot;> </xref> a gyűjteményhez."
  syntax:
    content: public void Add (System.ServiceModel.Routing.Configuration.BackupEndpointCollection element);
    parameters:
    - id: element
      type: System.ServiceModel.Routing.Configuration.BackupEndpointCollection
      description: "A biztonsági mentési végpont lehet hozzáadni."
  overload: System.ServiceModel.Routing.Configuration.BackupListCollection.Add*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Clear
  id: Clear
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: BackupListCollection.Clear()
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.Clear()
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Eltávolítja az összes elem a gyűjteményből."
  syntax:
    content: public void Clear ();
    parameters: []
  overload: System.ServiceModel.Routing.Configuration.BackupListCollection.Clear*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.CreateNewElement
  id: CreateNewElement
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  langs:
  - csharp
  name: CreateNewElement()
  nameWithType: BackupListCollection.CreateNewElement()
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.CreateNewElement()
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Létrehoz egy új <xref href=&quot;System.ServiceModel.Routing.Configuration.BackupEndpointCollection&quot;> </xref>."
  syntax:
    content: protected override System.Configuration.ConfigurationElement CreateNewElement ();
    parameters: []
    return:
      type: System.Configuration.ConfigurationElement
      description: "Új konfigurációs elemet."
  overload: System.ServiceModel.Routing.Configuration.BackupListCollection.CreateNewElement*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: BackupListCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Lekérdezi a megadott konfigurációs elem elem kulcsa."
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "A konfigurációs elem kulcsa vissza."
    return:
      type: System.Object
      description: "A megadott konfigurációs elem kulcsa."
  overload: System.ServiceModel.Routing.Configuration.BackupListCollection.GetElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Item(System.String)
  id: Item(System.String)
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  langs:
  - csharp
  name: Item(String)
  nameWithType: BackupListCollection.Item(String)
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.Item(String)
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.ServiceModel.Routing.Configuration.BackupEndpointCollection&quot;> </xref> a megadott indexű."
  syntax:
    content: public System.ServiceModel.Routing.Configuration.BackupEndpointCollection this[string name] { get; }
    parameters:
    - id: name
      type: System.String
      description: "A kulcs az elem érhető el."
    return:
      type: System.ServiceModel.Routing.Configuration.BackupEndpointCollection
      description: "Egy biztonsági mentési végpontot, amely megfelel a megadott kulcs."
  overload: System.ServiceModel.Routing.Configuration.BackupListCollection.Item*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Remove(System.ServiceModel.Routing.Configuration.BackupEndpointCollection)
  id: Remove(System.ServiceModel.Routing.Configuration.BackupEndpointCollection)
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  langs:
  - csharp
  name: Remove(BackupEndpointCollection)
  nameWithType: BackupListCollection.Remove(BackupEndpointCollection)
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.Remove(BackupEndpointCollection)
  type: Method
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Eltávolítja a megadott első előfordulásának <xref href=&quot;System.ServiceModel.Routing.Configuration.BackupEndpointCollection&quot;> </xref> a gyűjteményből."
  syntax:
    content: public void Remove (System.ServiceModel.Routing.Configuration.BackupEndpointCollection element);
    parameters:
    - id: element
      type: System.ServiceModel.Routing.Configuration.BackupEndpointCollection
      description: "A biztonsági mentési végpont a gyűjteményből."
  overload: System.ServiceModel.Routing.Configuration.BackupListCollection.Remove*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElementCollection
  isExternal: false
  name: System.Configuration.ConfigurationElementCollection
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.#ctor
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: BackupListCollection()
  nameWithType: BackupListCollection.BackupListCollection()
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.BackupListCollection()
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Add(System.ServiceModel.Routing.Configuration.BackupEndpointCollection)
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: Add(BackupEndpointCollection)
  nameWithType: BackupListCollection.Add(BackupEndpointCollection)
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.Add(BackupEndpointCollection)
- uid: System.ServiceModel.Routing.Configuration.BackupEndpointCollection
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: BackupEndpointCollection
  nameWithType: BackupEndpointCollection
  fullName: System.ServiceModel.Routing.Configuration.BackupEndpointCollection
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Clear
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: Clear()
  nameWithType: BackupListCollection.Clear()
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.Clear()
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.CreateNewElement
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: CreateNewElement()
  nameWithType: BackupListCollection.CreateNewElement()
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.CreateNewElement()
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: BackupListCollection.GetElementKey(ConfigurationElement)
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Item(System.String)
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: Item(String)
  nameWithType: BackupListCollection.Item(String)
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.Item(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Remove(System.ServiceModel.Routing.Configuration.BackupEndpointCollection)
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: Remove(BackupEndpointCollection)
  nameWithType: BackupListCollection.Remove(BackupEndpointCollection)
  fullName: System.ServiceModel.Routing.Configuration.BackupListCollection.Remove(BackupEndpointCollection)
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.#ctor*
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: BackupListCollection
  nameWithType: BackupListCollection.BackupListCollection
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Add*
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: Add
  nameWithType: BackupListCollection.Add
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Clear*
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: Clear
  nameWithType: BackupListCollection.Clear
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.CreateNewElement*
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: CreateNewElement
  nameWithType: BackupListCollection.CreateNewElement
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.GetElementKey*
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: GetElementKey
  nameWithType: BackupListCollection.GetElementKey
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Item*
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: Item
  nameWithType: BackupListCollection.Item
- uid: System.ServiceModel.Routing.Configuration.BackupListCollection.Remove*
  parent: System.ServiceModel.Routing.Configuration.BackupListCollection
  isExternal: false
  name: Remove
  nameWithType: BackupListCollection.Remove
