### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationSettings
  id: ConfigurationSettings
  children:
  - System.Configuration.ConfigurationSettings.AppSettings
  - System.Configuration.ConfigurationSettings.GetConfig(System.String)
  langs:
  - csharp
  name: ConfigurationSettings
  nameWithType: ConfigurationSettings
  fullName: System.Configuration.ConfigurationSettings
  type: Class
  summary: "Futásidejű 1.0 és 1.1 támogatást biztosít a konfigurációs szakaszokat és az általános konfigurációs beállítások beolvasásakor."
  remarks: "A statikus metódusok és ConfigurationSettings típusú tulajdonságok használata a javasolt módja a következő 1.0 és 1.1-es alkalmazások futásidőben konfigurációs adatainak olvasásakor.      > [!NOTE] > A ConfigurationSettings osztály Itt csak a visszamenőleges kompatibilitás érdekében. Az új alkalmazások kell használnia a <xref:System.Configuration.ConfigurationManager>osztály vagy <xref:System.Web.Configuration.WebConfigurationManager>osztály helyette.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager> A két osztály használatát, fel kell vennie egy hivatkozást a projekt vagy az alkalmazás a System.Configuration névteret."
  syntax:
    content: public sealed class ConfigurationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.AppSettings
  id: AppSettings
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi a csak olvasható <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> alkalmazás beállítások szakaszában a konfigurációs fájl."
  remarks: "A `appSettings` Szakaszelem a konfigurációs fájl olyan név/érték párok, az alkalmazás használhat bármilyen célra sorozata.       Ez a metódus elavult, és az előző verziókkal való kompatibilitás változatlan marad. Használja helyette a GetSection metódust.      > [!NOTE] > A <xref:System.Configuration.ConfigurationSettings>osztály Itt csak az előző verziókkal való kompatibilitás.</xref:System.Configuration.ConfigurationSettings> Használjon a <xref:System.Configuration.ConfigurationManager>osztály vagy <xref:System.Web.Configuration.WebConfigurationManager>osztály helyette.</xref:System.Web.Configuration.WebConfigurationManager> </xref:System.Configuration.ConfigurationManager>"
  syntax:
    content: public static System.Collections.Specialized.NameValueCollection AppSettings { get; }
    return:
      type: System.Collections.Specialized.NameValueCollection
      description: "A csak olvasható <xref href=&quot;System.Collections.Specialized.NameValueCollection&quot;> </xref> alkalmazás beállítások szakaszában a konfigurációs fájlból."
  overload: System.Configuration.ConfigurationSettings.AppSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  id: GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  langs:
  - csharp
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Vissza a <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> objektum az átadott konfigurációs szakasz neve és elérési útja."
  remarks: "Ez a metódus elavult, és az előző verziókkal való kompatibilitás változatlan marad. Használja helyette a GetSection metódust."
  syntax:
    content: public static object GetConfig (string sectionName);
    parameters:
    - id: sectionName
      type: System.String
      description: "A konfiguráció neve és elérési útját, például a &quot;system.net/settings&quot;."
    return:
      type: System.Object
      description: "A <xref href=&quot;System.Configuration.ConfigurationSection&quot;> </xref> objektum az átadott konfigurációs szakasz neve és elérési útja.       <div class=&quot;alert NOTE&quot;>    A <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> osztály csak a visszamenőleges kompatibilitás biztosít. Használjon a <xref href=&quot;System.Configuration.ConfigurationManager&quot;> </xref> osztály vagy <xref href=&quot;System.Web.Configuration.WebConfigurationManager&quot;> </xref> osztály helyett.      </div>"
  overload: System.Configuration.ConfigurationSettings.GetConfig*
  exceptions:
  - type: System.Configuration.ConfigurationException
    commentId: T:System.Configuration.ConfigurationException
    description: "Nem sikerült beolvasni a kért szakasz."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationException
  nameWithType: ConfigurationException
  fullName: System.Configuration.ConfigurationException
- uid: System.Configuration.ConfigurationSettings.AppSettings
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
  fullName: System.Configuration.ConfigurationSettings.AppSettings
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.ConfigurationSettings.GetConfig(System.String)
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig(String)
  nameWithType: ConfigurationSettings.GetConfig(String)
  fullName: System.Configuration.ConfigurationSettings.GetConfig(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationSettings.AppSettings*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: AppSettings
  nameWithType: ConfigurationSettings.AppSettings
- uid: System.Configuration.ConfigurationSettings.GetConfig*
  parent: System.Configuration.ConfigurationSettings
  isExternal: false
  name: GetConfig
  nameWithType: ConfigurationSettings.GetConfig
