### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection
  id: AudienceUriElementCollection
  children:
  - System.IdentityModel.Configuration.AudienceUriElementCollection.#ctor
  - System.IdentityModel.Configuration.AudienceUriElementCollection.CreateNewElement
  - System.IdentityModel.Configuration.AudienceUriElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  - System.IdentityModel.Configuration.AudienceUriElementCollection.Init
  - System.IdentityModel.Configuration.AudienceUriElementCollection.Mode
  - System.IdentityModel.Configuration.AudienceUriElementCollection.Properties
  langs:
  - csharp
  name: AudienceUriElementCollection
  nameWithType: AudienceUriElementCollection
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection
  type: Class
  summary: "Jelöli egy <xref uid=&quot;langword_csharp_&lt;audienceUris&gt;&quot; name=&quot;&lt;audienceUris&gt;&quot; href=&quot;&quot;> </xref> egy konfigurációs fájlban."
  remarks: "A `<audienceUris>` elem határozza meg az URI-k, mint egy függő entitás azonosítására elfogadható készletét. Jogkivonatok nem fogja elfogadni, kivéve, ha azok egy URI-azonosítók megengedett célközönség hatóköre. Alapértelmezés szerint a gyűjtemény nem URI-azonosítók tartalmaz. A `mode` attribútumnak számbavételi érték, például a &quot;Mindig&quot;, &quot;BearerTokenOnly&quot;, &quot;Soha&quot;. Ez az attribútum által képviselt a <xref:System.IdentityModel.Configuration.AudienceUriElementCollection.Mode%2A>tulajdonság.</xref:System.IdentityModel.Configuration.AudienceUriElementCollection.Mode%2A> A biztonsági jogkivonat-kezelők az SAML 1.1-es és a SAML 2.0 token típusok használata engedélyezett célközönség URI-korlátozásokat az ebben a gyűjteményben bármelyik értékek <xref:System.IdentityModel.Tokens.SamlSecurityTokenRequirement>objektumok.</xref:System.IdentityModel.Tokens.SamlSecurityTokenRequirement>       Egyes célközönség URI-értékek jelölik <xref:System.IdentityModel.Configuration.AudienceUriElement>objektumok a gyűjteményben.</xref:System.IdentityModel.Configuration.AudienceUriElement>"
  syntax:
    content: >-
      [System.Configuration.ConfigurationCollection(typeof(System.IdentityModel.Configuration.AudienceUriElement), CollectionType=System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap)]

      public sealed class AudienceUriElementCollection : System.Configuration.ConfigurationElementCollection
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationElementCollection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.AddElementName
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Configuration.ConfigurationElement,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.BaseAdd(System.Int32,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseClear
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseGet(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseGetAllKeys
  - System.Configuration.ConfigurationElementCollection.BaseGetKey(System.Int32)
  - System.Configuration.ConfigurationElementCollection.BaseIndexOf(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.BaseIsRemoved(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemove(System.Object)
  - System.Configuration.ConfigurationElementCollection.BaseRemoveAt(System.Int32)
  - System.Configuration.ConfigurationElementCollection.ClearElementName
  - System.Configuration.ConfigurationElementCollection.CollectionType
  - System.Configuration.ConfigurationElementCollection.CopyTo(System.Configuration.ConfigurationElement[],System.Int32)
  - System.Configuration.ConfigurationElementCollection.Count
  - System.Configuration.ConfigurationElementCollection.CreateNewElement(System.String)
  - System.Configuration.ConfigurationElementCollection.ElementName
  - System.Configuration.ConfigurationElementCollection.EmitClear
  - System.Configuration.ConfigurationElementCollection.Equals(System.Object)
  - System.Configuration.ConfigurationElementCollection.GetEnumerator
  - System.Configuration.ConfigurationElementCollection.GetHashCode
  - System.Configuration.ConfigurationElementCollection.IsElementName(System.String)
  - System.Configuration.ConfigurationElementCollection.IsElementRemovable(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.IsModified
  - System.Configuration.ConfigurationElementCollection.IsReadOnly
  - System.Configuration.ConfigurationElementCollection.IsSynchronized
  - System.Configuration.ConfigurationElementCollection.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElementCollection.RemoveElementName
  - System.Configuration.ConfigurationElementCollection.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElementCollection.ResetModified
  - System.Configuration.ConfigurationElementCollection.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElementCollection.SetReadOnly
  - System.Configuration.ConfigurationElementCollection.SyncRoot
  - System.Configuration.ConfigurationElementCollection.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Configuration.ConfigurationElementCollection.ThrowOnDuplicate
  - System.Configuration.ConfigurationElementCollection.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  langs:
  - csharp
  name: AudienceUriElementCollection()
  nameWithType: AudienceUriElementCollection.AudienceUriElementCollection()
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.AudienceUriElementCollection()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.Configuration.AudienceUriElementCollection&quot;> </xref> osztály."
  syntax:
    content: public AudienceUriElementCollection ();
    parameters: []
  overload: System.IdentityModel.Configuration.AudienceUriElementCollection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.CreateNewElement
  id: CreateNewElement
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  langs:
  - csharp
  name: CreateNewElement()
  nameWithType: AudienceUriElementCollection.CreateNewElement()
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.CreateNewElement()
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationElement CreateNewElement ();
    parameters: []
    return:
      type: System.Configuration.ConfigurationElement
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.IdentityModel.Configuration.AudienceUriElementCollection.CreateNewElement*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  id: GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  langs:
  - csharp
  name: GetElementKey(ConfigurationElement)
  nameWithType: AudienceUriElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.GetElementKey(ConfigurationElement)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override object GetElementKey (System.Configuration.ConfigurationElement element);
    parameters:
    - id: element
      type: System.Configuration.ConfigurationElement
      description: "Fel kell venni a párbeszédpanelre."
    return:
      type: System.Object
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.IdentityModel.Configuration.AudienceUriElementCollection.GetElementKey*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Init
  id: Init
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  langs:
  - csharp
  name: Init()
  nameWithType: AudienceUriElementCollection.Init()
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.Init()
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override void Init ();
    parameters: []
  overload: System.IdentityModel.Configuration.AudienceUriElementCollection.Init*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Mode
  id: Mode
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  langs:
  - csharp
  name: Mode
  nameWithType: AudienceUriElementCollection.Mode
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.Mode
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi vagy beállítja a célközönség módját."
  remarks: "Megfelel-e a `mode` attribútuma a [ \\&lt; audienceUris\\&gt;](../Topic/%3CaudienceUris%3E.md) elemet."
  syntax:
    content: public System.IdentityModel.Selectors.AudienceUriMode Mode { get; set; }
    return:
      type: System.IdentityModel.Selectors.AudienceUriMode
      description: "A célközönség módját. Az alapértelmezett érték <xref href=&quot;System.IdentityModel.Selectors.AudienceUriMode&quot;> </xref>."
  overload: System.IdentityModel.Configuration.AudienceUriElementCollection.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  langs:
  - csharp
  name: Properties
  nameWithType: AudienceUriElementCollection.Properties
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.IdentityModel.Configuration.AudienceUriElementCollection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElementCollection
  isExternal: false
  name: System.Configuration.ConfigurationElementCollection
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.#ctor
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: AudienceUriElementCollection()
  nameWithType: AudienceUriElementCollection.AudienceUriElementCollection()
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.AudienceUriElementCollection()
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.CreateNewElement
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: CreateNewElement()
  nameWithType: AudienceUriElementCollection.CreateNewElement()
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.CreateNewElement()
- uid: System.Configuration.ConfigurationElement
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElement
  nameWithType: ConfigurationElement
  fullName: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.GetElementKey(System.Configuration.ConfigurationElement)
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: GetElementKey(ConfigurationElement)
  nameWithType: AudienceUriElementCollection.GetElementKey(ConfigurationElement)
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.GetElementKey(ConfigurationElement)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Init
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: Init()
  nameWithType: AudienceUriElementCollection.Init()
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.Init()
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Mode
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: Mode
  nameWithType: AudienceUriElementCollection.Mode
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.Mode
- uid: System.IdentityModel.Selectors.AudienceUriMode
  parent: System.IdentityModel.Selectors
  isExternal: false
  name: AudienceUriMode
  nameWithType: AudienceUriMode
  fullName: System.IdentityModel.Selectors.AudienceUriMode
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Properties
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: Properties
  nameWithType: AudienceUriElementCollection.Properties
  fullName: System.IdentityModel.Configuration.AudienceUriElementCollection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.#ctor*
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: AudienceUriElementCollection
  nameWithType: AudienceUriElementCollection.AudienceUriElementCollection
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.CreateNewElement*
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: CreateNewElement
  nameWithType: AudienceUriElementCollection.CreateNewElement
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.GetElementKey*
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: GetElementKey
  nameWithType: AudienceUriElementCollection.GetElementKey
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Init*
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: Init
  nameWithType: AudienceUriElementCollection.Init
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Mode*
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: Mode
  nameWithType: AudienceUriElementCollection.Mode
- uid: System.IdentityModel.Configuration.AudienceUriElementCollection.Properties*
  parent: System.IdentityModel.Configuration.AudienceUriElementCollection
  isExternal: false
  name: Properties
  nameWithType: AudienceUriElementCollection.Properties
