### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FcnMode
  id: FcnMode
  children:
  - System.Web.Configuration.FcnMode.Default
  - System.Web.Configuration.FcnMode.Disabled
  - System.Web.Configuration.FcnMode.NotSet
  - System.Web.Configuration.FcnMode.Single
  langs:
  - csharp
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
  type: Enum
  summary: "Adja meg az alkalmazás viselkedését (FCN) értesítést."
  syntax:
    content: public enum FcnMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Default
  id: Default
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Minden alkönyvtár az alkalmazás létrehoz egy objektumot, amely figyeli az alkönyvtárat. Ez az alapértelmezett viselkedése."
  syntax:
    content: Default
    return:
      type: System.Web.Configuration.FcnMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Disabled
  id: Disabled
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Értesítést le van tiltva."
  syntax:
    content: Disabled
    return:
      type: System.Web.Configuration.FcnMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.NotSet
  id: NotSet
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Értesítést nincs beállítva, ezért az alkalmazás létrehoz egy objektumot, amely minden alkönyvtár figyeli. Ez az alapértelmezett viselkedése."
  syntax:
    content: NotSet
    return:
      type: System.Web.Configuration.FcnMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FcnMode.Single
  id: Single
  parent: System.Web.Configuration.FcnMode
  langs:
  - csharp
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Az alkalmazás figyelése könyvtárat egy objektumot hoz létre, és használja az objektum összes alkönyvtár figyeléséhez."
  syntax:
    content: Single
    return:
      type: System.Web.Configuration.FcnMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.FcnMode.Default
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Default
  nameWithType: FcnMode.Default
  fullName: System.Web.Configuration.FcnMode.Default
- uid: System.Web.Configuration.FcnMode
  parent: System.Web.Configuration
  isExternal: false
  name: FcnMode
  nameWithType: FcnMode
  fullName: System.Web.Configuration.FcnMode
- uid: System.Web.Configuration.FcnMode.Disabled
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Disabled
  nameWithType: FcnMode.Disabled
  fullName: System.Web.Configuration.FcnMode.Disabled
- uid: System.Web.Configuration.FcnMode.NotSet
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: NotSet
  nameWithType: FcnMode.NotSet
  fullName: System.Web.Configuration.FcnMode.NotSet
- uid: System.Web.Configuration.FcnMode.Single
  parent: System.Web.Configuration.FcnMode
  isExternal: false
  name: Single
  nameWithType: FcnMode.Single
  fullName: System.Web.Configuration.FcnMode.Single
