### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  id: FederationConfigurationCreatedEventArgs
  children:
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  - System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  type: Class
  summary: "Adja meg az adatait a <xref href=&quot;System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated&quot;> </xref> esemény."
  remarks: "A <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName>esemény jelenik meg, ha az első HTTP-modulja a webes alkalmazás hivatkozik a <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfiguration%2A?displayProperty=fullName>tulajdonság.</xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfiguration%2A?displayProperty=fullName> </xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> Az első hozzáférés az e tulajdonság okok egy <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>létrehozni és inicializálni a konfigurációs objektum.</xref:System.IdentityModel.Services.Configuration.FederationConfiguration> A <xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName>majd egy esemény jelenik meg.</xref:System.IdentityModel.Services.FederatedAuthentication.FederationConfigurationCreated?displayProperty=fullName> Végezheti el az újonnan létrehozott <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>objektum keresztül a <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A?displayProperty=fullName>tulajdonság eseménykezelőben vizsgálja meg és módosíthatja azt.</xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A?displayProperty=fullName> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>"
  syntax:
    content: 'public class FederationConfigurationCreatedEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  id: '#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)'
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  type: Constructor
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs&quot;> </xref> osztály a megadott összevonási configuration objektummal."
  remarks: "Inicializálja a <xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A>tulajdonság a összevonási konfigurációs objektum által megadott `config`.</xref:System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration%2A>"
  syntax:
    content: public FederationConfigurationCreatedEventArgs (System.IdentityModel.Services.Configuration.FederationConfiguration config);
    parameters:
    - id: config
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: "Az összevonási konfigurációs objektum. A <xref href=&quot;System.IdentityModel.Services.Configuration.FederationConfiguration&quot;> </xref> objektum tartalmazza a konfigurálható tulajdonságai a WS-Federation hitelesítési modul (<xref href=&quot;System.IdentityModel.Services.WSFederationAuthenticationModule&quot;></xref>) és a munkamenet hitelesítési modul (<xref href=&quot;System.IdentityModel.Services.SessionAuthenticationModule&quot;></xref>) egy webalkalmazásban."
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  id: FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  langs:
  - csharp
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  type: Property
  assemblies:
  - System.IdentityModel.Services
  namespace: System.IdentityModel.Services.Configuration
  summary: "Lekérdezi vagy beállítja az összevonási konfigurációs objektum inicializálása a konfigurációs fájlból."
  remarks: "A <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>objektum tartalmazza a konfigurálható tulajdonságai a WS-Federation hitelesítési modul (<xref:System.IdentityModel.Services.WSFederationAuthenticationModule>) és a munkamenet hitelesítési modul (<xref:System.IdentityModel.Services.SessionAuthenticationModule>) egy webalkalmazásban.</xref:System.IdentityModel.Services.SessionAuthenticationModule> </xref:System.IdentityModel.Services.WSFederationAuthenticationModule> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>       A beállítások módosításához adhatók meg tulajdonságok a <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>biztosíthat, hogy ezt a tulajdonságot, vagy által hivatkozott objektum egy új <xref:System.IdentityModel.Services.Configuration.FederationConfiguration>objektum.</xref:System.IdentityModel.Services.Configuration.FederationConfiguration> </xref:System.IdentityModel.Services.Configuration.FederationConfiguration>"
  syntax:
    content: public System.IdentityModel.Services.Configuration.FederationConfiguration FederationConfiguration { get; set; }
    return:
      type: System.IdentityModel.Services.Configuration.FederationConfiguration
      description: "Az összevonási konfigurációs objektum, amely a konfigurációjából inicializálása."
  overload: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor(System.IdentityModel.Services.Configuration.FederationConfiguration)
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs(FederationConfiguration)
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs(FederationConfiguration)
- uid: System.IdentityModel.Services.Configuration.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
  fullName: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.#ctor*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfigurationCreatedEventArgs
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfigurationCreatedEventArgs
- uid: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs.FederationConfiguration*
  parent: System.IdentityModel.Services.Configuration.FederationConfigurationCreatedEventArgs
  isExternal: false
  name: FederationConfiguration
  nameWithType: FederationConfigurationCreatedEventArgs.FederationConfiguration
