### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.InvalidDeploymentException
  id: InvalidDeploymentException
  children:
  - System.Deployment.Application.InvalidDeploymentException.#ctor
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: InvalidDeploymentException
  nameWithType: InvalidDeploymentException
  fullName: System.Deployment.Application.InvalidDeploymentException
  type: Class
  summary: "Azt jelzi, hogy [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] nem olvasható be a központi telepítés vagy az alkalmazás jegyzékfájljai."
  remarks: "InvalidDeploymentException jelzi a sérült telepítés vagy az alkalmazás jegyzékében egy [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] alkalmazás. A hiba akkor fordulhat elő, mert a jegyzékfájlban vannak rosszul formázott, hogy a sémáikat az elemei rendelkezik ismeretlen, vagy eltérő a digitális aláírások.       Több valószínűleg sérült is, ha manuálisan szerkessze az telepítésidentitás, se fájlok egy szövegszerkesztővel. A probléma általában elhárítása újragenerálása által a [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] központi telepítés, amely létrehozza az új központi telepítési és alkalmazási jegyzékfájljai. A részletes hibakeresési lépéseket tekintse meg a következőket."
  syntax:
    content: 'public class InvalidDeploymentException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException()
  nameWithType: InvalidDeploymentException.InvalidDeploymentException()
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.InvalidDeploymentException&quot;> </xref> osztály."
  syntax:
    content: public InvalidDeploymentException ();
    parameters: []
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(String)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.InvalidDeploymentException&quot;> </xref> a megadott üzenet, amely leírja a kivétel a osztályt."
  syntax:
    content: public InvalidDeploymentException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(SerializationInfo,StreamingContext)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.InvalidDeploymentException&quot;> </xref> osztály."
  syntax:
    content: protected InvalidDeploymentException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.InvalidDeploymentException
  langs:
  - csharp
  name: InvalidDeploymentException(String,Exception)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.InvalidDeploymentException&quot;> </xref> osztály."
  syntax:
    content: public InvalidDeploymentException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.Deployment.Application.InvalidDeploymentException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException()
  nameWithType: InvalidDeploymentException.InvalidDeploymentException()
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException()
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(String)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(SerializationInfo,StreamingContext)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException(String,Exception)
  nameWithType: InvalidDeploymentException.InvalidDeploymentException(String,Exception)
  fullName: System.Deployment.Application.InvalidDeploymentException.InvalidDeploymentException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.InvalidDeploymentException.#ctor*
  parent: System.Deployment.Application.InvalidDeploymentException
  isExternal: false
  name: InvalidDeploymentException
  nameWithType: InvalidDeploymentException.InvalidDeploymentException
