### YamlMime:ManagedReference
items:
- uid: System.Windows.Media.ImageSourceValueSerializer
  id: ImageSourceValueSerializer
  children:
  - System.Windows.Media.ImageSourceValueSerializer.#ctor
  - System.Windows.Media.ImageSourceValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.ImageSourceValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.ImageSourceValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Media.ImageSourceValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: ImageSourceValueSerializer
  nameWithType: ImageSourceValueSerializer
  fullName: System.Windows.Media.ImageSourceValueSerializer
  type: Class
  summary: "Konvertálja példányai <xref:System.String>példányai érkező vagy oda irányuló <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref>.</xref:System.String>"
  remarks: "Ez az osztály általában csak szükség szerint a <xref:System.Windows.Markup.Primitives.MarkupWriter>szerializálási célokra.</xref:System.Windows.Markup.Primitives.MarkupWriter>"
  syntax:
    content: 'public class ImageSourceValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Media.ImageSourceValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Media.ImageSourceValueSerializer
  langs:
  - csharp
  name: ImageSourceValueSerializer()
  nameWithType: ImageSourceValueSerializer.ImageSourceValueSerializer()
  fullName: System.Windows.Media.ImageSourceValueSerializer.ImageSourceValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Windows.Media.ImageSourceValueSerializer&quot;> </xref> osztály."
  syntax:
    content: public ImageSourceValueSerializer ();
    parameters: []
  overload: System.Windows.Media.ImageSourceValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.ImageSourceValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.ImageSourceValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: ImageSourceValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.ImageSourceValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media
  summary: "Meghatározza, hogy egy <xref:System.String>példányának konvertálható <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "<xref:System.String>kiértékelheti az átalakításhoz.</xref:System.String>"
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Környezeti információkat felhasználva az átalakításhoz."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az érték átalakítható; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Media.ImageSourceValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.ImageSourceValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.ImageSourceValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ImageSourceValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.ImageSourceValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media
  summary: "Meghatározza, hogy egy példánya <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref> <xref:System.String>.</xref:System.String> konvertálható"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Példányának <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref> átalakításhoz kiértékeléséhez."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Környezeti információkat felhasználva az átalakításhoz."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha <code> value </code> konvertálni kell egy <xref:System.String>; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Media.ImageSourceValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.ImageSourceValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.ImageSourceValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: ImageSourceValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.ImageSourceValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media
  summary: "Konvertálja a <xref:System.String>való egy <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Karakterlánc-érték konvertálása egy <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref>."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Környezeti információkat felhasználva az átalakításhoz."
    return:
      type: System.Object
      description: "Egy új példányát <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref> a megadott alapján <code> value </code>."
  overload: System.Windows.Media.ImageSourceValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Media.ImageSourceValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.ImageSourceValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ImageSourceValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.ImageSourceValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Media
  summary: "Konvertálja példányának <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref> <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "A <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref> átalakításhoz kiértékeléséhez."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Környezeti információkat felhasználva az átalakításhoz."
    return:
      type: System.String
      description: "A <xref:System.String>a megadott ábrázolását <xref href=&quot;System.Windows.Media.ImageSource&quot;> </xref> objektum.</xref:System.String>"
  overload: System.Windows.Media.ImageSourceValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Media.ImageSourceValueSerializer.#ctor
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: ImageSourceValueSerializer()
  nameWithType: ImageSourceValueSerializer.ImageSourceValueSerializer()
  fullName: System.Windows.Media.ImageSourceValueSerializer.ImageSourceValueSerializer()
- uid: System.Windows.Media.ImageSourceValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: ImageSourceValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.ImageSourceValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Media.ImageSourceValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: ImageSourceValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.ImageSourceValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Media.ImageSourceValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: ImageSourceValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Media.ImageSourceValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Media.ImageSourceValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: ImageSourceValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Media.ImageSourceValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Media.ImageSourceValueSerializer.#ctor*
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: ImageSourceValueSerializer
  nameWithType: ImageSourceValueSerializer.ImageSourceValueSerializer
- uid: System.Windows.Media.ImageSourceValueSerializer.CanConvertFromString*
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: ImageSourceValueSerializer.CanConvertFromString
- uid: System.Windows.Media.ImageSourceValueSerializer.CanConvertToString*
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: ImageSourceValueSerializer.CanConvertToString
- uid: System.Windows.Media.ImageSourceValueSerializer.ConvertFromString*
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: ImageSourceValueSerializer.ConvertFromString
- uid: System.Windows.Media.ImageSourceValueSerializer.ConvertToString*
  parent: System.Windows.Media.ImageSourceValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: ImageSourceValueSerializer.ConvertToString
