### YamlMime:ManagedReference
items:
- uid: System.Configuration.ApplicationScopedSettingAttribute
  id: ApplicationScopedSettingAttribute
  children:
  - System.Configuration.ApplicationScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute
  fullName: System.Configuration.ApplicationScopedSettingAttribute
  type: Class
  summary: "Meghatározza, hogy az alkalmazás beállításainak tulajdonság értéke egy közös az alkalmazás minden felhasználó számára. Ez az osztály nem örökölhető."
  remarks: "Alkalmazás tulajdonságai rendelkezik, amely alapul, vagy az alkalmazás vagy a felhasználói szintű hatókörrel. Mivel a kategóriák utalnak, alkalmazásokra kiterjedő hatókörű beállítások tulajdonságai bevezetését a egységes értékek az alkalmazás minden felhasználó mivel felhasználói hatókörbe tartozó tulajdonságok értékeit az alkalmazás minden felhasználó dedikált.       A ApplicationScopedSettingAttribute azt jelzi, hogy a tulajdonság kell kezelni egy alkalmazás szintű beállítás, és hogy megfelelő tároló-szempontjait ennek megfelelően kell tenni a beállítások szolgáltató.       Egy hatókör attribútum esetén az egyes beállítások tulajdonság. Ha egy tulajdonság nem alkalmazható az vagy egy ApplicationScopedSettingAttribute vagy <xref:System.Configuration.UserScopedSettingAttribute>, a tulajdonság nem ismeri fel a beállításszolgáltató – a rendszer nem szerializálja.</xref:System.Configuration.UserScopedSettingAttribute> Érvénytelen, azonban az attribútumok alkalmazandó ugyanahhoz a tulajdonsághoz. Ilyen kísérlet hatására a <xref:System.Configuration.ConfigurationErrorsException>jelezni, hogy.</xref:System.Configuration.ConfigurationErrorsException>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class ApplicationScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.ApplicationScopedSettingAttribute
  langs:
  - csharp
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.ApplicationScopedSettingAttribute&quot;> </xref> osztály."
  remarks: "Minden alkalmazás beállítások tulajdonság ahhoz, hogy felismerik és a beállítások szolgáltató szerializálni a hatókörre attribútummal kell alkalmazni."
  syntax:
    content: public ApplicationScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute()
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
  fullName: System.Configuration.ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute()
- uid: System.Configuration.ApplicationScopedSettingAttribute.#ctor*
  parent: System.Configuration.ApplicationScopedSettingAttribute
  isExternal: false
  name: ApplicationScopedSettingAttribute
  nameWithType: ApplicationScopedSettingAttribute.ApplicationScopedSettingAttribute
