### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CompatibleFrameworkMissingException
  id: CompatibleFrameworkMissingException
  children:
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  - System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  langs:
  - csharp
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException
  type: Class
  summary: "A kivétel történt, amikor egy alkalmazás kompatibilis a .NET-keretrendszer verziója nem található."
  syntax:
    content: 'public class CompatibleFrameworkMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> osztály rendszer által megadott üzenetet, amely leírja a hibát."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonság az új példány egy rendszer által megadott üzenetet, amely leírja, hogy a hiba, például a &quot;Kompatibilis keretrendszer nem található.&quot;</xref:System.Exception.Message%2A> Ez az üzenet figyelembe veszi a rendszer jelenlegi kulturális környezethez.       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Az üzenet honosított hibakarakterlánc. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException ();
    parameters: []
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> osztály egy adott üzenet, amely leírja a hibát."
  remarks: "Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A megadott hiba üzenet karakterláncot `message`. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> a szerializált adatok osztályt."
  remarks: "Ez a konstruktor nevezik meglévő kölcsönökre adatfolyam továbbított kivétel objektum deszerializálása közben."
  syntax:
    content: protected CompatibleFrameworkMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmaznia kell egy hivatkozást az előző kivétel az a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza vagy `null` Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Deployment.Application.CompatibleFrameworkMissingException>.</xref:System.Deployment.Application.CompatibleFrameworkMissingException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A megadott hiba üzenet karakterláncot `message`. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public CompatibleFrameworkMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  id: CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: ".NET-keretrendszer verziója, ahol telepítheti és futtathatja az alkalmazást listájának lekérése."
  syntax:
    content: public System.Deployment.Application.CompatibleFrameworks CompatibleFrameworks { get; }
    return:
      type: System.Deployment.Application.CompatibleFrameworks
      description: "Ha az alkalmazás telepítheti és futtathatja .NET-keretrendszer-verziók listáját."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.CompatibleFrameworkMissingException&quot;> </xref> a szerializált adatok osztályt."
  remarks: "Ez a konstruktor nevezik meglévő kölcsönökre adatfolyam továbbított kivétel objektum deszerializálása közben."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException()
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException()
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException(String,Exception)
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworkMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworks
  parent: System.Deployment.Application
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworks
  fullName: System.Deployment.Application.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.#ctor*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworkMissingException
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworkMissingException
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.CompatibleFrameworks*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: CompatibleFrameworks
  nameWithType: CompatibleFrameworkMissingException.CompatibleFrameworks
- uid: System.Deployment.Application.CompatibleFrameworkMissingException.GetObjectData*
  parent: System.Deployment.Application.CompatibleFrameworkMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: CompatibleFrameworkMissingException.GetObjectData
