### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlObjectReaderSettings
  id: XamlObjectReaderSettings
  children:
  - System.Xaml.XamlObjectReaderSettings.#ctor
  - System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  langs:
  - csharp
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings
  fullName: System.Xaml.XamlObjectReaderSettings
  type: Class
  summary: "Megadja a szabályok feldolgozásának vagy beállításait egy <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref>."
  syntax:
    content: 'public class XamlObjectReaderSettings : System.Xaml.XamlReaderSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlReaderSettings
  implements: []
  inheritedMembers:
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Xaml.XamlObjectReaderSettings&quot;> </xref> osztály."
  syntax:
    content: public XamlObjectReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlObjectReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  id: RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  langs:
  - csharp
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdez vagy beállít egy értéket, amely meghatározza, hogy írók, amelyek használják a társított <xref href=&quot;System.Xaml.XamlObjectReader&quot;> </xref> környezetben kell használnak Tervező beállításai tartalom explicit módon írására."
  remarks: "Ez a beállítás belső le kell kérdezni. Annak hatását a következő viselkedés a környezet, amely egy <xref:System.Xaml.XamlObjectReader>bármely fázisok <xref:System.Xaml.XamlWriter>:-a RequireExplicitContentVisibility csak viselkedik azokhoz a tulajdonságokhoz ahol <xref:System.Xaml.XamlMember.IsWritePublic%2A>van `false`, és mikor egy `ShouldSerialize` minta nem érhető el a tulajdonságérték.</xref:System.Xaml.XamlMember.IsWritePublic%2A> </xref:System.Xaml.XamlWriter> </xref:System.Xaml.XamlObjectReader>      -Ha az első pont utasításában értéke true, és RequireExplicitContentVisibility `true`, majd a Tervező beállításai határozzák meg, hogy a tulajdonság a kimenetet tartalmat írja, vagy a tulajdonság minősül. Tervező beállítások eléréséhez belső API-k, a .NET-keretrendszer XAML-szolgáltatások segítségével, és olvasási alapuló <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>a szerelvények biztonsági.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute> Ebben az esetben belső ellenőrzi, hogy az érték <xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName>és a kimenetet írja a tulajdonságra.</xref:System.ComponentModel.DesignerSerializationVisibility?displayProperty=fullName> Ellenkező esetben a tartalom implicit minősül.      – Ha az első pontjában utasítás `true`, és RequireExplicitContentVisibility van `false`, a tulajdonság mindig ír a kimeneti és <xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>a szerelvények biztonsági lényegtelen.</xref:System.ComponentModel.DesignerSerializationVisibilityAttribute>"
  syntax:
    content: public bool RequireExplicitContentVisibility { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>a kimeneti tartalom azokban az esetekben, amelyekben <xref:System.Xaml.XamlMember.IsWritePublic*>jelenti, hogy a környezet írók írásra használja a Tervező beállításai <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> Ha Tervező beállításokat figyelmen kívül hagyja.</xref:System.Xaml.XamlMember.IsWritePublic*>"
  overload: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlReaderSettings
  isExternal: false
  name: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.#ctor
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings()
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings()
  fullName: System.Xaml.XamlObjectReaderSettings.XamlObjectReaderSettings()
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
  fullName: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlObjectReaderSettings.#ctor*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: XamlObjectReaderSettings
  nameWithType: XamlObjectReaderSettings.XamlObjectReaderSettings
- uid: System.Xaml.XamlObjectReaderSettings.RequireExplicitContentVisibility*
  parent: System.Xaml.XamlObjectReaderSettings
  isExternal: false
  name: RequireExplicitContentVisibility
  nameWithType: XamlObjectReaderSettings.RequireExplicitContentVisibility
