### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlXmlWriterSettings
  id: XamlXmlWriterSettings
  children:
  - System.Xaml.XamlXmlWriterSettings.#ctor
  - System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  - System.Xaml.XamlXmlWriterSettings.CloseOutput
  - System.Xaml.XamlXmlWriterSettings.Copy
  langs:
  - csharp
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
  type: Class
  summary: "Inicializálási beállításokat biztosít a <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> XAML író végrehajtására."
  remarks: "Az alapértelmezett érték az összes XamlXmlWriterSettings érték `false`."
  syntax:
    content: 'public class XamlXmlWriterSettings : System.Xaml.XamlWriterSettings'
  inheritance:
  - System.Object
  - System.Xaml.XamlWriterSettings
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> osztály."
  syntax:
    content: public XamlXmlWriterSettings ();
    parameters: []
  overload: System.Xaml.XamlXmlWriterSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  id: AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdez vagy beállít egy értéket, amely megadja, hogy a <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> mindig kell feltételeznie érvényes XAML bemeneti ismétlődő megoldási vagy egyéb hiba ellenőrzése céljából."
  syntax:
    content: public bool AssumeValidInput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> bizonyos, az érvényesítés vagy a hiba ellenőrzéseket, például a kivételek kivétel ismétlődő tagok kihagyja. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Ha a <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> kivételt jelez, ha érvénytelen XAML-kódot a rendszer észlelt. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  id: CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdez vagy beállít egy értéket, amely megadja, hogy a <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> kell gombra kattintva azonnal bezárhatja a <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> egyéb műveleteket, vagy hogy az XAML-író kell írásával a puffer kimeneti Bezárás előtt. Ezt a beállítást használja óvatosan; azonnal bezárja azt eredményezheti, hogy érvénytelen XAML-kódot, amely nem lehet újra betölteni."
  remarks: "Ez a beállítás hatással van a logikája <xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>, mely hívások `Close` a az alapul szolgáló <xref:System.Xml.XmlWriter>vagy <xref:System.IO.TextWriter>CloseOutput esetén `true`; vagy meghívja <xref:System.Xaml.XamlXmlWriter.Flush%2A>(újra kötve az alapul szolgáló <xref:System.Xml.XmlWriter>vagy <xref:System.IO.TextWriter>) CloseOutput esetén `false`.</xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Flush%2A> </xref:System.IO.TextWriter> </xref:System.Xml.XmlWriter> </xref:System.Xaml.XamlXmlWriter.Dispose%2A?displayProperty=fullName>"
  syntax:
    content: public bool CloseOutput { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> azonnal bezáródik a <xref uid=&quot;langword_csharp_Dispose&quot; name=&quot;Dispose&quot; href=&quot;&quot;> </xref> vagy hasonló műveletek. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Ha a fennmaradó puffer kimeneti írása előtt a <xref href=&quot;System.Xaml.XamlXmlWriter&quot;> </xref> megjelenik. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  id: Copy
  parent: System.Xaml.XamlXmlWriterSettings
  langs:
  - csharp
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
  type: Method
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Ez olyan másolatát adja vissza <xref href=&quot;System.Xaml.XamlXmlWriterSettings&quot;> </xref> példány."
  syntax:
    content: public System.Xaml.XamlXmlWriterSettings Copy ();
    parameters: []
    return:
      type: System.Xaml.XamlXmlWriterSettings
      description: "A visszaadott példány."
  overload: System.Xaml.XamlXmlWriterSettings.Copy*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Xaml.XamlWriterSettings
  isExternal: false
  name: System.Xaml.XamlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings()
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings()
  fullName: System.Xaml.XamlXmlWriterSettings.XamlXmlWriterSettings()
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
  fullName: System.Xaml.XamlXmlWriterSettings.AssumeValidInput
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
  fullName: System.Xaml.XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy()
  nameWithType: XamlXmlWriterSettings.Copy()
  fullName: System.Xaml.XamlXmlWriterSettings.Copy()
- uid: System.Xaml.XamlXmlWriterSettings
  parent: System.Xaml
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings
  fullName: System.Xaml.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.#ctor*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: XamlXmlWriterSettings
  nameWithType: XamlXmlWriterSettings.XamlXmlWriterSettings
- uid: System.Xaml.XamlXmlWriterSettings.AssumeValidInput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: AssumeValidInput
  nameWithType: XamlXmlWriterSettings.AssumeValidInput
- uid: System.Xaml.XamlXmlWriterSettings.CloseOutput*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: CloseOutput
  nameWithType: XamlXmlWriterSettings.CloseOutput
- uid: System.Xaml.XamlXmlWriterSettings.Copy*
  parent: System.Xaml.XamlXmlWriterSettings
  isExternal: false
  name: Copy
  nameWithType: XamlXmlWriterSettings.Copy
