### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSerializeAsAttribute
  id: SettingsSerializeAsAttribute
  children:
  - System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  - System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  langs:
  - csharp
  name: SettingsSerializeAsAttribute
  nameWithType: SettingsSerializeAsAttribute
  fullName: System.Configuration.SettingsSerializeAsAttribute
  type: Class
  summary: "Meghatározza a szerializálási mechanizmusa, amelyet a beállítások szolgáltatót kell használnia. Ez az osztály nem örökölhető."
  remarks: "A beállítások szolgáltató támogatja a .NET-keretrendszer szabványos szerializálási sémák egynél több gyakran. Ezek a rendszerek vázolt által a <xref:System.Configuration.SettingsSerializeAs>számbavételi, és egyszerű szövegként, XML és bináris szerializálást.</xref:System.Configuration.SettingsSerializeAs> Emellett a szolgáltató opcionálisan támogathatja az egy egyéni szerializálási séma.       Az a SettingsSerializeAsAttribute megadhatja, mely sorba rendezési mechanizmust kell használni az adott alkalmazáshoz beállítások osztály vagy tulajdonság. Ez az attribútum a beállításszolgáltató kérelem minősül. Előfordulhat, hogy figyelmen kívül lesz hagyva, vagy hibát okozhat, ha a szolgáltató vagy az egyes tulajdonságtípus nem támogatja a megadott szerializálási séma. Ez az attribútum nincs jelen, ha a szolgáltató általában egy alapértelmezett sorba rendezési mechanizmust, leggyakrabban egyszerű szövegként adja meg.       A beállítások szolgáltató dinamikusan módosítását futásidőben szerializálási mechanizmusa rendelkezhetnek, bár ez nem egy tipikus képesség."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsSerializeAsAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  id: '#ctor(System.Configuration.SettingsSerializeAs)'
  parent: System.Configuration.SettingsSerializeAsAttribute
  langs:
  - csharp
  name: SettingsSerializeAsAttribute(SettingsSerializeAs)
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  fullName: System.Configuration.SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy példányát inicializálja a <xref href=&quot;System.Configuration.SettingsSerializeAsAttribute&quot;> </xref> osztály."
  remarks: "Ha konvertálni a beállításszolgáltató vagy a tulajdonság típusa nem támogatja a szerializálási séma által megadott a `serializeAs` paraméter, a művelet lehet az alábbi eredményeket egyikét:-a beállításszolgáltató előfordulhat, hogy az attribútum figyelmen kívül, és használja az alapértelmezett szerializálási séma.      -A szerializálási válasz nélkül nem. Az alkalmazás beállításainak tulajdonság nem maradnak meg.      -Kivétel a lehetséges, hogy a szerializálás során következik be."
  syntax:
    content: public SettingsSerializeAsAttribute (System.Configuration.SettingsSerializeAs serializeAs);
    parameters:
    - id: serializeAs
      type: System.Configuration.SettingsSerializeAs
      description: "A <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> számba érték, amely meghatározza a szerializálási séma."
  overload: System.Configuration.SettingsSerializeAsAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  id: SerializeAs
  parent: System.Configuration.SettingsSerializeAsAttribute
  langs:
  - csharp
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
  fullName: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> számbavételi érték, amely meghatározza a szerializálási séma."
  remarks: "Ennek a tulajdonságnak értéke a <xref:System.Configuration.SettingsSerializeAsAttribute.%23ctor%2A>konstruktor.</xref:System.Configuration.SettingsSerializeAsAttribute.%23ctor%2A>"
  syntax:
    content: public System.Configuration.SettingsSerializeAs SerializeAs { get; }
    return:
      type: System.Configuration.SettingsSerializeAs
      description: "A <xref href=&quot;System.Configuration.SettingsSerializeAs&quot;> </xref> számba érték, amely meghatározza a szerializálási séma."
  overload: System.Configuration.SettingsSerializeAsAttribute.SerializeAs*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor(System.Configuration.SettingsSerializeAs)
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SettingsSerializeAsAttribute(SettingsSerializeAs)
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
  fullName: System.Configuration.SettingsSerializeAsAttribute.SettingsSerializeAsAttribute(SettingsSerializeAs)
- uid: System.Configuration.SettingsSerializeAs
  parent: System.Configuration
  isExternal: false
  name: SettingsSerializeAs
  nameWithType: SettingsSerializeAs
  fullName: System.Configuration.SettingsSerializeAs
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
  fullName: System.Configuration.SettingsSerializeAsAttribute.SerializeAs
- uid: System.Configuration.SettingsSerializeAsAttribute.#ctor*
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SettingsSerializeAsAttribute
  nameWithType: SettingsSerializeAsAttribute.SettingsSerializeAsAttribute
- uid: System.Configuration.SettingsSerializeAsAttribute.SerializeAs*
  parent: System.Configuration.SettingsSerializeAsAttribute
  isExternal: false
  name: SerializeAs
  nameWithType: SettingsSerializeAsAttribute.SerializeAs
