### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.Compiler
  id: Compiler
  children:
  - System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  - System.Web.Configuration.Compiler.CompilerOptions
  - System.Web.Configuration.Compiler.Extension
  - System.Web.Configuration.Compiler.Language
  - System.Web.Configuration.Compiler.Properties
  - System.Web.Configuration.Compiler.Type
  - System.Web.Configuration.Compiler.WarningLevel
  langs:
  - csharp
  name: Compiler
  nameWithType: Compiler
  fullName: System.Web.Configuration.Compiler
  type: Class
  summary: "Határozza meg, amely támogatja a webes alkalmazások fordítási infrastruktúráját fordító. Ez az osztály nem örökölhető."
  remarks: "A fordítóprogram osztály programon keresztüli eléréséhez a fordító konfigurációs elem lehetőséget biztosít."
  syntax:
    content: 'public sealed class Compiler : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  id: '#ctor(System.String,System.String,System.String,System.String,System.Int32)'
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Létrehoz egy új egy <xref href=&quot;System.Web.Configuration.Compiler&quot;> </xref> inicializálása a megadott értékekre."
  syntax:
    content: public Compiler (string compilerOptions, string extension, string language, string type, int warningLevel);
    parameters:
    - id: compilerOptions
      type: System.String
      description: "Felelt meg a fordítás során további fordítóprogram-specifikus beállításokat sorolja fel."
    - id: extension
      type: System.String
      description: "A fájlnév kiterjesztések dinamikus háttérkód fájlok pontosvesszővel elválasztott listáját tartalmazza. Például: &quot;.cs&quot;."
    - id: language
      type: System.String
      description: "A dinamikus fordítási fájlokban használt nyelvek pontosvesszővel elválasztott listáját tartalmazza. Például &quot;c#; cs; csharp&quot;."
    - id: type
      type: System.String
      description: "Adja meg egy vesszővel tagolt osztály/összeállítás kombinációja, amely jelzi a .NET-keretrendszer osztály."
    - id: warningLevel
      type: System.Int32
      description: "Megadja a fordító figyelmeztetési szinteket."
  overload: System.Web.Configuration.Compiler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.CompilerOptions
  id: CompilerOptions
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "A fordítóprogram-specifikus beállításokat fordítás közbeni listájának lekérése."
  syntax:
    content: public string CompilerOptions { get; }
    return:
      type: System.String
      description: "Egy érték, a fordítás közbeni fordító vonatkozó beállítások megadása. Ez nem egy egyesített készlet de ahelyett, hogy felülírja a korábban meghatározott értékeit korábbi konfigurációs bejegyzéseket."
  overload: System.Web.Configuration.Compiler.CompilerOptions*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Extension
  id: Extension
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Fájlnév kiterjesztések dinamikus háttérkód fájlok listájának lekérése."
  remarks: "A fájlnév kiterjesztések listája több bővítmény tartalmaz, a lista esetén pontosvesszővel elválasztott."
  syntax:
    content: public string Extension { get; }
    return:
      type: System.String
      description: "A fájlnév kiterjesztések dinamikus háttérkód fájlok megadó értéket, a kód könyvtárban, és egyéb fájlok hivatkozott fájlokat."
  overload: System.Web.Configuration.Compiler.Extension*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Language
  id: Language
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Programozási nyelvek a dinamikus fordítási fájlokban használt listájának lekérése."
  remarks: "Programozási nyelvek listáját tartalmazza az egynél több nyelv, a lista esetén pontosvesszővel elválasztott."
  syntax:
    content: public string Language { get; }
    return:
      type: System.String
      description: "A dinamikus fordítási fájlokban használt programozási nyelvek megadó értéket."
  overload: System.Web.Configuration.Compiler.Language*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Properties
  id: Properties
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.Compiler.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.Type
  id: Type
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "A dinamikus fordítási fájloknál lekéri a nyelvi szolgáltatónak fordító nevét."
  remarks: "A típus neve, a nyelvi szolgáltatónak, beleértve a szolgáltató általi megvalósítása tartalmazó szerelvény nevét."
  syntax:
    content: public string Type { get; }
    return:
      type: System.String
      description: "A dinamikus fordítási fájlokban használt nyelv fordító nevét megadó értéket."
  overload: System.Web.Configuration.Compiler.Type*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.Compiler.WarningLevel
  id: WarningLevel
  parent: System.Web.Configuration.Compiler
  langs:
  - csharp
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a fordító figyelmeztetést."
  remarks: "Adja meg az alapértelmezett fordító figyelmeztetést; Meghatározza, ahol a nyelvi szolgáltatónak fordítási figyelmeztetések tekinti hibák szintjét."
  syntax:
    content: public int WarningLevel { get; }
    return:
      type: System.Int32
      description: "Egy érték megadása a fordító figyelmeztetést."
  overload: System.Web.Configuration.Compiler.WarningLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.Compiler.#ctor(System.String,System.String,System.String,System.String,System.Int32)
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler(String,String,String,String,Int32)
  nameWithType: Compiler.Compiler(String,String,String,String,Int32)
  fullName: System.Web.Configuration.Compiler.Compiler(String,String,String,String,Int32)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.Compiler.CompilerOptions
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
  fullName: System.Web.Configuration.Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
  fullName: System.Web.Configuration.Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
  fullName: System.Web.Configuration.Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
  fullName: System.Web.Configuration.Compiler.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.Compiler.Type
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
  fullName: System.Web.Configuration.Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
  fullName: System.Web.Configuration.Compiler.WarningLevel
- uid: System.Web.Configuration.Compiler.#ctor*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Compiler
  nameWithType: Compiler.Compiler
- uid: System.Web.Configuration.Compiler.CompilerOptions*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: CompilerOptions
  nameWithType: Compiler.CompilerOptions
- uid: System.Web.Configuration.Compiler.Extension*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Extension
  nameWithType: Compiler.Extension
- uid: System.Web.Configuration.Compiler.Language*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Language
  nameWithType: Compiler.Language
- uid: System.Web.Configuration.Compiler.Properties*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Properties
  nameWithType: Compiler.Properties
- uid: System.Web.Configuration.Compiler.Type*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: Type
  nameWithType: Compiler.Type
- uid: System.Web.Configuration.Compiler.WarningLevel*
  parent: System.Web.Configuration.Compiler
  isExternal: false
  name: WarningLevel
  nameWithType: Compiler.WarningLevel
