### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TicketCompatibilityMode
  id: TicketCompatibilityMode
  children:
  - System.Web.Configuration.TicketCompatibilityMode.Framework20
  - System.Web.Configuration.TicketCompatibilityMode.Framework40
  langs:
  - csharp
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
  type: Enum
  summary: "Határozza meg, hogy az egyezményes világidő (UTC) vagy a helyi idő használata a az űrlapos hitelesítés jegy lejáratát."
  remarks: "Az ASP.NET űrlapos hitelesítés jegy lejáratát egyezményes világidő (UTC) vagy a helyi idő használatával tárolhatja. Alkalmazások között, és a .NET-keretrendszer különböző verziói között, a jegy lejárati ideje használatával adhatók meg a `ticketCompatilityMode` elem attribútuma. Az alapértelmezett érték a `ticketCompatibilityMode` attribútum Framework20."
  example:
  - "The following example configures the forms authentication ticket expiration date as UTC time.  \n  \n```  \n<system.web>  \n  <authentication mode=\"Forms\">   \n    <forms ticketCompatilityMode=\"Framework40\">  \n    </forms>  \n  </authentication>  \n</system.web>  \n```"
  syntax:
    content: public enum TicketCompatibilityMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  id: Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Meghatározza, hogy a jegy lejárati dátumot tárolja-e a helyi idő szerint. Ez az alapértelmezett beállítás."
  syntax:
    content: Framework20
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  id: Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  langs:
  - csharp
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Meghatározza, hogy a jegy lejárati dátum UTC formátumban tárolja."
  syntax:
    content: Framework40
    return:
      type: System.Web.Configuration.TicketCompatibilityMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework20
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework20
  nameWithType: TicketCompatibilityMode.Framework20
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework20
- uid: System.Web.Configuration.TicketCompatibilityMode
  parent: System.Web.Configuration
  isExternal: false
  name: TicketCompatibilityMode
  nameWithType: TicketCompatibilityMode
  fullName: System.Web.Configuration.TicketCompatibilityMode
- uid: System.Web.Configuration.TicketCompatibilityMode.Framework40
  parent: System.Web.Configuration.TicketCompatibilityMode
  isExternal: false
  name: Framework40
  nameWithType: TicketCompatibilityMode.Framework40
  fullName: System.Web.Configuration.TicketCompatibilityMode.Framework40
