### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FullTrustAssembliesSection
  id: FullTrustAssembliesSection
  children:
  - System.Web.Configuration.FullTrustAssembliesSection.#ctor
  - System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssemblies
  - System.Web.Configuration.FullTrustAssembliesSection.Properties
  langs:
  - csharp
  name: FullTrustAssembliesSection
  nameWithType: FullTrustAssembliesSection
  fullName: System.Web.Configuration.FullTrustAssembliesSection
  type: Class
  summary: "Konfigurálja a teljesen megbízható szerelvények készletét. Ez az osztály nem örökölhető."
  remarks: "A FullTrustAssembliesSection osztály lehetővé teszi az ASP.NET-alkalmazás részlegesen megbízható tartományban teljesen megbízható szerelvények megadását.       Egy szerelvény konfigurálásához rendelkeznie kell nyilvános kulcsát hexadecimális karakterláncos ábrázolása. Ezt a kulcsot kap a erős nevének (Sn.exe) eszközzel. Az eszköz jeleníti meg a nyilvános kulcsú hexadecimális karakterlánc-ábrázolása, amelyekkel a konfigurációban. A nyilvános kulcsú token is képes. További információkért lásd: [Sn.exe (erős név eszköz)](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following example shows how to specify a full-trust assembly by using the `fullTrustAssemblies` section in a configuration file.  \n  \n```  \n<fullTrustAssemblies>  \n  <add assemblyName=\"MyAssembly\" version=\"1.0.0.0\"   \n    publicKey=\"hex_key_representation\" />  \n</fullTrustAssemblies>  \n```"
  syntax:
    content: 'public sealed class FullTrustAssembliesSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.FullTrustAssembliesSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.FullTrustAssembliesSection
  langs:
  - csharp
  name: FullTrustAssembliesSection()
  nameWithType: FullTrustAssembliesSection.FullTrustAssembliesSection()
  fullName: System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssembliesSection()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.FullTrustAssembliesSection&quot;> </xref> osztály."
  syntax:
    content: public FullTrustAssembliesSection ();
    parameters: []
  overload: System.Web.Configuration.FullTrustAssembliesSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssemblies
  id: FullTrustAssemblies
  parent: System.Web.Configuration.FullTrustAssembliesSection
  langs:
  - csharp
  name: FullTrustAssemblies
  nameWithType: FullTrustAssembliesSection.FullTrustAssemblies
  fullName: System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssemblies
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Web.Configuration.FullTrustAssemblyCollection&quot;> </xref> a teljesen megbízható szerelvények gyűjteménye."
  syntax:
    content: public System.Web.Configuration.FullTrustAssemblyCollection FullTrustAssemblies { get; }
    return:
      type: System.Web.Configuration.FullTrustAssemblyCollection
      description: "Teljesen megbízható szerelvények gyűjteménye."
  overload: System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssemblies*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FullTrustAssembliesSection.Properties
  id: Properties
  parent: System.Web.Configuration.FullTrustAssembliesSection
  langs:
  - csharp
  name: Properties
  nameWithType: FullTrustAssembliesSection.Properties
  fullName: System.Web.Configuration.FullTrustAssembliesSection.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.FullTrustAssembliesSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.FullTrustAssembliesSection.#ctor
  parent: System.Web.Configuration.FullTrustAssembliesSection
  isExternal: false
  name: FullTrustAssembliesSection()
  nameWithType: FullTrustAssembliesSection.FullTrustAssembliesSection()
  fullName: System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssembliesSection()
- uid: System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssemblies
  parent: System.Web.Configuration.FullTrustAssembliesSection
  isExternal: false
  name: FullTrustAssemblies
  nameWithType: FullTrustAssembliesSection.FullTrustAssemblies
  fullName: System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssemblies
- uid: System.Web.Configuration.FullTrustAssemblyCollection
  parent: System.Web.Configuration
  isExternal: false
  name: FullTrustAssemblyCollection
  nameWithType: FullTrustAssemblyCollection
  fullName: System.Web.Configuration.FullTrustAssemblyCollection
- uid: System.Web.Configuration.FullTrustAssembliesSection.Properties
  parent: System.Web.Configuration.FullTrustAssembliesSection
  isExternal: false
  name: Properties
  nameWithType: FullTrustAssembliesSection.Properties
  fullName: System.Web.Configuration.FullTrustAssembliesSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FullTrustAssembliesSection.#ctor*
  parent: System.Web.Configuration.FullTrustAssembliesSection
  isExternal: false
  name: FullTrustAssembliesSection
  nameWithType: FullTrustAssembliesSection.FullTrustAssembliesSection
- uid: System.Web.Configuration.FullTrustAssembliesSection.FullTrustAssemblies*
  parent: System.Web.Configuration.FullTrustAssembliesSection
  isExternal: false
  name: FullTrustAssemblies
  nameWithType: FullTrustAssembliesSection.FullTrustAssemblies
- uid: System.Web.Configuration.FullTrustAssembliesSection.Properties*
  parent: System.Web.Configuration.FullTrustAssembliesSection
  isExternal: false
  name: Properties
  nameWithType: FullTrustAssembliesSection.Properties
