### YamlMime:ManagedReference
items:
- uid: System.Web.DynamicData.ContextConfiguration
  id: ContextConfiguration
  children:
  - System.Web.DynamicData.ContextConfiguration.#ctor
  - System.Web.DynamicData.ContextConfiguration.MetadataProviderFactory
  - System.Web.DynamicData.ContextConfiguration.ScaffoldAllTables
  langs:
  - csharp
  name: ContextConfiguration
  nameWithType: ContextConfiguration
  fullName: System.Web.DynamicData.ContextConfiguration
  type: Class
  summary: "Annak érdekében, hogy testreszabási egy adatkörnyezet példány információkat nyújt."
  remarks: "A ContextConfiguration osztály adatokhoz való hozzáférés testreszabása teszi lehetővé. Például használhatja ezt az osztályt webalkalmazás állványok engedélyezéséhez, vagy egy egyéni metaadat-szolgáltató megadása."
  example:
  - "The following example shows how to use the ContextConfiguration class when you call the <xref:System.Web.DynamicData.MetaModel.RegisterContext%2A> method in order to register a data context with scaffolding enabled.  \n  \n [!code-vb[System.Web.DynamicData.MetaModel#99](~/add/codesnippet/visualbasic/System.Web.DynamicData.MetaModel.ClassLibrary1/global.asax.vb#99)]\n [!code-cs[System.Web.DynamicData.MetaModel#99](~/add/codesnippet/csharp/t-system.web.dynamicdata_9_1.cs)]"
  syntax:
    content: public class ContextConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.DynamicData.ContextConfiguration.#ctor
  id: '#ctor'
  parent: System.Web.DynamicData.ContextConfiguration
  langs:
  - csharp
  name: ContextConfiguration()
  nameWithType: ContextConfiguration.ContextConfiguration()
  fullName: System.Web.DynamicData.ContextConfiguration.ContextConfiguration()
  type: Constructor
  assemblies:
  - System.Web.DynamicData
  namespace: System.Web.DynamicData
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.DynamicData.ContextConfiguration&quot;> </xref> osztály."
  syntax:
    content: public ContextConfiguration ();
    parameters: []
  overload: System.Web.DynamicData.ContextConfiguration.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.DynamicData.ContextConfiguration.MetadataProviderFactory
  id: MetadataProviderFactory
  parent: System.Web.DynamicData.ContextConfiguration
  langs:
  - csharp
  name: MetadataProviderFactory
  nameWithType: ContextConfiguration.MetadataProviderFactory
  fullName: System.Web.DynamicData.ContextConfiguration.MetadataProviderFactory
  type: Property
  assemblies:
  - System.Web.DynamicData
  namespace: System.Web.DynamicData
  summary: "Lekérdezi vagy beállítja a metaadat-szolgáltató."
  remarks: "Ez a módszer lehetővé teszi, hogy egy adott adatkörnyezetet egyéni metaadat szolgáltatót adható meg."
  syntax:
    content: public Func<Type,System.ComponentModel.TypeDescriptionProvider> MetadataProviderFactory { get; set; }
    return:
      type: System.Func{System.Type,System.ComponentModel.TypeDescriptionProvider}
      description: "A metaadat-szolgáltató típusa."
  overload: System.Web.DynamicData.ContextConfiguration.MetadataProviderFactory*
  exceptions: []
  platform:
  - net462
- uid: System.Web.DynamicData.ContextConfiguration.ScaffoldAllTables
  id: ScaffoldAllTables
  parent: System.Web.DynamicData.ContextConfiguration
  langs:
  - csharp
  name: ScaffoldAllTables
  nameWithType: ContextConfiguration.ScaffoldAllTables
  fullName: System.Web.DynamicData.ContextConfiguration.ScaffoldAllTables
  type: Property
  assemblies:
  - System.Web.DynamicData
  namespace: System.Web.DynamicData
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy engedélyezve van-e állványok."
  syntax:
    content: public bool ScaffoldAllTables { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha engedélyezve van a állványok; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.DynamicData.ContextConfiguration.ScaffoldAllTables*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.DynamicData.ContextConfiguration.#ctor
  parent: System.Web.DynamicData.ContextConfiguration
  isExternal: false
  name: ContextConfiguration()
  nameWithType: ContextConfiguration.ContextConfiguration()
  fullName: System.Web.DynamicData.ContextConfiguration.ContextConfiguration()
- uid: System.Web.DynamicData.ContextConfiguration.MetadataProviderFactory
  parent: System.Web.DynamicData.ContextConfiguration
  isExternal: false
  name: MetadataProviderFactory
  nameWithType: ContextConfiguration.MetadataProviderFactory
  fullName: System.Web.DynamicData.ContextConfiguration.MetadataProviderFactory
- uid: System.Func{System.Type,System.ComponentModel.TypeDescriptionProvider}
  parent: System
  isExternal: true
  name: Func<Type,TypeDescriptionProvider>
  nameWithType: Func<Type,TypeDescriptionProvider>
  fullName: System.Func<System.Type,System.ComponentModel.TypeDescriptionProvider>
  spec.csharp:
  - uid: System.Func`2
    name: Func
    nameWithType: Func
    fullName: Func<System.Type,System.ComponentModel.TypeDescriptionProvider>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Type
    name: Type
    nameWithType: Type
    fullName: Type
  - name: ','
    nameWithType: ','
    fullName: ','
  - uid: System.ComponentModel.TypeDescriptionProvider
    name: TypeDescriptionProvider
    nameWithType: TypeDescriptionProvider
    fullName: TypeDescriptionProvider
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Web.DynamicData.ContextConfiguration.ScaffoldAllTables
  parent: System.Web.DynamicData.ContextConfiguration
  isExternal: false
  name: ScaffoldAllTables
  nameWithType: ContextConfiguration.ScaffoldAllTables
  fullName: System.Web.DynamicData.ContextConfiguration.ScaffoldAllTables
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.DynamicData.ContextConfiguration.#ctor*
  parent: System.Web.DynamicData.ContextConfiguration
  isExternal: false
  name: ContextConfiguration
  nameWithType: ContextConfiguration.ContextConfiguration
- uid: System.Web.DynamicData.ContextConfiguration.MetadataProviderFactory*
  parent: System.Web.DynamicData.ContextConfiguration
  isExternal: false
  name: MetadataProviderFactory
  nameWithType: ContextConfiguration.MetadataProviderFactory
- uid: System.Web.DynamicData.ContextConfiguration.ScaffoldAllTables*
  parent: System.Web.DynamicData.ContextConfiguration
  isExternal: false
  name: ScaffoldAllTables
  nameWithType: ContextConfiguration.ScaffoldAllTables
