### YamlMime:ManagedReference
items:
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute
  id: NoSettingsVersionUpgradeAttribute
  children:
  - System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute
  type: Class
  summary: "Meghatározza, hogy a beállítások szolgáltató tiltsa le a bármely logika, amely lekérdezi meghívni, amikor a rendszer észlelt egy alkalmazás frissítését. Ez az osztály nem örökölhető."
  remarks: "Egy teljes funkciókészletet kínáló alkalmazás szolgáltatója, amely támogatja az alkalmazás versioning létrehozásához a szolgáltatónak tartalmaznia kell a <xref:System.Configuration.IApplicationSettingsProvider>felületet.</xref:System.Configuration.IApplicationSettingsProvider> Egy ezen a felületen tagja a <xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A>metódust, hogy értesítsék a szolgáltatót, hogy egy alkalmazás új verziója telepítve van-e nevezik.</xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A> Válaszként a szolgáltató várhatóan hajtsa végre a megfelelő műveletet, általában áttelepítése Alkalmazásbeállítások részhez.       A NoSettingsVersionUpgradeAttribute tájékoztatja a szolgáltatót arra, hogy letiltsa az aktuális beállítások osztály társított frissítési logikát. Ezért az érték a tulajdonság csoport az előző verzió nem kell áttelepíteni az új verzióra.      > [!NOTE] > Ez az attribútum csak egyéni alkalmazás tulajdonságai kell alkalmazni."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class NoSettingsVersionUpgradeAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  langs:
  - csharp
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.NoSettingsVersionUpgradeAttribute&quot;> </xref> osztály."
  remarks: "Ez az <xref:System.Configuration.NoSettingsVersionUpgradeAttribute>osztály</xref:System.Configuration.NoSettingsVersionUpgradeAttribute> a fordító által biztosított alapértelmezett konstruktor"
  syntax:
    content: public NoSettingsVersionUpgradeAttribute ();
    parameters: []
  overload: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute()
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
  fullName: System.Configuration.NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute()
- uid: System.Configuration.NoSettingsVersionUpgradeAttribute.#ctor*
  parent: System.Configuration.NoSettingsVersionUpgradeAttribute
  isExternal: false
  name: NoSettingsVersionUpgradeAttribute
  nameWithType: NoSettingsVersionUpgradeAttribute.NoSettingsVersionUpgradeAttribute
