### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler
  id: HttpCapabilitiesSectionHandler
  children:
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  - System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler
  type: Class
  summary: "Elősegíti a való olvasáskor a <xref uid=&quot;langword_csharp_&lt;browserCaps&gt;&quot; name=&quot;&lt;browserCaps&gt;&quot; href=&quot;&quot;> </xref> szakasza egy konfigurációs fájlban és példányának létrehozását a <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> osztály, amely az ügyfél böngészője képességek adatait tartalmazza."
  remarks: "A HttpCapabilitiesSectionHandler osztály és a megfelelő `<browserCaps>` konfigurációs szakasz elavulttá vált a .NET-keretrendszer 2.0-s verziójában. A preferált böngészőszolgáltatások kezelésére szolgáló lesz böngésző definíciós fájljait, fordításának <xref:System.Web.Configuration.BrowserCapabilitiesFactory>osztály</xref:System.Web.Configuration.BrowserCapabilitiesFactory> által használható Mindkét konfigurációs módszereit, amelyek célja az, hogy az <xref:System.Web.HttpBrowserCapabilities>osztály, amely elérhető az <xref:System.Web.HttpRequest.Browser%2A> <xref:System.Web.HttpRequest>osztály</xref:System.Web.HttpRequest> tulajdonsága</xref:System.Web.HttpRequest.Browser%2A> </xref:System.Web.HttpBrowserCapabilities> készítése       A tulajdonos alternatív előnyöket böngészőszolgáltatások tárolására használ a böngésző definíciós fájlok számára biztosítja. Kínál a nagyobb teljesítményt, mert a böngésző a helydefiníciós adatokat elemezni az XML-konfigurációs fájlból, és időben osztály lefordítva. A böngésző csomagdefiníciós fájlok olyan is egyszerűbben kezelhető:-a definíciók hierarchikus, és így támaszkodjon kisebb a reguláris kifejezések a böngészőszolgáltatások meghatározásához.      -A definíciók rendszerezheti több fájlt, így könnyebben kezelhető.      -A definíciók bármely szinten, vagy a Machine.config vagy egy adott alkalmazás szintjén adhatók meg. Ezzel a megoldással történő teljes készletét megtisztítja a definíciók felülbírálja a képességeket a böngészőnek történő másolásának szükségességét."
  syntax:
    content: 'public class HttpCapabilitiesSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.HttpCapabilitiesSectionHandler&quot;> </xref> osztály."
  syntax:
    content: public HttpCapabilitiesSectionHandler ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Létrehoz egy példányát a <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> osztály, amely az ügyfél böngészője képességek adatait tartalmazza."
  remarks: "Ez az osztály származtatható a böngésző definition adatait a `<browserCaps>` konfigurációs szakasz. Ez a szakasz a .NET-keretrendszer 2.0-s verziója elavult."
  syntax:
    content: public object Create (object parent, object configurationContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "A szülő konfiguráció csomópontot."
    - id: configurationContext
      type: System.Object
      description: "Az aktuális konfigurációs fájl konfiguráció környezetében."
    - id: section
      type: System.Xml.XmlNode
      description: "A konfigurációs fájl adatokat tartalmazó részét."
    return:
      type: System.Object
      description: "Példányának <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> , amely az ügyfél böngészője képességek adatait tartalmazza."
  overload: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler()
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler()
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: HttpCapabilitiesSectionHandler
  nameWithType: HttpCapabilitiesSectionHandler.HttpCapabilitiesSectionHandler
- uid: System.Web.Configuration.HttpCapabilitiesSectionHandler.Create*
  parent: System.Web.Configuration.HttpCapabilitiesSectionHandler
  isExternal: false
  name: Create
  nameWithType: HttpCapabilitiesSectionHandler.Create
