### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CustomErrorsRedirectMode
  id: CustomErrorsRedirectMode
  children:
  - System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  - System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  langs:
  - csharp
  name: CustomErrorsRedirectMode
  nameWithType: CustomErrorsRedirectMode
  fullName: System.Web.Configuration.CustomErrorsRedirectMode
  type: Enum
  summary: "Adja meg az eredeti kérelem URL-CÍMÉT a rendszer hogyan kezelje, ha egyéni hibalapot jelenik meg az értékeket."
  remarks: "Ha úgy állítja be a CustomErrorsRedirectMode értéket használ a <xref:System.Web.Configuration.CustomErrorsSection.RedirectMode%2A>tulajdonság.</xref:System.Web.Configuration.CustomErrorsSection.RedirectMode%2A>"
  syntax:
    content: public enum CustomErrorsRedirectMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  id: ResponseRedirect
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  langs:
  - csharp
  name: ResponseRedirect
  nameWithType: CustomErrorsRedirectMode.ResponseRedirect
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Megjeleníti a hibalap, és módosítsa az URL-címet az eredeti kérelem."
  syntax:
    content: ResponseRedirect
    return:
      type: System.Web.Configuration.CustomErrorsRedirectMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  id: ResponseRewrite
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  langs:
  - csharp
  name: ResponseRewrite
  nameWithType: CustomErrorsRedirectMode.ResponseRewrite
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Megjeleníti a hibalap az eredeti URL-cím megváltoztatása nélkül."
  syntax:
    content: ResponseRewrite
    return:
      type: System.Web.Configuration.CustomErrorsRedirectMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  isExternal: false
  name: ResponseRedirect
  nameWithType: CustomErrorsRedirectMode.ResponseRedirect
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRedirect
- uid: System.Web.Configuration.CustomErrorsRedirectMode
  parent: System.Web.Configuration
  isExternal: false
  name: CustomErrorsRedirectMode
  nameWithType: CustomErrorsRedirectMode
  fullName: System.Web.Configuration.CustomErrorsRedirectMode
- uid: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
  parent: System.Web.Configuration.CustomErrorsRedirectMode
  isExternal: false
  name: ResponseRewrite
  nameWithType: CustomErrorsRedirectMode.ResponseRewrite
  fullName: System.Web.Configuration.CustomErrorsRedirectMode.ResponseRewrite
