### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  id: AuthorizationPolicyTypeElement
  children:
  - System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor
  - System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor(System.String)
  - System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
  - System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
  langs:
  - csharp
  name: AuthorizationPolicyTypeElement
  nameWithType: AuthorizationPolicyTypeElement
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  type: Class
  summary: "Megadja az engedélyezési házirend, amely lehetővé teszi, hogy a bemeneti jogcímek egy készletét be egy másik készlet jogcímek átalakítása konfigurációs elemet tartalmaz. Hozzáférés-vezérlés is vagy megtagadhatja a, amelyek alapján. Ez az osztály nem örökölhető."
  remarks: "A hozzáférés-vezérlési modell támogatja a létesítést engedélyezési házirendjei típusként. Ez az elem konfigurálja az engedélyezési házirend-megvalósítás, amelyek lehetővé teszik a bemeneti jogcímek egy készletét be egy másik készlet jogcímek átalakítása készlete. A majd üzemeltetett a jogcímek egy készletét, és egy hozzáférés-vezérlési döntési éri el az engedélyezési házirend átalakítása fázis után."
  syntax:
    content: 'public sealed class AuthorizationPolicyTypeElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  langs:
  - csharp
  name: AuthorizationPolicyTypeElement()
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement()
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.AuthorizationPolicyTypeElement&quot;> </xref> osztály."
  syntax:
    content: public AuthorizationPolicyTypeElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  langs:
  - csharp
  name: AuthorizationPolicyTypeElement(String)
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement(String)
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.AuthorizationPolicyTypeElement&quot;> </xref> a megadott típusú osztályra."
  syntax:
    content: public AuthorizationPolicyTypeElement (string policyType);
    parameters:
    - id: policyType
      type: System.String
      description: "Inicializálása szabályzat típusát."
  overload: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>policyType</code>van <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> vagy üres."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
  id: PolicyType
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  langs:
  - csharp
  name: PolicyType
  nameWithType: AuthorizationPolicyTypeElement.PolicyType
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a házirend típusát."
  syntax:
    content: public string PolicyType { get; set; }
    return:
      type: System.String
      description: "A házirend típusát."
  overload: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  langs:
  - csharp
  name: Properties
  nameWithType: AuthorizationPolicyTypeElement.Properties
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: AuthorizationPolicyTypeElement()
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement()
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement()
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: AuthorizationPolicyTypeElement(String)
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement(String)
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: PolicyType
  nameWithType: AuthorizationPolicyTypeElement.PolicyType
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: Properties
  nameWithType: AuthorizationPolicyTypeElement.Properties
  fullName: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.#ctor*
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: AuthorizationPolicyTypeElement
  nameWithType: AuthorizationPolicyTypeElement.AuthorizationPolicyTypeElement
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.PolicyType*
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: PolicyType
  nameWithType: AuthorizationPolicyTypeElement.PolicyType
- uid: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement.Properties*
  parent: System.ServiceModel.Configuration.AuthorizationPolicyTypeElement
  isExternal: false
  name: Properties
  nameWithType: AuthorizationPolicyTypeElement.Properties
