### YamlMime:ManagedReference
items:
- uid: System.Configuration.IdnElement
  id: IdnElement
  children:
  - System.Configuration.IdnElement.#ctor
  - System.Configuration.IdnElement.Enabled
  - System.Configuration.IdnElement.Properties
  langs:
  - csharp
  name: IdnElement
  nameWithType: IdnElement
  fullName: System.Configuration.IdnElement
  type: Class
  summary: "A konfigurációs beállítás a nemzetközi tartományneveket (IDN) feldolgozás alatt álló biztosít a &lt;xref:System.Uri?displayProperty=fullName&gt; osztály."
  remarks: "A meglévő <xref:System.Uri?displayProperty=fullName>osztály megtörtént-e támogatásához nemzetközi erőforrás-azonosítók (IRI) alapú RFC 3987.</xref:System.Uri?displayProperty=fullName> Aktuális felhasználók nem fogják látni a .NET-keretrendszer 2.0 viselkedésből változásait, kivéve, ha kifejezetten engedélyezi IRI. Ez biztosítja az alkalmazás a .NET-keretrendszer korábbi verzióival is kompatibilisek.       A konfigurációs beállítást a IdnElement közvetve vezérli a <xref:System.Configuration.IriParsingElement>konfigurációs beállítása a vezérlők IRI feldolgozása az <xref:System.Uri?displayProperty=fullName>osztályhoz.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement> IRI feldolgozási képességének lehetséges IDN engedélyezni kell. Ha IRI feldolgozási le van tiltva, majd IDN feldolgozási állítja be az alapértelmezett beállítást, ha a .NET-keretrendszer 2.0 viselkedés kompatibilitási használja, és IDN-nevek nem használhatók.       Nemzetközi tartományneveket (IDN) attribútum csak vezérlők IDN feldolgozását. Minden más IRI feldolgozás (például a karakter normalizálási) alapértelmezés szerint történik.       A konfigurációs beállítása a IdnElement fogja beolvasni egyszer amikor az első <xref:System.Uri?displayProperty=fullName>osztály összeállított.</xref:System.Uri?displayProperty=fullName> Az időnek az elteltével konfigurációs beállításainak változtatásai figyelmen kívül lesznek hagyva.       IRI által nyújtott további információkért lásd: az <xref:System.Uri?displayProperty=fullName>osztály</xref:System.Uri?displayProperty=fullName> a megjegyzések területén"
  syntax:
    content: 'public sealed class IdnElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Configuration.IdnElement.#ctor
  id: '#ctor'
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: IdnElement()
  nameWithType: IdnElement.IdnElement()
  fullName: System.Configuration.IdnElement.IdnElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.IdnElement&quot;> </xref> osztály."
  remarks: "Ez a konstruktor létrehoz egy <xref:System.Configuration.IdnElement>példány</xref:System.Configuration.IdnElement>"
  syntax:
    content: public IdnElement ();
    parameters: []
  overload: System.Configuration.IdnElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IdnElement.Enabled
  id: Enabled
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: Enabled
  nameWithType: IdnElement.Enabled
  fullName: System.Configuration.IdnElement.Enabled
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi vagy beállítja a értékét a <xref href=&quot;System.Configuration.IdnElement&quot;> </xref> konfigurációs beállítás."
  remarks: "Nemzetközi tartományneveket (IDN) attribútum csak vezérlők IDN feldolgozását. Minden más nemzetközi erőforrás-azonosítók (IRI) a feldolgozás (például a karakter normalizálási) alapértelmezés szerint történik.       A konfigurációs beállítást <xref:System.Configuration.IdnElement>közvetve vezérli a <xref:System.Configuration.IriParsingElement?displayProperty=fullName>konfigurációs beállítás, amely szabályozza a IRI feldolgozás alatt álló <xref:System.Uri?displayProperty=fullName>osztályhoz.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IriParsingElement?displayProperty=fullName> </xref:System.Configuration.IdnElement> IRI feldolgozási képességének lehetséges IDN engedélyezni kell. Ha IRI feldolgozási le van tiltva, majd IDN feldolgozási állítja be az alapértelmezett beállítást, ha a .NET-keretrendszer 2.0 viselkedés kompatibilitási használja, és IDN-nevek nem használhatók.       A konfigurációs beállítást a <xref:System.Configuration.IdnElement>fogja beolvasni egyszer amikor az első <xref:System.Uri?displayProperty=fullName>osztály összeállított.</xref:System.Uri?displayProperty=fullName> </xref:System.Configuration.IdnElement> Az időnek az elteltével konfigurációs beállításainak változtatásai figyelmen kívül lesznek hagyva.       IRI által nyújtott további információkért lásd: az <xref:System.Uri?displayProperty=fullName>osztály</xref:System.Uri?displayProperty=fullName> a megjegyzések területén"
  syntax:
    content: public UriIdnScope Enabled { get; set; }
    return:
      type: System.UriIdnScope
      description: "A <xref href=&quot;System.UriIdnScope&quot;> </xref> , amely tartalmazza az aktuális konfigurációs beállítás IDN feldolgozásra."
  overload: System.Configuration.IdnElement.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IdnElement.Properties
  id: Properties
  parent: System.Configuration.IdnElement
  langs:
  - csharp
  name: Properties
  nameWithType: IdnElement.Properties
  fullName: System.Configuration.IdnElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Configuration.IdnElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Configuration.IdnElement.#ctor
  parent: System.Configuration.IdnElement
  isExternal: false
  name: IdnElement()
  nameWithType: IdnElement.IdnElement()
  fullName: System.Configuration.IdnElement.IdnElement()
- uid: System.Configuration.IdnElement.Enabled
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Enabled
  nameWithType: IdnElement.Enabled
  fullName: System.Configuration.IdnElement.Enabled
- uid: System.UriIdnScope
  parent: System
  isExternal: false
  name: UriIdnScope
  nameWithType: UriIdnScope
  fullName: System.UriIdnScope
- uid: System.Configuration.IdnElement.Properties
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Properties
  nameWithType: IdnElement.Properties
  fullName: System.Configuration.IdnElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Configuration.IdnElement.#ctor*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: IdnElement
  nameWithType: IdnElement.IdnElement
- uid: System.Configuration.IdnElement.Enabled*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Enabled
  nameWithType: IdnElement.Enabled
- uid: System.Configuration.IdnElement.Properties*
  parent: System.Configuration.IdnElement
  isExternal: false
  name: Properties
  nameWithType: IdnElement.Properties
