### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings
  id: PeerResolverSettings
  children:
  - System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor
  - System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
  - System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
  - System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
  langs:
  - csharp
  name: PeerResolverSettings
  nameWithType: PeerResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings
  type: Class
  summary: "Meghatározza a társ-feloldó szolgáltatás beállításait."
  syntax:
    content: public class PeerResolverSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  langs:
  - csharp
  name: PeerResolverSettings()
  nameWithType: PeerResolverSettings.PeerResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.PeerResolverSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.PeerResolvers.PeerResolverSettings&quot;> </xref> osztály."
  syntax:
    content: public PeerResolverSettings ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
  id: Custom
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  langs:
  - csharp
  name: Custom
  nameWithType: PeerResolverSettings.Custom
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Lekérdezi az egyéni társfeloldó a beállításait."
  remarks: "Ez a tulajdonság értéke csak akkor, ha <xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode%2A> <xref:System.ServiceModel.PeerResolvers.PeerResolverMode>.</xref:System.ServiceModel.PeerResolvers.PeerResolverMode> beállítása</xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode%2A>"
  syntax:
    content: public System.ServiceModel.PeerResolvers.PeerCustomResolverSettings Custom { get; }
    return:
      type: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
      description: "<xref href=&quot;System.ServiceModel.PeerResolvers.PeerCustomResolverSettings&quot;></xref>a beállítások és a társított egyéni társ feloldó szolgáltatás feloldó példányát tartalmazó."
  overload: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
  id: Mode
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  langs:
  - csharp
  name: Mode
  nameWithType: PeerResolverSettings.Mode
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Lekérdezi vagy beállítja a társ feloldó példány a szolgáltatáshoz rendelt vagy PNRP-specifikus, egy egyéni feloldó, vagy automatikusan határozza meg."
  syntax:
    content: public System.ServiceModel.PeerResolvers.PeerResolverMode Mode { get; set; }
    return:
      type: System.ServiceModel.PeerResolvers.PeerResolverMode
      description: "<xref href=&quot;System.ServiceModel.PeerResolvers.PeerResolverMode&quot;></xref>számbavételi érték, amely megadja a társ-feloldó szolgáltatás módját."
  overload: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
  id: ReferralPolicy
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  langs:
  - csharp
  name: ReferralPolicy
  nameWithType: PeerResolverSettings.ReferralPolicy
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Lekérdezi vagy beállítja a társ feloldó szolgáltatás által használt konkrét átirányítási házirendet."
  syntax:
    content: public System.ServiceModel.PeerResolvers.PeerReferralPolicy ReferralPolicy { get; set; }
    return:
      type: System.ServiceModel.PeerResolvers.PeerReferralPolicy
      description: "<xref href=&quot;System.ServiceModel.PeerResolvers.PeerReferralPolicy&quot;></xref>amely megadja, hogy társ hivatkozások megosztásának vagy sem."
  overload: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: PeerResolverSettings()
  nameWithType: PeerResolverSettings.PeerResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.PeerResolverSettings()
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: Custom
  nameWithType: PeerResolverSettings.Custom
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  parent: System.ServiceModel.PeerResolvers
  isExternal: false
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: Mode
  nameWithType: PeerResolverSettings.Mode
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode
- uid: System.ServiceModel.PeerResolvers.PeerResolverMode
  parent: System.ServiceModel.PeerResolvers
  isExternal: false
  name: PeerResolverMode
  nameWithType: PeerResolverMode
  fullName: System.ServiceModel.PeerResolvers.PeerResolverMode
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: ReferralPolicy
  nameWithType: PeerResolverSettings.ReferralPolicy
  fullName: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy
- uid: System.ServiceModel.PeerResolvers.PeerReferralPolicy
  parent: System.ServiceModel.PeerResolvers
  isExternal: false
  name: PeerReferralPolicy
  nameWithType: PeerReferralPolicy
  fullName: System.ServiceModel.PeerResolvers.PeerReferralPolicy
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.#ctor*
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: PeerResolverSettings
  nameWithType: PeerResolverSettings.PeerResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom*
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: Custom
  nameWithType: PeerResolverSettings.Custom
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.Mode*
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: Mode
  nameWithType: PeerResolverSettings.Mode
- uid: System.ServiceModel.PeerResolvers.PeerResolverSettings.ReferralPolicy*
  parent: System.ServiceModel.PeerResolvers.PeerResolverSettings
  isExternal: false
  name: ReferralPolicy
  nameWithType: PeerResolverSettings.ReferralPolicy
