### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory
  id: IInternalConfigSettingsFactory
  children:
  - System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit
  - System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(System.Configuration.Internal.IInternalConfigSystem,System.Boolean)
  langs:
  - csharp
  name: IInternalConfigSettingsFactory
  nameWithType: IInternalConfigSettingsFactory
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory
  type: Interface
  summary: "Állítsa be a konfigurációs rendszer által használt felület meghatározása a <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> osztály."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IInternalConfigSettingsFactory
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit
  id: CompleteInit
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  langs:
  - csharp
  name: CompleteInit()
  nameWithType: IInternalConfigSettingsFactory.CompleteInit()
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Azt jelzi, hogy inicializálása a konfiguráció rendszer befejeződött."
  syntax:
    content: public void CompleteInit ();
    parameters: []
  overload: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(System.Configuration.Internal.IInternalConfigSystem,System.Boolean)
  id: SetConfigurationSystem(System.Configuration.Internal.IInternalConfigSystem,System.Boolean)
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  langs:
  - csharp
  name: SetConfigurationSystem(IInternalConfigSystem,Boolean)
  nameWithType: IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem,Boolean)
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem,Boolean)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Itt hierarchikus konfigurációs beállításokat és a megadott kiterjesztések az ASP.NET a konfigurációs rendszer."
  syntax:
    content: public void SetConfigurationSystem (System.Configuration.Internal.IInternalConfigSystem internalConfigSystem, bool initComplete);
    parameters:
    - id: internalConfigSystem
      type: System.Configuration.Internal.IInternalConfigSystem
      description: "Egy <xref href=&quot;System.Configuration.Internal.IInternalConfigSystem&quot;> </xref> objektum által használt a <xref href=&quot;System.Configuration.ConfigurationSettings&quot;> </xref> osztály."
    - id: initComplete
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az inicializálási folyamatot a konfigurációs rendszer befejeződött; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  isExternal: false
  name: CompleteInit()
  nameWithType: IInternalConfigSettingsFactory.CompleteInit()
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit()
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(System.Configuration.Internal.IInternalConfigSystem,System.Boolean)
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  isExternal: false
  name: SetConfigurationSystem(IInternalConfigSystem,Boolean)
  nameWithType: IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem,Boolean)
  fullName: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem(IInternalConfigSystem,Boolean)
- uid: System.Configuration.Internal.IInternalConfigSystem
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigSystem
  nameWithType: IInternalConfigSystem
  fullName: System.Configuration.Internal.IInternalConfigSystem
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.CompleteInit*
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  isExternal: false
  name: CompleteInit
  nameWithType: IInternalConfigSettingsFactory.CompleteInit
- uid: System.Configuration.Internal.IInternalConfigSettingsFactory.SetConfigurationSystem*
  parent: System.Configuration.Internal.IInternalConfigSettingsFactory
  isExternal: false
  name: SetConfigurationSystem
  nameWithType: IInternalConfigSettingsFactory.SetConfigurationSystem
