### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigSystem
  id: IConfigSystem
  children:
  - System.Configuration.Internal.IConfigSystem.Host
  - System.Configuration.Internal.IConfigSystem.Init(System.Type,System.Object[])
  - System.Configuration.Internal.IConfigSystem.Root
  langs:
  - csharp
  name: IConfigSystem
  nameWithType: IConfigSystem
  fullName: System.Configuration.Internal.IConfigSystem
  type: Interface
  summary: "A .NET-keretrendszer konfigurációs tulajdonságok inicializálása támogatásához használt felület meghatározása."
  syntax:
    content: public interface IConfigSystem
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigSystem.Host
  id: Host
  parent: System.Configuration.Internal.IConfigSystem
  langs:
  - csharp
  name: Host
  nameWithType: IConfigSystem.Host
  fullName: System.Configuration.Internal.IConfigSystem.Host
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a konfigurációs állomás."
  syntax:
    content: public System.Configuration.Internal.IInternalConfigHost Host { get; }
    return:
      type: System.Configuration.Internal.IInternalConfigHost
      description: "Egy <xref href=&quot;System.Configuration.Internal.IInternalConfigHost&quot;> </xref> inicializálni az alkalmazás konfigurációs tulajdonságok a .NET-keretrendszer által használt objektum."
  overload: System.Configuration.Internal.IConfigSystem.Host*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigSystem.Init(System.Type,System.Object[])
  id: Init(System.Type,System.Object[])
  parent: System.Configuration.Internal.IConfigSystem
  langs:
  - csharp
  name: Init(Type,Object[])
  nameWithType: IConfigSystem.Init(Type,Object[])
  fullName: System.Configuration.Internal.IConfigSystem.Init(Type,Object[])
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "A konfigurációs objektum inicializálása."
  syntax:
    content: public void Init (Type typeConfigHost, object[] hostInitParams);
    parameters:
    - id: typeConfigHost
      type: System.Type
      description: "A konfigurációs fogadó típusa."
    - id: hostInitParams
      type: System.Object[]
      description: "Konfigurációs állomás paraméterek tömbjét."
  overload: System.Configuration.Internal.IConfigSystem.Init*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigSystem.Root
  id: Root
  parent: System.Configuration.Internal.IConfigSystem
  langs:
  - csharp
  name: Root
  nameWithType: IConfigSystem.Root
  fullName: System.Configuration.Internal.IConfigSystem.Root
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a konfigurációs hierarchiában gyökérmappájában."
  remarks: "A <xref:System.Configuration.Internal.IInternalConfigRoot>objektum kezelhetőek létrehozását, eltávolítása és a konfigurációs rekordok keresési szálbiztos módon.</xref:System.Configuration.Internal.IInternalConfigRoot>"
  syntax:
    content: public System.Configuration.Internal.IInternalConfigRoot Root { get; }
    return:
      type: System.Configuration.Internal.IInternalConfigRoot
      description: "Egy <xref href=&quot;System.Configuration.Internal.IInternalConfigRoot&quot;> </xref> objektum."
  overload: System.Configuration.Internal.IConfigSystem.Root*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IConfigSystem.Host
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Host
  nameWithType: IConfigSystem.Host
  fullName: System.Configuration.Internal.IConfigSystem.Host
- uid: System.Configuration.Internal.IInternalConfigHost
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigHost
  nameWithType: IInternalConfigHost
  fullName: System.Configuration.Internal.IInternalConfigHost
- uid: System.Configuration.Internal.IConfigSystem.Init(System.Type,System.Object[])
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Init(Type,Object[])
  nameWithType: IConfigSystem.Init(Type,Object[])
  fullName: System.Configuration.Internal.IConfigSystem.Init(Type,Object[])
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Object[]
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object[]
  spec.csharp:
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: Object[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Configuration.Internal.IConfigSystem.Root
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Root
  nameWithType: IConfigSystem.Root
  fullName: System.Configuration.Internal.IConfigSystem.Root
- uid: System.Configuration.Internal.IInternalConfigRoot
  parent: System.Configuration.Internal
  isExternal: false
  name: IInternalConfigRoot
  nameWithType: IInternalConfigRoot
  fullName: System.Configuration.Internal.IInternalConfigRoot
- uid: System.Configuration.Internal.IConfigSystem.Host*
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Host
  nameWithType: IConfigSystem.Host
- uid: System.Configuration.Internal.IConfigSystem.Init*
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Init
  nameWithType: IConfigSystem.Init
- uid: System.Configuration.Internal.IConfigSystem.Root*
  parent: System.Configuration.Internal.IConfigSystem
  isExternal: false
  name: Root
  nameWithType: IConfigSystem.Root
