### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.NetMsmqSecurity
  id: NetMsmqSecurity
  children:
  - System.ServiceModel.NetMsmqSecurity.#ctor
  - System.ServiceModel.NetMsmqSecurity.Message
  - System.ServiceModel.NetMsmqSecurity.Mode
  - System.ServiceModel.NetMsmqSecurity.Transport
  langs:
  - csharp
  name: NetMsmqSecurity
  nameWithType: NetMsmqSecurity
  fullName: System.ServiceModel.NetMsmqSecurity
  type: Class
  summary: "A NetMsmqSecurity osztály az MSMQ funkciókat foglalja az használata esetén a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> kötés."
  remarks: "Ilyen típusú objektum példányának létrehozásakor hozza létre a <xref:System.ServiceModel.NetMsmqBinding>kötés.</xref:System.ServiceModel.NetMsmqBinding> Ez az objektum használhatja a hivatkozhasson rá az összes kapcsolódó különféle biztonsági beállítás a <xref:System.ServiceModel.NetMsmqBinding>kötés.</xref:System.ServiceModel.NetMsmqBinding>"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#1](~/add/codesnippet/csharp/t-system.servicemodel.ne_3_1.cs)]
     [!code-vb[UENetMsmqSecurity#1](~/add/codesnippet/visualbasic/t-system.servicemodel.ne_3_1.vb)]
  syntax:
    content: public sealed class NetMsmqSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: NetMsmqSecurity()
  nameWithType: NetMsmqSecurity.NetMsmqSecurity()
  fullName: System.ServiceModel.NetMsmqSecurity.NetMsmqSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.NetMsmqSecurity&quot;> </xref> osztály."
  syntax:
    content: public NetMsmqSecurity ();
    parameters: []
  overload: System.ServiceModel.NetMsmqSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Message
  id: Message
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Message
  nameWithType: NetMsmqSecurity.Message
  fullName: System.ServiceModel.NetMsmqSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> , amely társítva van a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> kötés."
  remarks: "A <xref:System.ServiceModel.MessageSecurityOverMsmq>magában foglalja a SOAP-üzenet biztonsági beállításait.</xref:System.ServiceModel.MessageSecurityOverMsmq>"
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#2](~/add/codesnippet/csharp/p-system.servicemodel.ne_11_1.cs)]
     [!code-vb[UENetMsmqSecurity#2](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_11_1.vb)]
  syntax:
    content: public System.ServiceModel.MessageSecurityOverMsmq Message { get; set; }
    return:
      type: System.ServiceModel.MessageSecurityOverMsmq
      description: "A <xref href=&quot;System.ServiceModel.MessageSecurityOverMsmq&quot;> </xref> , amely társítva van a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> kötés."
  overload: System.ServiceModel.NetMsmqSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Mode
  id: Mode
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
  fullName: System.ServiceModel.NetMsmqSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> , amely társítva van a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> kötés."
  remarks: "Ez a tulajdonság határozza meg a biztonsági a társított NetMsmqBinding használják. Az alábbi lista részletesen ismerteti az elfogadható értékek:- **nincs** -nincs biztonsági szolgál.      - **Átviteli** – a transport security szolgál.      - **Üzenet** -üzenet-alapú biztonsági szolgál.      - **Mindkét** -mindkét üzenet-alapú biztonsági és a transport biztonsági szolgál."
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#3](~/add/codesnippet/csharp/p-system.servicemodel.ne_13_1.cs)]
     [!code-vb[UENetMsmqSecurity#3](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_13_1.vb)]
  syntax:
    content: public System.ServiceModel.NetMsmqSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.NetMsmqSecurityMode
      description: "A <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> , amely társítva van a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> kötés."
  overload: System.ServiceModel.NetMsmqSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Értéke nem egy <xref href=&quot;System.ServiceModel.NetMsmqSecurityMode&quot;> </xref> értékeket."
  platform:
  - net462
- uid: System.ServiceModel.NetMsmqSecurity.Transport
  id: Transport
  parent: System.ServiceModel.NetMsmqSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
  fullName: System.ServiceModel.NetMsmqSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> , amely társítva van a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> kötés."
  remarks: "Ez a tulajdonság lehetővé teszi, hogy az MSMQ átviteli biztonsági beállításai a hozzáférést."
  example:
  - >-
    [!code-cs[UENetMsmqSecurity#4](~/add/codesnippet/csharp/p-system.servicemodel.ne_19_1.cs)]
     [!code-vb[UENetMsmqSecurity#4](~/add/codesnippet/visualbasic/p-system.servicemodel.ne_19_1.vb)]
  syntax:
    content: public System.ServiceModel.MsmqTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.MsmqTransportSecurity
      description: "A <xref href=&quot;System.ServiceModel.MsmqTransportSecurity&quot;> </xref> , amely társítva van a <xref href=&quot;System.ServiceModel.NetMsmqBinding&quot;> </xref> kötés."
  overload: System.ServiceModel.NetMsmqSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.NetMsmqSecurity.#ctor
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: NetMsmqSecurity()
  nameWithType: NetMsmqSecurity.NetMsmqSecurity()
  fullName: System.ServiceModel.NetMsmqSecurity.NetMsmqSecurity()
- uid: System.ServiceModel.NetMsmqSecurity.Message
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurity.Message
  fullName: System.ServiceModel.NetMsmqSecurity.Message
- uid: System.ServiceModel.MessageSecurityOverMsmq
  parent: System.ServiceModel
  isExternal: false
  name: MessageSecurityOverMsmq
  nameWithType: MessageSecurityOverMsmq
  fullName: System.ServiceModel.MessageSecurityOverMsmq
- uid: System.ServiceModel.NetMsmqSecurity.Mode
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
  fullName: System.ServiceModel.NetMsmqSecurity.Mode
- uid: System.ServiceModel.NetMsmqSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: NetMsmqSecurityMode
  nameWithType: NetMsmqSecurityMode
  fullName: System.ServiceModel.NetMsmqSecurityMode
- uid: System.ServiceModel.NetMsmqSecurity.Transport
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
  fullName: System.ServiceModel.NetMsmqSecurity.Transport
- uid: System.ServiceModel.MsmqTransportSecurity
  parent: System.ServiceModel
  isExternal: false
  name: MsmqTransportSecurity
  nameWithType: MsmqTransportSecurity
  fullName: System.ServiceModel.MsmqTransportSecurity
- uid: System.ServiceModel.NetMsmqSecurity.#ctor*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: NetMsmqSecurity
  nameWithType: NetMsmqSecurity.NetMsmqSecurity
- uid: System.ServiceModel.NetMsmqSecurity.Message*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Message
  nameWithType: NetMsmqSecurity.Message
- uid: System.ServiceModel.NetMsmqSecurity.Mode*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Mode
  nameWithType: NetMsmqSecurity.Mode
- uid: System.ServiceModel.NetMsmqSecurity.Transport*
  parent: System.ServiceModel.NetMsmqSecurity
  isExternal: false
  name: Transport
  nameWithType: NetMsmqSecurity.Transport
