### YamlMime:ManagedReference
items:
- uid: System.Windows.Automation.ClientSettings
  id: ClientSettings
  children:
  - System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  - System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  langs:
  - csharp
  name: ClientSettings
  nameWithType: ClientSettings
  fullName: System.Windows.Automation.ClientSettings
  type: Class
  summary: "Ügyféloldali szolgáltatók az ügyfél számára elérhetővé metódust tartalmaz."
  syntax:
    content: public static class ClientSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  id: RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  parent: System.Windows.Automation.ClientSettings
  langs:
  - csharp
  name: RegisterClientSideProviderAssembly(AssemblyName)
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  type: Method
  assemblies:
  - UIAutomationClient
  namespace: System.Windows.Automation
  summary: "Regisztrálja az ügyféloldali szolgáltatók tartalmazó szerelvényt."
  remarks: "Ez a módszer egy szerelvény betöltése ügyféloldali Felhasználófelület-automatizálási szolgáltatók Felhasználófelület-automatizálási ügyfelek által indításkor nevezik. A saját szerelvény megvalósított szolgáltatók használó alkalmazások meg kell hívnia az <xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviders%2A>.</xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviders%2A>"
  example:
  - For example code, see [Register a Client-Side Provider Assembly](~/add/includes/ajax-current-ext-md.md).
  syntax:
    content: public static void RegisterClientSideProviderAssembly (System.Reflection.AssemblyName assemblyName);
    parameters:
    - id: assemblyName
      type: System.Reflection.AssemblyName
      description: "A szerelvény neve."
  overload: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly*
  exceptions:
  - type: System.Windows.Automation.ProxyAssemblyNotLoadedException
    commentId: T:System.Windows.Automation.ProxyAssemblyNotLoadedException
    description: "A szerelvény nem lehet betölteni."
  platform:
  - net462
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  id: RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  parent: System.Windows.Automation.ClientSettings
  langs:
  - csharp
  name: RegisterClientSideProviders(ClientSideProviderDescription[])
  nameWithType: ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  type: Method
  assemblies:
  - UIAutomationClient
  namespace: System.Windows.Automation
  summary: "Ügyféloldali szolgáltatók regisztrálása."
  remarks: "Ezt a módszert nevezik indításkor az ügyfelek, amelyek a saját ügyféloldali szolgáltatók megvalósításához. Egy külön szerelvény szolgáltatók használó ügyfelek <xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly%2A>.</xref:System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly%2A> kell hívni."
  example:
  - For example code, see [Implement UI Automation Providers in a Client Application](~/add/includes/ajax-current-ext-md.md).
  syntax:
    content: public static void RegisterClientSideProviders (System.Windows.Automation.ClientSideProviderDescription[] clientSideProviderDescription);
    parameters:
    - id: clientSideProviderDescription
      type: System.Windows.Automation.ClientSideProviderDescription[]
      description: "Szolgáltató leírások tömbjét."
  overload: System.Windows.Automation.ClientSettings.RegisterClientSideProviders*
  exceptions:
  - type: System.Windows.Automation.ProxyAssemblyNotLoadedException
    commentId: T:System.Windows.Automation.ProxyAssemblyNotLoadedException
    description: "A szerelvény nem lehet betölteni."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Windows.Automation.ProxyAssemblyNotLoadedException
  parent: System.Windows.Automation
  isExternal: false
  name: ProxyAssemblyNotLoadedException
  nameWithType: ProxyAssemblyNotLoadedException
  fullName: System.Windows.Automation.ProxyAssemblyNotLoadedException
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(System.Reflection.AssemblyName)
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviderAssembly(AssemblyName)
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly(AssemblyName)
- uid: System.Reflection.AssemblyName
  parent: System.Reflection
  isExternal: true
  name: AssemblyName
  nameWithType: AssemblyName
  fullName: System.Reflection.AssemblyName
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(System.Windows.Automation.ClientSideProviderDescription[])
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviders(ClientSideProviderDescription[])
  nameWithType: ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
  fullName: System.Windows.Automation.ClientSettings.RegisterClientSideProviders(ClientSideProviderDescription[])
- uid: System.Windows.Automation.ClientSideProviderDescription[]
  parent: System.Windows.Automation
  isExternal: false
  name: ClientSideProviderDescription
  nameWithType: ClientSideProviderDescription
  fullName: System.Windows.Automation.ClientSideProviderDescription[]
  spec.csharp:
  - uid: System.Windows.Automation.ClientSideProviderDescription
    name: ClientSideProviderDescription
    nameWithType: ClientSideProviderDescription
    fullName: ClientSideProviderDescription[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviderAssembly*
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviderAssembly
  nameWithType: ClientSettings.RegisterClientSideProviderAssembly
- uid: System.Windows.Automation.ClientSettings.RegisterClientSideProviders*
  parent: System.Windows.Automation.ClientSettings
  isExternal: false
  name: RegisterClientSideProviders
  nameWithType: ClientSettings.RegisterClientSideProviders
