### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.HttpCapabilitiesProvider
  id: HttpCapabilitiesProvider
  children:
  - System.Web.Configuration.HttpCapabilitiesProvider.#ctor
  - System.Web.Configuration.HttpCapabilitiesProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  langs:
  - csharp
  name: HttpCapabilitiesProvider
  nameWithType: HttpCapabilitiesProvider
  fullName: System.Web.Configuration.HttpCapabilitiesProvider
  type: Class
  summary: "Lehetővé teszi a böngésző-definíciók testreszabása. Testre szabhatja az algoritmus, amely azonosítja a böngészőben, a bejövő szereplő információ alapján <xref href=&quot;System.Web.HttpRequest&quot;> </xref>."
  syntax:
    content: public abstract class HttpCapabilitiesProvider
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesProvider.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.HttpCapabilitiesProvider
  langs:
  - csharp
  name: HttpCapabilitiesProvider()
  nameWithType: HttpCapabilitiesProvider.HttpCapabilitiesProvider()
  fullName: System.Web.Configuration.HttpCapabilitiesProvider.HttpCapabilitiesProvider()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.HttpCapabilitiesProvider&quot;> </xref> osztály."
  syntax:
    content: protected HttpCapabilitiesProvider ();
    parameters: []
  overload: System.Web.Configuration.HttpCapabilitiesProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.HttpCapabilitiesProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  id: GetBrowserCapabilities(System.Web.HttpRequest)
  parent: System.Web.Configuration.HttpCapabilitiesProvider
  langs:
  - csharp
  name: GetBrowserCapabilities(HttpRequest)
  nameWithType: HttpCapabilitiesProvider.GetBrowserCapabilities(HttpRequest)
  fullName: System.Web.Configuration.HttpCapabilitiesProvider.GetBrowserCapabilities(HttpRequest)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> az aktuális böngésző objektum."
  syntax:
    content: public abstract System.Web.HttpBrowserCapabilities GetBrowserCapabilities (System.Web.HttpRequest request);
    parameters:
    - id: request
      type: System.Web.HttpRequest
      description: "Az aktuális <xref href=&quot;System.Web.HttpRequest&quot;> </xref> objektum."
    return:
      type: System.Web.HttpBrowserCapabilities
      description: "A <xref href=&quot;System.Web.HttpBrowserCapabilities&quot;> </xref> az aktuális böngésző objektum."
  overload: System.Web.Configuration.HttpCapabilitiesProvider.GetBrowserCapabilities*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.Configuration.HttpCapabilitiesProvider.#ctor
  parent: System.Web.Configuration.HttpCapabilitiesProvider
  isExternal: false
  name: HttpCapabilitiesProvider()
  nameWithType: HttpCapabilitiesProvider.HttpCapabilitiesProvider()
  fullName: System.Web.Configuration.HttpCapabilitiesProvider.HttpCapabilitiesProvider()
- uid: System.Web.Configuration.HttpCapabilitiesProvider.GetBrowserCapabilities(System.Web.HttpRequest)
  parent: System.Web.Configuration.HttpCapabilitiesProvider
  isExternal: false
  name: GetBrowserCapabilities(HttpRequest)
  nameWithType: HttpCapabilitiesProvider.GetBrowserCapabilities(HttpRequest)
  fullName: System.Web.Configuration.HttpCapabilitiesProvider.GetBrowserCapabilities(HttpRequest)
- uid: System.Web.HttpBrowserCapabilities
  parent: System.Web
  isExternal: false
  name: HttpBrowserCapabilities
  nameWithType: HttpBrowserCapabilities
  fullName: System.Web.HttpBrowserCapabilities
- uid: System.Web.HttpRequest
  parent: System.Web
  isExternal: false
  name: HttpRequest
  nameWithType: HttpRequest
  fullName: System.Web.HttpRequest
- uid: System.Web.Configuration.HttpCapabilitiesProvider.#ctor*
  parent: System.Web.Configuration.HttpCapabilitiesProvider
  isExternal: false
  name: HttpCapabilitiesProvider
  nameWithType: HttpCapabilitiesProvider.HttpCapabilitiesProvider
- uid: System.Web.Configuration.HttpCapabilitiesProvider.GetBrowserCapabilities*
  parent: System.Web.Configuration.HttpCapabilitiesProvider
  isExternal: false
  name: GetBrowserCapabilities
  nameWithType: HttpCapabilitiesProvider.GetBrowserCapabilities
