### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs
  id: DownloadProgressChangedEventArgs
  children:
  - System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  - System.Deployment.Application.DownloadProgressChangedEventArgs.State
  - System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  langs:
  - csharp
  name: DownloadProgressChangedEventArgs
  nameWithType: DownloadProgressChangedEventArgs
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs
  type: Class
  summary: "Adja meg az adatait a <xref href=&quot;System.Deployment.Application.InPlaceHostingManager.DownloadProgressChanged&quot;> </xref> esemény."
  remarks: "Egy konzolalkalmazásban óta események szálak számát, a szálkészlet kívül hozzárendelt frissítés folyamatban lévő események sorrendje, egy későbbi előző események képest csökkenése megjelenítő kaphat. Ilyen viselkedést, a Windows Forms alkalmazásban nem látják, mert a Windows Forms események feldolgozása sorrendben történik a felhasználói felület szálán üzenet várósorból kirakni."
  example:
  - "The following code example demonstrates the use of DownloadProgressChangedEventArgs in the context of an application that uses <xref:System.Deployment.Application.InPlaceHostingManager> to download and install a ClickOnce application programmatically.  \n  \n [!code-vb[System.Deployment.Application.InPlaceHostingManager#1](~/add/codesnippet/visualbasic/InPlaceHostingManagerProjectVB/Form1.vb#1)]\n [!code-cs[System.Deployment.Application.InPlaceHostingManager#1](~/add/codesnippet/csharp/InPlaceHostingManagerProject/Form1.cs#1)]"
  syntax:
    content: 'public class DownloadProgressChangedEventArgs : System.ComponentModel.ProgressChangedEventArgs'
  inheritance:
  - System.ComponentModel.ProgressChangedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  id: BytesDownloaded
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a helyi számítógép letöltött bájtok száma."
  syntax:
    content: public long BytesDownloaded { get; }
    return:
      type: System.Int64
      description: "Egy <xref:System.Int64>bájtok számát jelöli letöltött.</xref:System.Int64>"
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  id: State
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "A letöltési folyamat állapotának beolvasása."
  syntax:
    content: public System.Deployment.Application.DeploymentProgressState State { get; }
    return:
      type: System.Deployment.Application.DeploymentProgressState
      description: "A <xref href=&quot;System.Deployment.Application.DeploymentProgressState&quot;> </xref> leíró, mely a ClickOnce alkalmazás része letöltődött érték."
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.State*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  id: TotalBytesToDownload
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  langs:
  - csharp
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "A letöltési művelet lekérdezi a bájtok teljes száma."
  syntax:
    content: public long TotalBytesToDownload { get; }
    return:
      type: System.Int64
      description: "Egy <xref:System.Int64>jelölő teljes mérete bájtban a letöltés.</xref:System.Int64>"
  overload: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.ProgressChangedEventArgs
  isExternal: false
  name: System.ComponentModel.ProgressChangedEventArgs
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.State
- uid: System.Deployment.Application.DeploymentProgressState
  parent: System.Deployment.Application
  isExternal: false
  name: DeploymentProgressState
  nameWithType: DeploymentProgressState
  fullName: System.Deployment.Application.DeploymentProgressState
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
  fullName: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.BytesDownloaded*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: BytesDownloaded
  nameWithType: DownloadProgressChangedEventArgs.BytesDownloaded
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.State*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: State
  nameWithType: DownloadProgressChangedEventArgs.State
- uid: System.Deployment.Application.DownloadProgressChangedEventArgs.TotalBytesToDownload*
  parent: System.Deployment.Application.DownloadProgressChangedEventArgs
  isExternal: false
  name: TotalBytesToDownload
  nameWithType: DownloadProgressChangedEventArgs.TotalBytesToDownload
