### YamlMime:ManagedReference
items:
- uid: System.Windows.Input.MouseActionValueSerializer
  id: MouseActionValueSerializer
  children:
  - System.Windows.Input.MouseActionValueSerializer.#ctor
  - System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  - System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  langs:
  - csharp
  name: MouseActionValueSerializer
  nameWithType: MouseActionValueSerializer
  fullName: System.Windows.Input.MouseActionValueSerializer
  type: Class
  summary: "Konvertálja példányai <xref:System.String>példányai érkező vagy oda irányuló <xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>.</xref:System.String>"
  remarks: "Ez az osztály általában csak szükség szerint a <xref:System.Windows.Markup.Primitives.MarkupWriter>szerializálási célokra.</xref:System.Windows.Markup.Primitives.MarkupWriter>      <a name=&quot;xamlTextUsage_MouseActionValueSerializer&quot;></a>## XAML szöveg kihasználtsága"
  syntax:
    content: 'public class MouseActionValueSerializer : System.Windows.Markup.ValueSerializer'
  inheritance:
  - System.Windows.Markup.ValueSerializer
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.#ctor
  id: '#ctor'
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: MouseActionValueSerializer()
  nameWithType: MouseActionValueSerializer.MouseActionValueSerializer()
  fullName: System.Windows.Input.MouseActionValueSerializer.MouseActionValueSerializer()
  type: Constructor
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Windows.Input.MouseActionValueSerializer&quot;> </xref> osztály."
  syntax:
    content: public MouseActionValueSerializer ();
    parameters: []
  overload: System.Windows.Input.MouseActionValueSerializer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Meghatározza, hogy a megadott <xref:System.String>alakítható át egy példánya lehet <xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override bool CanConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "Értékelje ki az átalakításhoz karakterláncot."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Környezeti információkat, amelyek lesznek felhasználva az átalakításhoz."
    return:
      type: System.Boolean
      description: "Mindig vissza <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Meghatározza, hogy a megadott <xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref> <xref:System.String>.</xref:System.String> konvertálható"
  syntax:
    content: public override bool CanConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "Átalakítás kiértékelése módosító kulcsok."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Környezeti információkat, amelyek lesznek felhasználva az átalakításhoz."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha <code> value </code> konvertálni kell egy <xref:System.String>; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.String>"
  overload: System.Windows.Input.MouseActionValueSerializer.CanConvertToString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  id: ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Konvertálja a <xref:System.String>be egy <xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>.</xref:System.String>"
  syntax:
    content: public override object ConvertFromString (string value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.String
      description: "A karakterlánc alakítani egy <xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Környezeti információkat, amelyek lesznek felhasználva az átalakításhoz."
    return:
      type: System.Object
      description: "Egy új példányát <xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref> a megadott alapján <code> value </code>."
  overload: System.Windows.Input.MouseActionValueSerializer.ConvertFromString*
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  id: ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  langs:
  - csharp
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  type: Method
  assemblies:
  - PresentationCore
  namespace: System.Windows.Input
  summary: "Konvertálja példányának <xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref> <xref:System.String>.</xref:System.String>"
  syntax:
    content: public override string ConvertToString (object value, System.Windows.Markup.IValueSerializerContext context);
    parameters:
    - id: value
      type: System.Object
      description: "A kulcs karakterlánccá konvertálni."
    - id: context
      type: System.Windows.Markup.IValueSerializerContext
      description: "Környezeti információkat, amelyek lesznek felhasználva az átalakításhoz."
    return:
      type: System.String
      description: "Egy megadott állandó karakterláncos ábrázolása <xref href=&quot;System.Windows.Input.MouseAction&quot;> </xref>."
  overload: System.Windows.Input.MouseActionValueSerializer.ConvertToString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Windows.Markup.ValueSerializer
  isExternal: false
  name: System.Windows.Markup.ValueSerializer
- uid: System.Windows.Input.MouseActionValueSerializer.#ctor
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: MouseActionValueSerializer()
  nameWithType: MouseActionValueSerializer.MouseActionValueSerializer()
  fullName: System.Windows.Input.MouseActionValueSerializer.MouseActionValueSerializer()
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString(String,IValueSerializerContext)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Windows.Markup.IValueSerializerContext
  parent: System.Windows.Markup
  isExternal: true
  name: IValueSerializerContext
  nameWithType: IValueSerializerContext
  fullName: System.Windows.Markup.IValueSerializerContext
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.CanConvertToString(Object,IValueSerializerContext)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(System.String,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertFromString(String,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertFromString(String,IValueSerializerContext)
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertToString(System.Object,System.Windows.Markup.IValueSerializerContext)
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertToString(Object,IValueSerializerContext)
  nameWithType: MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
  fullName: System.Windows.Input.MouseActionValueSerializer.ConvertToString(Object,IValueSerializerContext)
- uid: System.Windows.Input.MouseActionValueSerializer.#ctor*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: MouseActionValueSerializer
  nameWithType: MouseActionValueSerializer.MouseActionValueSerializer
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertFromString*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertFromString
  nameWithType: MouseActionValueSerializer.CanConvertFromString
- uid: System.Windows.Input.MouseActionValueSerializer.CanConvertToString*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: CanConvertToString
  nameWithType: MouseActionValueSerializer.CanConvertToString
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertFromString*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertFromString
  nameWithType: MouseActionValueSerializer.ConvertFromString
- uid: System.Windows.Input.MouseActionValueSerializer.ConvertToString*
  parent: System.Windows.Input.MouseActionValueSerializer
  isExternal: false
  name: ConvertToString
  nameWithType: MouseActionValueSerializer.ConvertToString
