### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  id: XPathMessageFilterElementComparer
  children:
  - System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  - System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  langs:
  - csharp
  name: XPathMessageFilterElementComparer
  nameWithType: XPathMessageFilterElementComparer
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  type: Class
  summary: "Hasonlítsa össze a két lehetőségeket kínál <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;> </xref> példányok."
  syntax:
    content: 'public class XPathMessageFilterElementComparer : System.Collections.IComparer'
  inheritance:
  - System.Object
  implements:
  - System.Collections.IComparer
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  langs:
  - csharp
  name: XPathMessageFilterElementComparer()
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElementComparer&quot;> </xref> osztály."
  syntax:
    content: public XPathMessageFilterElementComparer ();
    parameters: []
  overload: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  id: System#Collections#IComparer#Compare(System.Object,System.Object)
  isEii: true
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  langs:
  - csharp
  name: System.Collections.IComparer.Compare(Object,Object)
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Hasonlítsa össze a két <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;> </xref> példányok."
  syntax:
    content: int IComparer.Compare (object x, object y);
    parameters:
    - id: x
      type: System.Object
      description: "A <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;></xref>."
    - id: y
      type: System.Object
      description: "A <xref href=&quot;System.ServiceModel.Configuration.XPathMessageFilterElement&quot;></xref>."
    return:
      type: System.Int32
      description: "A következő táblázat a lehetséges értékek.       <table><thead><tr><th> Érték       </th><th> Állapot       </th></tr></thead><tbody><tr><td> -1       </td><td><code>x</code>is less than <code>y</code>.       </td></tr><tr><td> 0       </td><td><code>x</code>is equal to <code>y</code>.       </td></tr><tr><td> 1       </td><td><code>x</code>nagyobb, mint <code> y </code>.       </td></tr></tbody></table>"
  overload: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Az XPath-szűrő által megadott <code> x </code> vagy <code> y </code> nem elemezhető."
  - type: System.IndexOutOfRangeException
    commentId: T:System.IndexOutOfRangeException
    description: "A megadott XPath névtérelőtag <code> x </code> vagy <code> y </code>.cannot található."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.IndexOutOfRangeException
  isExternal: true
  name: System.IndexOutOfRangeException
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: XPathMessageFilterElementComparer()
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.XPathMessageFilterElementComparer()
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare(System.Object,System.Object)
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: System.Collections.IComparer.Compare(Object,Object)
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
  fullName: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System.Collections.IComparer.Compare(Object,Object)
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.#ctor*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: XPathMessageFilterElementComparer
  nameWithType: XPathMessageFilterElementComparer.XPathMessageFilterElementComparer
- uid: System.ServiceModel.Configuration.XPathMessageFilterElementComparer.System#Collections#IComparer#Compare*
  parent: System.ServiceModel.Configuration.XPathMessageFilterElementComparer
  isExternal: false
  name: System.Collections.IComparer.Compare
  nameWithType: XPathMessageFilterElementComparer.System.Collections.IComparer.Compare
