### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsDescriptionAttribute
  id: SettingsDescriptionAttribute
  children:
  - System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  - System.Configuration.SettingsDescriptionAttribute.Description
  langs:
  - csharp
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute
  fullName: System.Configuration.SettingsDescriptionAttribute
  type: Class
  summary: "Itt egy karakterlánc, amely az egyes konfigurációs tulajdonság. Ez az osztály nem örökölhető."
  remarks: "A SettingsDescriptionAttribute célja segítség nyújtása tervezőeszközök idő és a futási idő felügyeleti eszközök azonosítására és a társított konfigurációs tulajdonság leíró.       Ez az attribútum nem kötelező, és csak az egyes konfigurációs tulajdonság szinten alkalmazható."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class SettingsDescriptionAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy példányát inicializálja a <xref href=&quot;System.Configuration.SettingsDescriptionAttribute&quot;> </xref> osztály."
  remarks: "Bár a leírás hossza elméleti maximális a <xref:System.String>osztály, amelynek hosszúsága által képviselt egy <xref:System.Int32>, a következő két gyakorlati szempontok mérete korlátozza a `description` paraméter:-nagy szövegek nehezen jeleníti meg a felhasználói felületen (UI) és a felhasználó számára, olvassa el a.</xref:System.Int32> </xref:System.String>      -Beállítások szolgáltatók összesített használati kvóták léptethet, és felhasználói konfiguráció kvóták kényszerítésére van szükség."
  syntax:
    content: public SettingsDescriptionAttribute (string description);
    parameters:
    - id: description
      type: System.String
      description: "A <xref:System.String>leíró szövegként.</xref:System.String>"
  overload: System.Configuration.SettingsDescriptionAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  id: Description
  parent: System.Configuration.SettingsDescriptionAttribute
  langs:
  - csharp
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A leíró szöveg lekérdezi a társított konfigurációs tulajdonság."
  remarks: "A Description tulajdonságot állítja be a <xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A>konstruktor.</xref:System.Configuration.SettingsDescriptionAttribute.%23ctor%2A>"
  syntax:
    content: public string Description { get; }
    return:
      type: System.String
      description: "A <xref:System.String>a társított konfigurációs tulajdonság a leíró szöveget tartalmazó.</xref:System.String>"
  overload: System.Configuration.SettingsDescriptionAttribute.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute(String)
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
  fullName: System.Configuration.SettingsDescriptionAttribute.SettingsDescriptionAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsDescriptionAttribute.Description
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
  fullName: System.Configuration.SettingsDescriptionAttribute.Description
- uid: System.Configuration.SettingsDescriptionAttribute.#ctor*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: SettingsDescriptionAttribute
  nameWithType: SettingsDescriptionAttribute.SettingsDescriptionAttribute
- uid: System.Configuration.SettingsDescriptionAttribute.Description*
  parent: System.Configuration.SettingsDescriptionAttribute
  isExternal: false
  name: Description
  nameWithType: SettingsDescriptionAttribute.Description
