### YamlMime:ManagedReference
items:
- uid: System.Configuration.DefaultSettingValueAttribute
  id: DefaultSettingValueAttribute
  children:
  - System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  - System.Configuration.DefaultSettingValueAttribute.Value
  langs:
  - csharp
  name: DefaultSettingValueAttribute
  nameWithType: DefaultSettingValueAttribute
  fullName: System.Configuration.DefaultSettingValueAttribute
  type: Class
  summary: "Adja meg az alkalmazás beállításainak tulajdonság alapértelmezett értéke."
  remarks: "> [!IMPORTANT]> DefaultSettingValueAttribute csak alkalmazható egyes beállításainak tulajdonságai; Ez az attribútum alkalmazandó az alkalmazás teljes beállítások osztály érvénytelen.       Eltérő beállításokat szolgáltatók lehet különböző követelményeket vagy korlátozásokat a a DefaultSettingValueAttribute használatát. Például a <xref:System.Configuration.LocalFileSettingsProvider>szükség erre az attribútumra, és felülírja, ha bármely érték ez az attribútum által megadott bármilyen érték – alapértelmezett vagy felhasználó által módosított – már szerepel az adattárban.</xref:System.Configuration.LocalFileSettingsProvider>       DefaultSettingValueAttribute megköveteli, hogy az alapértelmezett érték a karakterláncból ábrázolhatók. Ennek eredményeképpen a beállításokat a XML-szerializáláshoz nem lehet ez az attribútum által megadott alapértelmezett értéket. Egyes szolgáltatók dönthetnek úgy, hogy támogatási több szerializálási rendszerek, amelyek használatával a <xref:System.Configuration.SettingsSerializeAsAttribute>.</xref:System.Configuration.SettingsSerializeAsAttribute> fordítás során adható meg      > [!CAUTION] > Ez az attribútum által megadott alapértelmezett értékek az eredményül kapott lefordított .exe vagy .dll fájlt egyszerű szövegként tárolódnak. Ezért ezek az alapértelmezett értékek eredendően nem biztonságos."
  example:
  - "The following code example demonstrates the use of the DefaultSettingValueAttribute applied to three of the four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The first three of these form properties have default values associated with them.  \n  \n The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.d_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.d_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class DefaultSettingValueAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.DefaultSettingValueAttribute
  langs:
  - csharp
  name: DefaultSettingValueAttribute(String)
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  fullName: System.Configuration.DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy példányát inicializálja a <xref href=&quot;System.Configuration.DefaultSettingValueAttribute&quot;> </xref> osztály."
  remarks: "A megadott karakterlánc, amely kompatibilis a tulajdonság típusa társított elérhető szerializálási mechanizmusa értéknek kell lennie. Például, ha a tulajdonság típusú <xref:System.Drawing.Color>, majd egy `value` a `&quot;Azure&quot;` lesz érvényes.</xref:System.Drawing.Color>      > [!CAUTION] > Ez az attribútum által megadott alapértelmezett értékek az eredményül kapott lefordított .exe vagy .dll fájlt egyszerű szövegként tárolódnak. Ezért ezek az alapértelmezett értékek eredendően nem biztonságos."
  syntax:
    content: public DefaultSettingValueAttribute (string value);
    parameters:
    - id: value
      type: System.String
      description: "A <xref:System.String>, amely jelöli az alapértelmezett érték a tulajdonság.</xref:System.String>"
  overload: System.Configuration.DefaultSettingValueAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DefaultSettingValueAttribute.Value
  id: Value
  parent: System.Configuration.DefaultSettingValueAttribute
  langs:
  - csharp
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
  fullName: System.Configuration.DefaultSettingValueAttribute.Value
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekéri az alapértelmezett érték az alkalmazás beállításainak tulajdonság."
  remarks: "A Value tulajdonság értéke a <xref:System.Configuration.DefaultSettingValueAttribute.%23ctor%2A>konstruktor.</xref:System.Configuration.DefaultSettingValueAttribute.%23ctor%2A>       Szolgáltatók beállítás támogatást nyújthat több szerializálási <xref:System.Configuration.SettingsSerializeAsAttribute>.</xref:System.Configuration.SettingsSerializeAsAttribute> adható meg"
  syntax:
    content: public string Value { get; }
    return:
      type: System.String
      description: "A <xref:System.String>, amely jelöli az alapértelmezett érték a tulajdonság.</xref:System.String>"
  overload: System.Configuration.DefaultSettingValueAttribute.Value*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor(System.String)
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: DefaultSettingValueAttribute(String)
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
  fullName: System.Configuration.DefaultSettingValueAttribute.DefaultSettingValueAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DefaultSettingValueAttribute.Value
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
  fullName: System.Configuration.DefaultSettingValueAttribute.Value
- uid: System.Configuration.DefaultSettingValueAttribute.#ctor*
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: DefaultSettingValueAttribute
  nameWithType: DefaultSettingValueAttribute.DefaultSettingValueAttribute
- uid: System.Configuration.DefaultSettingValueAttribute.Value*
  parent: System.Configuration.DefaultSettingValueAttribute
  isExternal: false
  name: Value
  nameWithType: DefaultSettingValueAttribute.Value
