### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement
  id: IdentityModelCachesElement
  children:
  - System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  - System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  - System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  - System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  - System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  langs:
  - csharp
  name: IdentityModelCachesElement
  nameWithType: IdentityModelCachesElement
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement
  type: Class
  summary: "Jelöli egy <xref uid=&quot;langword_csharp_&lt;caches&gt;&quot; name=&quot;&lt;caches&gt;&quot; href=&quot;&quot;> </xref> egy konfigurációs fájlban. Ez az osztály nem örökölhető."
  remarks: "A `<caches>` elem konfigurálja a WIF gyorsítótárazási szolgáltatásokat. A biztonsági jogkivonat gyorsítótár típusa és a hitelesítési karakterláncok ismétlésének gyorsítótár használatára történő regisztrálást. Akkor adhatók meg a szolgáltatási szint alatt, a `<identityConfiguration>` elem vagy egy biztonsági jogkivonat-kezelő gyűjtemény a `<securityTokenHandlerConfiguration>` elemet. A `Caches` tulajdonsága a <xref:System.IdentityModel.Configuration.IdentityConfigurationElement>osztály és a <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement>osztály a példánya: IdentityModelCachesElement.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement> </xref:System.IdentityModel.Configuration.IdentityConfigurationElement> Miután a konfigurációs fájl beolvasása megtörtént, konfigurált gyorsítótárat jelölik a <xref:System.IdentityModel.Configuration.IdentityModelCaches>osztályhoz.</xref:System.IdentityModel.Configuration.IdentityModelCaches>"
  syntax:
    content: 'public sealed class IdentityModelCachesElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: IdentityModelCachesElement()
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement()
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IdentityModelCachesElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.Configuration.IdentityModelCachesElement&quot;> </xref> osztály."
  syntax:
    content: public IdentityModelCachesElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  id: IsConfigured
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi egy érték, amely azt jelzi, hogy ez az elem konfigurálva van-e."
  syntax:
    content: public bool IsConfigured { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az elem konfigurálva van. Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  id: SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi vagy beállítja a <xref:System.Type>token munkamenet-gyorsítótár.</xref:System.Type>"
  remarks: "Ez a tulajdonság opcionális. Megfelel a `<sessionSecurityTokenCache>` elem alatt megadott a `<caches>`. Azt határozza meg a munkamenet biztonsági jogkivonatokat tárolására szolgáló gyorsítótár. Minden munkamenet token gyorsítótárak kell származnia:<xref:System.IdentityModel.Tokens.SessionSecurityTokenCache></xref:System.IdentityModel.Tokens.SessionSecurityTokenCache>"
  syntax:
    content: public System.IdentityModel.Configuration.CustomTypeElement SessionSecurityTokenCache { get; set; }
    return:
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: "A munkamenet biztonságijogkivonat-gyorsítótár típusa. A típus kell származnia: [System.IdentityModel.Tokens.SessionSecurityTokenCache](~/add/includes/ajax-current-ext-md.md)."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  id: TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  langs:
  - csharp
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi vagy beállítja a <xref:System.Type>jogkivonat visszajátszásos gyorsítótár.</xref:System.Type>"
  remarks: "Ez a tulajdonság opcionális. Megfelel egy `<tokenReplayCache>` elem alatt megadott a `<caches>` elemet. Azt határozza meg a megismételt jogkivonatok észleli a gyorsítótárban. Minden ismétlési gyorsítótár kell származnia: <xref:System.IdentityModel.Tokens.TokenReplayCache>visszajátszás-érzékelés engedélyezve van a `<tokenReplayDetection>` elem.</xref:System.IdentityModel.Tokens.TokenReplayCache> Ez az elem képviseli az <xref:System.IdentityModel.Configuration.TokenReplayDetectionElement>osztályhoz.</xref:System.IdentityModel.Configuration.TokenReplayDetectionElement>"
  syntax:
    content: public System.IdentityModel.Configuration.CustomTypeElement TokenReplayCache { get; set; }
    return:
      type: System.IdentityModel.Configuration.CustomTypeElement
      description: "A hitelesítési karakterláncok ismétlésének gyorsítótár típusa. A típus kell származnia: [System.IdentityModel.Tokens.TokenReplayCache](~/add/includes/ajax-current-ext-md.md)."
  overload: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IdentityModelCachesElement()
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement()
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IdentityModelCachesElement()
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.CustomTypeElement
  parent: System.IdentityModel.Configuration
  isExternal: false
  name: CustomTypeElement
  nameWithType: CustomTypeElement
  fullName: System.IdentityModel.Configuration.CustomTypeElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
  fullName: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.#ctor*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IdentityModelCachesElement
  nameWithType: IdentityModelCachesElement.IdentityModelCachesElement
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.IsConfigured*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: IsConfigured
  nameWithType: IdentityModelCachesElement.IsConfigured
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.Properties*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: Properties
  nameWithType: IdentityModelCachesElement.Properties
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.SessionSecurityTokenCache*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: SessionSecurityTokenCache
  nameWithType: IdentityModelCachesElement.SessionSecurityTokenCache
- uid: System.IdentityModel.Configuration.IdentityModelCachesElement.TokenReplayCache*
  parent: System.IdentityModel.Configuration.IdentityModelCachesElement
  isExternal: false
  name: TokenReplayCache
  nameWithType: IdentityModelCachesElement.TokenReplayCache
