### YamlMime:ManagedReference
items:
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  id: PeerApplicationLaunchInfo
  children:
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  - System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  langs:
  - csharp
  name: PeerApplicationLaunchInfo
  nameWithType: PeerApplicationLaunchInfo
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  type: Class
  summary: "A szükséges indítási adatait jelöli egy <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> , amely egy társ együttműködés meghívó válaszul kezdeményezte."
  remarks: "Egy alkalmazás vizsgálhatja meg a <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A>és <xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A>Ez az osztály a lekérése a meghívóra, amelyben az alkalmazás indítási kezdeményezett jellemző tulajdonságok.</xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message%2A> </xref:System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data%2A>       Ez az osztály használatához egy <xref:System.Security.Permissions.PermissionState> <xref:System.Security.Permissions.PermissionState>.</xref:System.Security.Permissions.PermissionState> </xref:System.Security.Permissions.PermissionState> Ebben az állapotban jön létre, amikor a <xref:System.Net.PeerToPeer.Collaboration.Peer>együttműködés munkamenet kezdete.</xref:System.Net.PeerToPeer.Collaboration.Peer>"
  syntax:
    content: public class PeerApplicationLaunchInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  id: Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Lekérdezi vagy beállítja a társított alkalmazás által meghatározott bináris adatok a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> meghívó."
  remarks: "Az adatok blob szabad formátumú, és a hívó által biztosított.  A maximális adatmennyiség megadható érték 4096 bájt.       Az adatokat nem lehet `null`."
  syntax:
    content: public byte[] Data { get; }
    return:
      type: System.Byte[]
      description: "Bájttömb társított úgy, hogy az adatok a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> meghívó."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  id: Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Beolvasni vagy megadni válasz társított üzenetet a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> meghívó."
  remarks: "Az üzenet maximális hossza 255 Unicode-karaktereket. Ha explicit módon megadott, alapértelmezett összes tulajdonságának értéke `null` referencia típusok."
  syntax:
    content: public string Message { get; }
    return:
      type: System.String
      description: "Szöveges üzenet társított a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerInvitationResponse&quot;> </xref> számára a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> meghívó."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  id: PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> a meghívó elküldte a."
  remarks: "Ha explicit módon megadott, alapértelmezett összes tulajdonságának értéke `null` referencia típusok."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerApplication PeerApplication { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerApplication
      description: "A <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> , amelynek a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerCollaboration&quot;> </xref> küldött meghívót."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  id: PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> , amely a meghívóra küldött."
  remarks: "Ha explicit módon megadott, alapértelmezett összes tulajdonságának értéke `null` referencia típusok."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerContact PeerContact { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerContact
      description: "A <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerContact&quot;> </xref> , amely a meghívóra küldött."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  exceptions: []
  platform:
  - net462
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  id: PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  langs:
  - csharp
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  type: Property
  assemblies:
  - System.Net
  namespace: System.Net.PeerToPeer.Collaboration
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> , amelyből a <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerApplication&quot;> </xref> küldött meghívót."
  remarks: "Ha explicit módon megadott, alapértelmezett összes tulajdonságának értéke `null` referencia típusok."
  syntax:
    content: public System.Net.PeerToPeer.Collaboration.PeerEndPoint PeerEndPoint { get; }
    return:
      type: System.Net.PeerToPeer.Collaboration.PeerEndPoint
      description: "A <xref href=&quot;System.Net.PeerToPeer.Collaboration.PeerEndPoint&quot;> </xref> amely a meghívóra érkezik."
  overload: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data
- uid: System.Byte[]
  parent: System
  isExternal: true
  name: Byte
  nameWithType: Byte
  fullName: System.Byte[]
  spec.csharp:
  - uid: System.Byte
    name: Byte
    nameWithType: Byte
    fullName: Byte[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplication
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplication
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerContact
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerContact
  nameWithType: PeerContact
  fullName: System.Net.PeerToPeer.Collaboration.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerEndPoint
  parent: System.Net.PeerToPeer.Collaboration
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerEndPoint
  fullName: System.Net.PeerToPeer.Collaboration.PeerEndPoint
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Data*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Data
  nameWithType: PeerApplicationLaunchInfo.Data
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.Message*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: Message
  nameWithType: PeerApplicationLaunchInfo.Message
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerApplication*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerApplication
  nameWithType: PeerApplicationLaunchInfo.PeerApplication
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerContact*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerContact
  nameWithType: PeerApplicationLaunchInfo.PeerContact
- uid: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo.PeerEndPoint*
  parent: System.Net.PeerToPeer.Collaboration.PeerApplicationLaunchInfo
  isExternal: false
  name: PeerEndPoint
  nameWithType: PeerApplicationLaunchInfo.PeerEndPoint
