### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.FolderLevelBuildProvider
  id: FolderLevelBuildProvider
  children:
  - System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  - System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  - System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  - System.Web.Configuration.FolderLevelBuildProvider.Name
  - System.Web.Configuration.FolderLevelBuildProvider.Properties
  - System.Web.Configuration.FolderLevelBuildProvider.Type
  langs:
  - csharp
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider
  fullName: System.Web.Configuration.FolderLevelBuildProvider
  type: Class
  summary: "Konfigurációs beállítások, amelyek lehetővé teszik a használata jelenti a <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> osztály a meghatározott mappákról."
  remarks: "Az ASP.NET-összeállító környezetet FolderLevelBuildProvider-objektumokat használ a különböző fájltípusokról és az almappák forráskód létrehozása az alkalmazásban. A FolderLevelBuildProvider osztályból származtatott osztályok forráskód Bin, App_GlobalResources, App_LocalResources, App_WebReferences, App_Browsers, valamint a téma mappákat, illetve más egyéni mappák létrehozása. Általában hogy ne hozzon létre a FolderLevelBuildProvider osztály egyik példányához tartozó közvetlenül. Ehelyett valósítja meg az abból származó osztály <xref:System.Web.Compilation.BuildProvider>és alkalmazza a <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>azt az osztályt, és adja meg a származtatott osztály használatra az ASP.NET-összeállító környezetet a.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute> </xref:System.Web.Compilation.BuildProvider> A <xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>osztály helyett a fájlok mappák célozza.</xref:System.Web.Compilation.FolderLevelBuildProviderAppliesToAttribute>       Használhat együtt FolderLevelBuildProvider osztály példányai <xref:System.Web.Compilation.AssemblyBuilder>objektumok be egy lefordított szerelvény egy vagy több fájl létrehozásához.</xref:System.Web.Compilation.AssemblyBuilder> A FolderLevelBuildProvider példány forráskód hoz létre az egyes fájlokhoz, a megfelelő nyelvet és a <xref:System.Web.Compilation.AssemblyBuilder>objektumot hoz létre minden egyes FolderLevelBuildProvider példányának egyetlen szerelvényben által közzétett forráskódban.</xref:System.Web.Compilation.AssemblyBuilder>       A FolderLevelBuildProvider osztály van megadva a `configuration` szakasz a Web.config fájl."
  example:
  - "The following example shows how to add a build provider named `BuildProvider1` to the Web.config file.  \n  \n```  \n<compilation>  \n  <folderLevelBuildProviders>  \n    <add type=\"BuildProvider1, Assembly1,Version=1.0.0.0,    \n        PublicKeyToken=xxxxx\"/>  \n  </folderLevelBuildProviders>  \n</compilation>  \n```"
  syntax:
    content: 'public sealed class FolderLevelBuildProvider : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> osztály azonosítót és a teljes nevet."
  syntax:
    content: public FolderLevelBuildProvider (string name, string type);
    parameters:
    - id: name
      type: System.String
      description: "Az azonosítóját, a <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> használatára."
    - id: type
      type: System.String
      description: "A teljesen minősített neve a <xref href=&quot;System.Web.Compilation.BuildProvider&quot;> </xref> használatára."
  overload: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Jelzi, hogy egy adott objektum aktuális egyenlő értéket ad vissza <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> objektum."
  syntax:
    content: public override bool Equals (object provider);
    parameters:
    - id: provider
      type: System.Object
      description: "A build szolgáltató objektum összehasonlítani."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a megadott mappa szint szolgáltató objektum megegyezik az aktuális objektum; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy kivonatoló kódot generál a <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> objektum."
  remarks: "Ezzel a módszerrel hoz létre, egész szám, amely a mappa szintű build szolgáltató objektum azonosítására használható. Ez a módszer örökli a <xref:System.Object.GetHashCode%2A>metódus.</xref:System.Object.GetHashCode%2A> A <xref:System.Object.GetHashCode%2A>metódus alkalmas kivonatoló algoritmusok és adatok struktúrák például egy kivonattáblát.</xref:System.Object.GetHashCode%2A>"
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "A kivonatoló kódját a <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> objektum."
  overload: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  id: Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja annak a nevét, a <xref href=&quot;System.Web.Configuration.FolderLevelBuildProvider&quot;> </xref> objektum."
  syntax:
    content: public string Name { get; set; }
    return:
      type: System.String
      description: "A build szolgáltató objektum neve."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Name*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  id: Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  id: Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  langs:
  - csharp
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja azt a build Szolgáltatóosztály teljesen minősített neve."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "A build Szolgáltatóosztály teljesen minősített neve."
  overload: System.Web.Configuration.FolderLevelBuildProvider.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor(System.String,System.String)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider(String,String)
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.FolderLevelBuildProvider(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals(System.Object)
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals(Object)
  nameWithType: FolderLevelBuildProvider.Equals(Object)
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode()
  nameWithType: FolderLevelBuildProvider.GetHashCode()
  fullName: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
  fullName: System.Web.Configuration.FolderLevelBuildProvider.Type
- uid: System.Web.Configuration.FolderLevelBuildProvider.#ctor*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: FolderLevelBuildProvider
  nameWithType: FolderLevelBuildProvider.FolderLevelBuildProvider
- uid: System.Web.Configuration.FolderLevelBuildProvider.Equals*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Equals
  nameWithType: FolderLevelBuildProvider.Equals
- uid: System.Web.Configuration.FolderLevelBuildProvider.GetHashCode*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: GetHashCode
  nameWithType: FolderLevelBuildProvider.GetHashCode
- uid: System.Web.Configuration.FolderLevelBuildProvider.Name*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Name
  nameWithType: FolderLevelBuildProvider.Name
- uid: System.Web.Configuration.FolderLevelBuildProvider.Properties*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Properties
  nameWithType: FolderLevelBuildProvider.Properties
- uid: System.Web.Configuration.FolderLevelBuildProvider.Type*
  parent: System.Web.Configuration.FolderLevelBuildProvider
  isExternal: false
  name: Type
  nameWithType: FolderLevelBuildProvider.Type
