### YamlMime:ManagedReference
items:
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  id: XmlFormatExtensionPointAttribute
  children:
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  - System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  type: Class
  summary: "XML-névtér és XML-névtérelőtag belül egy szolgáltatásleírás leírás formátum bővítmény használatához adja meg. Ez az osztály nem örökölhető."
  remarks: "A szolgáltatás leírása formátumkiterjesztésnek terjeszti ki, hogyan ASP.NET használatával létrehozott XML-webszolgáltatás létrejön egy szolgáltatás leírása. Pontosabban a szolgáltatás leírása formátumkiterjesztésnek XML-elemek hozzáadása a szolgáltatás leírása. Ez akkor hasznos, ha egy SOAP-bővítmény XML-webszolgáltatás, az ügyfél és a kiszolgáló oldalán futtatásához épül, mert SOAP-bővítményeket információ nem automatikusan történik a szolgáltatás leírása. A SOAP-bővítmény hozzáadása a szolgáltatás leírása, ha egy ügyfél így értelmezni tud, hogy az adott SOAP kiterjesztéssel kell futnia. Példa egy SOAP-bővítmény, amely az ügyfél és a kiszolgálón is futnia kell, hogy egy titkosítási SOAP bővítményt. Ha egy titkosítási SOAP bővítményt csak a kiszolgálón fut, és visszatérési értékekkel, az titkosítja a mielőtt elküldi őket az ügyfélnek, az ügyfél futtató visszafejtése a SOAP-üzenet SOAP kiterjesztéssel kell rendelkeznie. Ellenkező esetben az ügyfél nem tudja feldolgozni a visszatérési érték.       A szolgáltatás leírása formátumkiterjesztésnek létrehozásához tegye a következőket: 1.  A <xref:System.Web.Services.Description.ServiceDescriptionFormatExtension>.</xref:System.Web.Services.Description.ServiceDescriptionFormatExtension> származó osztály létrehozása      2.  Alkalmazza a <xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>az osztályhoz, és adja meg a bővítmény pontokat, ahol a szolgáltatás leírása formátumkiterjesztésnek fusson.</xref:System.Web.Services.Configuration.XmlFormatExtensionAttribute>      3.  Lehetősége van az osztály egy XmlFormatExtensionPointAttribute vonatkoznak, és jelöljön ki egy tagot az osztályon belül új bővítmény pontra járhasson el.      4.  Szükség esetén alkalmazzon egy <xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>az osztályhoz, és adja meg az XML-névtérelőtag hozzá kell rendelni a szolgáltatás leírása formátumkiterjesztésnek által létrehozott XML-elemeket.</xref:System.Web.Services.Configuration.XmlFormatExtensionPrefixAttribute>      5.  Konfigurálja a szolgáltatás leírása formátumkiterjesztésnek futtatni a `serviceDescriptionFormatExtensionTypes` a konfigurációs fájl részét."
  example:
  - >-
    [!code-cs[ServiceDescriptionFormatExtension#1](~/add/codesnippet/csharp/t-system.web.services.co_1_1.cs)]
     [!code-vb[ServiceDescriptionFormatExtension#1](~/add/codesnippet/visualbasic/t-system.web.services.co_1_1.vb)]
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class)]

      public sealed class XmlFormatExtensionPointAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  type: Constructor
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Services.Configuration.XmlFormatExtensionPointAttribute&quot;> </xref> osztály."
  syntax:
    content: public XmlFormatExtensionPointAttribute (string memberName);
    parameters:
    - id: memberName
      type: System.String
      description: "A szolgáltatás leírása formátumkiterjesztésnek, amelyeken a szolgáltatás leírása formátumkiterjesztésnek társítva megvalósító osztály tagjai."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  id: AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Lekérdezi vagy beállítja azt jelzi, hogy a szolgáltatás leírása formátumkiterjesztésnek megvalósító osztály tagjai a megadott értéket a <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>tulajdonság fogadhat nyers XML-elemeket.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>"
  syntax:
    content: public bool AllowElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a szolgáltatás leírása megvalósító osztály tagjai formázza a megadott fájlnévkiterjesztés a <xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*>tulajdonság nyers XML-elemeket fogad el; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*> Az alapértelmezett érték <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  id: MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  langs:
  - csharp
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  type: Property
  assemblies:
  - System.Web.Services
  namespace: System.Web.Services.Configuration
  summary: "Meghatározza, hogy a szolgáltatás leírása formátumkiterjesztésnek megvalósító osztály tagja lehet-e a szolgáltatás leírása formátumkiterjesztésnek társítva."
  syntax:
    content: public string MemberName { get; set; }
    return:
      type: System.String
      description: "A szolgáltatás leírása formátumkiterjesztésnek, amelyeken a szolgáltatás leírása formátumkiterjesztésnek társítva megvalósító osztály tagjai."
  overload: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor(System.String)
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute(String)
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
  fullName: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.#ctor*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: XmlFormatExtensionPointAttribute
  nameWithType: XmlFormatExtensionPointAttribute.XmlFormatExtensionPointAttribute
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.AllowElements*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: AllowElements
  nameWithType: XmlFormatExtensionPointAttribute.AllowElements
- uid: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute.MemberName*
  parent: System.Web.Services.Configuration.XmlFormatExtensionPointAttribute
  isExternal: false
  name: MemberName
  nameWithType: XmlFormatExtensionPointAttribute.MemberName
