### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.BehaviorsSection
  id: BehaviorsSection
  children:
  - System.ServiceModel.Configuration.BehaviorsSection.#ctor
  - System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
  - System.ServiceModel.Configuration.BehaviorsSection.Properties
  - System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
  langs:
  - csharp
  name: BehaviorsSection
  nameWithType: BehaviorsSection
  fullName: System.ServiceModel.Configuration.BehaviorsSection
  type: Class
  summary: "A konfigurációs szakasz gyermek bejegyzéseket, amelyek tartalmazó jelöli <xref uid=&quot;langword_csharp_behavior&quot; name=&quot;behavior&quot; href=&quot;&quot;> </xref> azonosíthatók azok egyedi elemek <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>."
  remarks: "A `behavior` elem tartalmazza-e a szolgáltatás működését a beállítások gyűjteménye. Minden egyes viselkedés indexelik a `name`. Szolgáltatások használják viselkedések történő kapcsolásával végezze el az ezzel a névvel."
  syntax:
    content: 'public class BehaviorsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BehaviorsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.BehaviorsSection
  langs:
  - csharp
  name: BehaviorsSection()
  nameWithType: BehaviorsSection.BehaviorsSection()
  fullName: System.ServiceModel.Configuration.BehaviorsSection.BehaviorsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.BehaviorsSection&quot;> </xref> osztály."
  syntax:
    content: public BehaviorsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.BehaviorsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
  id: EndpointBehaviors
  parent: System.ServiceModel.Configuration.BehaviorsSection
  langs:
  - csharp
  name: EndpointBehaviors
  nameWithType: BehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi a gyermek bejegyzéseit, amelyek azonosíthatók azok egyedi végpont viselkedés elemek <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>."
  syntax:
    content: public System.ServiceModel.Configuration.EndpointBehaviorElementCollection EndpointBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.EndpointBehaviorElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Configuration.EndpointBehaviorElementCollection&quot;> </xref> tartalmazó végpont viselkedés elemek azonosíthatók azok egyedi <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BehaviorsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.BehaviorsSection
  langs:
  - csharp
  name: Properties
  nameWithType: BehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.BehaviorsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> gyűjteményét tartalmazó példány <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> objektumok, amelyek lehetnek attribútumok vagy <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> objektumokat a konfigurációs elem."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> gyűjteményét tartalmazó példány <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> objektumok, amelyek lehetnek attribútumok vagy <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> a konfigurációs elem objektumok."
  overload: System.ServiceModel.Configuration.BehaviorsSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
  id: ServiceBehaviors
  parent: System.ServiceModel.Configuration.BehaviorsSection
  langs:
  - csharp
  name: ServiceBehaviors
  nameWithType: BehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi a gyermek bejegyzéseket, amelyek azonosíthatók azok egyedi viselkedés szolgáltatáselemek <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>."
  syntax:
    content: public System.ServiceModel.Configuration.ServiceBehaviorElementCollection ServiceBehaviors { get; }
    return:
      type: System.ServiceModel.Configuration.ServiceBehaviorElementCollection
      description: "A <xref href=&quot;System.ServiceModel.Configuration.ServiceBehaviorElementCollection&quot;> </xref> , amely tartalmazza az egyedi által azonosított viselkedés szolgáltatáselemek <xref uid=&quot;langword_csharp_name&quot; name=&quot;name&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.BehaviorsSection.#ctor
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: BehaviorsSection()
  nameWithType: BehaviorsSection.BehaviorsSection()
  fullName: System.ServiceModel.Configuration.BehaviorsSection.BehaviorsSection()
- uid: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: BehaviorsSection.EndpointBehaviors
  fullName: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.EndpointBehaviorElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: EndpointBehaviorElementCollection
  nameWithType: EndpointBehaviorElementCollection
  fullName: System.ServiceModel.Configuration.EndpointBehaviorElementCollection
- uid: System.ServiceModel.Configuration.BehaviorsSection.Properties
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: BehaviorsSection.Properties
  fullName: System.ServiceModel.Configuration.BehaviorsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: BehaviorsSection.ServiceBehaviors
  fullName: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors
- uid: System.ServiceModel.Configuration.ServiceBehaviorElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceBehaviorElementCollection
  nameWithType: ServiceBehaviorElementCollection
  fullName: System.ServiceModel.Configuration.ServiceBehaviorElementCollection
- uid: System.ServiceModel.Configuration.BehaviorsSection.#ctor*
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: BehaviorsSection
  nameWithType: BehaviorsSection.BehaviorsSection
- uid: System.ServiceModel.Configuration.BehaviorsSection.EndpointBehaviors*
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: EndpointBehaviors
  nameWithType: BehaviorsSection.EndpointBehaviors
- uid: System.ServiceModel.Configuration.BehaviorsSection.Properties*
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: Properties
  nameWithType: BehaviorsSection.Properties
- uid: System.ServiceModel.Configuration.BehaviorsSection.ServiceBehaviors*
  parent: System.ServiceModel.Configuration.BehaviorsSection
  isExternal: false
  name: ServiceBehaviors
  nameWithType: BehaviorsSection.ServiceBehaviors
