### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingProfileServiceSection
  id: ScriptingProfileServiceSection
  children:
  - System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  - System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  - System.Web.Configuration.ScriptingProfileServiceSection.Properties
  - System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  - System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  langs:
  - csharp
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection
  fullName: System.Web.Configuration.ScriptingProfileServiceSection
  type: Class
  summary: "A konfigurációs szakasz profil Szolgáltatásbeállítások jelöli. Ez az osztály nem örökölhető."
  remarks: "A ScriptingProfileServiceSection osztály lehetővé teszi programozott módon hozzáférhet, és módosíthatja a `profileService` elemet a konfigurációs szakasz az ASP.NET-alkalmazások AJAX-funkciók használatára.       A profil szolgáltatásával és a felhasználói identitás, az aktuális kéréshez hozzárendelt profil tulajdonságainak beállítása. Ez azt jelenti, hogy a profil szolgáltatás működik-e a hitelesített felhasználók számára. Azt is működik, a névtelen felhasználók számára a névtelen azonosítást funkció engedélyezve (vagy nem érhető el) esetén a konfigurációs fájlban."
  example:
  - "The following example shows how to declaratively specify values for properties of the ScriptingProfileServiceSection class in a configuration file.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <profileService enabled=\"true\"   \n        readAccessProperties=\"FirstName,LastName\"   \n        writeAccessProperties=\"FirstName,LastName\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example shows how to access the ScriptingProfileServiceSection section programmatically.  \n  \n [!code-cs[System.Web.Configuration#2](~/add/codesnippet/csharp/t-system.web.configurati_50_1.cs)]\n [!code-vb[System.Web.Configuration#2](~/add/codesnippet/visualbasic/t-system.web.configurati_50_1.vb)]"
  syntax:
    content: 'public sealed class ScriptingProfileServiceSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: ScriptingProfileServiceSection()
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.ScriptingProfileServiceSection&quot;> </xref> osztály."
  syntax:
    content: public ScriptingProfileServiceSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingProfileServiceSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  id: Enabled
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy a profil szolgáltatás az ASP.NET AJAX-kompatibilis alkalmazás érhető el."
  syntax:
    content: public bool Enabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a profil szolgáltatás engedélyezve van; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ScriptingProfileServiceSection.Enabled*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.ScriptingProfileServiceSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  id: ReadAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja az írásvédett profiltulajdonságok."
  remarks: "Ahhoz, hogy írásvédett profiltulajdonságok AJAX-kompatibilis alkalmazásokban, adja hozzá a ReadAccessProperties tulajdonság egy vagy több profil tulajdonság neve.       ReadAccessProperties állíthat be egy üres karakterlánc-tömbben. Ez azt jelenti, hogy nincs profiltulajdonságok ügyféloldali parancsprogram beolvasáshoz engedélyezettek."
  syntax:
    content: public string[] ReadAccessProperties { get; set; }
    return:
      type: System.String[]
      description: "Az írásvédett profiltulajdonságok nevét tartalmazó tömb."
  overload: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  id: WriteAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  langs:
  - csharp
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja a írási profiltulajdonságok."
  remarks: "Profiltulajdonságok írási hozzáféréssel az AJAX-kompatibilis alkalmazások használatához adja hozzá a WriteAccessProperties tulajdonság egy vagy több profil tulajdonság neve.       WriteAccessProperties állíthat be egy üres karakterlánc-tömbben. Ez azt jelenti, hogy nincs profiltulajdonságok engedélyezettek-e az ügyféloldali parancsprogram kell beállítani."
  syntax:
    content: public string[] WriteAccessProperties { get; set; }
    return:
      type: System.String[]
      description: "Az írási hozzáféréssel profiltulajdonságok nevét tartalmazó tömb."
  overload: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ScriptingProfileServiceSection()
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection()
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ScriptingProfileServiceSection()
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Enabled
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
  fullName: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.#ctor*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ScriptingProfileServiceSection
  nameWithType: ScriptingProfileServiceSection.ScriptingProfileServiceSection
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Enabled*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Enabled
  nameWithType: ScriptingProfileServiceSection.Enabled
- uid: System.Web.Configuration.ScriptingProfileServiceSection.Properties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingProfileServiceSection.Properties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.ReadAccessProperties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: ReadAccessProperties
  nameWithType: ScriptingProfileServiceSection.ReadAccessProperties
- uid: System.Web.Configuration.ScriptingProfileServiceSection.WriteAccessProperties*
  parent: System.Web.Configuration.ScriptingProfileServiceSection
  isExternal: false
  name: WriteAccessProperties
  nameWithType: ScriptingProfileServiceSection.WriteAccessProperties
