### YamlMime:ManagedReference
items:
- uid: System.Configuration.OverrideMode
  id: OverrideMode
  children:
  - System.Configuration.OverrideMode.Allow
  - System.Configuration.OverrideMode.Deny
  - System.Configuration.OverrideMode.Inherit
  langs:
  - csharp
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
  type: Enum
  summary: "Meghatározza a felülbírálás viselkedését egy konfigurációs elem konfigurációs elemek gyermek címtárakban."
  remarks: "Használja az OverrideMode enumerálási értékeket <xref:System.Configuration.SectionInformation.OverrideMode%2A> <xref:System.Configuration.SectionInformation>osztály</xref:System.Configuration.SectionInformation> tulajdonságának</xref:System.Configuration.SectionInformation.OverrideMode%2A> beállítása Ahhoz, hogy programozott módon adja meg a konfigurációs elem vagy a csoport felülbírálása viselkedését állítani ezt a tulajdonságot. A felülbírálás összes konfigurációs elemek viselkedésének egy elemen belül deklarációval beállításához használja a `allowOverride` attribútum. A <xref:System.Configuration.SectionInformation.OverrideMode%2A>tulajdonság lehetővé teszi az elemek részletesebben vezérelheti a `location` elem.</xref:System.Configuration.SectionInformation.OverrideMode%2A>"
  syntax:
    content: public enum OverrideMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Allow
  id: Allow
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "A konfigurációs beállítás, elem vagy csoport felülbírálhatja gyermek könyvtárakban található beállításokkal."
  syntax:
    content: Allow
    return:
      type: System.Configuration.OverrideMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Deny
  id: Deny
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "A konfigurációs beállítás, az elem vagy a csoport nem bírálható felül a gyermek könyvtárak beállítások."
  syntax:
    content: Deny
    return:
      type: System.Configuration.OverrideMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.OverrideMode.Inherit
  id: Inherit
  parent: System.Configuration.OverrideMode
  langs:
  - csharp
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Gyermek címtárakban, ha explicit módon engedélyezi a szülőelem, az aktuális konfigurációs elem vagy a csoport konfigurációs beállítások felülbírálják a konfigurációs beállítás, elem vagy csoport. Megadott engedély bírálja felül a <xref uid=&quot;langword_csharp_OverrideMode&quot; name=&quot;OverrideMode&quot; href=&quot;&quot;> </xref> attribútum."
  syntax:
    content: Inherit
    return:
      type: System.Configuration.OverrideMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.OverrideMode.Allow
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Allow
  nameWithType: OverrideMode.Allow
  fullName: System.Configuration.OverrideMode.Allow
- uid: System.Configuration.OverrideMode
  parent: System.Configuration
  isExternal: false
  name: OverrideMode
  nameWithType: OverrideMode
  fullName: System.Configuration.OverrideMode
- uid: System.Configuration.OverrideMode.Deny
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Deny
  nameWithType: OverrideMode.Deny
  fullName: System.Configuration.OverrideMode.Deny
- uid: System.Configuration.OverrideMode.Inherit
  parent: System.Configuration.OverrideMode
  isExternal: false
  name: Inherit
  nameWithType: OverrideMode.Inherit
  fullName: System.Configuration.OverrideMode.Inherit
