### YamlMime:ManagedReference
items:
- uid: System.Configuration.IConfigurationSectionHandler
  id: IConfigurationSectionHandler
  children:
  - System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: IConfigurationSectionHandler
  nameWithType: IConfigurationSectionHandler
  fullName: System.Configuration.IConfigurationSectionHandler
  type: Interface
  summary: "Kezeli az egyes konfigurációs szakasz elérésére."
  remarks: "**Fontos** IConfigurationSectionHandler elavult a .NET-keretrendszer 2.0 vagy újabb. De, mert belső használja, akkor lett megtartva. A példa található [hogyan: hozzon létre egyéni konfigurációs szakaszok segítségével IConfigurationSectionHandler](~/add/includes/ajax-current-ext-md.md). Ha az előző példában használ, adja összeállítani, a .NET-keretrendszer 1.0 és 1.1-es verziójában.       A .NET-keretrendszer 2.0-s verziója és az újabb, akkor inkább kell származnia: a <xref:System.Configuration.ConfigurationSection>osztály a konfigurációs szakasz kezelőjének végrehajtása.</xref:System.Configuration.ConfigurationSection> A példa található [hogyan: hozzon létre egyéni konfigurációs szakaszok segítségével ConfigurationSection](~/add/includes/ajax-current-ext-md.md).       A IConfigurationSectionHandler osztály példányai szál biztonságos és állapot nélküli kell lennie. A <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>módszer egyszerre több szálból hívható kell.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A>       Ezenkívül a konfigurációs objektum által generált a <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metódusnak kell lennie a szál biztonságos és nem módosítható.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A> A konfigurációs objektumok gyorsítótárba kerüljenek-e a konfigurációs rendszer, mert fontos nem módosíthatja a szülő argumentumának a <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>metódus.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A> Például ha a visszatérési értéke <xref:System.Configuration.IConfigurationSectionHandler.Create%2A>csak olyan kisméretű módosítás a szülő ezeket a módosításokat kell végezni a szülő nem az eredeti másolat.</xref:System.Configuration.IConfigurationSectionHandler.Create%2A>"
  syntax:
    content: public interface IConfigurationSectionHandler
  implements: []
  platform:
  - net462
- uid: System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IConfigurationSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A konfigurációs szakasz kezelőjének létrehozása."
  remarks: "Példányait a <xref:System.Configuration.IConfigurationSectionHandler>osztály szál biztonságos és állapot nélküli kell lennie.</xref:System.Configuration.IConfigurationSectionHandler> A Create metódussal egyszerre több szálból hívható kell.       Ezenkívül a konfigurációs objektum által a Create metódussal létrehozott kell szál biztonságos és nem módosítható. A konfigurációs objektumok gyorsítótárba kerüljenek-e a konfigurációs rendszer, mert nem fontos a szülő argumentum létrehozása módosítására. Például ha az eredményül kapott értéket a Create csak a szülő kis módosítását, ezeket a módosításokat kell végezni a szülő nem az eredeti másolat."
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Szülői objektumon."
    - id: configContext
      type: System.Object
      description: "Konfigurációs környezeti objektumot."
    - id: section
      type: System.Xml.XmlNode
      description: "A szakasz XML-csomópont."
    return:
      type: System.Object
      description: "A létrehozott szakasz objektum."
  overload: System.Configuration.IConfigurationSectionHandler.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IConfigurationSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.IConfigurationSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: IConfigurationSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.IConfigurationSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.IConfigurationSectionHandler.Create*
  parent: System.Configuration.IConfigurationSectionHandler
  isExternal: false
  name: Create
  nameWithType: IConfigurationSectionHandler.Create
