### YamlMime:ManagedReference
items:
- uid: System.Web.UI.ValidationSettings
  id: ValidationSettings
  children:
  - System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
  langs:
  - csharp
  name: ValidationSettings
  nameWithType: ValidationSettings
  fullName: System.Web.UI.ValidationSettings
  type: Class
  summary: "Ügyfelek ellenőrzése az alkalmazás beállításait tartalmazza."
  syntax:
    content: public static class ValidationSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
  id: UnobtrusiveValidationMode
  parent: System.Web.UI.ValidationSettings
  langs:
  - csharp
  name: UnobtrusiveValidationMode
  nameWithType: ValidationSettings.UnobtrusiveValidationMode
  fullName: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.UI
  summary: "Lekérdezi vagy beállítja az alkalmazás ügyfélmódban érvényesítése."
  syntax:
    content: public static System.Web.UI.UnobtrusiveValidationMode UnobtrusiveValidationMode { get; set; }
    return:
      type: System.Web.UI.UnobtrusiveValidationMode
      description: "Az alkalmazás ügyfél érvényesítési módját."
  overload: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
  parent: System.Web.UI.ValidationSettings
  isExternal: false
  name: UnobtrusiveValidationMode
  nameWithType: ValidationSettings.UnobtrusiveValidationMode
  fullName: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode
- uid: System.Web.UI.UnobtrusiveValidationMode
  parent: System.Web.UI
  isExternal: false
  name: UnobtrusiveValidationMode
  nameWithType: UnobtrusiveValidationMode
  fullName: System.Web.UI.UnobtrusiveValidationMode
- uid: System.Web.UI.ValidationSettings.UnobtrusiveValidationMode*
  parent: System.Web.UI.ValidationSettings
  isExternal: false
  name: UnobtrusiveValidationMode
  nameWithType: ValidationSettings.UnobtrusiveValidationMode
