### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigurationManagerInternal
  id: IConfigurationManagerInternal
  children:
  - System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  - System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  - System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  - System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  - System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  langs:
  - csharp
  name: IConfigurationManagerInternal
  nameWithType: IConfigurationManagerInternal
  fullName: System.Configuration.Internal.IConfigurationManagerInternal
  type: Interface
  summary: "Inicializálni a konfigurációs tulajdonságok a .NET-keretrendszer által használt felület meghatározása."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IConfigurationManagerInternal
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  id: ApplicationConfigUri
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a konfigurációs fájl nevét, az alkalmazás elérési útja kapcsolódik."
  syntax:
    content: public string ApplicationConfigUri { get; }
    return:
      type: System.String
      description: "A konfigurációs fájl nevét jelölő karakterlánc-érték."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  id: ExeLocalConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a helyi konfigurációs könyvtárban, az alkalmazás bejegyzés alapulnak."
  syntax:
    content: public string ExeLocalConfigDirectory { get; }
    return:
      type: System.String
      description: "Egy karakterlánc, amely a helyi konfigurációs könyvtárban."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  id: ExeLocalConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a helyi konfigurációs az alkalmazás elérési útja bejegyzés alapulnak."
  syntax:
    content: public string ExeLocalConfigPath { get; }
    return:
      type: System.String
      description: "Az alkalmazás a helyi konfigurációs elérési utat jelölő karakterláncot."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  id: ExeProductName
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekéri a termék neve, az alkalmazás bejegyzés alapulnak."
  syntax:
    content: public string ExeProductName { get; }
    return:
      type: System.String
      description: "Egy karakterláncértéket, amely a termék nevét, az alkalmazás."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  id: ExeProductVersion
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a termék alkalmazásverziónként bejegyzés alapulnak."
  syntax:
    content: public string ExeProductVersion { get; }
    return:
      type: System.String
      description: "Az alkalmazás termékverziója jelölő karakterláncot."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  id: ExeRoamingConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a bejegyzés szerelvény alapján az alkalmazás központi konfigurációs könyvtára."
  syntax:
    content: public string ExeRoamingConfigDirectory { get; }
    return:
      type: System.String
      description: "Az alkalmazás központi konfigurációs könyvtára jelölő karakterláncot."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  id: ExeRoamingConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a barangoló felhasználói konfigurációs elérési út az alkalmazás bejegyzés szerelvény alapján."
  syntax:
    content: public string ExeRoamingConfigPath { get; }
    return:
      type: System.String
      description: "A barangoló felhasználói konfigurációs elérési utat jelölő karakterláncot."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  id: MachineConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekéri a konfigurációs elérési útja a Machine.config fájlban."
  syntax:
    content: public string MachineConfigPath { get; }
    return:
      type: System.String
      description: "A Machine.config fájl elérési útját jelölő karakterláncot."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  id: SetConfigurationSystemInProgress
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "A konfigurációs rendszer állapotát jelző érték beolvasása."
  remarks: "A SetConfigurationSystemInProgress tulajdonságot használja <xref:System.Diagnostics>-konfiguráció inicializálása közben.</xref:System.Diagnostics>"
  syntax:
    content: public bool SetConfigurationSystemInProgress { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a konfigurációs rendszer inicializálása; folyamatban van Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  id: SupportsUserConfig
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi egy érték, amely megadja, hogy támogatja-e a felhasználói beállításokat."
  syntax:
    content: public bool SupportsUserConfig { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a konfigurációs rendszer támogatja a felhasználó-konfigurációs beállítások; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  id: UserConfigFilename
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  langs:
  - csharp
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Lekérdezi a felhasználó-konfigurációs beállítások tárolására használt fájl nevét."
  syntax:
    content: public string UserConfigFilename { get; }
    return:
      type: System.String
      description: "Egy nevét fogja tárolni a felhasználó-konfigurációs fájlt megadó karakterláncot."
  overload: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
  fullName: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ApplicationConfigUri*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ApplicationConfigUri
  nameWithType: IConfigurationManagerInternal.ApplicationConfigUri
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigDirectory*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeLocalConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeLocalConfigPath
  nameWithType: IConfigurationManagerInternal.ExeLocalConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductName*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductName
  nameWithType: IConfigurationManagerInternal.ExeProductName
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeProductVersion*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeProductVersion
  nameWithType: IConfigurationManagerInternal.ExeProductVersion
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigDirectory*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigDirectory
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigDirectory
- uid: System.Configuration.Internal.IConfigurationManagerInternal.ExeRoamingConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: ExeRoamingConfigPath
  nameWithType: IConfigurationManagerInternal.ExeRoamingConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.MachineConfigPath*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: MachineConfigPath
  nameWithType: IConfigurationManagerInternal.MachineConfigPath
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SetConfigurationSystemInProgress*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SetConfigurationSystemInProgress
  nameWithType: IConfigurationManagerInternal.SetConfigurationSystemInProgress
- uid: System.Configuration.Internal.IConfigurationManagerInternal.SupportsUserConfig*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: SupportsUserConfig
  nameWithType: IConfigurationManagerInternal.SupportsUserConfig
- uid: System.Configuration.Internal.IConfigurationManagerInternal.UserConfigFilename*
  parent: System.Configuration.Internal.IConfigurationManagerInternal
  isExternal: false
  name: UserConfigFilename
  nameWithType: IConfigurationManagerInternal.UserConfigFilename
