### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.TagMapInfo
  id: TagMapInfo
  children:
  - System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  - System.Web.Configuration.TagMapInfo.Equals(System.Object)
  - System.Web.Configuration.TagMapInfo.GetHashCode
  - System.Web.Configuration.TagMapInfo.MappedTagType
  - System.Web.Configuration.TagMapInfo.Properties
  - System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Web.Configuration.TagMapInfo.TagType
  langs:
  - csharp
  name: TagMapInfo
  nameWithType: TagMapInfo
  fullName: System.Web.Configuration.TagMapInfo
  type: Class
  summary: "Ismételt leképezését, utasítás egyetlen konfigurációs címkét tartalmaz. Ez az osztály nem örökölhető."
  remarks: "A TagMapInfo osztály lehetővé teszi, hogy a címkék típusú megfelelteti a fordítás során. Az újbóli hozzárendelés hatására az összes lapok és vezérlők az ASP.NET alkalmazás a konfigurációs fájl hatókörébe tartozó helyett az eredeti címke típus használandó leképezett típus.       A <xref:System.Web.Configuration.TagMapCollection>osztály lehetővé teszi a programozott hozzáférést, és módosítsa a `tagMapping` az alszakasz a `pages` szakaszt egy konfigurációs fájl.</xref:System.Web.Configuration.TagMapCollection> Belül a `tagMappings` alszakasz, adhat hozzá és címkéket típusok teljesen minősített erős név megadásával közötti hozzárendelések törlése.      > [!NOTE] > Más attribútumokat és gyűjteményeket eltérően a `pages` szakaszban nem egyező ASP.NET lap direktívájában címke meghajtószámtól rendelkezik."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for several properties of the TagMapInfo class.  \n  \n```  \n<system.web>  \n  <pages>  \n    <tagMapping>  \n      <add  \n        tagType=  \n          \"System.Web.UI.WebControls.WebParts.WebPartManager\"  \n        mappedTagType=  \n          \"Microsoft.Sharepoint.WebPartPartManager,   \n           MSPS.Web.dll, Version='2.0.0.0'\"   \n      />  \n    </tagMapping>  \n  </pages>  \n</system.web>  \n```  \n  \n The following code example shows how to use the <xref:System.Web.Configuration.TagMapCollection> class to programmatically modify tag-mapping settings. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#17](~/add/codesnippet/csharp/t-system.web.configurati_73_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#17](~/add/codesnippet/visualbasic/t-system.web.configurati_73_1.vb)]"
  syntax:
    content: 'public sealed class TagMapInfo : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: TagMapInfo(String,String)
  nameWithType: TagMapInfo.TagMapInfo(String,String)
  fullName: System.Web.Configuration.TagMapInfo.TagMapInfo(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.TagMapInfo&quot;> </xref> osztály átadott tulajdonság értékei alapján."
  remarks: ''
  example:
  - "The following code example shows how to use the TagMapInfo constructor. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[System.Web.Configuration.PagesSection#42](~/add/codesnippet/csharp/m-system.web.configurati_25_1.cs)]\n [!code-vb[System.Web.Configuration.PagesSection#42](~/add/codesnippet/visualbasic/m-system.web.configurati_25_1.vb)]"
  syntax:
    content: public TagMapInfo (string tagTypeName, string mappedTagTypeName);
    parameters:
    - id: tagTypeName
      type: System.String
      description: "A teljesen minősített nevet típusú újramegfeleltetése alatt álló címkét."
    - id: mappedTagTypeName
      type: System.String
      description: "A neve, amelyhez a címke újramegfeleltetésekor, és a támogató részletek típusú."
  overload: System.Web.Configuration.TagMapInfo.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.Equals(System.Object)
  id: Equals(System.Object)
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: Equals(Object)
  nameWithType: TagMapInfo.Equals(Object)
  fullName: System.Web.Configuration.TagMapInfo.Equals(Object)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Ez a példány egy másik objektumhoz hasonlítja össze."
  syntax:
    content: public override bool Equals (object o);
    parameters:
    - id: o
      type: System.Object
      description: "Az összehasonlítandó objektum."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az objektumok azonos; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.TagMapInfo.Equals*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.GetHashCode
  id: GetHashCode
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: GetHashCode()
  nameWithType: TagMapInfo.GetHashCode()
  fullName: System.Web.Configuration.TagMapInfo.GetHashCode()
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Az aktuális példány egy kivonatoló értékét adja vissza."
  syntax:
    content: public override int GetHashCode ();
    parameters: []
    return:
      type: System.Int32
      description: "Az aktuális példány kivonatot."
  overload: System.Web.Configuration.TagMapInfo.GetHashCode*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.MappedTagType
  id: MappedTagType
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
  fullName: System.Web.Configuration.TagMapInfo.MappedTagType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja a nevét, amelyhez a címke újramegfeleltetésekor típusú."
  remarks: "Címke meghajtószámtól, a fordítás során következik be. Az újbóli hozzárendelés hatására a (MappedTagType tulajdonság által megadott) leképezett típus használható az eredeti típusát (által a <xref:System.Web.Configuration.TagMapInfo.TagType%2A>tulajdonság) összes lapok és vezérlők az ASP.NET alkalmazás a konfigurációs fájl hatókörébe tartozó.</xref:System.Web.Configuration.TagMapInfo.TagType%2A>      > [!NOTE] > Egy üres értéket ehhez a tulajdonsághoz, mert a konfigurációs rendszer kivételt jelez, amikor az objektum szerializált."
  example:
  - "The following code example shows how to use the MappedTagType property. It is part of a larger example for the <xref:System.Web.Configuration.PagesSection> type.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string MappedTagType { get; set; }
    return:
      type: System.String
      description: "A neve, amelyhez a címke újramegfeleltetésekor típusú. Az alapértelmezett érték egy üres karakterlánc."
  overload: System.Web.Configuration.TagMapInfo.MappedTagType*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.Properties
  id: Properties
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: Properties
  nameWithType: TagMapInfo.Properties
  fullName: System.Web.Configuration.TagMapInfo.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.TagMapInfo.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  id: SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: TagMapInfo.SerializeElement(XmlWriter,Boolean)
  fullName: System.Web.Configuration.TagMapInfo.SerializeElement(XmlWriter,Boolean)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override bool SerializeElement (System.Xml.XmlWriter writer, bool serializeCollectionKey);
    parameters:
    - id: writer
      type: System.Xml.XmlWriter
      description: "Fel kell venni a párbeszédpanelre."
    - id: serializeCollectionKey
      type: System.Boolean
      description: "Fel kell venni a párbeszédpanelre."
    return:
      type: System.Boolean
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.TagMapInfo.SerializeElement*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.TagMapInfo.TagType
  id: TagType
  parent: System.Web.Configuration.TagMapInfo
  langs:
  - csharp
  name: TagType
  nameWithType: TagMapInfo.TagType
  fullName: System.Web.Configuration.TagMapInfo.TagType
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja az eredeti típus újramegfeleltetése alatt a címke neve."
  remarks: "Címke meghajtószámtól, a fordítás során következik be. Az újbóli hozzárendelés hatására a leképezett típus (által a <xref:System.Web.Configuration.TagMapInfo.MappedTagType%2A>tulajdonság) összes lapok és vezérlők az ASP.NET alkalmazás a konfigurációs fájl hatókörébe tartozó helyett az eredeti típusát (TagType tulajdonság által megadott) használt.</xref:System.Web.Configuration.TagMapInfo.MappedTagType%2A>      > [!NOTE] > Egy üres értéket ehhez a tulajdonsághoz, mert a konfigurációs rendszer kivételt jelez, amikor az objektum szerializált."
  example:
  - "The following code example shows how to use the TagType property. This code example is part of a larger example provided for the <xref:System.Web.Configuration.PagesSection> class.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]"
  syntax:
    content: public string TagType { get; set; }
    return:
      type: System.String
      description: "Az eredeti típus újramegfeleltetése alatt a címke neve."
  overload: System.Web.Configuration.TagMapInfo.TagType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.TagMapInfo.#ctor(System.String,System.String)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagMapInfo(String,String)
  nameWithType: TagMapInfo.TagMapInfo(String,String)
  fullName: System.Web.Configuration.TagMapInfo.TagMapInfo(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.TagMapInfo.Equals(System.Object)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Equals(Object)
  nameWithType: TagMapInfo.Equals(Object)
  fullName: System.Web.Configuration.TagMapInfo.Equals(Object)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Web.Configuration.TagMapInfo.GetHashCode
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: GetHashCode()
  nameWithType: TagMapInfo.GetHashCode()
  fullName: System.Web.Configuration.TagMapInfo.GetHashCode()
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.TagMapInfo.MappedTagType
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
  fullName: System.Web.Configuration.TagMapInfo.MappedTagType
- uid: System.Web.Configuration.TagMapInfo.Properties
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Properties
  nameWithType: TagMapInfo.Properties
  fullName: System.Web.Configuration.TagMapInfo.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.TagMapInfo.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: SerializeElement(XmlWriter,Boolean)
  nameWithType: TagMapInfo.SerializeElement(XmlWriter,Boolean)
  fullName: System.Web.Configuration.TagMapInfo.SerializeElement(XmlWriter,Boolean)
- uid: System.Xml.XmlWriter
  parent: System.Xml
  isExternal: true
  name: XmlWriter
  nameWithType: XmlWriter
  fullName: System.Xml.XmlWriter
- uid: System.Web.Configuration.TagMapInfo.TagType
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagType
  nameWithType: TagMapInfo.TagType
  fullName: System.Web.Configuration.TagMapInfo.TagType
- uid: System.Web.Configuration.TagMapInfo.#ctor*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagMapInfo
  nameWithType: TagMapInfo.TagMapInfo
- uid: System.Web.Configuration.TagMapInfo.Equals*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Equals
  nameWithType: TagMapInfo.Equals
- uid: System.Web.Configuration.TagMapInfo.GetHashCode*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: GetHashCode
  nameWithType: TagMapInfo.GetHashCode
- uid: System.Web.Configuration.TagMapInfo.MappedTagType*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: MappedTagType
  nameWithType: TagMapInfo.MappedTagType
- uid: System.Web.Configuration.TagMapInfo.Properties*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: Properties
  nameWithType: TagMapInfo.Properties
- uid: System.Web.Configuration.TagMapInfo.SerializeElement*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: SerializeElement
  nameWithType: TagMapInfo.SerializeElement
- uid: System.Web.Configuration.TagMapInfo.TagType*
  parent: System.Web.Configuration.TagMapInfo
  isExternal: false
  name: TagType
  nameWithType: TagMapInfo.TagType
