### YamlMime:ManagedReference
items:
- uid: System.Printing.PrintJobSettings
  id: PrintJobSettings
  children:
  - System.Printing.PrintJobSettings.CurrentPrintTicket
  - System.Printing.PrintJobSettings.Description
  langs:
  - csharp
  name: PrintJobSettings
  nameWithType: PrintJobSettings
  fullName: System.Printing.PrintJobSettings
  type: Class
  summary: "A nyomtatási feladat ismerteti."
  remarks: "A <xref:System.Printing.PrintTicket>objektum, amely az érték, a <xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A>tulajdonság, a nyomtatási feladat az összes részletes beállításait tartalmazza.</xref:System.Printing.PrintJobSettings.CurrentPrintTicket%2A> </xref:System.Printing.PrintTicket> A szülő PrintJobSettings, adhat hozzá leírást csak.      > [!CAUTION] > Belül osztályokat a <xref:System.Printing>egy Windows-szolgáltatás vagy az ASP.NET alkalmazás vagy szolgáltatás használata nem támogatott névtér.</xref:System.Printing> Váratlan problémák próbál használni ezeket az osztályokat a belül e típusok egyikét is eredményezhet, például csökken a teljesítmény- és futásidejű kivételek szolgáltatás.       Ha ki szeretné nyomtatni a Windows Forms-alkalmazás, tekintse meg a <xref:System.Drawing.Printing>névtér.</xref:System.Drawing.Printing>"
  syntax:
    content: public class PrintJobSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  id: CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Lekérdezi vagy beállítja a <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> objektum, amely tárolja a nyomtatási feladat az összes részletes beállítás."
  remarks: "A CurrentPrintTicket tulajdonság beállítása nem ellenőrzi vagy módosíthatja a megadott <xref:System.Printing.PrintTicket>egy bizonyos <xref:System.Printing.PrintQueue>.</xref:System.Printing.PrintQueue> </xref:System.Printing.PrintTicket>  Szükség esetén használja a <xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>metódussal hozzon létre egy <xref:System.Printing.PrintQueue>-adott <xref:System.Printing.PrintTicket>érvényes a megadott nyomtató.</xref:System.Printing.PrintTicket> </xref:System.Printing.PrintQueue> </xref:System.Printing.PrintQueue.MergeAndValidatePrintTicket%2A>"
  syntax:
    content: public System.Printing.PrintTicket CurrentPrintTicket { get; set; }
    return:
      type: System.Printing.PrintTicket
      description: "A <xref href=&quot;System.Printing.PrintTicket&quot;> </xref> objektum, amely tartalmazza a példányszámot nyomtatni, például a nyomtatási feladat részleteit, és hogy: tűzés vagy kétoldalas nyomtatást használja."
  overload: System.Printing.PrintJobSettings.CurrentPrintTicket*
  exceptions: []
  platform:
  - net462
- uid: System.Printing.PrintJobSettings.Description
  id: Description
  parent: System.Printing.PrintJobSettings
  langs:
  - csharp
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
  type: Property
  assemblies:
  - System.Printing
  namespace: System.Printing
  summary: "Lekérdezi vagy beállítja a nyomtatási feladatok leírása."
  syntax:
    content: public string Description { get; set; }
    return:
      type: System.String
      description: "Egy <xref:System.String>, amely leírja, hogy a nyomtatási feladatok, például &quot;negyedéves jelentés.&quot;</xref:System.String>"
  overload: System.Printing.PrintJobSettings.Description*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
  fullName: System.Printing.PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintTicket
  parent: System.Printing
  isExternal: false
  name: PrintTicket
  nameWithType: PrintTicket
  fullName: System.Printing.PrintTicket
- uid: System.Printing.PrintJobSettings.Description
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
  fullName: System.Printing.PrintJobSettings.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Printing.PrintJobSettings.CurrentPrintTicket*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: CurrentPrintTicket
  nameWithType: PrintJobSettings.CurrentPrintTicket
- uid: System.Printing.PrintJobSettings.Description*
  parent: System.Printing.PrintJobSettings
  isExternal: false
  name: Description
  nameWithType: PrintJobSettings.Description
