### YamlMime:ManagedReference
items:
- uid: System.Runtime.Hosting.ApplicationActivator
  id: ApplicationActivator
  children:
  - System.Runtime.Hosting.ApplicationActivator.#ctor
  - System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext)
  - System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext,System.String[])
  - System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(System.AppDomainSetup)
  langs:
  - csharp
  name: ApplicationActivator
  nameWithType: ApplicationActivator
  fullName: System.Runtime.Hosting.ApplicationActivator
  type: Class
  summary: "Az alaposztály biztosít szerelvények jegyzékfájl-alapú aktiválást."
  remarks: "A ApplicationActivator osztály minden kijelölt egyetlen példánya van <xref:System.AppDomain>mely összes aktiválás hívások útválasztása.</xref:System.AppDomain> A <xref:System.AppDomainManager>az aktuális <xref:System.AppDomain>erre a célra a saját egyéni ApplicationActivator biztosíthat.</xref:System.AppDomain> </xref:System.AppDomainManager> Ha egy egyéni ApplicationActivator nem áll rendelkezésre, az alapértelmezett példánya ApplicationActivator jön létre.       A következő lépések azt mutatják be az alapértelmezett viselkedése <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstance%2A>metódus megvalósításában: 1.</xref:System.Runtime.Hosting.ApplicationActivator.CreateInstance%2A>  Ellenőrzi, hogy a <xref:System.ActivationContext>a bővítmény kell aktivált megegyezik a <xref:System.ActivationContext>az aktuális tartomány; Ha nem, a 2. lépés folytatódik.</xref:System.ActivationContext> </xref:System.ActivationContext> Ellenkező esetben a szerelvény végrehajtja, és egy csomagolni eredményét adja vissza.      2.  A bővítmény a egy új <xref:System.AppDomain>.</xref:System.AppDomain> aktiválása A következő lépésekkel <xref:System.AppDomain>a használatával <xref:System.Runtime.Hosting.ActivationArguments>a bővítményt. az</xref:System.Runtime.Hosting.ActivationArguments> </xref:System.AppDomain> új inicializálása          1.  Létrehoz egy új <xref:System.AppDomainSetup>objektum használatával egy <xref:System.Runtime.Hosting.ActivationArguments>objektum, amely tartalmazza az aktiválási környezet esetében a beépülő modult.</xref:System.Runtime.Hosting.ActivationArguments> </xref:System.AppDomainSetup>          2.  Hívások a <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>módszer új tartomány létrehozása a <xref:System.AppDomainSetup>objektum.</xref:System.AppDomainSetup> </xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>          3.  A <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>metódus meghívja a <xref:System.Security.HostSecurityManager.DetermineApplicationTrust%2A?displayProperty=fullName>metódus egy <xref:System.Security.Policy.ApplicationTrust>objektum a bővítményt. az</xref:System.Security.Policy.ApplicationTrust> beszerzése</xref:System.Security.HostSecurityManager.DetermineApplicationTrust%2A?displayProperty=fullName> </xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A> Ha a <xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A>tulajdonság beolvasása `true`, a végrehajtása.</xref:System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun%2A> Ha nem, <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>jelez a <xref:System.Security.Policy.PolicyException>jelzi, hogy végrehajtási engedélyt nem zárolható.</xref:System.Security.Policy.PolicyException> </xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>          4.  Ha a megbízható futtatása, majd egy új <xref:System.AppDomain>létrehozása és beállítása a <xref:System.ActivationContext>a bővítmény és a betöltött és végrehajtani.</xref:System.ActivationContext> </xref:System.AppDomain>          5.  Az eredmény a aktiválási lett visszaadva, akkor egy csomagolni.       Egy egyéni aktiváló átalakítható bővítmény egy meghatározott körülmények között az aktiválást. Például egy egyéni aktiváló találta egy meglévő <xref:System.AppDomain>a beépülő modul helyett egy új tartományt létre minden alkalommal aktiválásához.</xref:System.AppDomain>       A következő lépések bemutatják egy egyéni ApplicationActivator bővítmény egy meglévő aktiváló viselkedését <xref:System.AppDomain>: 1.</xref:System.AppDomain>  Az egyéni aktiváló talál azonos tartományhoz <xref:System.ActivationContext>, a bővítmény, amely aktiválása folyamatban van.</xref:System.ActivationContext>      2.  Ha a <xref:System.ActivationContext>soha nem is látható volt előtt a folyamat során az egyéni aktiváló létrehoz egy új <xref:System.AppDomain>esetében ez <xref:System.ActivationContext>a <xref:System.AppDomain.CreateDomain%2A>metódus közvetlenül, vagy a tevékenység a <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A>az alap osztálynál</xref:System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper%2A> delegálása</xref:System.AppDomain.CreateDomain%2A> </xref:System.ActivationContext> </xref:System.AppDomain> </xref:System.ActivationContext>      3.  Egy meglévő tartomány azonos <xref:System.ActivationContext>, majd az aktiváló delegálhatja a <xref:System.Runtime.Hosting.ApplicationActivator.CreateInstance%2A>metódus hívásakor a céltartomány ApplicationActivator.</xref:System.Runtime.Hosting.ApplicationActivator.CreateInstance%2A> </xref:System.ActivationContext> Vegye figyelembe, hogy ez lenne egy ApplicationActivator <xref:System.AppDomain>.</xref:System.AppDomain> célja a tartományok közötti hívása"
  example:
  - "The following code example shows how to obtain an ApplicationActivator object from the current <xref:System.AppDomain.DomainManager%2A> for a manifest-based application.  \n  \n [!code-vb[System.Runtime.Hosting.ApplicationActivator#1](~/add/codesnippet/visualbasic/t-system.runtime.hosting_0_1.vb)]\n [!code-cs[System.Runtime.Hosting.ApplicationActivator#1](~/add/codesnippet/csharp/t-system.runtime.hosting_0_1.cs)]"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ApplicationActivator
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Runtime.Hosting.ApplicationActivator.#ctor
  id: '#ctor'
  parent: System.Runtime.Hosting.ApplicationActivator
  langs:
  - csharp
  name: ApplicationActivator()
  nameWithType: ApplicationActivator.ApplicationActivator()
  fullName: System.Runtime.Hosting.ApplicationActivator.ApplicationActivator()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System.Runtime.Hosting
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Runtime.Hosting.ApplicationActivator&quot;> </xref> osztály."
  syntax:
    content: public ApplicationActivator ();
    parameters: []
  overload: System.Runtime.Hosting.ApplicationActivator.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext)
  id: CreateInstance(System.ActivationContext)
  parent: System.Runtime.Hosting.ApplicationActivator
  langs:
  - csharp
  name: CreateInstance(ActivationContext)
  nameWithType: ApplicationActivator.CreateInstance(ActivationContext)
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.Hosting
  summary: "A megadott aktiválási környezet használatával hoz létre aktiválni kell, hogy az alkalmazás egy példánya."
  remarks: "Ez a módszer a jegyzékfájl-alapú aktiválási kérelmek számára készült."
  syntax:
    content: public virtual System.Runtime.Remoting.ObjectHandle CreateInstance (ActivationContext activationContext);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: "Egy <xref href=&quot;System.ActivationContext&quot;> </xref> , amely azonosítja az alkalmazás aktiválásához."
    return:
      type: System.Runtime.Remoting.ObjectHandle
      description: "Egy <xref href=&quot;System.Runtime.Remoting.ObjectHandle&quot;> </xref> az alkalmazásfuttatás visszatérési értéke, amely egy burkolót. Az eredményül kapott értéket a tényleges objektum eléréséhez burkolatlan kell lennie."
  overload: System.Runtime.Hosting.ApplicationActivator.CreateInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>activationContext</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext,System.String[])
  id: CreateInstance(System.ActivationContext,System.String[])
  parent: System.Runtime.Hosting.ApplicationActivator
  langs:
  - csharp
  name: CreateInstance(ActivationContext,String[])
  nameWithType: ApplicationActivator.CreateInstance(ActivationContext,String[])
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext,String[])
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.Hosting
  summary: "A megadott aktiválási környezet és az egyéni aktiválási adatok használatával hoz létre aktiválni kell, hogy az alkalmazás egy példánya."
  remarks: "Ez a módszer a jegyzékfájl-alapú aktiválási kérelmek számára készült. Az aktiválási adatok például a lekérdezési karakterláncra vonatkozó részében egy URL-cím áll."
  syntax:
    content: public virtual System.Runtime.Remoting.ObjectHandle CreateInstance (ActivationContext activationContext, string[] activationCustomData);
    parameters:
    - id: activationContext
      type: System.ActivationContext
      description: "Egy <xref href=&quot;System.ActivationContext&quot;> </xref> , amely azonosítja az alkalmazás aktiválásához."
    - id: activationCustomData
      type: System.String[]
      description: "Egyéni aktiválási adatokhoz."
    return:
      type: System.Runtime.Remoting.ObjectHandle
      description: "Egy <xref href=&quot;System.Runtime.Remoting.ObjectHandle&quot;> </xref> az alkalmazásfuttatás visszatérési értéke, amely egy burkolót. Az eredményül kapott értéket a tényleges objektum eléréséhez burkolatlan kell lennie."
  overload: System.Runtime.Hosting.ApplicationActivator.CreateInstance*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>activationContext</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(System.AppDomainSetup)
  id: CreateInstanceHelper(System.AppDomainSetup)
  parent: System.Runtime.Hosting.ApplicationActivator
  langs:
  - csharp
  name: CreateInstanceHelper(AppDomainSetup)
  nameWithType: ApplicationActivator.CreateInstanceHelper(AppDomainSetup)
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(AppDomainSetup)
  type: Method
  assemblies:
  - mscorlib
  namespace: System.Runtime.Hosting
  summary: "A megadott használó alkalmazások az példányát <xref href=&quot;System.AppDomainSetup&quot;> </xref> objektum."
  remarks: "Ez a módszer a jegyzékfájl-alapú aktiválási kérelmek számára készült."
  syntax:
    content: protected static System.Runtime.Remoting.ObjectHandle CreateInstanceHelper (AppDomainSetup adSetup);
    parameters:
    - id: adSetup
      type: System.AppDomainSetup
      description: "Egy <xref href=&quot;System.AppDomainSetup&quot;> </xref> objektum, amelynek <xref:System.AppDomainSetup.ActivationArguments*>tulajdonság azonosítja az alkalmazás aktiválásához.</xref:System.AppDomainSetup.ActivationArguments*>"
    return:
      type: System.Runtime.Remoting.ObjectHandle
      description: "Egy <xref href=&quot;System.Runtime.Remoting.ObjectHandle&quot;> </xref> az alkalmazásfuttatás visszatérési értéke, amely egy burkolót. Az eredményül kapott értéket a tényleges objektum eléréséhez burkolatlan kell lennie."
  overload: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper*
  exceptions:
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "The <xref:System.AppDomainSetup.ActivationArguments*> property of <code>adSetup </code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>.</xref:System.AppDomainSetup.ActivationArguments*>"
  - type: System.Security.Policy.PolicyException
    commentId: T:System.Security.Policy.PolicyException
    description: "Az alkalmazáspéldány végrehajtása sikertelen, mert a házirend-beállításokat, a jelenlegi alkalmazás tartományban nem ad meg az alkalmazás futtatásához engedély."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.Security.Policy.PolicyException
  parent: System.Security.Policy
  isExternal: false
  name: PolicyException
  nameWithType: PolicyException
  fullName: System.Security.Policy.PolicyException
- uid: System.Runtime.Hosting.ApplicationActivator.#ctor
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: ApplicationActivator()
  nameWithType: ApplicationActivator.ApplicationActivator()
  fullName: System.Runtime.Hosting.ApplicationActivator.ApplicationActivator()
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext)
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstance(ActivationContext)
  nameWithType: ApplicationActivator.CreateInstance(ActivationContext)
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext)
- uid: System.Runtime.Remoting.ObjectHandle
  parent: System.Runtime.Remoting
  isExternal: false
  name: ObjectHandle
  nameWithType: ObjectHandle
  fullName: System.Runtime.Remoting.ObjectHandle
- uid: System.ActivationContext
  parent: System
  isExternal: false
  name: ActivationContext
  nameWithType: ActivationContext
  fullName: System.ActivationContext
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance(System.ActivationContext,System.String[])
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstance(ActivationContext,String[])
  nameWithType: ApplicationActivator.CreateInstance(ActivationContext,String[])
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstance(ActivationContext,String[])
- uid: System.String[]
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String[]
  spec.csharp:
  - uid: System.String
    name: String
    nameWithType: String
    fullName: String[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(System.AppDomainSetup)
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstanceHelper(AppDomainSetup)
  nameWithType: ApplicationActivator.CreateInstanceHelper(AppDomainSetup)
  fullName: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(AppDomainSetup)
- uid: System.AppDomainSetup
  parent: System
  isExternal: false
  name: AppDomainSetup
  nameWithType: AppDomainSetup
  fullName: System.AppDomainSetup
- uid: System.Runtime.Hosting.ApplicationActivator.#ctor*
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: ApplicationActivator
  nameWithType: ApplicationActivator.ApplicationActivator
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstance*
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstance
  nameWithType: ApplicationActivator.CreateInstance
- uid: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper*
  parent: System.Runtime.Hosting.ApplicationActivator
  isExternal: false
  name: CreateInstanceHelper
  nameWithType: ApplicationActivator.CreateInstanceHelper
