### YamlMime:ManagedReference
items:
- uid: System.Configuration.Internal.IConfigurationManagerHelper
  id: IConfigurationManagerHelper
  children:
  - System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  langs:
  - csharp
  name: IConfigurationManagerHelper
  nameWithType: IConfigurationManagerHelper
  fullName: System.Configuration.Internal.IConfigurationManagerHelper
  type: Interface
  summary: "A .NET-keretrendszer konfigurációs Felügyelet támogatásához használt felület meghatározása."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public interface IConfigurationManagerHelper
  implements: []
  platform:
  - net462
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  id: EnsureNetConfigLoaded
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  langs:
  - csharp
  name: EnsureNetConfigLoaded()
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded()
  fullName: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Internal
  summary: "Biztosítja, hogy a hálózati konfiguráció van betöltve."
  remarks: "Ez a módszer annak megelőzésére szolgál a hálózati osztályok holtpont biztosításával, hogy olyan hálózati beállításokat be van töltve, mielőtt a hálózati kérések."
  syntax:
    content: public void EnsureNetConfigLoaded ();
    parameters: []
  overload: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  isExternal: false
  name: EnsureNetConfigLoaded()
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded()
  fullName: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded()
- uid: System.Configuration.Internal.IConfigurationManagerHelper.EnsureNetConfigLoaded*
  parent: System.Configuration.Internal.IConfigurationManagerHelper
  isExternal: false
  name: EnsureNetConfigLoaded
  nameWithType: IConfigurationManagerHelper.EnsureNetConfigLoaded
