### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.SupportedRuntimeMissingException
  id: SupportedRuntimeMissingException
  children:
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  - System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  langs:
  - csharp
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException
  fullName: System.Deployment.Application.SupportedRuntimeMissingException
  type: Class
  summary: "A kivétel történt, amikor az alkalmazás kompatibilis futásidejű verziót nem található."
  syntax:
    content: 'public class SupportedRuntimeMissingException : System.Deployment.Application.DependentPlatformMissingException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  - System.Deployment.Application.DependentPlatformMissingException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DependentPlatformMissingException.SupportUrl
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> osztály rendszer által megadott üzenetet, amely leírja a hibát."
  remarks: "Ez a konstruktor inicializálja a <xref:System.Exception.Message%2A>tulajdonság az új példány egy rendszer által megadott üzenetet, amely leírja, hogy a hiba, például a &quot;Futásidejű hiányzó kivételt.&quot;</xref:System.Exception.Message%2A> Ez az üzenet figyelembe veszi a rendszer jelenlegi kulturális környezethez.       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A honosított hibakarakterlánc üzenet. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException ();
    parameters: []
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> osztály egy adott üzenet, amely leírja a hibát."
  remarks: "Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A hiba üzenet mezőben megadott karakterlánc `message`. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> a szerializált adatok osztályt."
  remarks: "Ez a konstruktor nevezik meglévő kölcsönökre az adatfolyam továbbított kivétel objektum deszerializálása közben."
  syntax:
    content: protected SupportedRuntimeMissingException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> megadott hibaüzenet, és hivatkozni kell a belső kivételben találhatók okozza-e ezt a kivételt, a osztályt."
  remarks: "Kivételt vált ki, mert egy előző kivétel közvetlen eredménye tartalmaznia kell egy hivatkozást az előző kivétel az a <xref:System.Exception.InnerException%2A>tulajdonság.</xref:System.Exception.InnerException%2A> A <xref:System.Exception.InnerException%2A>tulajdonság a konstruktornak átadott ugyanazt az értéket adja vissza vagy `null` Ha a <xref:System.Exception.InnerException%2A>tulajdonság nem adja meg a belső kivétel értékét a konstruktor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       Az alábbi táblázat a kezdeti tulajdonságértékek <xref:System.Deployment.Application.SupportedRuntimeMissingException>.</xref:System.Deployment.Application.SupportedRuntimeMissingException> példánya      | Tulajdonság |} Érték |}   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| A hiba üzenet mezőben megadott karakterlánc `message`. |}</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public SupportedRuntimeMissingException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel az következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  type: Method
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.SupportedRuntimeMissingException&quot;> </xref> a szerializált adatok osztályt."
  remarks: "Ez a konstruktor nevezik meglévő kölcsönökre az adatfolyam továbbított kivétel objektum deszerializálása közben."
  syntax:
    content: public override void GetObjectData (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  id: SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  langs:
  - csharp
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a futtatókörnyezet, ahol telepítheti és futtathatja az alkalmazás verziója."
  syntax:
    content: public string SupportedRuntimeVersion { get; }
    return:
      type: System.String
      description: "A futásidejű verziószámot tartalmazó karakterlánc."
  overload: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DependentPlatformMissingException
  isExternal: false
  name: System.Deployment.Application.DependentPlatformMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException()
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException()
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException()
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException(String,Exception)
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeMissingException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData(SerializationInfo,StreamingContext)
  nameWithType: SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData(SerializationInfo,StreamingContext)
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
  fullName: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion
- uid: System.Deployment.Application.SupportedRuntimeMissingException.#ctor*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeMissingException
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeMissingException
- uid: System.Deployment.Application.SupportedRuntimeMissingException.GetObjectData*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: GetObjectData
  nameWithType: SupportedRuntimeMissingException.GetObjectData
- uid: System.Deployment.Application.SupportedRuntimeMissingException.SupportedRuntimeVersion*
  parent: System.Deployment.Application.SupportedRuntimeMissingException
  isExternal: false
  name: SupportedRuntimeVersion
  nameWithType: SupportedRuntimeMissingException.SupportedRuntimeVersion
