### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.WSHttpSecurity
  id: WSHttpSecurity
  children:
  - System.ServiceModel.WSHttpSecurity.#ctor
  - System.ServiceModel.WSHttpSecurity.Message
  - System.ServiceModel.WSHttpSecurity.Mode
  - System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage
  - System.ServiceModel.WSHttpSecurity.ShouldSerializeMode
  - System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport
  - System.ServiceModel.WSHttpSecurity.Transport
  langs:
  - csharp
  name: WSHttpSecurity
  nameWithType: WSHttpSecurity
  fullName: System.ServiceModel.WSHttpSecurity
  type: Class
  summary: "A biztonsági beállításokat adja meg a <xref href=&quot;System.ServiceModel.WSHttpBinding&quot;> </xref>."
  remarks: "A <xref:System.ServiceModel.WSHttpBinding>osztály, amely implementálja a WS - szolgáltatásokkal való együttműködés készült * specifikációk.</xref:System.ServiceModel.WSHttpBinding> A kötéshez a transport biztonsági Secure Sockets Layer (SSL) HTTP vagy HTTPS."
  syntax:
    content: public sealed class WSHttpSecurity
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.#ctor
  id: '#ctor'
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: WSHttpSecurity()
  nameWithType: WSHttpSecurity.WSHttpSecurity()
  fullName: System.ServiceModel.WSHttpSecurity.WSHttpSecurity()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.WSHttpSecurity&quot;> </xref> osztály."
  syntax:
    content: public WSHttpSecurity ();
    parameters: []
  overload: System.ServiceModel.WSHttpSecurity.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.Message
  id: Message
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: Message
  nameWithType: WSHttpSecurity.Message
  fullName: System.ServiceModel.WSHttpSecurity.Message
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Lekérdezi a kötés üzenet szintű biztonsági beállításait."
  remarks: ''
  example:
  - "The following code illustrates use of this property.  \n  \n [!code-cs[c_CreateSecureSession#4](~/add/codesnippet/csharp/p-system.servicemodel.ws_20_1.cs)]"
  syntax:
    content: public System.ServiceModel.NonDualMessageSecurityOverHttp Message { get; set; }
    return:
      type: System.ServiceModel.NonDualMessageSecurityOverHttp
      description: "A <xref href=&quot;System.ServiceModel.NonDualMessageSecurityOverHttp&quot;> </xref> példány.       The default value includes: <>*> with default set to <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>, <>*> is <xref:System.ServiceModel.MessageCredentialType>, <>*> is <>*>, and <xref:System.ServiceModel.MessageSecurityOverHttp.NegotiateServiceCredential*> is <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>.</xref:System.ServiceModel.MessageSecurityOverHttp.NegotiateServiceCredential*></xref:System.ServiceModel.MessageCredentialType>"
  overload: System.ServiceModel.WSHttpSecurity.Message*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.Mode
  id: Mode
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: Mode
  nameWithType: WSHttpSecurity.Mode
  fullName: System.ServiceModel.WSHttpSecurity.Mode
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Megadja az üzenetet <xref:System.ServiceModel.SecurityMode>Ehhez a kötéshez.</xref:System.ServiceModel.SecurityMode>"
  remarks: "Ez a tulajdonság határozza meg, hogy a beállítások a <xref:System.ServiceModel.WSHttpSecurity.Transport%2A>és/vagy <xref:System.ServiceModel.WSHttpSecurity.Message%2A>tulajdonság gyűjtők is, vagy előfordulhat, hogy nem érvénybe.</xref:System.ServiceModel.WSHttpSecurity.Message%2A> </xref:System.ServiceModel.WSHttpSecurity.Transport%2A>"
  example:
  - "The following code sets this property.  \n  \n [!code-cs[c_CreateSecureSession#3](~/add/codesnippet/csharp/p-system.servicemodel.ws_11_1.cs)]"
  syntax:
    content: public System.ServiceModel.SecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.SecurityMode
      description: "A <xref:System.ServiceModel.SecurityMode>Ehhez a kötéshez.</xref:System.ServiceModel.SecurityMode> Az alapértelmezett érték <xref:System.ServiceModel.SecurityMode>.</xref:System.ServiceModel.SecurityMode>"
  overload: System.ServiceModel.WSHttpSecurity.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "A mód beállítása értéke nincs definiálva."
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage
  id: ShouldSerializeMessage
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMessage()
  nameWithType: WSHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Visszaadja egy érték, amely azt jelzi, hogy a <xref:System.ServiceModel.WSHttpSecurity.Message*>tulajdonság alapértelmezett értéke megváltozott, és kell szerializálni.</xref:System.ServiceModel.WSHttpSecurity.Message*> Ezt használja a [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] az XAML-integráció."
  syntax:
    content: public bool ShouldSerializeMessage ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a <xref:System.ServiceModel.WSHttpSecurity.Message*>tulajdonság értéke kell lennie, mivel a szerializált; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSHttpSecurity.Message*>"
  overload: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode
  id: ShouldSerializeMode
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeMode()
  nameWithType: WSHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Visszaadja egy érték, amely azt jelzi, hogy a <xref:System.ServiceModel.WSHttpSecurity.Mode*>tulajdonság alapértelmezett értéke megváltozott, és kell szerializálni.</xref:System.ServiceModel.WSHttpSecurity.Mode*> Ezt használja a [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] az XAML-integráció."
  syntax:
    content: public bool ShouldSerializeMode ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a <xref:System.ServiceModel.WSHttpSecurity.Mode*>tulajdonság értéke kell lennie, mivel a szerializált; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSHttpSecurity.Mode*>"
  overload: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport
  id: ShouldSerializeTransport
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: ShouldSerializeTransport()
  nameWithType: WSHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "Visszaadja egy érték, amely azt jelzi, hogy a <xref:System.ServiceModel.WSHttpSecurity.Transport*>tulajdonság alapértelmezett értéke megváltozott, és kell szerializálni.</xref:System.ServiceModel.WSHttpSecurity.Transport*>"
  syntax:
    content: public bool ShouldSerializeTransport ();
    parameters: []
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a <xref:System.ServiceModel.WSHttpSecurity.Transport*>tulajdonság értéke kell lennie, mivel a szerializált; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>.</xref:System.ServiceModel.WSHttpSecurity.Transport*>"
  overload: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.WSHttpSecurity.Transport
  id: Transport
  parent: System.ServiceModel.WSHttpSecurity
  langs:
  - csharp
  name: Transport
  nameWithType: WSHttpSecurity.Transport
  fullName: System.ServiceModel.WSHttpSecurity.Transport
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel
  summary: "A kötés átviteli szintű biztonsági beállításait tartalmazó objektum beolvasása."
  remarks: "Ez a tulajdonság által visszaadott objektum segítségével az átvitel a kötés biztonsági beállításainak megadása."
  example:
  - "The following code sets the client credential type to Windows.  \n  \n```c#  \n// The code uses a shortcut to specify the security mode to Transport.  \nWSHttpBinding b = new WSHttpBinding(SecurityMode.Transport);  \nb.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows;  \n```  \n  \n```vb#  \n' The code uses a shortcut to specify the security mode to Transport.  \nDim b As WSHttpBinding = new WSHttpBinding(SecurityMode.Transport)  \nb.Security.Transport.ClientCredentialType = HttpClientCredentialType.Windows  \n```"
  syntax:
    content: public System.ServiceModel.HttpTransportSecurity Transport { get; set; }
    return:
      type: System.ServiceModel.HttpTransportSecurity
      description: "A <xref:System.ServiceModel.HttpTransportSecurity>Ehhez a kötéshez.</xref:System.ServiceModel.HttpTransportSecurity>       Az alapértelmezett érték tartalmaz egy <> </> *> a <xref:System.ServiceModel.HttpClientCredentialType>és egy <> </> *> a <xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;> </xref>.</xref:System.ServiceModel.HttpClientCredentialType>"
  overload: System.ServiceModel.WSHttpSecurity.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.WSHttpSecurity.#ctor
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: WSHttpSecurity()
  nameWithType: WSHttpSecurity.WSHttpSecurity()
  fullName: System.ServiceModel.WSHttpSecurity.WSHttpSecurity()
- uid: System.ServiceModel.WSHttpSecurity.Message
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSHttpSecurity.Message
  fullName: System.ServiceModel.WSHttpSecurity.Message
- uid: System.ServiceModel.NonDualMessageSecurityOverHttp
  parent: System.ServiceModel
  isExternal: false
  name: NonDualMessageSecurityOverHttp
  nameWithType: NonDualMessageSecurityOverHttp
  fullName: System.ServiceModel.NonDualMessageSecurityOverHttp
- uid: System.ServiceModel.WSHttpSecurity.Mode
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSHttpSecurity.Mode
  fullName: System.ServiceModel.WSHttpSecurity.Mode
- uid: System.ServiceModel.SecurityMode
  parent: System.ServiceModel
  isExternal: true
  name: SecurityMode
  nameWithType: SecurityMode
  fullName: System.ServiceModel.SecurityMode
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage()
  nameWithType: WSHttpSecurity.ShouldSerializeMessage()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage()
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeMode()
  nameWithType: WSHttpSecurity.ShouldSerializeMode()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode()
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport()
  nameWithType: WSHttpSecurity.ShouldSerializeTransport()
  fullName: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport()
- uid: System.ServiceModel.WSHttpSecurity.Transport
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: WSHttpSecurity.Transport
  fullName: System.ServiceModel.WSHttpSecurity.Transport
- uid: System.ServiceModel.HttpTransportSecurity
  parent: System.ServiceModel
  isExternal: true
  name: HttpTransportSecurity
  nameWithType: HttpTransportSecurity
  fullName: System.ServiceModel.HttpTransportSecurity
- uid: System.ServiceModel.WSHttpSecurity.#ctor*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: WSHttpSecurity
  nameWithType: WSHttpSecurity.WSHttpSecurity
- uid: System.ServiceModel.WSHttpSecurity.Message*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Message
  nameWithType: WSHttpSecurity.Message
- uid: System.ServiceModel.WSHttpSecurity.Mode*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Mode
  nameWithType: WSHttpSecurity.Mode
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMessage*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeMessage
  nameWithType: WSHttpSecurity.ShouldSerializeMessage
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeMode*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeMode
  nameWithType: WSHttpSecurity.ShouldSerializeMode
- uid: System.ServiceModel.WSHttpSecurity.ShouldSerializeTransport*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: ShouldSerializeTransport
  nameWithType: WSHttpSecurity.ShouldSerializeTransport
- uid: System.ServiceModel.WSHttpSecurity.Transport*
  parent: System.ServiceModel.WSHttpSecurity
  isExternal: false
  name: Transport
  nameWithType: WSHttpSecurity.Transport
