### YamlMime:ManagedReference
items:
- uid: System.Drawing.Configuration.SystemDrawingSection
  id: SystemDrawingSection
  children:
  - System.Drawing.Configuration.SystemDrawingSection.#ctor
  - System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
  - System.Drawing.Configuration.SystemDrawingSection.Properties
  langs:
  - csharp
  name: SystemDrawingSection
  nameWithType: SystemDrawingSection
  fullName: System.Drawing.Configuration.SystemDrawingSection
  type: Class
  summary: "A konfigurációs szakasz található osztályok által használt jelöli a <xref href=&quot;System.Drawing&quot;> </xref> névtér."
  syntax:
    content: 'public sealed class SystemDrawingSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Drawing.Configuration.SystemDrawingSection.#ctor
  id: '#ctor'
  parent: System.Drawing.Configuration.SystemDrawingSection
  langs:
  - csharp
  name: SystemDrawingSection()
  nameWithType: SystemDrawingSection.SystemDrawingSection()
  fullName: System.Drawing.Configuration.SystemDrawingSection.SystemDrawingSection()
  type: Constructor
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Drawing.Configuration.SystemDrawingSection&quot;> </xref> osztály."
  syntax:
    content: public SystemDrawingSection ();
    parameters: []
  overload: System.Drawing.Configuration.SystemDrawingSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
  id: BitmapSuffix
  parent: System.Drawing.Configuration.SystemDrawingSection
  langs:
  - csharp
  name: BitmapSuffix
  nameWithType: SystemDrawingSection.BitmapSuffix
  fullName: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
  type: Property
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Configuration
  summary: "Lekérdezi vagy beállítja a jelző utótaghoz, így a fájl nevét jelzi hozzáfűzése egy <xref href=&quot;System.Drawing.ToolboxBitmapAttribute&quot;> </xref> amikor egy szerelvény deklaráltak egy <xref href=&quot;System.Drawing.BitmapSuffixInSameAssemblyAttribute&quot;> </xref> vagy egy <xref href=&quot;System.Drawing.BitmapSuffixInSatelliteAssemblyAttribute&quot;> </xref>."
  remarks: "A bitkép utótagot fűz hozzá a előtt a kiterjesztést a fájlnév. Például az bitkép előtagja pedig &quot;. test.1.0&quot;, egy <xref:System.Drawing.ToolboxBitmapAttribute>&quot;my.bmp&quot; hivatkozás &quot;my.test.1.0.bmp&quot; kerül értelmezésre.</xref:System.Drawing.ToolboxBitmapAttribute>"
  syntax:
    content: public string BitmapSuffix { get; set; }
    return:
      type: System.String
      description: "A bitkép utótag."
  overload: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix*
  exceptions: []
  platform:
  - net462
- uid: System.Drawing.Configuration.SystemDrawingSection.Properties
  id: Properties
  parent: System.Drawing.Configuration.SystemDrawingSection
  langs:
  - csharp
  name: Properties
  nameWithType: SystemDrawingSection.Properties
  fullName: System.Drawing.Configuration.SystemDrawingSection.Properties
  type: Property
  assemblies:
  - System.Drawing
  namespace: System.Drawing.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Drawing.Configuration.SystemDrawingSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Drawing.Configuration.SystemDrawingSection.#ctor
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: SystemDrawingSection()
  nameWithType: SystemDrawingSection.SystemDrawingSection()
  fullName: System.Drawing.Configuration.SystemDrawingSection.SystemDrawingSection()
- uid: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: BitmapSuffix
  nameWithType: SystemDrawingSection.BitmapSuffix
  fullName: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Drawing.Configuration.SystemDrawingSection.Properties
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: Properties
  nameWithType: SystemDrawingSection.Properties
  fullName: System.Drawing.Configuration.SystemDrawingSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Drawing.Configuration.SystemDrawingSection.#ctor*
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: SystemDrawingSection
  nameWithType: SystemDrawingSection.SystemDrawingSection
- uid: System.Drawing.Configuration.SystemDrawingSection.BitmapSuffix*
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: BitmapSuffix
  nameWithType: SystemDrawingSection.BitmapSuffix
- uid: System.Drawing.Configuration.SystemDrawingSection.Properties*
  parent: System.Drawing.Configuration.SystemDrawingSection
  isExternal: false
  name: Properties
  nameWithType: SystemDrawingSection.Properties
