### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.SystemWebCachingSectionGroup
  id: SystemWebCachingSectionGroup
  children:
  - System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  - System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  - System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  - System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  - System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  langs:
  - csharp
  name: SystemWebCachingSectionGroup
  nameWithType: SystemWebCachingSectionGroup
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup
  type: Class
  summary: "Konfigurálja a <xref uid=&quot;langword_csharp_caching&quot; name=&quot;caching&quot; href=&quot;&quot;> </xref> csoport konfigurációs fájlban. Ez az osztály nem örökölhető."
  remarks: "A SystemWebCachingSectionGroup osztály programozott módon hozzáférhet, és módosíthatja lehetőséget biztosít a `caching` egy konfigurációs fájl részét.       A SystemWebCachingSectionGroup osztály és a `caching` szakaszban adja meg a webhely vagy alkalmazás gyorsítótárazása központosított felügyeletet. Ez lehetővé teszi a gyorsítótárazáshoz telepíteni, módosítani és le van tiltva az alkalmazás egyes oldalán módosítása nélkül.       Az ASP.NET gyorsítótárazást megvalósítja az <xref:System.Web.Caching.Cache>osztályhoz.</xref:System.Web.Caching.Cache> További információkért lásd: [ASP.NET gyorsítótárazás áttekintése](~/add/includes/ajax-current-ext-md.md) az alábbi lista ismerteti a két típus ASP.NET gyorsítótárazásának biztosít.      -Az első nevezik kimeneti gyorsítótár, amely lehetővé teszi a dinamikus lap és felhasználói vezérlő válaszok tárolásához. További kérések nem hajtotta végre a lap, vagy a felhasználói kód; a gyorsítótárazott kimenetét a kérés teljesítéséhez használja. Kimeneti gyorsítótár beállításainak használatával végezheti el a <xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache%2A>és <xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings%2A>Tulajdonságok.</xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings%2A> </xref:System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache%2A>      – Gyorsítótár a második típusú olyan gyorsítótárazáshoz, olyan hagyományos alkalmazás adat, amely segítségével programozott módon server memóriába tetszőleges objektumok tárolására, így az alkalmazás menteni tudja a időt és hozza létre őket szükséges erőforrásokat. Ezeket a beállításokat a gyorsítótár végezheti el a <xref:System.Web.Configuration.SystemWebCachingSectionGroup.Cache%2A>tulajdonság.</xref:System.Web.Configuration.SystemWebCachingSectionGroup.Cache%2A>"
  example:
  - "The following code example shows how to obtain the SystemWebCachingSectionGroup object from the configuration file associated with an existing Web application. You can use this object to access the sections contained in the `caching` group.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#1](~/add/codesnippet/csharp/t-system.web.configurati_82_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#1](~/add/codesnippet/visualbasic/t-system.web.configurati_82_1.vb)]"
  syntax:
    content: 'public sealed class SystemWebCachingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: SystemWebCachingSectionGroup()
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Létrehoz egy új példányát <xref href=&quot;System.Web.Configuration.SystemWebCachingSectionGroup&quot;> </xref>."
  remarks: "A SystemWebCachingSectionGroup konstruktor nem célja, hogy közvetlenül a kódból használni. Az ASP.NET konfigurációs rendszer nevezik. Példányának beszerezte a <xref:System.Web.Configuration.SystemWebCachingSectionGroup>osztály használatával a <xref:System.Configuration.Configuration.GetSection%2A>metódus.</xref:System.Configuration.Configuration.GetSection%2A> </xref:System.Web.Configuration.SystemWebCachingSectionGroup>"
  syntax:
    content: public SystemWebCachingSectionGroup ();
    parameters: []
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  id: Cache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a <xref uid=&quot;langword_csharp_cache&quot; name=&quot;cache&quot; href=&quot;&quot;> </xref> található a konfigurációs szakasz."
  remarks: "A <xref:System.Web.Configuration.CacheSection>objektum hivatkozik a `cache` a konfigurációs fájl részét.</xref:System.Web.Configuration.CacheSection> Használhatja a <xref:System.Web.Configuration.CacheSection>osztály módosítása a `cache` szakasz programozott.</xref:System.Web.Configuration.CacheSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.CacheSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#2](~/add/codesnippet/csharp/p-system.web.configurati_388_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#2](~/add/codesnippet/visualbasic/p-system.web.configurati_388_1.vb)]"
  syntax:
    content: public System.Web.Configuration.CacheSection Cache { get; }
    return:
      type: System.Web.Configuration.CacheSection
      description: "A <xref href=&quot;System.Web.Configuration.CacheSection&quot;> </xref> objektum."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.Cache*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  id: OutputCache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a <xref uid=&quot;langword_csharp_outputCache&quot; name=&quot;outputCache&quot; href=&quot;&quot;> </xref> található a konfigurációs szakasz."
  remarks: "A <xref:System.Web.Configuration.OutputCacheSection>objektum hivatkozik a `outputCache` a konfigurációs fájl részét.</xref:System.Web.Configuration.OutputCacheSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.OutputCacheSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#3](~/add/codesnippet/csharp/p-system.web.configurati_104_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#3](~/add/codesnippet/visualbasic/p-system.web.configurati_104_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheSection OutputCache { get; }
    return:
      type: System.Web.Configuration.OutputCacheSection
      description: "A <xref href=&quot;System.Web.Configuration.OutputCacheSection&quot;> </xref> objektum."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  id: OutputCacheSettings
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a <xref uid=&quot;langword_csharp_outputCacheSettings&quot; name=&quot;outputCacheSettings&quot; href=&quot;&quot;> </xref> található a konfigurációs szakasz."
  remarks: "A <xref:System.Web.Configuration.OutputCacheSettingsSection>objektum hivatkozik a `outputCacheSettings` a konfigurációs fájl részét.</xref:System.Web.Configuration.OutputCacheSettingsSection>       A kimeneti gyorsítótár beállításainak engedélyezése vagy lemezes állandó kimeneti gyorsítótár letiltani, adja meg a helyét a gyorsítótárazható adatok megőrzése és alkalmazásonként a gyorsítótár maximális méretének megadása.       ASP.NET lehetővé teszi egy lap válasza több verzióinak gyorsítótárazása deklaratív módon az irányelv attribútumok használatával, és programozott módon, a tulajdonságai és metódusai <xref:System.Web.HttpCachePolicy>osztályhoz.</xref:System.Web.HttpCachePolicy>       Úgy konfigurálja, az alkalmazás használatával ugyanaz az eredmény érhető el a <xref:System.Web.Configuration.OutputCacheSettingsSection>vagy a <xref:System.Web.Configuration.OutputCacheProfile>típusa.</xref:System.Web.Configuration.OutputCacheProfile> </xref:System.Web.Configuration.OutputCacheSettingsSection>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.OutputCacheSettingsSection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#4](~/add/codesnippet/csharp/p-system.web.configurati_173_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#4](~/add/codesnippet/visualbasic/p-system.web.configurati_173_1.vb)]"
  syntax:
    content: public System.Web.Configuration.OutputCacheSettingsSection OutputCacheSettings { get; }
    return:
      type: System.Web.Configuration.OutputCacheSettingsSection
      description: "A <xref href=&quot;System.Web.Configuration.OutputCacheSettingsSection&quot;> </xref> objektum."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  id: SqlCacheDependency
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  langs:
  - csharp
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a <xref uid=&quot;langword_csharp_sqlCacheDependency&quot; name=&quot;sqlCacheDependency&quot; href=&quot;&quot;> </xref> található a konfigurációs szakasz."
  remarks: "A <xref:System.Web.Configuration.SqlCacheDependencySection>objektum hivatkozik a `sqlCacheDependency` a konfigurációs fájl részét.</xref:System.Web.Configuration.SqlCacheDependencySection>       Az SQL gyorsítótár-függőségének kapcsolatot hoz létre egy ASP.NET-alkalmazás gyorsítótárába, SQL Server adatbázis bizonyos táblájához tárolt elem között. Egy példányát a <xref:System.Web.Caching.SqlCacheDependency>osztály kell figyelni a tábla, így amikor megváltoztatja a táblázat az elem automatikusan törlődni fognak a gyorsítótárból.</xref:System.Web.Caching.SqlCacheDependency>"
  example:
  - "The following code example shows how to obtain the <xref:System.Web.Configuration.SqlCacheDependencySection> object from the configuration file of an existing Web application.  \n  \n [!code-cs[System.Web.Configuration.SystemWebCachingSectionGroup#5](~/add/codesnippet/csharp/p-system.web.configurati_8_1.cs)]\n [!code-vb[System.Web.Configuration.SystemWebCachingSectionGroup#5](~/add/codesnippet/visualbasic/p-system.web.configurati_8_1.vb)]"
  syntax:
    content: public System.Web.Configuration.SqlCacheDependencySection SqlCacheDependency { get; }
    return:
      type: System.Web.Configuration.SqlCacheDependencySection
      description: "A <xref href=&quot;System.Web.Configuration.SqlCacheDependencySection&quot;> </xref> objektum."
  overload: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SystemWebCachingSectionGroup()
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SystemWebCachingSectionGroup()
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.Cache
- uid: System.Web.Configuration.CacheSection
  parent: System.Web.Configuration
  isExternal: false
  name: CacheSection
  nameWithType: CacheSection
  fullName: System.Web.Configuration.CacheSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache
- uid: System.Web.Configuration.OutputCacheSection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheSection
  nameWithType: OutputCacheSection
  fullName: System.Web.Configuration.OutputCacheSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings
- uid: System.Web.Configuration.OutputCacheSettingsSection
  parent: System.Web.Configuration
  isExternal: false
  name: OutputCacheSettingsSection
  nameWithType: OutputCacheSettingsSection
  fullName: System.Web.Configuration.OutputCacheSettingsSection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
  fullName: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency
- uid: System.Web.Configuration.SqlCacheDependencySection
  parent: System.Web.Configuration
  isExternal: false
  name: SqlCacheDependencySection
  nameWithType: SqlCacheDependencySection
  fullName: System.Web.Configuration.SqlCacheDependencySection
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.#ctor*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SystemWebCachingSectionGroup
  nameWithType: SystemWebCachingSectionGroup.SystemWebCachingSectionGroup
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.Cache*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: Cache
  nameWithType: SystemWebCachingSectionGroup.Cache
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCache*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCache
  nameWithType: SystemWebCachingSectionGroup.OutputCache
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.OutputCacheSettings*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: OutputCacheSettings
  nameWithType: SystemWebCachingSectionGroup.OutputCacheSettings
- uid: System.Web.Configuration.SystemWebCachingSectionGroup.SqlCacheDependency*
  parent: System.Web.Configuration.SystemWebCachingSectionGroup
  isExternal: false
  name: SqlCacheDependency
  nameWithType: SystemWebCachingSectionGroup.SqlCacheDependency
