### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.CustomErrorsMode
  id: CustomErrorsMode
  children:
  - System.Web.Configuration.CustomErrorsMode.Off
  - System.Web.Configuration.CustomErrorsMode.On
  - System.Web.Configuration.CustomErrorsMode.RemoteOnly
  langs:
  - csharp
  name: CustomErrorsMode
  nameWithType: CustomErrorsMode
  fullName: System.Web.Configuration.CustomErrorsMode
  type: Enum
  summary: "Megadja az egyéni hibák modalitást értékeit."
  remarks: "A CustomErrorsMode is használhatja, ha a beállítás értékeinek enumerálása a <xref:System.Web.Configuration.CustomErrorsSection.Mode%2A>tulajdonság.</xref:System.Web.Configuration.CustomErrorsSection.Mode%2A> Ezeket az értékeket határozza meg, hogy az egyéni hibák engedélyezésekor, le van tiltva, vagy csak a távoli ügyfelek számára látható."
  example:
  - "The following code example shows how to set the <xref:System.Web.Configuration.CustomErrorsSection.Mode%2A> property.  \n  \n [!code-vb[System.Web.Configuration.CustomErrorsSection#9](~/add/codesnippet/visualbasic/t-system.web.configurati_54_1.vb)]\n [!code-cs[System.Web.Configuration.CustomErrorsSection#9](~/add/codesnippet/csharp/t-system.web.configurati_54_1.cs)]"
  syntax:
    content: public enum CustomErrorsMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.Off
  id: Off
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: Off
  nameWithType: CustomErrorsMode.Off
  fullName: System.Web.Configuration.CustomErrorsMode.Off
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Letiltja az egyéni hibák, lehetővé téve a standard hibák megjelenítését."
  syntax:
    content: Off
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.On
  id: On
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: On
  nameWithType: CustomErrorsMode.On
  fullName: System.Web.Configuration.CustomErrorsMode.On
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lehetővé teszi, hogy az egyéni hibák. Ha nincs <xref:System.Web.Configuration.CustomErrorsSection.DefaultRedirect*>van megadva, standard hibák kiállított.</xref:System.Web.Configuration.CustomErrorsSection.DefaultRedirect*>"
  syntax:
    content: On
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  id: RemoteOnly
  parent: System.Web.Configuration.CustomErrorsMode
  langs:
  - csharp
  name: RemoteOnly
  nameWithType: CustomErrorsMode.RemoteOnly
  fullName: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lehetővé teszi a távoli ügyfelek csak az egyéni hibák. Az egyéni hibák távoli ügyfelekre mutató csak is látható, és az ASP.NET-hibákat a helyi gazdagép számára jelennek meg."
  syntax:
    content: RemoteOnly
    return:
      type: System.Web.Configuration.CustomErrorsMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.CustomErrorsMode.Off
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: Off
  nameWithType: CustomErrorsMode.Off
  fullName: System.Web.Configuration.CustomErrorsMode.Off
- uid: System.Web.Configuration.CustomErrorsMode
  parent: System.Web.Configuration
  isExternal: false
  name: CustomErrorsMode
  nameWithType: CustomErrorsMode
  fullName: System.Web.Configuration.CustomErrorsMode
- uid: System.Web.Configuration.CustomErrorsMode.On
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: On
  nameWithType: CustomErrorsMode.On
  fullName: System.Web.Configuration.CustomErrorsMode.On
- uid: System.Web.Configuration.CustomErrorsMode.RemoteOnly
  parent: System.Web.Configuration.CustomErrorsMode
  isExternal: false
  name: RemoteOnly
  nameWithType: CustomErrorsMode.RemoteOnly
  fullName: System.Web.Configuration.CustomErrorsMode.RemoteOnly
