### YamlMime:ManagedReference
items:
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  id: ApplicationPartitionCollection
  children:
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  - System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  langs:
  - csharp
  name: ApplicationPartitionCollection
  nameWithType: ApplicationPartitionCollection
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  type: Class
  summary: "A ApplicationPartitionCollection osztály gyűjteménye csak olvasható tartalmazó <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> objektumok."
  syntax:
    content: 'public class ApplicationPartitionCollection : System.Collections.ReadOnlyCollectionBase'
  inheritance:
  - System.Object
  - System.Collections.ReadOnlyCollectionBase
  implements: []
  inheritedMembers:
  - System.Collections.ReadOnlyCollectionBase.Count
  - System.Collections.ReadOnlyCollectionBase.GetEnumerator
  - System.Collections.ReadOnlyCollectionBase.InnerList
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#CopyTo(System.Array,System.Int32)
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#IsSynchronized
  - System.Collections.ReadOnlyCollectionBase.System#Collections#ICollection#SyncRoot
  platform:
  - net462
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  id: Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: Contains(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.Contains(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(ApplicationPartition)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: "Meghatározza, hogy a megadott <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> objektum van ebben a gyűjteményben."
  syntax:
    content: public bool Contains (System.DirectoryServices.ActiveDirectory.ApplicationPartition applicationPartition);
    parameters:
    - id: applicationPartition
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: "A <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> objektum ebben a gyűjteményben."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> szerepel a gyűjteményben, ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>applicationPartition</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  id: CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: CopyTo(ApplicationPartition[],Int32)
  nameWithType: ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: "Másolja át az összes <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> ebben a gyűjteményben, a megadott tömb, a megadott indextől a céltömb kezdődő objektumok."
  syntax:
    content: public void CopyTo (System.DirectoryServices.ActiveDirectory.ApplicationPartition[] applicationPartitions, int index);
    parameters:
    - id: applicationPartitions
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition[]
      description: "A tömb <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> , amely megkapja a gyűjtemény elemeinek objektumok."
    - id: index
      type: System.Int32
      description: "A nulla alapú indexét `applicationPartitions` Ha ez a módszer indítja el, másolja az ehhez a gyűjteményhez."
  overload: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo*
  exceptions:
  - type: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
    commentId: T:System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
    description: "Az alapul szolgáló címtárszolgáltatás hívása hibát eredményezett."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "A céltömb nincs elég nagy a forrás-gyűjtemény mérete alapján, és a <code> index </code> megadott."
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>applicationPartitions</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "A <code> index </code> megadott a céltömb tartományán kívül esik."
  platform:
  - net462
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  id: IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: IndexOf(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  type: Method
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: "Visszaadja a megadott első előfordulásának <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> objektum ebben a gyűjteményben."
  syntax:
    content: public int IndexOf (System.DirectoryServices.ActiveDirectory.ApplicationPartition applicationPartition);
    parameters:
    - id: applicationPartition
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: "A <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> objektum ebben a gyűjteményben."
    return:
      type: System.Int32
      description: "Az első egyező elem nulla alapú indexét. -1, ha nem ez a gyűjtemény tagjai azonos <code> applicationPartition </code>."
  overload: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf*
  exceptions:
  - type: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
    commentId: T:System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
    description: "Az alapul szolgáló címtárszolgáltatás hívása hibát eredményezett."
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>applicationPartition</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  platform:
  - net462
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: ApplicationPartitionCollection.Item(Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(Int32)
  type: Property
  assemblies:
  - System.DirectoryServices
  namespace: System.DirectoryServices.ActiveDirectory
  summary: "Lekérdezi egy <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> objektum ebben a gyűjteményben."
  syntax:
    content: public System.DirectoryServices.ActiveDirectory.ApplicationPartition this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "A nulla alapú indexét a <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> objektum eléréséhez."
    return:
      type: System.DirectoryServices.ActiveDirectory.ApplicationPartition
      description: "A <xref href=&quot;System.DirectoryServices.ActiveDirectory.ApplicationPartition&quot;> </xref> objektum, amely a megadott indexnél."
  overload: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "A <code> index </code> megadott gyűjtemény tartományán kívül esik."
  platform:
  - net462
references:
- uid: System.Collections.ReadOnlyCollectionBase
  isExternal: false
  name: System.Collections.ReadOnlyCollectionBase
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ActiveDirectoryOperationException
  nameWithType: ActiveDirectoryOperationException
  fullName: System.DirectoryServices.ActiveDirectory.ActiveDirectoryOperationException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Contains(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.Contains(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains(ApplicationPartition)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ApplicationPartition
  nameWithType: ApplicationPartition
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartition
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(System.DirectoryServices.ActiveDirectory.ApplicationPartition[],System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: CopyTo(ApplicationPartition[],Int32)
  nameWithType: ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo(ApplicationPartition[],Int32)
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition[]
  parent: System.DirectoryServices.ActiveDirectory
  isExternal: false
  name: ApplicationPartition
  nameWithType: ApplicationPartition
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartition[]
  spec.csharp:
  - uid: System.DirectoryServices.ActiveDirectory.ApplicationPartition
    name: ApplicationPartition
    nameWithType: ApplicationPartition
    fullName: ApplicationPartition[]
  - name: '[]'
    nameWithType: '[]'
    fullName: '[]'
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(System.DirectoryServices.ActiveDirectory.ApplicationPartition)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: IndexOf(ApplicationPartition)
  nameWithType: ApplicationPartitionCollection.IndexOf(ApplicationPartition)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf(ApplicationPartition)
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(System.Int32)
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: ApplicationPartitionCollection.Item(Int32)
  fullName: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item(Int32)
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Contains*
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Contains
  nameWithType: ApplicationPartitionCollection.Contains
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.CopyTo*
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: CopyTo
  nameWithType: ApplicationPartitionCollection.CopyTo
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.IndexOf*
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: IndexOf
  nameWithType: ApplicationPartitionCollection.IndexOf
- uid: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection.Item*
  parent: System.DirectoryServices.ActiveDirectory.ApplicationPartitionCollection
  isExternal: false
  name: Item
  nameWithType: ApplicationPartitionCollection.Item
