### YamlMime:ManagedReference
items:
- uid: System.Xaml.XamlReaderSettings
  id: XamlReaderSettings
  children:
  - System.Xaml.XamlReaderSettings.#ctor
  - System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  - System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  - System.Xaml.XamlReaderSettings.BaseUri
  - System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  - System.Xaml.XamlReaderSettings.LocalAssembly
  - System.Xaml.XamlReaderSettings.ProvideLineInfo
  - System.Xaml.XamlReaderSettings.ValuesMustBeString
  langs:
  - csharp
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
  type: Class
  summary: "Megadja a szabályok feldolgozásának vagy beállításait egy <xref href=&quot;System.Xaml.XamlReader&quot;> </xref> végrehajtására."
  remarks: "Alapértelmezés szerint a inicializált xamlreadersettings objektumban objektum értékeket használja, az a Tulajdonságok megegyeznek az alapértelmezett beállításokat, például a várt `false` logikai tulajdonságok és a null értékeket azokhoz a referencia-típus tulajdonságait. Alapértelmezett inicializálása a következő értékek eredményezi: - a <xref:System.Xaml.XamlReaderSettings.BaseUri%2A>és <xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A>tulajdonság `null`.</xref:System.Xaml.XamlReaderSettings.LocalAssembly%2A> </xref:System.Xaml.XamlReaderSettings.BaseUri%2A>      -A <xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>tulajdonság `false`.</xref:System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements%2A>      -A <xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>tulajdonság `false` az objektummodell; azonban akkor állítható be `true` a betöltött végrehajtható fájlok és a hibakeresési beállításokat, vagy XAML-séma környezet által alapján futásidőben.</xref:System.Xaml.XamlReaderSettings.ProvideLineInfo%2A>"
  syntax:
    content: public class XamlReaderSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor
  id: '#ctor'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> osztály."
  remarks: "További információ a <xref:System.Xaml.XamlReaderSettings>példány alapértelmezett <xref:System.Xaml.XamlReaderSettings>.</xref:System.Xaml.XamlReaderSettings> című</xref:System.Xaml.XamlReaderSettings> inicializálása"
  syntax:
    content: public XamlReaderSettings ();
    parameters: []
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  id: '#ctor(System.Xaml.XamlReaderSettings)'
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  type: Constructor
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> osztály egy másik értékek alapján <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> objektum."
  remarks: "Ez a konstruktor támogatja az XAML-olvasók, ahol további beállításokat is származhat más résztvevői a adatolvasási folyamata beállítások egyesítése."
  syntax:
    content: public XamlReaderSettings (System.Xaml.XamlReaderSettings settings);
    parameters:
    - id: settings
      type: System.Xaml.XamlReaderSettings
      description: "Egy meglévő <xref href=&quot;System.Xaml.XamlReaderSettings&quot;> </xref> objektum."
  overload: System.Xaml.XamlReaderSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  id: AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy a legfelső szintű objektum tartalmazhatják tagok, amelyek rendelkeznek egy védett hozzáférési kódmodell, amikor a rendszer jelzi, hogy az XAML-típus leképezése."
  remarks: "Ez a beállítás egyes XAML-megvalósítások, például a legfelső szintű objektum esetén gyakran a &quot;factory&quot; generálásához egy minta típusból egy példányát, ha adott minta típusa nem mindig gyakorlati objektumpéldány WPF szempontjából érték. Például egy gyökérmappájában `UserControl` egy bizonyos jelentése WPF és a Silverlight alkalmazás esetében, és `UserControl` előfordulhat, hogy védett tulajdonságok (`UserControl.Content`), hogy az elemző kell-e a hozzáférést. Eszközök és a Tervező felületek is ilyen tulajdonságok hozzáférés szükséges. Ezekben az esetekben általában kell jelenteni az XAML-típus rendszerre írható tulajdonságok annak ellenére, hogy a védett hozzáférést a biztonsági típus rendszerben."
  syntax:
    content: public bool AllowProtectedMembersOnRoot { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a legfelső szintű objektum tartozhat tagok, amelyek rendelkeznek egy védett hozzáférési kódmodell; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.BaseUri
  id: BaseUri
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdezi vagy beállítja az alap URI relatív elérési utak feloldásához használt."
  remarks: "A .NET Framework XAML szolgáltatások API egyes URI-kapcsolódó tulajdonságok tekinti URI-azonosítók az XAML-névterek karakterláncok; azonban ezt a tulajdonságot használja valódi <xref:System.Uri>típusa.</xref:System.Uri>"
  syntax:
    content: public Uri BaseUri { get; set; }
    return:
      type: System.Uri
      description: "Az alap URI-azonosító használata. Az alapértelmezett érték <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.BaseUri*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  id: IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdez vagy beállít egy értéket, amely meghatározza, hogy az XAML-olvasó figyelmen kívül hagyja az értékek <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> tulajdonságelemek létező attribútumok."
  remarks: "Honosítási, során a `x:Uid` attribútum alapján kódkiterjesztési elemek határozza meg, hogy a honosítási eszközök honosításhoz különálló entitások XAML-elemek is dolgozni. Attribútumok általában nem jelennek meg a tulajdonságelemek XAML-kódban. Azonban `x:Uid` kivétel azért, mert néhány módjait kerül honosított szöveg egy tulajdonság elemben tartalmat, ahelyett, hogy egy külön objektumként, amely képes fogadni a saját `x:Uid`. Egy IgnoreUidsOnPropertyElements érték `true` lehetővé teszi, hogy a szigorúbb módját. Az alapértelmezett érték `false` folytatja a tulajdonságelem `x:Uid` attribútumok."
  syntax:
    content: public bool IgnoreUidsOnPropertyElements { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az olvasó figyelmen kívül hagyja az értékek <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> tulajdonságelemek attribútumok. <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;></xref>Ha az olvasó kell feldolgozni <xref uid=&quot;langword_csharp_x:Uid&quot; name=&quot;x:Uid&quot; href=&quot;&quot;> </xref> tulajdonságelemek attribútumok. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  id: LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdezi vagy beállítja az aktuális helyi szerelvény a feldolgozás képviselő objektum. A szerelvény adatok segítő API-hívásokban például &lt;xref:System.Xaml.XamlType.GetAllMembers%2A?displayProperty=fullName&gt;."
  syntax:
    content: public System.Reflection.Assembly LocalAssembly { get; set; }
    return:
      type: System.Reflection.Assembly
      description: "A CLR-beli reflexiós <xref:System.Reflection.Assembly>objektum.</xref:System.Reflection.Assembly>"
  overload: System.Xaml.XamlReaderSettings.LocalAssembly*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  id: ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdezi vagy beállítja egy érték, amely megadja, hogy az olvasó biztosíthat a sor számának megjelenítése és elhelyezése."
  remarks: "ProvideLineInfo van `false` az objektummodell; azonban akkor állítható be `true` alapján a betöltött végrehajtható fájlok és a hibakeresési beállításokat futásidőben."
  syntax:
    content: public bool ProvideLineInfo { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az olvasó biztosíthat sor megjelenítése és elhelyezése az információk; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  exceptions: []
  platform:
  - net462
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  id: ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  langs:
  - csharp
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
  type: Property
  assemblies:
  - System.Xaml
  namespace: System.Xaml
  summary: "Lekérdez vagy beállít egy értéket, amely meghatározza, hogy az olvasó érvényesíti, amely minden <xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;> </xref> csomópontok feldolgozni, mint egy <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref> típusa."
  remarks: "Kívül <xref:System.String>, egy lehetséges `Value` <xref:System.Windows.Markup.XData>.</xref:System.Windows.Markup.XData> tartalma az egyes XAML-megvalósítások</xref:System.String>"
  syntax:
    content: public bool ValuesMustBeString { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az olvasó érvényesíti, amely csak <xref uid=&quot;langword_csharp_String&quot; name=&quot;String&quot; href=&quot;&quot;> </xref> lévő <xref uid=&quot;langword_csharp_Value&quot; name=&quot;Value&quot; href=&quot;&quot;> </xref> csomópontok; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Xaml.XamlReaderSettings.#ctor
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings()
  nameWithType: XamlReaderSettings.XamlReaderSettings()
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings()
- uid: System.Xaml.XamlReaderSettings.#ctor(System.Xaml.XamlReaderSettings)
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings(XamlReaderSettings)
  nameWithType: XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
  fullName: System.Xaml.XamlReaderSettings.XamlReaderSettings(XamlReaderSettings)
- uid: System.Xaml.XamlReaderSettings
  parent: System.Xaml
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings
  fullName: System.Xaml.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
  fullName: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Xaml.XamlReaderSettings.BaseUri
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
  fullName: System.Xaml.XamlReaderSettings.BaseUri
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
  fullName: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
  fullName: System.Xaml.XamlReaderSettings.LocalAssembly
- uid: System.Reflection.Assembly
  parent: System.Reflection
  isExternal: true
  name: Assembly
  nameWithType: Assembly
  fullName: System.Reflection.Assembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
  fullName: System.Xaml.XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
  fullName: System.Xaml.XamlReaderSettings.ValuesMustBeString
- uid: System.Xaml.XamlReaderSettings.#ctor*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: XamlReaderSettings
  nameWithType: XamlReaderSettings.XamlReaderSettings
- uid: System.Xaml.XamlReaderSettings.AllowProtectedMembersOnRoot*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: AllowProtectedMembersOnRoot
  nameWithType: XamlReaderSettings.AllowProtectedMembersOnRoot
- uid: System.Xaml.XamlReaderSettings.BaseUri*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: BaseUri
  nameWithType: XamlReaderSettings.BaseUri
- uid: System.Xaml.XamlReaderSettings.IgnoreUidsOnPropertyElements*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: IgnoreUidsOnPropertyElements
  nameWithType: XamlReaderSettings.IgnoreUidsOnPropertyElements
- uid: System.Xaml.XamlReaderSettings.LocalAssembly*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: LocalAssembly
  nameWithType: XamlReaderSettings.LocalAssembly
- uid: System.Xaml.XamlReaderSettings.ProvideLineInfo*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ProvideLineInfo
  nameWithType: XamlReaderSettings.ProvideLineInfo
- uid: System.Xaml.XamlReaderSettings.ValuesMustBeString*
  parent: System.Xaml.XamlReaderSettings
  isExternal: false
  name: ValuesMustBeString
  nameWithType: XamlReaderSettings.ValuesMustBeString
