### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsProviderAttribute
  id: SettingsProviderAttribute
  children:
  - System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  - System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  - System.Configuration.SettingsProviderAttribute.ProviderTypeName
  langs:
  - csharp
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute
  fullName: System.Configuration.SettingsProviderAttribute
  type: Class
  summary: "Megadja a beállítások szolgáltatót tárolási biztosítja az aktuális alkalmazás beállítások osztály vagy tulajdonság. Ez az osztály nem örökölhető."
  remarks: "Minden alkalmazás beállítások osztály beállítások alkalmazástulajdonságok, amelyek megfelelnek az adatokat, amelyek továbbra is fennáll, az alkalmazás végrehajtások közötti olyan csoportját határozza meg. Azonban a beállításszolgáltató – osztályból származtatott osztály <xref:System.Configuration.SettingsProvider>–, amelyek ténylegesen a tárolási mechanizmust biztosít.</xref:System.Configuration.SettingsProvider>       A SettingsProviderAttribute megadja a beállítások szolgáltatót tárolási biztosít az alkalmazás tulajdonságai. Ez az attribútum a teljes alkalmazás beállítások osztály vagy egyéni alkalmazás tulajdonságai is alkalmazható. A tulajdonság szinten adja meg a SettingsProviderAttribute felül fogja írni a osztály szintű attribútum. Ha a beállításszolgáltató explicit módon nincs megadva, az alapértelmezett szolgáltató használja. Ügyfél-alkalmazások esetében az alapértelmezett szolgáltató <xref:System.Configuration.LocalFileSettingsProvider>.</xref:System.Configuration.LocalFileSettingsProvider>       Szolgáltatók beállítása nem lehet megállapítani, futási időben. A futásidejű tároló módszerek meghatározása a beállítások Szolgáltatóosztály magát a kell bekódolni.      > [!CAUTION] > Tetszőleges harmadik féltől származó egyéni beállítások szolgáltatók használata nem eredendően nem biztonságos, mert ezek a szolgáltatók az alkalmazás konfigurációs adatok teljes olvasási/írási hozzáférést. A beállítások szolgáltató kell lennie alaposan vetted általános célú elfogadása előtt."
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SettingsProviderAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy példányát inicializálja a <xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;> </xref> osztály."
  remarks: "A típus neve az a név a osztályból származó <xref:System.Configuration.SettingsProvider>, vagyis beállítások szolgáltató megadva.</xref:System.Configuration.SettingsProvider>      > [!CAUTION] > Tetszőleges harmadik féltől származó egyéni beállítások szolgáltatók használata nem eredendően nem biztonságos, mert ezek a szolgáltatók az alkalmazás konfigurációs adatok teljes olvasási/írási hozzáférést. A beállítások szolgáltató kell lennie alaposan vetted általános célú elfogadása előtt."
  syntax:
    content: public SettingsProviderAttribute (string providerTypeName);
    parameters:
    - id: providerTypeName
      type: System.String
      description: "A <xref:System.String>tartalmazó a beállítások szolgáltató neve.</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.SettingsProviderAttribute&quot;> </xref> osztály."
  syntax:
    content: public SettingsProviderAttribute (Type providerType);
    parameters:
    - id: providerType
      type: System.Type
      description: "A <xref:System.Type>Beállítások szolgáltató típust tartalmazó.</xref:System.Type>"
  overload: System.Configuration.SettingsProviderAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  id: ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  langs:
  - csharp
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi a beállítások szolgáltató nevét."
  remarks: "A ProviderTypeName tulajdonság értéke az <xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>a osztálynak</xref:System.Configuration.SettingsProviderAttribute.%23ctor%2A>"
  syntax:
    content: public string ProviderTypeName { get; }
    return:
      type: System.String
      description: "A <xref:System.String>tartalmazó a beállítások szolgáltató neve.</xref:System.String>"
  overload: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.String)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(String)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(String)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.SettingsProviderAttribute.#ctor(System.Type)
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute(Type)
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute(Type)
  fullName: System.Configuration.SettingsProviderAttribute.SettingsProviderAttribute(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
  fullName: System.Configuration.SettingsProviderAttribute.ProviderTypeName
- uid: System.Configuration.SettingsProviderAttribute.#ctor*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: SettingsProviderAttribute
  nameWithType: SettingsProviderAttribute.SettingsProviderAttribute
- uid: System.Configuration.SettingsProviderAttribute.ProviderTypeName*
  parent: System.Configuration.SettingsProviderAttribute
  isExternal: false
  name: ProviderTypeName
  nameWithType: SettingsProviderAttribute.ProviderTypeName
