### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  id: ICustomIdentityConfiguration
  children:
  - System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  langs:
  - csharp
  name: ICustomIdentityConfiguration
  nameWithType: ICustomIdentityConfiguration
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  type: Interface
  summary: "Határozza meg, amelyek lehetővé teszik egyéni konfiguráció betöltése osztály módszerek."
  remarks: "Az XML-osztályok a ICustomIdentityConfiguration felületet megvalósító egyéni konfigurációs be tudják tölteni.       A Windows Identity Foundation (WIF) osztályok számos valósítja meg a szükséges, hogy a konfigurációs fájlból származó származtatott osztályok egyéni konfigurációs képességet ICustomIdentityConfiguration illesztőfelületet. A WIF osztályok számos alap implementálásához a módszer az alapértelmezett konfiguráció meg a megfelelő objektumokat jelölnek."
  syntax:
    content: public interface ICustomIdentityConfiguration
  implements: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  id: LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  langs:
  - csharp
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  type: Method
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Terhelések egyéni konfigurációs XML-fájljából. Írja felül a metódust egyéni konfigurációs elemek kezelése."
  remarks: "A konfigurációs infrastruktúra a LoadCustomConfiguration metódust hívja. Ez a metódus hívásakor a `nodelist` a paraméter tartalmazza a legfelső szintű alárendelt elemei a szülőelem, konfigurálja az object osztályt a konfigurációs fájlból. Például egy osztály származtatott <xref:System.IdentityModel.Tokens.IssuerNameRegistry>, alárendelt elemei fog rendelkezni a [ \\&lt; issuerNameRegistry\\&gt;](../Topic/%3CissuerNameRegistry%3E.md) elemnek átadott a `nodelist` paraméter.</xref:System.IdentityModel.Tokens.IssuerNameRegistry> A `nodelist` áll teljesen <xref:System.Xml.XmlElement>objektumok.</xref:System.Xml.XmlElement> Ezek mindegyikének lehet attribútumokat és attól függően, hogy a konfigurációs séma a konfigurálni kívánt osztályhoz meghatározott gyermekelemek."
  syntax:
    content: public void LoadCustomConfiguration (System.Xml.XmlNodeList nodeList);
    parameters:
    - id: nodeList
      type: System.Xml.XmlNodeList
      description: "Az egyéni konfigurációs tartalmazó XML-csomópontnak. A lista minden csomópont van típusú <xref href=&quot;System.Xml.XmlElement&quot;> </xref>."
  overload: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(System.Xml.XmlNodeList)
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration(XmlNodeList)
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
  fullName: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration(XmlNodeList)
- uid: System.Xml.XmlNodeList
  parent: System.Xml
  isExternal: false
  name: XmlNodeList
  nameWithType: XmlNodeList
  fullName: System.Xml.XmlNodeList
- uid: System.IdentityModel.Configuration.ICustomIdentityConfiguration.LoadCustomConfiguration*
  parent: System.IdentityModel.Configuration.ICustomIdentityConfiguration
  isExternal: false
  name: LoadCustomConfiguration
  nameWithType: ICustomIdentityConfiguration.LoadCustomConfiguration
