### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.WebApplicationLevel
  id: WebApplicationLevel
  children:
  - System.Web.Configuration.WebApplicationLevel.AboveApplication
  - System.Web.Configuration.WebApplicationLevel.AtApplication
  - System.Web.Configuration.WebApplicationLevel.BelowApplication
  langs:
  - csharp
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
  type: Enum
  summary: "A webalkalmazás konfigurációs fájl elérési útja szintjét adja meg."
  remarks: "A WebApplicationLevel osztály biztosít három szintje, amely segítségével különböztetheti meg egymástól a konfigurációs fájl helyére egy ASP.NET-webalkalmazás gyökérszinten viszonyítva. A három elérési szintű típusok a következők: AboveApplication AtApplication és BelowApplication."
  syntax:
    content: public enum WebApplicationLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  id: AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Megadja, hogy a konfigurációs fájl alapján a jelenlegi ASP.NET webes alkalmazás a globális könyvtárban található."
  syntax:
    content: AboveApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  id: AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Megadja, hogy a konfigurációs fájl az aktuális ASP.NET webes alkalmazás gyökérkönyvtárában."
  syntax:
    content: AtApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  id: BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  langs:
  - csharp
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Meghatározza, hogy a konfigurációs fájl nem a jelenlegi ASP.NET webalkalmazás alkönyvtárát."
  syntax:
    content: BelowApplication
    return:
      type: System.Web.Configuration.WebApplicationLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.WebApplicationLevel.AboveApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AboveApplication
  nameWithType: WebApplicationLevel.AboveApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AboveApplication
- uid: System.Web.Configuration.WebApplicationLevel
  parent: System.Web.Configuration
  isExternal: false
  name: WebApplicationLevel
  nameWithType: WebApplicationLevel
  fullName: System.Web.Configuration.WebApplicationLevel
- uid: System.Web.Configuration.WebApplicationLevel.AtApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: AtApplication
  nameWithType: WebApplicationLevel.AtApplication
  fullName: System.Web.Configuration.WebApplicationLevel.AtApplication
- uid: System.Web.Configuration.WebApplicationLevel.BelowApplication
  parent: System.Web.Configuration.WebApplicationLevel
  isExternal: false
  name: BelowApplication
  nameWithType: WebApplicationLevel.BelowApplication
  fullName: System.Web.Configuration.WebApplicationLevel.BelowApplication
