### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentProgressChangedEventHandler
  id: DeploymentProgressChangedEventHandler
  langs:
  - csharp
  name: DeploymentProgressChangedEventHandler
  nameWithType: DeploymentProgressChangedEventHandler
  fullName: System.Deployment.Application.DeploymentProgressChangedEventHandler
  type: Delegate
  summary: "A kezelő mód a <xref href=&quot;System.Deployment.Application.ApplicationDeployment.CheckForUpdateProgressChanged&quot;> </xref> esemény, <xref href=&quot;System.Deployment.Application.ApplicationDeployment.UpdateProgressChanged&quot;> </xref> esemény, vagy <xref href=&quot;System.Deployment.Application.ApplicationDeployment.DownloadFileGroupProgressChanged&quot;> </xref> az esemény egy <xref href=&quot;System.Deployment.Application.ApplicationDeployment&quot;> </xref>."
  remarks: 'Amikor létrehoz egy DeploymentProgressChangedEventHandler delegált, meg kell adnia a módszert, amelyet az esemény kezelnek. Az esemény társítja a eseménykezelő, vegye fel a küldött példányának az esemény. Az eseménykezelő nevezzük az esemény akkor következik be, amikor, ha nem távolítja el a delegált. Eseménykezelő meghatalmazottak kapcsolatos további információkért lásd: [NIB: események és -Delegáltaknak](http://msdn.microsoft.com/en-us/d98fd58b-fa4f-4598-8378-addf4355a115).'
  syntax:
    content: public delegate void DeploymentProgressChangedEventHandler(object sender, DeploymentProgressChangedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
