### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement
  id: WebHttpSecurityElement
  children:
  - System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  - System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  langs:
  - csharp
  name: WebHttpSecurityElement
  nameWithType: WebHttpSecurityElement
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement
  type: Class
  summary: "XML-elem, amely a szolgáltatás biztonsági beállítja a végpontok, amelyek a HTTP-kérelmek fogadásához. Ez az osztály nem örökölhető."
  syntax:
    content: 'public sealed class WebHttpSecurityElement : System.ServiceModel.Configuration.ServiceModelConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: WebHttpSecurityElement()
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.WebHttpSecurityElement()
  type: Constructor
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.WebHttpSecurityElement&quot;> </xref> osztály."
  syntax:
    content: public WebHttpSecurityElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  id: Mode
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi egy XML-elem, amely meghatározza a biztonsági módot az alapvető HTTP-szolgáltatás."
  remarks: "Ez a tulajdonság határozza meg, hogy a beállítások a <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>tulajdonság életbe lép.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A>"
  syntax:
    content: public System.ServiceModel.WebHttpSecurityMode Mode { get; set; }
    return:
      type: System.ServiceModel.WebHttpSecurityMode
      description: "Érték <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref> , amely azt jelzi, hogy átviteli szintű biztonsági vagy nem használja a végpont. Az alapértelmezett érték <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "Az érték nem egy érvényes <xref href=&quot;System.ServiceModel.WebHttpSecurityMode&quot;> </xref>."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  id: Transport
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  langs:
  - csharp
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  type: Property
  assemblies:
  - System.ServiceModel.Web
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi egy XML-elem, amely jelzi a átvitelszintű biztonság szolgáltatásvégpont beállításai HTTP-kérelmek fogadásához."
  remarks: "Használja a <xref:System.ServiceModel.Configuration.WebHttpSecurityElement>az átvitel biztonsági paramétereinek a beállításához tulajdonság objektum.</xref:System.ServiceModel.Configuration.WebHttpSecurityElement> A <xref:System.ServiceModel.WebHttpSecurityMode>értékre kell állítani a <xref:System.ServiceModel.WebHttpSecurityMode>vagy <xref:System.ServiceModel.WebHttpSecurityMode>által megadott beállítások értékét a <xref:System.ServiceModel.WebHttpSecurity.Transport%2A>válik a szolgáltatási végpont tulajdonság.</xref:System.ServiceModel.WebHttpSecurity.Transport%2A> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode> </xref:System.ServiceModel.WebHttpSecurityMode> Ez az érték beállítható, konfigurációs vagy az a <xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>konstruktor.</xref:System.ServiceModel.WebHttpBinding.%23ctor%28System.ServiceModel.WebHttpSecurityMode%29>"
  syntax:
    content: public System.ServiceModel.Configuration.HttpTransportSecurityElement Transport { get; }
    return:
      type: System.ServiceModel.Configuration.HttpTransportSecurityElement
      description: "A <xref href=&quot;System.ServiceModel.Configuration.WebHttpSecurityElement&quot;> </xref> , amely megadja, hogy az átviteli szintű biztonsági beállításokat. Az alapértelmezett értékek beállítása vannak egy <> </> *> a <xref:System.ServiceModel.HttpClientCredentialType>, egy <> </> *> a <xref href=&quot;System.ServiceModel.HttpProxyCredentialType&quot;> </xref>, és <xref:System.ServiceModel.HttpTransportSecurity.Realm*>= &quot;&quot;.</xref:System.ServiceModel.HttpTransportSecurity.Realm*> </xref:System.ServiceModel.HttpClientCredentialType>"
  overload: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.ServiceModelConfigurationElement
  isExternal: false
  name: System.ServiceModel.Configuration.ServiceModelConfigurationElement
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: WebHttpSecurityElement()
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement()
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.WebHttpSecurityElement()
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode
- uid: System.ServiceModel.WebHttpSecurityMode
  parent: System.ServiceModel
  isExternal: false
  name: WebHttpSecurityMode
  nameWithType: WebHttpSecurityMode
  fullName: System.ServiceModel.WebHttpSecurityMode
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
  fullName: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport
- uid: System.ServiceModel.Configuration.HttpTransportSecurityElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: HttpTransportSecurityElement
  nameWithType: HttpTransportSecurityElement
  fullName: System.ServiceModel.Configuration.HttpTransportSecurityElement
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.#ctor*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: WebHttpSecurityElement
  nameWithType: WebHttpSecurityElement.WebHttpSecurityElement
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Mode*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Mode
  nameWithType: WebHttpSecurityElement.Mode
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Properties*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Properties
  nameWithType: WebHttpSecurityElement.Properties
- uid: System.ServiceModel.Configuration.WebHttpSecurityElement.Transport*
  parent: System.ServiceModel.Configuration.WebHttpSecurityElement
  isExternal: false
  name: Transport
  nameWithType: WebHttpSecurityElement.Transport
