### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier
  id: IApplicationIdentifier
  children:
  - System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  langs:
  - csharp
  name: IApplicationIdentifier
  nameWithType: IApplicationIdentifier
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier
  type: Interface
  summary: "Határozza meg, a gyorsítótár-megvalósítással segítségével kommunikál a gazdagép-környezetben alkalmazástartományok azonosítója."
  remarks: "A [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] ASP.NET például a gazdagép-környezetben a a IApplicationIdentifier felület segítségével, amely azonosítja az egyes alkalmazástartományok karakterláncok meghatározása. A gazdagép-környezetben a IApplicationIdentifier felületet valósítja meg. Ez az interfész számára elérhető lesz <xref:System.Runtime.Caching.ObjectCache>megvalósítások keresztül a <xref:System.Runtime.Caching.ObjectCache.Host%2A>tulajdonság.</xref:System.Runtime.Caching.ObjectCache.Host%2A> </xref:System.Runtime.Caching.ObjectCache>       A gyorsítótár-megvalósítással használja ezt a hivatkozást az alkalmazástartomány azonosítója. ASP.NET, a gyorsítótár-megvalósítások segítségével az alkalmazásazonosító gyorsítótár teljesítményszámlálók azonosítóinak összeállításához. Így lehetővé teszi a teljesítmény nevek számláló példányai, amelyek több alkalmazástartományok futtatásakor alkalmazástartományok között meg lehet különböztetni."
  syntax:
    content: public interface IApplicationIdentifier
  implements: []
  platform:
  - net462
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  id: GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  langs:
  - csharp
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
  type: Method
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Hosting
  summary: "Lekéri egy alkalmazástartomány azonosítója."
  remarks: "A GetApplicationId módszer általában megvalósítja a [!INCLUDE[dnprdnshort](~/add/includes/dnprdnshort-md.md)] ahhoz, hogy egy alkalmazás-azonosító, a gazdagép-környezetben egy <xref:System.Runtime.Caching.ObjectCache>végrehajtása.</xref:System.Runtime.Caching.ObjectCache> A <xref:System.Runtime.Caching.ObjectCache>megvalósítási ezt az információt használja a futó alkalmazások tartományának azonosításához.</xref:System.Runtime.Caching.ObjectCache>       Például az ASP.NET, a gyorsítótár használja az alkalmazásazonosító gyorsítótár teljesítményszámlálók azonosítóinak összeállításához. A gyorsítótár meghívja az GetApplicationId módszer, amely megvalósítja a gazdagép-környezetben, és a gazdagép azonosítóját adja vissza. Így lehetővé teszi a teljesítmény nevek számláló példányai, amelyek több alkalmazástartományok futtatásakor alkalmazástartományok között meg lehet különböztetni."
  syntax:
    content: public string GetApplicationId ();
    parameters: []
    return:
      type: System.String
      description: "Az aktuális tartomány alkalmazás egyedi azonosítója."
  overload: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId()
  nameWithType: IApplicationIdentifier.GetApplicationId()
  fullName: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId()
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Runtime.Caching.Hosting.IApplicationIdentifier.GetApplicationId*
  parent: System.Runtime.Caching.Hosting.IApplicationIdentifier
  isExternal: false
  name: GetApplicationId
  nameWithType: IApplicationIdentifier.GetApplicationId
