### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.WsdlImporterElement
  id: WsdlImporterElement
  children:
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  - System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  - System.ServiceModel.Configuration.WsdlImporterElement.Properties
  - System.ServiceModel.Configuration.WsdlImporterElement.Type
  langs:
  - csharp
  name: WsdlImporterElement
  nameWithType: WsdlImporterElement
  fullName: System.ServiceModel.Configuration.WsdlImporterElement
  type: Class
  summary: "A konfigurációs elem, amely meghatározza a Web Services Description Language (WSDL) 1.1-es metaadatok importálása a WS-Policy mellékletek jelöli."
  remarks: "A <xref:System.ServiceModel.Description.WsdlImporter>szolgál a metaadatok importálása, valamint ezt az információt átalakítása különböző osztályok, amelyek megfelelnek a szerződés és a végpont.</xref:System.ServiceModel.Description.WsdlImporter>       Szelektív importálhatja a szerződés és a végpont adatokat és teszi közzé az importálási hibáit, és amelyek fogadják az importálási és az átalakítási folyamat kapcsolódik típusinformációt tulajdonságokat. Importáló kötési információ és a házirend-dokumentumok, a WSDL-dokumentumok, a WSDL-bővítmények és a XML-sémadokumentumokban eléréséhez tulajdonságokat is támogatja."
  syntax:
    content: 'public sealed class WsdlImporterElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement()
  nameWithType: WsdlImporterElement.WsdlImporterElement()
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> osztály."
  syntax:
    content: public WsdlImporterElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement(String)
  nameWithType: WsdlImporterElement.WsdlImporterElement(String)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(String)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> osztály az adott típusú."
  syntax:
    content: public WsdlImporterElement (string type);
    parameters:
    - id: type
      type: System.String
      description: "A megadott típus."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  id: '#ctor(System.Type)'
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: WsdlImporterElement(Type)
  nameWithType: WsdlImporterElement.WsdlImporterElement(Type)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(Type)
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.WsdlImporterElement&quot;> </xref> osztály az adott típusú."
  syntax:
    content: public WsdlImporterElement (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "A megadott típus."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type
  id: Type
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  langs:
  - csharp
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Type
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a konfigurációs elem típusát."
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "A konfigurációs elem típusa."
  overload: System.ServiceModel.Configuration.WsdlImporterElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement()
  nameWithType: WsdlImporterElement.WsdlImporterElement()
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement()
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.String)
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement(String)
  nameWithType: WsdlImporterElement.WsdlImporterElement(String)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor(System.Type)
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement(Type)
  nameWithType: WsdlImporterElement.WsdlImporterElement(Type)
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.WsdlImporterElement(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Properties
  nameWithType: WsdlImporterElement.Properties
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Type
  nameWithType: WsdlImporterElement.Type
  fullName: System.ServiceModel.Configuration.WsdlImporterElement.Type
- uid: System.ServiceModel.Configuration.WsdlImporterElement.#ctor*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: WsdlImporterElement
  nameWithType: WsdlImporterElement.WsdlImporterElement
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Properties*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Properties
  nameWithType: WsdlImporterElement.Properties
- uid: System.ServiceModel.Configuration.WsdlImporterElement.Type*
  parent: System.ServiceModel.Configuration.WsdlImporterElement
  isExternal: false
  name: Type
  nameWithType: WsdlImporterElement.Type
