### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.ExtensionsSection
  id: ExtensionsSection
  children:
  - System.ServiceModel.Configuration.ExtensionsSection.#ctor
  - System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  - System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  - System.ServiceModel.Configuration.ExtensionsSection.Properties
  langs:
  - csharp
  name: ExtensionsSection
  nameWithType: ExtensionsSection
  fullName: System.ServiceModel.Configuration.ExtensionsSection
  type: Class
  summary: "A bővítmény-definíciók tartalmazó konfigurációs szakasz jelöli."
  syntax:
    content: 'public class ExtensionsSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: ExtensionsSection()
  nameWithType: ExtensionsSection.ExtensionsSection()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.ExtensionsSection()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.ExtensionsSection&quot;> </xref> osztály."
  syntax:
    content: public ExtensionsSection ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionsSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  id: BehaviorExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi a szakaszában az összes viselkedés-bővítmény."
  remarks: "Viselkedés bővítmények lehetővé teszik, hogy a felhasználó felhasználói viselkedés elemek létrehozásához. Ezek az elemek használható együtt a normál [!INCLUDE[indigo1](~/add/includes/ajax-current-ext-md.md)] viselkedés elemek."
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BehaviorExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "Viselkedés bővítmények gyűjteménye."
  overload: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  id: BindingElementExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Az összes a kötési elem bővítmény szakaszában meghatározott lekérdezi."
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BindingElementExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "Kötési elem bővítmények gyűjteménye."
  overload: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  id: BindingExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi a szakaszában az összes kötési-bővítmény."
  remarks: "Kötési bővítmények lehetővé teszik a felhasználónak egyéni kötések részeként hozza létre a felhasználó által definiált kötőelemekké való használatra. Programozott módon a kötési bővítmény olyan, amely megvalósítja a BindingElement absztrakt osztály."
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection BindingExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "Bővítmények kötés gyűjteménye."
  overload: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  id: EndpointExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi egy <xref href=&quot;System.ServiceModel.Configuration.ExtensionElementCollection&quot;> </xref> objektum, amely tartalmazza a megadott végpont-bővítményt."
  syntax:
    content: public System.ServiceModel.Configuration.ExtensionElementCollection EndpointExtensions { get; }
    return:
      type: System.ServiceModel.Configuration.ExtensionElementCollection
      description: "Végpont bővítmények gyűjteménye."
  overload: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  id: InitializeDefault
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: InitializeDefault()
  nameWithType: ExtensionsSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Inicializálja az alapértelmezés szerinti érték a konfigurációs szakasz."
  syntax:
    content: protected override void InitializeDefault ();
    parameters: []
  overload: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.ExtensionsSection
  langs:
  - csharp
  name: Properties
  nameWithType: ExtensionsSection.Properties
  fullName: System.ServiceModel.Configuration.ExtensionsSection.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> gyűjteményét tartalmazó példány <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> objektumok, amelyek lehetnek attribútumok vagy <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> objektumokat a konfigurációs elem."
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "A <xref href=&quot;System.Configuration.ConfigurationPropertyCollection&quot;> </xref> gyűjteményét tartalmazó példány <xref href=&quot;System.Configuration.ConfigurationProperty&quot;> </xref> objektumok, amelyek lehetnek attribútumok vagy <xref href=&quot;System.Configuration.ConfigurationElement&quot;> </xref> a konfigurációs elem objektumok."
  overload: System.ServiceModel.Configuration.ExtensionsSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: ExtensionsSection()
  nameWithType: ExtensionsSection.ExtensionsSection()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.ExtensionsSection()
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions
- uid: System.ServiceModel.Configuration.ExtensionElementCollection
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ExtensionElementCollection
  nameWithType: ExtensionElementCollection
  fullName: System.ServiceModel.Configuration.ExtensionElementCollection
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
  fullName: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: InitializeDefault()
  nameWithType: ExtensionsSection.InitializeDefault()
  fullName: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault()
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: Properties
  nameWithType: ExtensionsSection.Properties
  fullName: System.ServiceModel.Configuration.ExtensionsSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.ExtensionsSection.#ctor*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: ExtensionsSection
  nameWithType: ExtensionsSection.ExtensionsSection
- uid: System.ServiceModel.Configuration.ExtensionsSection.BehaviorExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BehaviorExtensions
  nameWithType: ExtensionsSection.BehaviorExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingElementExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingElementExtensions
  nameWithType: ExtensionsSection.BindingElementExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.BindingExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: BindingExtensions
  nameWithType: ExtensionsSection.BindingExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.EndpointExtensions*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: EndpointExtensions
  nameWithType: ExtensionsSection.EndpointExtensions
- uid: System.ServiceModel.Configuration.ExtensionsSection.InitializeDefault*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: InitializeDefault
  nameWithType: ExtensionsSection.InitializeDefault
- uid: System.ServiceModel.Configuration.ExtensionsSection.Properties*
  parent: System.ServiceModel.Configuration.ExtensionsSection
  isExternal: false
  name: Properties
  nameWithType: ExtensionsSection.Properties
