### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  id: ScriptingScriptResourceHandlerSection
  children:
  - System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor
  - System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
  - System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
  - System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
  langs:
  - csharp
  name: ScriptingScriptResourceHandlerSection
  nameWithType: ScriptingScriptResourceHandlerSection
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  type: Class
  summary: "Jelöli egy <xref uid=&quot;langword_csharp_ScriptingScriptResourceHandler&quot; name=&quot;ScriptingScriptResourceHandler&quot; href=&quot;&quot;> </xref> konfigurációs szakasz a <xref uid=&quot;langword_csharp_&lt;scripting&gt;&quot; name=&quot;&lt;scripting&gt;&quot; href=&quot;&quot;> </xref> elemet a konfigurációs fájl. Ez az osztály nem örökölhető."
  remarks: "Ez a típus használható lekérése vagy beállítása, hogy a gyorsítótár, vagy tömörítés engedélyezve van a szerelvényben erőforrásként beágyazott ECMAScript (JavaScript) fájlok."
  syntax:
    content: 'public sealed class ScriptingScriptResourceHandlerSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  langs:
  - csharp
  name: ScriptingScriptResourceHandlerSection()
  nameWithType: ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection()
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.ScriptingScriptResourceHandlerSection&quot;> </xref> osztály."
  syntax:
    content: public ScriptingScriptResourceHandlerSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
  id: EnableCaching
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  langs:
  - csharp
  name: EnableCaching
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCaching
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja, hogy a gyorsítótár engedélyezve van a szerelvényben erőforrásként beágyazott parancsfájlok."
  remarks: "A EnableCaching tulajdonság lekérdezi vagy beállítja az értéket, az eredmények a beágyazott parancsfájl gyorsítótárazása, minden lehetséges honosítási objektumok gyorsítótárazása és parancsfájlok gyorsítótárazása."
  syntax:
    content: public bool EnableCaching { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a gyorsítótár engedélyezve van a szerelvényben; erőforrásként beágyazott parancsfájlok Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
  id: EnableCompression
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  langs:
  - csharp
  name: EnableCompression
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCompression
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja, hogy a parancsfájlok a szerelvények erőforrásként beágyazott tömörítését engedélyezték-e."
  remarks: "A EnableCompression tulajdonság lekérdezi vagy beállítja az értéket, amely jelzi, hogy a következő tömörítése:-parancsfájl-erőforrásként a szerelvények beágyazott fájlok.      -Honosítási objektumok, például az erőforrásfájl (.resx kiterjesztésű) található erőforrásait.      -A parancsfájl erőforrás-kezelő által szolgáltatott parancsfájlok.      > [!NOTE] > A kérést küldő böngésző nem támogatja a tömörítést, ha ez a tulajdonság nincs hatása."
  syntax:
    content: public bool EnableCompression { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a parancsfájlok a szerelvények; erőforrásként beágyazott tömörítését engedélyezték Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingScriptResourceHandlerSection.Properties
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: ScriptingScriptResourceHandlerSection()
  nameWithType: ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection()
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection()
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: EnableCaching
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCaching
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: EnableCompression
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCompression
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingScriptResourceHandlerSection.Properties
  fullName: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.#ctor*
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: ScriptingScriptResourceHandlerSection
  nameWithType: ScriptingScriptResourceHandlerSection.ScriptingScriptResourceHandlerSection
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCaching*
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: EnableCaching
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCaching
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.EnableCompression*
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: EnableCompression
  nameWithType: ScriptingScriptResourceHandlerSection.EnableCompression
- uid: System.Web.Configuration.ScriptingScriptResourceHandlerSection.Properties*
  parent: System.Web.Configuration.ScriptingScriptResourceHandlerSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingScriptResourceHandlerSection.Properties
