### YamlMime:ManagedReference
items:
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement
  id: IssuerNameRegistryElement
  children:
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  - System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  langs:
  - csharp
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement
  type: Class
  summary: "Jelöli egy <xref uid=&quot;langword_csharp_&lt;issuerNameRegistry&gt;&quot; name=&quot;&lt;issuerNameRegistry&gt;&quot; href=&quot;&quot;> </xref> egy konfigurációs fájlban. Ez az osztály nem örökölhető."
  remarks: "A `<issuerNameRegistry>` elem konfigurálja a kibocsátó neve beállításjegyzék. A kibocsátó neve beállításjegyzék kibocsátó jogkivonatok van leképezve a karakterlánc nevét. A <xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A>tulajdonság (jelölő a `type` attribútum elem) állítható be olyan egyéni típusra regisztrálni.</xref:System.IdentityModel.Configuration.IssuerNameRegistryElement.Type%2A> Alapértelmezés szerint egy típusú <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>feltételezi.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>       A `<issuerNameRegistry>` elem adhatók meg a szolgáltatási szint alatt, a `<identityConfiguration>` elem vagy egy biztonsági jogkivonat-kezelő gyűjtemény a `<securityTokenHandlerConfiguration>` elemet. A `IssuerNameRegistry` tulajdonsága a <xref:System.IdentityModel.Configuration.IdentityConfigurationElement>osztály és a <xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement>osztály a példánya: IssuerNameRegistryElement.</xref:System.IdentityModel.Configuration.SecurityTokenHandlerConfigurationElement> </xref:System.IdentityModel.Configuration.IdentityConfigurationElement>"
  syntax:
    content: 'public sealed class IssuerNameRegistryElement : System.IdentityModel.Configuration.ConfigurationElementInterceptor'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ChildNodes
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.ElementAsXml
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.IdentityModel.Configuration.ConfigurationElementInterceptor.Reset(System.Configuration.ConfigurationElement)
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  id: '#ctor'
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
  type: Constructor
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.IdentityModel.Configuration.IssuerNameRegistryElement&quot;> </xref> osztály."
  syntax:
    content: public IssuerNameRegistryElement ();
    parameters: []
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  id: Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  id: Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  langs:
  - csharp
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  type: Property
  assemblies:
  - System.IdentityModel
  namespace: System.IdentityModel.Configuration
  summary: "Lekérdezi vagy beállítja a karakterlánc a <xref:System.Type>a kibocsátó neve beállításjegyzék.</xref:System.Type>"
  remarks: "Ez a tulajdonság opcionális. Megfelel a `type` attribútuma a `<issuerNameRegistry>` elemet. Ha nincs megadva, a tulajdonság értéke `null`, egyfajta <xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>feltételezi.</xref:System.IdentityModel.Tokens.ConfigurationBasedIssuerNameRegistry>"
  syntax:
    content: public string Type { get; set; }
    return:
      type: System.String
      description: "A karakterlánc-ábrázolása, a <xref:System.Type>a kibocsátó neve beállításjegyzék.</xref:System.Type> A típus kell származnia: a <xref href=&quot;System.IdentityModel.Tokens.IssuerNameRegistry&quot;> </xref> osztály."
  overload: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  exceptions: []
  platform:
  - net462
references:
- uid: System.IdentityModel.Configuration.ConfigurationElementInterceptor
  isExternal: false
  name: System.IdentityModel.Configuration.ConfigurationElementInterceptor
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement()
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement()
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.IssuerNameRegistryElement()
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
  fullName: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.#ctor*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: IssuerNameRegistryElement
  nameWithType: IssuerNameRegistryElement.IssuerNameRegistryElement
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Properties*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Properties
  nameWithType: IssuerNameRegistryElement.Properties
- uid: System.IdentityModel.Configuration.IssuerNameRegistryElement.Type*
  parent: System.IdentityModel.Configuration.IssuerNameRegistryElement
  isExternal: false
  name: Type
  nameWithType: IssuerNameRegistryElement.Type
