### YamlMime:ManagedReference
items:
- uid: System.Configuration.UserScopedSettingAttribute
  id: UserScopedSettingAttribute
  children:
  - System.Configuration.UserScopedSettingAttribute.#ctor
  langs:
  - csharp
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute
  fullName: System.Configuration.UserScopedSettingAttribute
  type: Class
  summary: "Meghatározza, hogy egy alkalmazás beállítások csoport vagy tulajdonság minden felhasználó az alkalmazások különböző értékeket tartalmazza. Ez az osztály nem örökölhető."
  remarks: "Alkalmazás tulajdonságai rendelkezik, amely alapul, vagy az alkalmazás vagy a felhasználói szintű hatókörrel. Mivel a kategóriák utalnak, alkalmazásokra kiterjedő hatókörű tulajdonságok bevezetését a egységes értékek az alkalmazás minden felhasználó mivel felhasználói hatókörbe tartozó tulajdonságok értékeit az alkalmazás minden felhasználó dedikált.       A UserScopedSettingAttribute tulajdonság azt jelzi, hogy a tulajdonság érdemes figyelembe venni a felhasználói beállítás, és hogy megfelelő tároló-szempontjait ennek megfelelően kell tenni a beállítások szolgáltató.       Egy hatókör attribútum mindegyik alkalmazás beállítások tulajdonság esetén. Ha egy tulajdonság nem alkalmazható sem a <xref:System.Configuration.ApplicationScopedSettingAttribute>vagy UserScopedSettingAttribute attribútum, a tulajdonság a rendszer figyelmen kívül hagyja a beállítások szolgáltató – a rendszer nem szerializálja.</xref:System.Configuration.ApplicationScopedSettingAttribute> Érvénytelen, azonban az attribútumok alkalmazandó beállításokat ugyanahhoz a tulajdonsághoz. Ilyen kísérlet hatására a <xref:System.Configuration.ConfigurationErrorsException>jelezni, hogy.</xref:System.Configuration.ConfigurationErrorsException>"
  example:
  - "The following code example demonstrates the use of the UserScopedSettingAttribute applied to all four properties of the `FormSettings` wrapper class, which is derived from the <xref:System.Configuration.ApplicationSettingsBase> class. This class is used to persist the location, size, background color, and text of form. The full code example is listed in the <xref:System.Configuration.ApplicationSettingsBase> class overview.  \n  \n [!code-cpp[AppSettingsSample#9](~/add/codesnippet/cpp/t-system.configuration.u_1.cpp)]\n [!code-cs[AppSettingsSample#9](~/add/codesnippet/csharp/t-system.configuration.u_1.cs)]\n [!code-vb[AppSettingsSample#9](~/add/codesnippet/visualbasic/AppSettingsSample/Form1.vb#9)]"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Property)]

      public sealed class UserScopedSettingAttribute : System.Configuration.SettingAttribute
  inheritance:
  - System.Attribute
  - System.Configuration.SettingAttribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  id: '#ctor'
  parent: System.Configuration.UserScopedSettingAttribute
  langs:
  - csharp
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.UserScopedSettingAttribute&quot;> </xref> osztály."
  remarks: "Minden alkalmazás beállítások tulajdonság ahhoz, hogy felismerik és a beállítások szolgáltató szerializálni a hatókörre attribútummal kell alkalmazni."
  syntax:
    content: public UserScopedSettingAttribute ();
    parameters: []
  overload: System.Configuration.UserScopedSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.SettingAttribute
  isExternal: false
  name: System.Configuration.SettingAttribute
- uid: System.Configuration.UserScopedSettingAttribute.#ctor
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute()
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute()
  fullName: System.Configuration.UserScopedSettingAttribute.UserScopedSettingAttribute()
- uid: System.Configuration.UserScopedSettingAttribute.#ctor*
  parent: System.Configuration.UserScopedSettingAttribute
  isExternal: false
  name: UserScopedSettingAttribute
  nameWithType: UserScopedSettingAttribute.UserScopedSettingAttribute
