### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.CheckForUpdateCompletedEventHandler
  id: CheckForUpdateCompletedEventHandler
  langs:
  - csharp
  name: CheckForUpdateCompletedEventHandler
  nameWithType: CheckForUpdateCompletedEventHandler
  fullName: System.Deployment.Application.CheckForUpdateCompletedEventHandler
  type: Delegate
  summary: "A kezelő mód a <xref href=&quot;System.Deployment.Application.ApplicationDeployment.CheckForUpdateCompleted&quot;> </xref> az esemény egy <xref href=&quot;System.Deployment.Application.ApplicationDeployment&quot;> </xref>."
  remarks: 'Egy CheckForUpdateCompletedEventHandler delegált létrehozásakor meg kell adnia a módszert, amelyet az esemény fogja kezelni. Az esemény társítja a eseménykezelő, vegye fel a küldött példányának az esemény. Az eseménykezelő nevezzük az esemény akkor következik be, amikor kivéve, ha törli a delegált. Eseménykezelő meghatalmazottak kapcsolatos további információkért lásd: [NIB: események és -Delegáltaknak](http://msdn.microsoft.com/en-us/d98fd58b-fa4f-4598-8378-addf4355a115).'
  syntax:
    content: public delegate void CheckForUpdateCompletedEventHandler(object sender, CheckForUpdateCompletedEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
