### YamlMime:ManagedReference
items:
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup
  id: CachingSectionGroup
  children:
  - System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  - System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  langs:
  - csharp
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup
  type: Class
  summary: "Meghatározza, hogy a konfigurációs szakasz for.NET keretrendszer gyorsítótárazás. Ez az osztály nem örökölhető."
  remarks: "A CachingSectionGroup osztály gyorsítótárazási szakaszban határozza meg (`system.runtime.caching`) a konfigurációs fájlok. Ebben a szakaszban konfigurálhatja a gyorsítótárak különböző típusú elemet tartalmaz. Az ASP.NET az csak a gyorsítótárazási szakaszában érhető elem elemhez. Ez az elem <xref:System.Runtime.Caching.MemoryCache>osztály</xref:System.Runtime.Caching.MemoryCache> alapuló gyorsítótárak konfigurálása"
  syntax:
    content: 'public sealed class CachingSectionGroup : System.Configuration.ConfigurationSectionGroup'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationSectionGroup
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration
  - System.Configuration.ConfigurationSectionGroup.ForceDeclaration(System.Boolean)
  - System.Configuration.ConfigurationSectionGroup.IsDeclarationRequired
  - System.Configuration.ConfigurationSectionGroup.IsDeclared
  - System.Configuration.ConfigurationSectionGroup.Name
  - System.Configuration.ConfigurationSectionGroup.SectionGroupName
  - System.Configuration.ConfigurationSectionGroup.SectionGroups
  - System.Configuration.ConfigurationSectionGroup.Sections
  - System.Configuration.ConfigurationSectionGroup.ShouldSerializeSectionGroupInTargetVersion(System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSectionGroup.Type
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  id: '#ctor'
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
  type: Constructor
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Runtime.Caching.Configuration.CachingSectionGroup&quot;> </xref> osztály."
  syntax:
    content: public CachingSectionGroup ();
    parameters: []
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  id: MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  langs:
  - csharp
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  type: Property
  assemblies:
  - System.Runtime.Caching
  namespace: System.Runtime.Caching.Configuration
  summary: "Lekérdezi a gyűjteménye <xref href=&quot;System.Runtime.Caching.Configuration.MemoryCacheElement&quot;> </xref> objektumok."
  remarks: "A MemoryCaches tulajdonság gyűjteményét adja vissza <xref:System.Runtime.Caching.Configuration.MemoryCacheSection>objektumok gyorsítótárazását a szakasz a fölérendelt.</xref:System.Runtime.Caching.Configuration.MemoryCacheSection>"
  syntax:
    content: public System.Runtime.Caching.Configuration.MemoryCacheSection MemoryCaches { get; }
    return:
      type: System.Runtime.Caching.Configuration.MemoryCacheSection
      description: "Gyorsítótár-szakasz objektumok gyűjteménye."
  overload: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSectionGroup
  isExternal: false
  name: System.Configuration.ConfigurationSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup()
  nameWithType: CachingSectionGroup.CachingSectionGroup()
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.CachingSectionGroup()
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
  fullName: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches
- uid: System.Runtime.Caching.Configuration.MemoryCacheSection
  parent: System.Runtime.Caching.Configuration
  isExternal: false
  name: MemoryCacheSection
  nameWithType: MemoryCacheSection
  fullName: System.Runtime.Caching.Configuration.MemoryCacheSection
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.#ctor*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: CachingSectionGroup
  nameWithType: CachingSectionGroup.CachingSectionGroup
- uid: System.Runtime.Caching.Configuration.CachingSectionGroup.MemoryCaches*
  parent: System.Runtime.Caching.Configuration.CachingSectionGroup
  isExternal: false
  name: MemoryCaches
  nameWithType: CachingSectionGroup.MemoryCaches
