### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.UnicodeDecodingConformance
  id: UnicodeDecodingConformance
  children:
  - System.Net.Configuration.UnicodeDecodingConformance.Auto
  - System.Net.Configuration.UnicodeDecodingConformance.Compat
  - System.Net.Configuration.UnicodeDecodingConformance.Loose
  - System.Net.Configuration.UnicodeDecodingConformance.Strict
  langs:
  - csharp
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
  type: Enum
  summary: "Meghatározza, hogyan Unicode-karaktereket értelmezik a <xref:System.Net.WebUtility.HtmlDecode*>módszerek.</xref:System.Net.WebUtility.HtmlDecode*>"
  remarks: "További információ a Unicode-karaktereket elvileg hogyan HTML kódolni,: [karakter használatával lehet kilépni markup és CSS](http://go.microsoft.com/fwlink/?LinkId=256607)."
  syntax:
    content: public enum UnicodeDecodingConformance
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  id: Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Használja az automatikus műveletekkel. Aktuális alkalmazás cél keretrendszer dekódolási viselkedését határozza meg. A [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)] , és később, a Unicode kódolási dekódolás szigorú."
  syntax:
    content: Auto
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  id: Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Kompatibilis viselkedés használja. Meghatározza, hogy a bejövő adatok nem lesz ellenőrizve érvényességi alatt dekódolni előtt. Például egy bemeneti karakterlánc &quot;&amp;amp; #xD84C;&quot; U + D84C, amely egy párosítatlan helyettesítő, akkor dekódolására. Emellett a dekóder nem érti az Állapotáttelepítési pontok kód kivéve, ha azok még jelenik meg HTML-kódolású helyettesek, ezért a inputstring &quot;&amp;#144308;&quot; a kimeneti karakterláncban eredményezne &quot;&amp;#144308;&quot;."
  syntax:
    content: Compat
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  id: Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Használjon laza viselkedését. Hasonló/Compat abban, hogy nincsenek érvényességi ellenőrizve, de a dekóder is együttműködik a kódpontokat. A bemeneti karakterlánc &quot;&amp;#144308;&quot; volna az a karakter U +&233;B4 megfelelően dekódolására. Ez a kapcsoló arra szolgál, hogy maximális együttműködési biztosíthat, amikor a dekóder nem ismeri a kódolású karakterlánc létrehozásához használja a szolgáltató formátumot."
  syntax:
    content: Loose
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  id: Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  langs:
  - csharp
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
  type: Field
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Használja a szigorú viselkedését. Meghatározza, hogy a bejövő kódolt adatok be van jelölve érvényességét alatt dekódolni előtt. Például egy bemeneti karakterlánc &quot;&amp;#144308;&quot; U +&233;B4, de egy bemeneti karakterlánc volna dekódolása &quot;&amp;#xD84C;&amp; #xDFB4;&quot;megfelelően dekódolás sikertelen lesz. Adatok már dekódolni a karakterláncban nem érvényességének ellenőrzése. Például egy &quot;\\ud800&quot; bemeneti karakterlánc eredményezi egy kimeneti karakterlánc &quot;\\ud800&quot;, mivel az már dekódolni helyettesítő átugorja dekódolás, akkor is, ha párosítatlan."
  syntax:
    content: Strict
    return:
      type: System.Net.Configuration.UnicodeDecodingConformance
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Net.Configuration.UnicodeDecodingConformance.Auto
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Auto
  nameWithType: UnicodeDecodingConformance.Auto
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Auto
- uid: System.Net.Configuration.UnicodeDecodingConformance
  parent: System.Net.Configuration
  isExternal: false
  name: UnicodeDecodingConformance
  nameWithType: UnicodeDecodingConformance
  fullName: System.Net.Configuration.UnicodeDecodingConformance
- uid: System.Net.Configuration.UnicodeDecodingConformance.Compat
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Compat
  nameWithType: UnicodeDecodingConformance.Compat
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Compat
- uid: System.Net.Configuration.UnicodeDecodingConformance.Loose
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Loose
  nameWithType: UnicodeDecodingConformance.Loose
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Loose
- uid: System.Net.Configuration.UnicodeDecodingConformance.Strict
  parent: System.Net.Configuration.UnicodeDecodingConformance
  isExternal: false
  name: Strict
  nameWithType: UnicodeDecodingConformance.Strict
  fullName: System.Net.Configuration.UnicodeDecodingConformance.Strict
