### YamlMime:ManagedReference
items:
- uid: System.Configuration.Provider.ProviderBase
  id: ProviderBase
  children:
  - System.Configuration.Provider.ProviderBase.#ctor
  - System.Configuration.Provider.ProviderBase.Description
  - System.Configuration.Provider.ProviderBase.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  - System.Configuration.Provider.ProviderBase.Name
  langs:
  - csharp
  name: ProviderBase
  nameWithType: ProviderBase
  fullName: System.Configuration.Provider.ProviderBase
  type: Class
  summary: "Biztosítja a bővíthető szolgáltatói modell egy alapszintű megvalósítás."
  remarks: "A szolgáltatói modell célja a több ASP.NET-szolgáltatások, például a tagság, profilok és védett konfigurációs funkciók egy része vagy egésze foglalják magukban. Lehetővé teszi a fejlesztői többféle megvalósítása a beágyazott funkciókat biztosító támogató osztályokat hozhatnak létre. A fejlesztők továbbá írhat az új funkciók a szolgáltatói modell. Ez lehet a szolgáltatás funkcióinak többféle megvalósítása támogatása nélkül másolása a szolgáltatást kód vagy az alkalmazási rétegre újraprogramozás, ha módosítani kell a végrehajtási metódus hatékony módot.       A ProviderBase osztály használata egyszerű, csak néhány alapvető módszerek és a Tulajdonságok vonatkozó összes szolgáltató tartalmazó. Szolgáltatás-specifikus szolgáltatók (például <xref:System.Web.Security.MembershipProvider>) ProviderBase öröklik, és a szükséges módszereket és támogatnia kell a szolgáltatáshoz tartozó függő szolgáltatók tulajdonságokhoz.</xref:System.Web.Security.MembershipProvider> Függő szolgáltatók (például <xref:System.Web.Security.SqlMembershipProvider>) pedig örökli a funkcióspecifikus szolgáltató (ebben az esetben <xref:System.Web.Security.MembershipProvider>).</xref:System.Web.Security.MembershipProvider> </xref:System.Web.Security.SqlMembershipProvider>       A legfontosabb a szolgáltatói modell célja, hogy a megvalósítás (például, hogy adatokat is megőrződjenek szöveges fájlként, vagy egy adatbázisban) kiveszik, az alkalmazás kódból. A szolgáltató típusa mellett a függő az adott szolgáltatás számára a konfigurációs fájlban van kijelölve. A szolgáltatás szintű szolgáltató majd a következő típusban: a konfigurációs fájlból olvassa be, és a szolgáltatás kód gyár kezeli. Az alkalmazás fejlesztőjének az alkalmazáskódban található a szolgáltatás osztályok használhatja. A megvalósítási típusa lecserélhető ki a konfigurációs fájlban, így nem kell újraírnia a a programot, hogy megfeleljen a különböző megvalósítási.       Az ASP.NET szolgáltatáshoz tartozó szolgáltatók a következők: többnyire absztrakt entitással egészült ki az adatok megőrzését megvalósításait szolgáltatások, mint a profilok vagy a tagság. Azonban ez a modell funkcióhoz, amely képes azért és többféle módon végrehajtott bármilyen más típusú alkalmazhatók."
  example:
  - For an example of how to use the ProviderBase class, see [Profile Provider Implementation Example](~/add/includes/ajax-current-ext-md.md).
  syntax:
    content: public abstract class ProviderBase
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderBase.#ctor
  id: '#ctor'
  parent: System.Configuration.Provider.ProviderBase
  langs:
  - csharp
  name: ProviderBase()
  nameWithType: ProviderBase.ProviderBase()
  fullName: System.Configuration.Provider.ProviderBase.ProviderBase()
  type: Constructor
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.Provider.ProviderBase&quot;> </xref> osztály."
  syntax:
    content: protected ProviderBase ();
    parameters: []
  overload: System.Configuration.Provider.ProviderBase.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderBase.Description
  id: Description
  parent: System.Configuration.Provider.ProviderBase
  langs:
  - csharp
  name: Description
  nameWithType: ProviderBase.Description
  fullName: System.Configuration.Provider.ProviderBase.Description
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Lekérdezi a felügyeleti eszközök vagy más felhasználói felületek (UI) megjelenítéshez megfelelő rövid, rövid leírását."
  remarks: "Ha egy konfigurált szolgáltató nem adja meg egy leírást, értékét a <xref:System.Configuration.Provider.ProviderBase.Name%2A>tulajdonság alapértelmezett adja vissza.</xref:System.Configuration.Provider.ProviderBase.Name%2A>"
  syntax:
    content: public virtual string Description { get; }
    return:
      type: System.String
      description: "A felügyeleti eszközök vagy más UI megjelenítéshez megfelelő rövid, könnyen megjegyezhető leírása."
  overload: System.Configuration.Provider.ProviderBase.Description*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderBase.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  id: Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.Provider.ProviderBase
  langs:
  - csharp
  name: Initialize(String,NameValueCollection)
  nameWithType: ProviderBase.Initialize(String,NameValueCollection)
  fullName: System.Configuration.Provider.ProviderBase.Initialize(String,NameValueCollection)
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "A szolgáltató inicializálása."
  remarks: "Alaposztály végrehajtása belső nyomon követi az a szám, ahányszor a szolgáltató `Initialize` metódus meghívása. Ha egy szolgáltató egynél többször inicializálva van-e egy `InvalidOperationException` vált ki, amely meghatározza, hogy a szolgáltató már inicializálva van.       Legtöbb szolgáltatás szolgáltatók hívás végrehajtása szolgáltatói inicializálása előtt inicializálni, mert ez a módszer egy központi helyen, a dupla inicializálási megakadályozza."
  example:
  - For an example of how to use Initialize, see [Profile Provider Implementation Example](~/add/includes/ajax-current-ext-md.md).
  syntax:
    content: public virtual void Initialize (string name, System.Collections.Specialized.NameValueCollection config);
    parameters:
    - id: name
      type: System.String
      description: "A szolgáltató valódi neve."
    - id: config
      type: System.Collections.Specialized.NameValueCollection
      description: "A szolgáltatói attribútumainak a szolgáltató a konfigurációban megadott megfelelő név/érték párok gyűjteménye."
  overload: System.Configuration.Provider.ProviderBase.Initialize*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "A szolgáltató neve nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  - type: System.ArgumentException
    commentId: T:System.ArgumentException
    description: "A szolgáltató neve van nulla hosszúságú."
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Kísérlet kell hívnia az Initialize metódust egy szolgáltatót, miután a szolgáltató inicializálása már megtörtént."
  platform:
  - net462
- uid: System.Configuration.Provider.ProviderBase.Name
  id: Name
  parent: System.Configuration.Provider.ProviderBase
  langs:
  - csharp
  name: Name
  nameWithType: ProviderBase.Name
  fullName: System.Configuration.Provider.ProviderBase.Name
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration.Provider
  summary: "Lekérdezi a rövid nevet használt a szolgáltató konfigurálása során."
  remarks: 'A javasolt minta a karakterláncot: [*szolgáltató létrehozó*] [*megvalósítási típusa*] [*szolgáltatás*] szolgáltató. Bár a <xref:System.Configuration.Provider.ProviderBase.Description%2A>tulajdonság is rövid leírását tartalmazza, a szolgáltató azonosítóként szolgál a Name tulajdonság.</xref:System.Configuration.Provider.ProviderBase.Description%2A>'
  syntax:
    content: public virtual string Name { get; }
    return:
      type: System.String
      description: "A szolgáltató konfigurálása során hivatkozik rövid nevét."
  overload: System.Configuration.Provider.ProviderBase.Name*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.ArgumentException
  isExternal: true
  name: System.ArgumentException
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.Configuration.Provider.ProviderBase.#ctor
  parent: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: ProviderBase()
  nameWithType: ProviderBase.ProviderBase()
  fullName: System.Configuration.Provider.ProviderBase.ProviderBase()
- uid: System.Configuration.Provider.ProviderBase.Description
  parent: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: Description
  nameWithType: ProviderBase.Description
  fullName: System.Configuration.Provider.ProviderBase.Description
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.Provider.ProviderBase.Initialize(System.String,System.Collections.Specialized.NameValueCollection)
  parent: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: Initialize(String,NameValueCollection)
  nameWithType: ProviderBase.Initialize(String,NameValueCollection)
  fullName: System.Configuration.Provider.ProviderBase.Initialize(String,NameValueCollection)
- uid: System.Collections.Specialized.NameValueCollection
  parent: System.Collections.Specialized
  isExternal: false
  name: NameValueCollection
  nameWithType: NameValueCollection
  fullName: System.Collections.Specialized.NameValueCollection
- uid: System.Configuration.Provider.ProviderBase.Name
  parent: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: Name
  nameWithType: ProviderBase.Name
  fullName: System.Configuration.Provider.ProviderBase.Name
- uid: System.Configuration.Provider.ProviderBase.#ctor*
  parent: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: ProviderBase
  nameWithType: ProviderBase.ProviderBase
- uid: System.Configuration.Provider.ProviderBase.Description*
  parent: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: Description
  nameWithType: ProviderBase.Description
- uid: System.Configuration.Provider.ProviderBase.Initialize*
  parent: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: Initialize
  nameWithType: ProviderBase.Initialize
- uid: System.Configuration.Provider.ProviderBase.Name*
  parent: System.Configuration.Provider.ProviderBase
  isExternal: false
  name: Name
  nameWithType: ProviderBase.Name
