### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig
  id: ClientRemotingConfig
  children:
  - System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  - System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  langs:
  - csharp
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig
  type: Class
  summary: "Határozza meg a statikus <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>módszer, amely létrehoz egy ügyfél távoli eljáráshívási konfigurációs fájlt az ügyfél típustárba.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write*>"
  remarks: "A <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>metódust használja a <xref:System.EnterpriseServices.Internal.Publish>osztály egy COM-illesztőfelület egy ügyfél típustárból (.tlb kiterjesztésű) létrehozása közben.</xref:System.EnterpriseServices.Internal.Publish> </xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> A <xref:System.EnterpriseServices.Internal.Publish>osztály egy SOAP-kompatibilis COM + alkalmazás tesz közzé COM-felületek.</xref:System.EnterpriseServices.Internal.Publish> A metódusok paramétereihez egyik egy közös nyelvi futtatókörnyezet (CLR) metaadatokat tartalmazó szerelvény neve, amely <xref:System.EnterpriseServices.Internal.Publish>már generált ügyfél típustár.</xref:System.EnterpriseServices.Internal.Publish>       <xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A>nem hívható közvetlenül kell.</xref:System.EnterpriseServices.Internal.ClientRemotingConfig.Write%2A> Ehelyett hívja meg az <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A> <xref:System.EnterpriseServices.Internal.Publish>osztály</xref:System.EnterpriseServices.Internal.Publish> metódusában</xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       ClientRemotingConfig a .NET-keretrendszer belsőleg használja. Nem szeretné használni az osztály a kódban közvetlenül."
  syntax:
    content: public class ClientRemotingConfig
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.EnterpriseServices.Internal.ClientRemotingConfig&quot;> </xref> osztály."
  syntax:
    content: public ClientRemotingConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  id: Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  langs:
  - csharp
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Létrehoz egy ügyfél távoli eljáráshívási konfigurációs fájlt az ügyfél típustárba SOAP-kompatibilis COM + alkalmazás."
  remarks: "A statikus írási metódust a <xref:System.EnterpriseServices.Internal.Publish>osztály egy COM-illesztőfelület egy ügyfél típustárból (.tlb kiterjesztésű) létrehozása közben.</xref:System.EnterpriseServices.Internal.Publish> A <xref:System.EnterpriseServices.Internal.Publish>osztály egy SOAP-kompatibilis COM + alkalmazás tesz közzé COM-felületek.</xref:System.EnterpriseServices.Internal.Publish>       Írási nem hívható közvetlenül kell. Ehelyett hívja meg az <xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A> <xref:System.EnterpriseServices.Internal.Publish>osztály</xref:System.EnterpriseServices.Internal.Publish> metódusában</xref:System.EnterpriseServices.Internal.Publish.ProcessClientTlb%2A>       A `BaseUrl` és `VRoot` paraméterértékek vannak összefűzéséhez (egy elválasztó az elérési útban, ha szükséges) űrlapon az ügyfélelemben `URL` attribútum értéke.       A `AssemblyName` paraméter meghatározza azt a CLR metaadatok tartalmazó szerelvény, amely <xref:System.EnterpriseServices.Internal.Publish>használatával a <xref:System.EnterpriseServices.Internal.GenerateMetadata>osztály, az ügyfél típustár már generált.</xref:System.EnterpriseServices.Internal.GenerateMetadata> </xref:System.EnterpriseServices.Internal.Publish>"
  syntax:
    content: public static bool Write (string DestinationDirectory, string VRoot, string BaseUrl, string AssemblyName, string TypeName, string ProgId, string Mode, string Transport);
    parameters:
    - id: DestinationDirectory
      type: System.String
      description: "A mappát, amelybe a konfigurációs fájl létrehozása."
    - id: VRoot
      type: System.String
      description: "A virtuális gyökér neve."
    - id: BaseUrl
      type: System.String
      description: "Az alap URL-címet, amely tartalmazza a virtuális gyökérkönyvtárat."
    - id: AssemblyName
      type: System.String
      description: "A közös nyelvi futtatókörnyezet (CLR) metaadatok típustár megfelelő tartalmazó szerelvény megjelenítendő nevét."
    - id: TypeName
      type: System.String
      description: "A típustár megfelelő CLR metaadatok tartalmazó szerelvény teljesen minősített neve."
    - id: ProgId
      type: System.String
      description: "Az osztály programozott azonosítóját."
    - id: Mode
      type: System.String
      description: "Az aktiválási mód."
    - id: Transport
      type: System.String
      description: "Nincs használatban. Adja meg <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> ehhez a paraméterhez."
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az ügyfél a távelérés konfigurációs fájl létrehozása sikerült; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig()
  nameWithType: ClientRemotingConfig.ClientRemotingConfig()
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.ClientRemotingConfig()
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write(String,String,String,String,String,String,String,String)
  nameWithType: ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ClientRemotingConfig.Write(String,String,String,String,String,String,String,String)
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: ClientRemotingConfig
  nameWithType: ClientRemotingConfig.ClientRemotingConfig
- uid: System.EnterpriseServices.Internal.ClientRemotingConfig.Write*
  parent: System.EnterpriseServices.Internal.ClientRemotingConfig
  isExternal: false
  name: Write
  nameWithType: ClientRemotingConfig.Write
