### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  id: PeerCustomResolverSettings
  children:
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  - System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  langs:
  - csharp
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  type: Class
  summary: "A meghatározott egyéni társ feloldó szolgáltatás példányának beállításait tartalmazza."
  remarks: "Ilyen típusú egyéni társ feloldó szolgáltatás, beleértve a szolgáltatás és bármely adott kötési beállításokat a társ végpontcím az alapszintű beállításokat határoz meg. Ezek a beállítások általában végrehajtva a <xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A>tulajdonság.</xref:System.ServiceModel.PeerResolvers.PeerResolverSettings.Custom%2A>"
  syntax:
    content: public class PeerCustomResolverSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.PeerResolvers.PeerCustomResolverSettings&quot;> </xref> osztály."
  syntax:
    content: public PeerCustomResolverSettings ();
    parameters: []
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  id: Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Lekérdezi vagy beállítja az egyéni társ feloldó szolgáltatást tartalmazó társcsomópont a végpont címét."
  syntax:
    content: public System.ServiceModel.EndpointAddress Address { get; set; }
    return:
      type: System.ServiceModel.EndpointAddress
      description: "<xref:System.ServiceModel.EndpointAddress>az egyéni társ feloldó szolgáltatást futtató társcsomópont végpont címét tartalmazza, amelyek.</xref:System.ServiceModel.EndpointAddress>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  id: Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Lekérdezi vagy beállítja a csatornakötés, az egyéni társ feloldó szolgáltatás által használt."
  remarks: "Ennek a kötési elemnek az ügyfél és a szolgáltatás csatorna figyelőként egy csatornagyár épülő előírásának biztosít. A beépített csatorna csatornák az egyéni társ feloldó szolgáltatás előállítására szolgál."
  syntax:
    content: public System.ServiceModel.Channels.Binding Binding { get; set; }
    return:
      type: System.ServiceModel.Channels.Binding
      description: "<xref:System.ServiceModel.Channels.Binding>amely tartalmazza ezt a szolgáltatást a kötési beállításokat.</xref:System.ServiceModel.Channels.Binding>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  id: IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Lekérdezi e a <xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>tulajdonság értéke.</xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>"
  syntax:
    content: public bool IsBindingSpecified { get; }
    return:
      type: System.Boolean
      description: "Értéke TRUE, ha a <xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>tulajdonság beállítva; hamis értéket, ha nem.</xref:System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*>"
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  id: Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  langs:
  - csharp
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.PeerResolvers
  summary: "Lekérdezi vagy beállítja az egyéni társ feloldó példány ezt a szolgáltatást."
  syntax:
    content: public System.ServiceModel.PeerResolver Resolver { get; set; }
    return:
      type: System.ServiceModel.PeerResolver
      description: "<xref href=&quot;System.ServiceModel.PeerResolver&quot;></xref>a szolgáltatás által használt példány."
  overload: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings()
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings()
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.PeerCustomResolverSettings()
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address
- uid: System.ServiceModel.EndpointAddress
  parent: System.ServiceModel
  isExternal: true
  name: EndpointAddress
  nameWithType: EndpointAddress
  fullName: System.ServiceModel.EndpointAddress
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.Channels.Binding
  parent: System.ServiceModel.Channels
  isExternal: true
  name: Binding
  nameWithType: Binding
  fullName: System.ServiceModel.Channels.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
  fullName: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver
- uid: System.ServiceModel.PeerResolver
  parent: System.ServiceModel
  isExternal: false
  name: PeerResolver
  nameWithType: PeerResolver
  fullName: System.ServiceModel.PeerResolver
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.#ctor*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: PeerCustomResolverSettings
  nameWithType: PeerCustomResolverSettings.PeerCustomResolverSettings
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Address*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Address
  nameWithType: PeerCustomResolverSettings.Address
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Binding*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Binding
  nameWithType: PeerCustomResolverSettings.Binding
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.IsBindingSpecified*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: IsBindingSpecified
  nameWithType: PeerCustomResolverSettings.IsBindingSpecified
- uid: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings.Resolver*
  parent: System.ServiceModel.PeerResolvers.PeerCustomResolverSettings
  isExternal: false
  name: Resolver
  nameWithType: PeerCustomResolverSettings.Resolver
