### YamlMime:ManagedReference
items:
- uid: System.Configuration.SpecialSettingAttribute
  id: SpecialSettingAttribute
  children:
  - System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  - System.Configuration.SpecialSettingAttribute.SpecialSetting
  langs:
  - csharp
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute
  fullName: System.Configuration.SpecialSettingAttribute
  type: Class
  summary: "Azt jelzi, hogy az alkalmazás beállításainak tulajdonság egy különleges jelentőséggel bír. Ez az osztály nem örökölhető."
  remarks: "Egyes alkalmazás tulajdonságai rendelkezik egy különös jelentősége, amely megváltoztatja a módját, ahol a kapcsolódó beállításokat szolgáltató kell dolgozza fel őket. A SpecialSettingAttribute ilyen tulajdonságok azonosítására szolgál. Ez az osztály használja a <xref:System.Configuration.SpecialSetting?displayProperty=fullName>számbavételi jelzéséhez, hogy milyen speciális kategóriájú a tulajdonság tartozik.</xref:System.Configuration.SpecialSetting?displayProperty=fullName>       SpecialSettingAttribute csak akkor kell alkalmazni, a beállítások osztály vagy az egyéni beállítások tulajdonság.       Hogy beállítások szolgáltató hogyan kezelje a SpecialSettingAttribute a példát lásd: az <xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>a <xref:System.Configuration.LocalFileSettingsProvider>osztálytól</xref:System.Configuration.LocalFileSettingsProvider> metódusában</xref:System.Configuration.LocalFileSettingsProvider.GetPropertyValues%2A>"
  syntax:
    content: >-
      [System.AttributeUsage(System.AttributeTargets.Class | System.AttributeTargets.Property)]

      public sealed class SpecialSettingAttribute : Attribute
  inheritance:
  - System.Attribute
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  id: '#ctor(System.Configuration.SpecialSetting)'
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.SpecialSettingAttribute&quot;> </xref> osztály."
  syntax:
    content: public SpecialSettingAttribute (System.Configuration.SpecialSetting specialSetting);
    parameters:
    - id: specialSetting
      type: System.Configuration.SpecialSetting
      description: "A <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> számbavételi érték. a kategória az alkalmazás beállításainak tulajdonság meghatározása."
  overload: System.Configuration.SpecialSettingAttribute.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  id: SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  langs:
  - csharp
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi a leíró a speciális beállítás kategória az alkalmazás beállításainak tulajdonság értéke."
  remarks: "A SpecialSetting tulajdonsága <xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A>konstruktorának ezt az osztályt</xref:System.Configuration.SpecialSettingAttribute.%23ctor%2A> ."
  syntax:
    content: public System.Configuration.SpecialSetting SpecialSetting { get; }
    return:
      type: System.Configuration.SpecialSetting
      description: "A <xref href=&quot;System.Configuration.SpecialSetting&quot;> </xref> számbavételi érték. a kategória az alkalmazás beállításainak tulajdonság meghatározása."
  overload: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Attribute
  isExternal: false
  name: System.Attribute
- uid: System.Configuration.SpecialSettingAttribute.#ctor(System.Configuration.SpecialSetting)
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute(SpecialSetting)
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSettingAttribute(SpecialSetting)
- uid: System.Configuration.SpecialSetting
  parent: System.Configuration
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSetting
  fullName: System.Configuration.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
  fullName: System.Configuration.SpecialSettingAttribute.SpecialSetting
- uid: System.Configuration.SpecialSettingAttribute.#ctor*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSettingAttribute
  nameWithType: SpecialSettingAttribute.SpecialSettingAttribute
- uid: System.Configuration.SpecialSettingAttribute.SpecialSetting*
  parent: System.Configuration.SpecialSettingAttribute
  isExternal: false
  name: SpecialSetting
  nameWithType: SpecialSettingAttribute.SpecialSetting
