### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Activities.SendSettings
  id: SendSettings
  children:
  - System.ServiceModel.Activities.SendSettings.#ctor
  - System.ServiceModel.Activities.SendSettings.Endpoint
  - System.ServiceModel.Activities.SendSettings.EndpointAddress
  - System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
  - System.ServiceModel.Activities.SendSettings.IsOneWay
  - System.ServiceModel.Activities.SendSettings.OwnerDisplayName
  - System.ServiceModel.Activities.SendSettings.ProtectionLevel
  - System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
  - System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
  langs:
  - csharp
  name: SendSettings
  nameWithType: SendSettings
  fullName: System.ServiceModel.Activities.SendSettings
  type: Class
  summary: "Üzenet küldése tevékenység beállításait jelölik."
  syntax:
    content: public sealed class SendSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: SendSettings()
  nameWithType: SendSettings.SendSettings()
  fullName: System.ServiceModel.Activities.SendSettings.SendSettings()
  type: Constructor
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Activities.SendSettings&quot;> </xref> osztály."
  syntax:
    content: public SendSettings ();
    parameters: []
  overload: System.ServiceModel.Activities.SendSettings.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.Endpoint
  id: Endpoint
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: Endpoint
  nameWithType: SendSettings.Endpoint
  fullName: System.ServiceModel.Activities.SendSettings.Endpoint
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Lekérdezi vagy beállítja a végpont üzeneteket küld."
  syntax:
    content: public System.ServiceModel.Endpoint Endpoint { get; set; }
    return:
      type: System.ServiceModel.Endpoint
      description: "A végpont üzeneteket küld."
  overload: System.ServiceModel.Activities.SendSettings.Endpoint*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.EndpointAddress
  id: EndpointAddress
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: EndpointAddress
  nameWithType: SendSettings.EndpointAddress
  fullName: System.ServiceModel.Activities.SendSettings.EndpointAddress
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Lekérdezi vagy beállítja a cím a végpont üzeneteket küld."
  syntax:
    content: public Uri EndpointAddress { get; set; }
    return:
      type: System.Uri
      description: "A végpont címét."
  overload: System.ServiceModel.Activities.SendSettings.EndpointAddress*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
  id: EndpointConfigurationName
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: EndpointConfigurationName
  nameWithType: SendSettings.EndpointConfigurationName
  fullName: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Lekérdezi vagy beállítja a végpont-konfiguráció nevét."
  syntax:
    content: public string EndpointConfigurationName { get; set; }
    return:
      type: System.String
      description: "A végpont-konfiguráció nevét."
  overload: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.IsOneWay
  id: IsOneWay
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: IsOneWay
  nameWithType: SendSettings.IsOneWay
  fullName: System.ServiceModel.Activities.SendSettings.IsOneWay
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy kommunikációs egyirányú."
  syntax:
    content: public bool IsOneWay { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a kommunikációs egyirányú; <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref> kétirányú kommunikációs esetén."
  overload: System.ServiceModel.Activities.SendSettings.IsOneWay*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.OwnerDisplayName
  id: OwnerDisplayName
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: OwnerDisplayName
  nameWithType: SendSettings.OwnerDisplayName
  fullName: System.ServiceModel.Activities.SendSettings.OwnerDisplayName
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Lekérdezi vagy beállítja a tulajdonos megjelenítendő nevét."
  syntax:
    content: public string OwnerDisplayName { get; set; }
    return:
      type: System.String
      description: "A tulajdonos megjelenítendő nevét."
  overload: System.ServiceModel.Activities.SendSettings.OwnerDisplayName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.ProtectionLevel
  id: ProtectionLevel
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: ProtectionLevel
  nameWithType: SendSettings.ProtectionLevel
  fullName: System.ServiceModel.Activities.SendSettings.ProtectionLevel
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, az üzenet védelmi szint."
  syntax:
    content: public Nullable<System.Net.Security.ProtectionLevel> ProtectionLevel { get; set; }
    return:
      type: System.Nullable{System.Net.Security.ProtectionLevel}
      description: "A számbavétel értékeinek egyike a <xref href=&quot;System.Net.Security.ProtectionLevel&quot;> </xref> enumerálása."
  overload: System.ServiceModel.Activities.SendSettings.ProtectionLevel*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
  id: RequirePersistBeforeSend
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: RequirePersistBeforeSend
  nameWithType: SendSettings.RequirePersistBeforeSend
  fullName: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy a munkafolyamat-példányhoz kell őrizhető meg, az üzenet elküldése előtt."
  syntax:
    content: public bool RequirePersistBeforeSend { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a munkafolyamat-szolgáltatás kell őrizhető meg; az üzenet elküldése előtt Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
  id: TokenImpersonationLevel
  parent: System.ServiceModel.Activities.SendSettings
  langs:
  - csharp
  name: TokenImpersonationLevel
  nameWithType: SendSettings.TokenImpersonationLevel
  fullName: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
  type: Property
  assemblies:
  - System.ServiceModel.Activities
  namespace: System.ServiceModel.Activities
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy az üzenet címzettje token megszemélyesítési szint engedélyezett."
  syntax:
    content: public System.Security.Principal.TokenImpersonationLevel TokenImpersonationLevel { get; set; }
    return:
      type: System.Security.Principal.TokenImpersonationLevel
      description: "A számbavétel értékeinek egyike a <xref:System.Security.Principal.TokenImpersonationLevel>számbavételi.</xref:System.Security.Principal.TokenImpersonationLevel>"
  overload: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Activities.SendSettings.#ctor
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: SendSettings()
  nameWithType: SendSettings.SendSettings()
  fullName: System.ServiceModel.Activities.SendSettings.SendSettings()
- uid: System.ServiceModel.Activities.SendSettings.Endpoint
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: Endpoint
  nameWithType: SendSettings.Endpoint
  fullName: System.ServiceModel.Activities.SendSettings.Endpoint
- uid: System.ServiceModel.Endpoint
  parent: System.ServiceModel
  isExternal: false
  name: Endpoint
  nameWithType: Endpoint
  fullName: System.ServiceModel.Endpoint
- uid: System.ServiceModel.Activities.SendSettings.EndpointAddress
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: EndpointAddress
  nameWithType: SendSettings.EndpointAddress
  fullName: System.ServiceModel.Activities.SendSettings.EndpointAddress
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: EndpointConfigurationName
  nameWithType: SendSettings.EndpointConfigurationName
  fullName: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Activities.SendSettings.IsOneWay
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: IsOneWay
  nameWithType: SendSettings.IsOneWay
  fullName: System.ServiceModel.Activities.SendSettings.IsOneWay
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Activities.SendSettings.OwnerDisplayName
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: OwnerDisplayName
  nameWithType: SendSettings.OwnerDisplayName
  fullName: System.ServiceModel.Activities.SendSettings.OwnerDisplayName
- uid: System.ServiceModel.Activities.SendSettings.ProtectionLevel
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: ProtectionLevel
  nameWithType: SendSettings.ProtectionLevel
  fullName: System.ServiceModel.Activities.SendSettings.ProtectionLevel
- uid: System.Nullable{System.Net.Security.ProtectionLevel}
  parent: System
  isExternal: true
  name: Nullable<ProtectionLevel>
  nameWithType: Nullable<ProtectionLevel>
  fullName: System.Nullable<System.Net.Security.ProtectionLevel>
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: Nullable<System.Net.Security.ProtectionLevel>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Net.Security.ProtectionLevel
    name: ProtectionLevel
    nameWithType: ProtectionLevel
    fullName: ProtectionLevel
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: RequirePersistBeforeSend
  nameWithType: SendSettings.RequirePersistBeforeSend
  fullName: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend
- uid: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: TokenImpersonationLevel
  nameWithType: SendSettings.TokenImpersonationLevel
  fullName: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel
- uid: System.Security.Principal.TokenImpersonationLevel
  parent: System.Security.Principal
  isExternal: true
  name: TokenImpersonationLevel
  nameWithType: TokenImpersonationLevel
  fullName: System.Security.Principal.TokenImpersonationLevel
- uid: System.ServiceModel.Activities.SendSettings.#ctor*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: SendSettings
  nameWithType: SendSettings.SendSettings
- uid: System.ServiceModel.Activities.SendSettings.Endpoint*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: Endpoint
  nameWithType: SendSettings.Endpoint
- uid: System.ServiceModel.Activities.SendSettings.EndpointAddress*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: EndpointAddress
  nameWithType: SendSettings.EndpointAddress
- uid: System.ServiceModel.Activities.SendSettings.EndpointConfigurationName*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: EndpointConfigurationName
  nameWithType: SendSettings.EndpointConfigurationName
- uid: System.ServiceModel.Activities.SendSettings.IsOneWay*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: IsOneWay
  nameWithType: SendSettings.IsOneWay
- uid: System.ServiceModel.Activities.SendSettings.OwnerDisplayName*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: OwnerDisplayName
  nameWithType: SendSettings.OwnerDisplayName
- uid: System.ServiceModel.Activities.SendSettings.ProtectionLevel*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: ProtectionLevel
  nameWithType: SendSettings.ProtectionLevel
- uid: System.ServiceModel.Activities.SendSettings.RequirePersistBeforeSend*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: RequirePersistBeforeSend
  nameWithType: SendSettings.RequirePersistBeforeSend
- uid: System.ServiceModel.Activities.SendSettings.TokenImpersonationLevel*
  parent: System.ServiceModel.Activities.SendSettings
  isExternal: false
  name: TokenImpersonationLevel
  nameWithType: SendSettings.TokenImpersonationLevel
