### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsSavingEventHandler
  id: SettingsSavingEventHandler
  langs:
  - csharp
  name: SettingsSavingEventHandler
  nameWithType: SettingsSavingEventHandler
  fullName: System.Configuration.SettingsSavingEventHandler
  type: Delegate
  summary: "A kezelő mód a <xref href=&quot;System.Configuration.ApplicationSettingsBase.SettingsSaving&quot;> </xref> esemény."
  remarks: "Az <xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>esemény akkor következik be, beállítások megmaradnak, általában <xref:System.Configuration.ApplicationSettingsBase.Save%2A>egy burkoló osztály <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> származó metódus</xref:System.Configuration.ApplicationSettingsBase.Save%2A> végrehajtása során alkalmazás csoport előtt</xref:System.Configuration.ApplicationSettingsBase.SettingsSaving>"
  syntax:
    content: public delegate void SettingsSavingEventHandler(object sender, CancelEventArgs e);
  inheritance:
  - System.Delegate
  platform:
  - net462
references:
- uid: System.Delegate
  isExternal: false
  name: System.Delegate
