### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ScriptingJsonSerializationSection
  id: ScriptingJsonSerializationSection
  children:
  - System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  - System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  - System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  - System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  - System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  langs:
  - csharp
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection
  type: Class
  summary: "Jelöli egy <xref uid=&quot;langword_csharp_jsonSerialization&quot; name=&quot;jsonSerialization&quot; href=&quot;&quot;> </xref> konfigurációs szakasz a <xref uid=&quot;langword_csharp_scripting&quot; name=&quot;scripting&quot; href=&quot;&quot;> </xref> elemet a konfigurációs fájl. Ez az osztály nem örökölhető."
  remarks: "A ScriptingJsonSerializationSection osztály lehetővé teszi programozott módon hozzáférhet, és módosíthatja a `jsonSerialization` elemet a konfigurációs szakasz az ASP.NET AJAX-funkciójával.       Ez a típus szerializálási és konfigurációs értékeket az AJAX-kompatibilis alkalmazások deszerializálási használható."
  example:
  - "The following configuration file excerpt shows how to declaratively specify values for properties of the ScriptingJsonSerializationSection class.  \n  \n```  \n<system.web.extensions>  \n  <scripting>  \n    <webServices>  \n      <jsonSerialization maxJsonLength=\"1000\" />  \n    </webServices>  \n  </scripting>  \n</system.web.extensions>  \n```  \n  \n The following example demonstrates how to access ScriptingJsonSerializationSection programmatically.  \n  \n [!code-cs[System.Web.Configuration#3](~/add/codesnippet/csharp/t-system.web.configurati_75_1.cs)]\n [!code-vb[System.Web.Configuration#3](~/add/codesnippet/visualbasic/t-system.web.configurati_75_1.vb)]"
  syntax:
    content: 'public sealed class ScriptingJsonSerializationSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  id: '#ctor'
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: ScriptingJsonSerializationSection()
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  type: Constructor
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.ScriptingJsonSerializationSection&quot;> </xref> osztály."
  syntax:
    content: public ScriptingJsonSerializationSection ();
    parameters: []
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  id: Converters
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Lekérdezi a <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;> </xref> gyűjteményét tartalmazó objektum <xref href=&quot;System.Web.Configuration.Converter&quot;> </xref> objektumok."
  syntax:
    content: public System.Web.Configuration.ConvertersCollection Converters { get; }
    return:
      type: System.Web.Configuration.ConvertersCollection
      description: "A <xref href=&quot;System.Web.Configuration.ConvertersCollection&quot;></xref> object."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.Converters*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  id: MaxJsonLength
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja azt a maximális hossz, amelyet az elfogad az <xref href=&quot;System.Web.Script.Serialization.JavaScriptSerializer&quot;> </xref> JavaScript Object Notation (JSON) karakterláncok objektum."
  remarks: "A MaxJsonLength tulajdonság csak azokra az a belső <xref:System.Web.Script.Serialization.JavaScriptSerializer>példány webes meghívni az aszinkron kommunikációs réteg által használt szolgáltatások módszerek.</xref:System.Web.Script.Serialization.JavaScriptSerializer>"
  syntax:
    content: public int MaxJsonLength { get; set; }
    return:
      type: System.Int32
      description: "Egész szám, amely a JSON-karakterlánc maximális hosszát jelenti. Az alapértelmezett érték 102400 karaktereket."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  id: Properties
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  id: RecursionLimit
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  langs:
  - csharp
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.Configuration
  summary: "Lekérdezi vagy beállítja a korlát korlátozási feldolgozni objektum szintek számát."
  remarks: "A recursionlimit értéknek tulajdonság az objektum hierarchiájának maximális szintjét hivatkozik, amely <xref:System.Web.Script.Serialization.JavaScriptSerializer>dolgozza fel a JavaScript Object Notation (JSON) karakterlánc deszerializálása során, vagy ha egy objektum szerializálásakor.</xref:System.Web.Script.Serialization.JavaScriptSerializer>       A recursionlimit értéknek értékének érvényes csak a belső <xref:System.Web.Script.Serialization.JavaScriptSerializer>példány webes meghívni az aszinkron kommunikációs réteg által használt szolgáltatások módszerek.</xref:System.Web.Script.Serialization.JavaScriptSerializer>"
  syntax:
    content: public int RecursionLimit { get; set; }
    return:
      type: System.Int32
      description: "Objektum szintek száma. Az alapértelmezett érték 100."
  overload: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit*
  exceptions:
  - type: System.ArgumentOutOfRangeException
    commentId: T:System.ArgumentOutOfRangeException
    description: "A tulajdonság egy értéket, amely kisebb, mint állítják."
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.ArgumentOutOfRangeException
  isExternal: true
  name: System.ArgumentOutOfRangeException
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: ScriptingJsonSerializationSection()
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.ScriptingJsonSerializationSection()
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Converters
- uid: System.Web.Configuration.ConvertersCollection
  parent: System.Web.Configuration
  isExternal: false
  name: ConvertersCollection
  nameWithType: ConvertersCollection
  fullName: System.Web.Configuration.ConvertersCollection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
  fullName: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.#ctor*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: ScriptingJsonSerializationSection
  nameWithType: ScriptingJsonSerializationSection.ScriptingJsonSerializationSection
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Converters*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Converters
  nameWithType: ScriptingJsonSerializationSection.Converters
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.MaxJsonLength*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: MaxJsonLength
  nameWithType: ScriptingJsonSerializationSection.MaxJsonLength
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.Properties*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: Properties
  nameWithType: ScriptingJsonSerializationSection.Properties
- uid: System.Web.Configuration.ScriptingJsonSerializationSection.RecursionLimit*
  parent: System.Web.Configuration.ScriptingJsonSerializationSection
  isExternal: false
  name: RecursionLimit
  nameWithType: ScriptingJsonSerializationSection.RecursionLimit
