### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.UrlMapping
  id: UrlMapping
  children:
  - System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  - System.Web.Configuration.UrlMapping.MappedUrl
  - System.Web.Configuration.UrlMapping.Properties
  - System.Web.Configuration.UrlMapping.Url
  langs:
  - csharp
  name: UrlMapping
  nameWithType: UrlMapping
  fullName: System.Web.Configuration.UrlMapping
  type: Class
  summary: "A Maps egy URL-cím akkor jelenik meg, a felhasználók számára, egy lap a webes alkalmazás URL-címét. Ez az osztály nem örökölhető."
  remarks: "A UrlMapping osztály lehetővé teszi egy URL-cím akkor jelenik meg a felhasználóknak, hogy létezik-e a webes alkalmazás URL-címet hozzárendelni. UrlMapping objektum felvételére a <xref:System.Web.Configuration.UrlMappingCollection>többek között a programozott megfelelője az `add` eleme a `urlMappings` szakaszt egy konfigurációs fájl.</xref:System.Web.Configuration.UrlMappingCollection>       Az egyes UrlMapping objektumok azonosító URL-címet két tulajdonságait tartalmazza. Egy tulajdonság határozza meg az URL-címet, a felhasználó; a másik a webes alkalmazás URL-címet adja meg. Záró üres karaktereket is figyelmen kívül hagyja a <xref:System.Web.Configuration.UrlMapping.Url%2A>és <xref:System.Web.Configuration.UrlMapping.MappedUrl%2A>Tulajdonságok.</xref:System.Web.Configuration.UrlMapping.MappedUrl%2A> </xref:System.Web.Configuration.UrlMapping.Url%2A>      > [!NOTE] > A UrlMapping tulajdonság információt írhat a kapcsolódó szakaszba a konfigurációs fájl alapján határozzák meg a szakasz tulajdonság <xref:System.Configuration.SectionInformation.AllowDefinition%2A>értéke <xref:System.Configuration.ConfigurationAllowDefinition>.</xref:System.Configuration.ConfigurationAllowDefinition> </xref:System.Configuration.SectionInformation.AllowDefinition%2A> korlátozások Írja be a konfigurációs fájl nem engedélyezett a hierarchiában szinten tett bármilyen kísérlet az elemző által generált hibaüzenetet eredményez. Az osztály használatával, olvassa el a konfigurációs adatokat a hierarchia bármely szintjén."
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/csharp/t-system.web.configurati_10_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/visualbasic/t-system.web.configurati_10_2.aspx)]"
  syntax:
    content: 'public sealed class UrlMapping : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
  type: Constructor
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.Configuration.UrlMapping&quot;> </xref> osztály."
  remarks: "A UrlMapping konstruktor ASP.NET elsősorban belső használatra készült. Nem kell származnia ebből az osztályból származik, és a Web.config fájl használható, mert feltehetőleg soha nem kell kódot használatát."
  example:
  - "The following example uses the <xref:System.Web.Configuration.UrlMappingsSection> of the Web.config file to map two URLs, and adds a mapping for an additional URL. When you modify and save the Web.config file, your application restarts.  \n  \n [!code-cs[XpsCreate#XpsCreateAddPkgContent](~/add/codesnippet/csharp/XpsCreate/XpsCreate.cs#xpscreateaddpkgcontent)]  \n[!code-cs[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/csharp/m-system.web.configurati_60_2.aspx)]\n[!code-vb[System.Web.Configuration.UrlMapping2#1](~/add/codesnippet/visualbasic/m-system.web.configurati_60_2.aspx)]"
  syntax:
    content: public UrlMapping (string url, string mappedUrl);
    parameters:
    - id: url
      type: System.String
      description: "A felhasználó számára megjelenő URL-címe"
    - id: mappedUrl
      type: System.String
      description: "Egy URL-cím már szerepel a webes alkalmazás."
  overload: System.Web.Configuration.UrlMapping.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  id: MappedUrl
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "A webes alkalmazás URL-címet."
  remarks: "A MappedUrl tulajdonság programozott megegyezik a a `mappedUrl` attribútuma a `add` eleme a `urlMappings` egy konfigurációs fájl részét.      > [!NOTE] > Használatakor az IIS 5.0-s, ha a MappedUrl tulajdonság nem támogatott típust (például az .asp oldal) (például egy .aspx fájl) egy támogatott típusra való leképezése hiba történik. Ez a leképezés típus az IIS 6.0-s verziója támogatott."
  example:
  - "The following code example shows how to obtain the MappedUrl property. This example is from a larger example for the <xref:System.Web.Configuration.UrlMapping> class.  \n  \n [!code-cs[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/csharp/p-system.web.configurati_113_1.aspx)]\n [!code-vb[System.Web.Configuration.UrlMapping2#4](~/add/codesnippet/visualbasic/p-system.web.configurati_113_1.aspx)]"
  syntax:
    content: public string MappedUrl { get; }
    return:
      type: System.String
      description: "A webes alkalmazás, amely által megadott értékre lett leképezve az URL-címet a <xref:System.Web.Configuration.UrlMapping.Url*>tulajdonság.</xref:System.Web.Configuration.UrlMapping.Url*>"
  overload: System.Web.Configuration.UrlMapping.MappedUrl*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.Properties
  id: Properties
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Web.Configuration.UrlMapping.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.UrlMapping.Url
  id: Url
  parent: System.Web.Configuration.UrlMapping
  langs:
  - csharp
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
  type: Property
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Lekérdezi a felhasználó számára megjelenített URL-CÍMÉT."
  remarks: "Az URL-cím tulajdonság programozott megegyezik a a `Url` attribútuma a `add` eleme a `urlMappings` egy konfigurációs fájl részét."
  example:
  - For an example, see the <xref:System.Web.Configuration.UrlMapping> class overview.
  syntax:
    content: public string Url { get; }
    return:
      type: System.String
      description: "A felhasználó számára megjelenített URL-címe."
  overload: System.Web.Configuration.UrlMapping.Url*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Web.Configuration.UrlMapping.#ctor(System.String,System.String)
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping(String,String)
  nameWithType: UrlMapping.UrlMapping(String,String)
  fullName: System.Web.Configuration.UrlMapping.UrlMapping(String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Configuration.UrlMapping.MappedUrl
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
  fullName: System.Web.Configuration.UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
  fullName: System.Web.Configuration.UrlMapping.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Web.Configuration.UrlMapping.Url
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
  fullName: System.Web.Configuration.UrlMapping.Url
- uid: System.Web.Configuration.UrlMapping.#ctor*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: UrlMapping
  nameWithType: UrlMapping.UrlMapping
- uid: System.Web.Configuration.UrlMapping.MappedUrl*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: MappedUrl
  nameWithType: UrlMapping.MappedUrl
- uid: System.Web.Configuration.UrlMapping.Properties*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Properties
  nameWithType: UrlMapping.Properties
- uid: System.Web.Configuration.UrlMapping.Url*
  parent: System.Web.Configuration.UrlMapping
  isExternal: false
  name: Url
  nameWithType: UrlMapping.Url
