### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.ProxyElement
  id: ProxyElement
  children:
  - System.Net.Configuration.ProxyElement.#ctor
  - System.Net.Configuration.ProxyElement.AutoDetect
  - System.Net.Configuration.ProxyElement.BypassOnLocal
  - System.Net.Configuration.ProxyElement.Properties
  - System.Net.Configuration.ProxyElement.ProxyAddress
  - System.Net.Configuration.ProxyElement.ScriptLocation
  - System.Net.Configuration.ProxyElement.UseSystemDefault
  langs:
  - csharp
  name: ProxyElement
  nameWithType: ProxyElement
  fullName: System.Net.Configuration.ProxyElement
  type: Class
  summary: "Azon webalkalmazás-proxy kiszolgáló konfigurációs beállításait. Ez az osztály nem örökölhető."
  remarks: "The following table shows the configuration attributes of the [\\&lt;proxy\\&gt; Element (Network Settings)](../Topic/%3Cproxy%3E%20Element%20\\(Network%20Settings\\).md) configuration element to which this class corresponds.  \n  \n|Element|Description|  \n|-------------|-----------------|  \n|`proxyaddress`|A URI that identifies the Web proxy server to use.|  \n|`bypassonlocal`|Determines whether the Web proxy is bypassed for local resources.|  \n|`usesystemdefault`|Controls whether the Internet Explorer Web proxy settings are used.|  \n|`useDefaultCredentialsForScriptDownload`|Controls whether default credentials are used when accessing the configuration script.|  \n|`scriptDownloadInterval`|Specifies the number of seconds that elapse before the configuration script is refreshed.|  \n|`scriptDownloadTimeout`|Specifies the number of seconds allowed for the configuration script to be downloaded.|  \n|`useDefaultCredentials`|Controls whether default credentials are used when accessing the Web proxy.|  \n  \n This class is used to specify and configure the Web proxy server to use for requests made with the <xref:System.Net.WebRequest> and <xref:System.Net.WebClient> classes.  \n  \n This class provides programmatic access to information that can be stored in configuration files."
  syntax:
    content: 'public sealed class ProxyElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ProxyElement()
  nameWithType: ProxyElement.ProxyElement()
  fullName: System.Net.Configuration.ProxyElement.ProxyElement()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Net.Configuration.ProxyElement&quot;> </xref> osztály."
  remarks: '-'
  syntax:
    content: public ProxyElement ();
    parameters: []
  overload: System.Net.Configuration.ProxyElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.AutoDetect
  id: AutoDetect
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: AutoDetect
  nameWithType: ProxyElement.AutoDetect
  fullName: System.Net.Configuration.ProxyElement.AutoDetect
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja az <xref:System.Net.Configuration.ProxyElement.AutoDetectValues>értéket, hogy szabályozza, hogy a webalkalmazás-proxy automatikusan észlelt.</xref:System.Net.Configuration.ProxyElement.AutoDetectValues>"
  syntax:
    content: public System.Net.Configuration.ProxyElement.AutoDetectValues AutoDetect { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.AutoDetectValues
      description: "<xref:System.Net.Configuration.ProxyElement.AutoDetectValues>Ha a <xref href=&quot;System.Net.WebProxy&quot;> </xref> automatikusan észlelt; <xref:System.Net.Configuration.ProxyElement.AutoDetectValues>Ha a <xref href=&quot;System.Net.WebProxy&quot;> </xref> nem észleli automatikusan; vagy <xref:System.Net.Configuration.ProxyElement.AutoDetectValues>.</xref:System.Net.Configuration.ProxyElement.AutoDetectValues> </xref:System.Net.Configuration.ProxyElement.AutoDetectValues></xref:System.Net.Configuration.ProxyElement.AutoDetectValues>"
  overload: System.Net.Configuration.ProxyElement.AutoDetect*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.BypassOnLocal
  id: BypassOnLocal
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: BypassOnLocal
  nameWithType: ProxyElement.BypassOnLocal
  fullName: System.Net.Configuration.ProxyElement.BypassOnLocal
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy a helyi erőforrások rendszer proxy-webkiszolgáló használatával beolvassa."
  remarks: "A konfigurációs elem szabályozza, hogy a hálózati erőforrásokra vonatkozó kéréseket a proxykiszolgálóhoz küldött vagy küldött közvetlenül a gazdagépre, amelyen az erőforrás található."
  syntax:
    content: public System.Net.Configuration.ProxyElement.BypassOnLocalValues BypassOnLocal { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.BypassOnLocalValues
      description: "A <xref:System.Net.Configuration.ProxyElement.BypassOnLocalValues>.</xref:System.Net.Configuration.ProxyElement.BypassOnLocalValues>       Amely jelzi, hogy a helyi erőforrások rendszer proxy-webkiszolgáló használatával beolvassa Avalue."
  overload: System.Net.Configuration.ProxyElement.BypassOnLocal*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.Properties
  id: Properties
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: Properties
  nameWithType: ProxyElement.Properties
  fullName: System.Net.Configuration.ProxyElement.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Net.Configuration.ProxyElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.ProxyAddress
  id: ProxyAddress
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ProxyAddress
  nameWithType: ProxyElement.ProxyAddress
  fullName: System.Net.Configuration.ProxyElement.ProxyAddress
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja az URI azonosító a webes proxykiszolgáló használatára."
  syntax:
    content: public Uri ProxyAddress { get; set; }
    return:
      type: System.Uri
      description: "A <xref:System.String>olyan URI.</xref:System.String>"
  overload: System.Net.Configuration.ProxyElement.ProxyAddress*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.ScriptLocation
  id: ScriptLocation
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: ScriptLocation
  nameWithType: ProxyElement.ScriptLocation
  fullName: System.Net.Configuration.ProxyElement.ScriptLocation
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja az <xref:System.Uri>érték, amely meghatározza az automatikus proxy észlelésének helyét parancsfájl</xref:System.Uri>"
  syntax:
    content: public Uri ScriptLocation { get; set; }
    return:
      type: System.Uri
      description: "A <xref:System.Uri>webhelyre a proxy automatikus észlelési parancsprogram</xref:System.Uri>"
  overload: System.Net.Configuration.ProxyElement.ScriptLocation*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.ProxyElement.UseSystemDefault
  id: UseSystemDefault
  parent: System.Net.Configuration.ProxyElement
  langs:
  - csharp
  name: UseSystemDefault
  nameWithType: ProxyElement.UseSystemDefault
  fullName: System.Net.Configuration.ProxyElement.UseSystemDefault
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja a <xref:System.Boolean>értéket, hogy szabályozza, hogy az Internet Explorer proxybeállítások vannak érvényben.</xref:System.Boolean>"
  syntax:
    content: public System.Net.Configuration.ProxyElement.UseSystemDefaultValues UseSystemDefault { get; set; }
    return:
      type: System.Net.Configuration.ProxyElement.UseSystemDefaultValues
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az Internet Explorer LAN-beállítások észlelésére, és adja meg az alapértelmezett használt <xref href=&quot;System.Net.WebProxy&quot;> </xref> használt kérelmek; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Net.Configuration.ProxyElement.UseSystemDefault*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.Net.Configuration.ProxyElement.#ctor
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyElement()
  nameWithType: ProxyElement.ProxyElement()
  fullName: System.Net.Configuration.ProxyElement.ProxyElement()
- uid: System.Net.Configuration.ProxyElement.AutoDetect
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: AutoDetect
  nameWithType: ProxyElement.AutoDetect
  fullName: System.Net.Configuration.ProxyElement.AutoDetect
- uid: System.Net.Configuration.ProxyElement.AutoDetectValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+AutoDetectValues
  nameWithType: ProxyElement+AutoDetectValues
  fullName: System.Net.Configuration.ProxyElement+AutoDetectValues
- uid: System.Net.Configuration.ProxyElement.BypassOnLocal
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: BypassOnLocal
  nameWithType: ProxyElement.BypassOnLocal
  fullName: System.Net.Configuration.ProxyElement.BypassOnLocal
- uid: System.Net.Configuration.ProxyElement.BypassOnLocalValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+BypassOnLocalValues
  nameWithType: ProxyElement+BypassOnLocalValues
  fullName: System.Net.Configuration.ProxyElement+BypassOnLocalValues
- uid: System.Net.Configuration.ProxyElement.Properties
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: Properties
  nameWithType: ProxyElement.Properties
  fullName: System.Net.Configuration.ProxyElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.ProxyElement.ProxyAddress
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyAddress
  nameWithType: ProxyElement.ProxyAddress
  fullName: System.Net.Configuration.ProxyElement.ProxyAddress
- uid: System.Uri
  parent: System
  isExternal: true
  name: Uri
  nameWithType: Uri
  fullName: System.Uri
- uid: System.Net.Configuration.ProxyElement.ScriptLocation
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ScriptLocation
  nameWithType: ProxyElement.ScriptLocation
  fullName: System.Net.Configuration.ProxyElement.ScriptLocation
- uid: System.Net.Configuration.ProxyElement.UseSystemDefault
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: UseSystemDefault
  nameWithType: ProxyElement.UseSystemDefault
  fullName: System.Net.Configuration.ProxyElement.UseSystemDefault
- uid: System.Net.Configuration.ProxyElement.UseSystemDefaultValues
  parent: System.Net.Configuration
  isExternal: false
  name: ProxyElement+UseSystemDefaultValues
  nameWithType: ProxyElement+UseSystemDefaultValues
  fullName: System.Net.Configuration.ProxyElement+UseSystemDefaultValues
- uid: System.Net.Configuration.ProxyElement.#ctor*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyElement
  nameWithType: ProxyElement.ProxyElement
- uid: System.Net.Configuration.ProxyElement.AutoDetect*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: AutoDetect
  nameWithType: ProxyElement.AutoDetect
- uid: System.Net.Configuration.ProxyElement.BypassOnLocal*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: BypassOnLocal
  nameWithType: ProxyElement.BypassOnLocal
- uid: System.Net.Configuration.ProxyElement.Properties*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: Properties
  nameWithType: ProxyElement.Properties
- uid: System.Net.Configuration.ProxyElement.ProxyAddress*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ProxyAddress
  nameWithType: ProxyElement.ProxyAddress
- uid: System.Net.Configuration.ProxyElement.ScriptLocation*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: ScriptLocation
  nameWithType: ProxyElement.ScriptLocation
- uid: System.Net.Configuration.ProxyElement.UseSystemDefault*
  parent: System.Net.Configuration.ProxyElement
  isExternal: false
  name: UseSystemDefault
  nameWithType: ProxyElement.UseSystemDefault
