### YamlMime:ManagedReference
items:
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs
  id: CreatingCookieEventArgs
  children:
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  - System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  - System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  - System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  - System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  langs:
  - csharp
  name: CreatingCookieEventArgs
  nameWithType: CreatingCookieEventArgs
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs
  type: Class
  summary: "Adja meg az adatait a <xref href=&quot;System.Web.ApplicationServices.AuthenticationService.CreatingCookie&quot;> </xref> esemény."
  remarks: "A CreatingCookieEventArgs osztály megadja az értékeket bármely <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>eseménykezelő.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Ez az osztály tulajdonságait használatával kérheti le a felhasználói hitelesítő adatokat, amikor létrehoz egy egyéni hitelesítési cookie-t.       A <xref:System.Web.ApplicationServices.AuthenticationService>osztály vált ki a <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>eseményt, amikor beállítja a hitelesítési cookie-k, miután a felhasználó hitelesítő adatainak hitelesített.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService> A <xref:System.Web.ApplicationServices.AuthenticationService>osztály egy CreatingCookieEventArgs objektumot hoz létre, és átadja a <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>eseménykezelő.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>       Visszaállíthatja a felhasználói hitelesítő adatokat a <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A>keresztül <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A>, és <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>Tulajdonságok.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.Password%2A></xref:System.Web.ApplicationServices.CreatingCookieEventArgs.UserName%2A> A <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A>tulajdonság hitelesítéséhez, például az azonosító számot kell egyéni értékeket tartalmazhat.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> A <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A>a tulajdonság azt jelzi, hogy a hitelesítési cookie fenn kell tartani a jelenlegi munkamenet korábbi.</xref:System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent%2A> Állítsa be a <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>tulajdonságot `true` létrehozásakor a hitelesítési cookie, hogy a <xref:System.Web.ApplicationServices.AuthenticationService>osztály nem hoz létre a cookie.</xref:System.Web.ApplicationServices.AuthenticationService> </xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the CreatingCookieEventArgs object to customize the authentication cookie. The handler saves the value from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential%2A> property in the authentication ticket and sets the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet%2A> property to `true` to indicate that the authentication cookie has been created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/t-system.web.application_1_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/t-system.web.application_1_1.asax)]"
  syntax:
    content: 'public class CreatingCookieEventArgs : EventArgs'
  inheritance:
  - System.EventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  id: CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy a hitelesítési cookie-hoz készült."
  remarks: "A <xref:System.Web.ApplicationServices.AuthenticationService>osztály ellenőrzi a CookieIsSet tulajdonság határozza meg, hogy a hitelesítési cookie-hoz készült.</xref:System.Web.ApplicationServices.AuthenticationService> Ez az érték `true` Ha hoz létre egy hitelesítési cookie eseménykezelő a <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>esemény.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> Ha CookieIsSet `false` (az alapértelmezett érték), a <xref:System.Web.ApplicationServices.AuthenticationService>osztály létrehoz egy hitelesítési cookie-t, ezzel a beállítással felülírja a cookie-k, amely a kezelőt hozott létre a <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie>esemény.</xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> </xref:System.Web.ApplicationServices.AuthenticationService>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The CookieIsSet property is set to `true` after the authentication ticket is created.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_11_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_11_1.asax)]"
  syntax:
    content: public bool CookieIsSet { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a hitelesítési cookie-k létrehozása; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  id: CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Lekérdezi a felhasználó által biztosított további hitelesítési értékeket."
  remarks: "A CustomCredential tulajdonsággal egyéni értékek a hitelesítési jegy lekérését. A CustomCredential tulajdonság értéke átadott a <xref:System.Web.ApplicationServices.AuthenticationService.Login%2A>metódus.</xref:System.Web.ApplicationServices.AuthenticationService.Login%2A> Általában ez a tulajdonság használható egyéni értékeket, amelyek a felhasználó nevét és jelszavát, például az azonosító számot is ellenőrizni kell átadni. Ha egynél több értéket a tulajdonság tárolja, a CustomCredential tulajdonság kell elemezni a értékek beolvasása érdekében."
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The value passed in the CustomCredential property is stored in the <xref:System.Web.Security.FormsAuthenticationTicket.UserData%2A> property of the forms authentication ticket.  \n  \n> [!NOTE]\n>  Store the CustomCredential property in a cookie only when you know that the data in the property is not sensitive. Malicious users can access the values in the cookie.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_2_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_2_1.asax)]"
  syntax:
    content: public string CustomCredential { get; }
    return:
      type: System.String
      description: "Az egyéni értékek a hitelesítéshez, eltérő felhasználónév és jelszó szükséges."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  id: IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Lekérdezi egy érték, amely azt jelzi, hogy a hitelesítési cookie megőrződjön-e túl az aktuális munkamenet."
  remarks: "Amikor létrehoz egy <xref:System.Web.Security.FormsAuthenticationTicket>objektum, a IsPersistent tulajdonság segítségével adja meg, hogy a hitelesítési cookie megőrzi-e túl az aktuális munkamenet.</xref:System.Web.Security.FormsAuthenticationTicket>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object in order to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.IsPersistent%2A> property of the <xref:System.Web.Security.FormsAuthenticationTicket> object is set to the value in the IsPersistent property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_0_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_0_1.asax)]"
  syntax:
    content: public bool IsPersistent { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a cookie-t kell őrizhetők meg az aktuális munkamenet; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  id: Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "A jelszó lekérdezi a felhasználó számára."
  remarks: "A jelszót megadó tulajdonság segítségével lekérje a jelszót, a hitelesítési jegy egyéni értékeket beállításakor.      > [!NOTE] > A jelszót megadó tulajdonság értékét nem menti a hitelesítési jegy. Egy rosszindulatú felhasználó elérheti a cookie-t, és lekérje a jelszót, annak ellenére, hogy a cookie titkosítása."
  syntax:
    content: public string Password { get; }
    return:
      type: System.String
      description: "A hitelesítéshez a felhasználó által megadott jelszót."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  exceptions: []
  platform:
  - net462
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  id: UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  langs:
  - csharp
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  type: Property
  assemblies:
  - System.Web.Extensions
  namespace: System.Web.ApplicationServices
  summary: "Lekérdezi a felhasználó nevét."
  remarks: "A UserName tulajdonság használatával a hitelesítési nevének beolvasására, a hitelesítési jegy egyéni értékeket beállításakor. Általában, beállíthatja a <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>tulajdonsága a <xref:System.Web.Security.FormsAuthenticationTicket>objektum felhasználónév értékre.</xref:System.Web.Security.FormsAuthenticationTicket> </xref:System.Web.Security.FormsAuthenticationTicket.Name%2A>"
  example:
  - "The following example shows an event handler for the <xref:System.Web.ApplicationServices.AuthenticationService.CreatingCookie> event. The handler retrieves user values from the <xref:System.Web.ApplicationServices.CreatingCookieEventArgs> object to customize the authentication cookie. The <xref:System.Web.Security.FormsAuthenticationTicket.Name%2A> property is set to the values of the UserName property.  \n  \n [!code-cs[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/csharp/p-system.web.application_6_1.asax)]\n [!code-vb[System.Web.Security.LoginService.CreatingCookieEventArgs#2](~/add/codesnippet/visualbasic/p-system.web.application_6_1.asax)]"
  syntax:
    content: public string UserName { get; }
    return:
      type: System.String
      description: "A hitelesítéshez a felhasználó által megadott név."
  overload: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.EventArgs
  isExternal: false
  name: System.EventArgs
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
  fullName: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CookieIsSet*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CookieIsSet
  nameWithType: CreatingCookieEventArgs.CookieIsSet
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.CustomCredential*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: CustomCredential
  nameWithType: CreatingCookieEventArgs.CustomCredential
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.IsPersistent*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: IsPersistent
  nameWithType: CreatingCookieEventArgs.IsPersistent
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.Password*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: Password
  nameWithType: CreatingCookieEventArgs.Password
- uid: System.Web.ApplicationServices.CreatingCookieEventArgs.UserName*
  parent: System.Web.ApplicationServices.CreatingCookieEventArgs
  isExternal: false
  name: UserName
  nameWithType: CreatingCookieEventArgs.UserName
