### YamlMime:ManagedReference
items:
- uid: System.Configuration.IPersistComponentSettings
  id: IPersistComponentSettings
  children:
  - System.Configuration.IPersistComponentSettings.LoadComponentSettings
  - System.Configuration.IPersistComponentSettings.ResetComponentSettings
  - System.Configuration.IPersistComponentSettings.SaveComponentSettings
  - System.Configuration.IPersistComponentSettings.SaveSettings
  - System.Configuration.IPersistComponentSettings.SettingsKey
  langs:
  - csharp
  name: IPersistComponentSettings
  nameWithType: IPersistComponentSettings
  fullName: System.Configuration.IPersistComponentSettings
  type: Interface
  summary: "Határozza meg a standard funkció a vezérlő vagy a szalagtár szerepel, amely tárolja, és az alkalmazásbeállítások beolvasása."
  remarks: "Általában adhat hozzá alkalmazás beállítások támogatási kérelmet hozzon létre egy beállítások burkoló osztály, amely származik <xref:System.Configuration.ApplicationSettingsBase>, majd adja hozzá ezt az osztályt speciális tulajdonságok</xref:System.Configuration.ApplicationSettingsBase> Azonban ez a megközelítés nem elég foglalják magukban Alkalmazásbeállítások vezérlőelem, hogy a tároló részleteit a védett. Az IPersistComponentSettings felülete alkalmazás beállítások állapot változáskérések vezérlő, összetevő vagy könyvtár modulra kommunikáció szabványos felülettel rendelkező alkalmazás. Tervezési idejű eszközök is függ az adott csatolón megfelelő kezeléséhez a vezérlőket és komponenseket."
  syntax:
    content: public interface IPersistComponentSettings
  implements: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings
  id: LoadComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: LoadComponentSettings()
  nameWithType: IPersistComponentSettings.LoadComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.LoadComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Olvassa be a vezérlő Alkalmazásbeállítások be a megfelelő tulajdonságokat, és frissíti a vezérlőhivatkozás."
  remarks: "Általában a LoadComponentSettings metódus két alapvető műveleteket hajtja végre:-azt eredményezi, hogy egyes beállítások alkalmazáspéldány frissítése az alkalmazás beállításainak tulajdonságai, értékeket általában meghívásával a vezérlő által tartalmazott a <xref:System.Configuration.ApplicationSettingsBase.Reload%2A>módszerek.</xref:System.Configuration.ApplicationSettingsBase.Reload%2A>      -Szükség szerint akkor frissíti a függő újratöltött beállításról tulajdonságok általános tulajdonságokhoz. Például, ha a beállítások osztályának egy `location` beállítások tulajdonság, LoadComponentSettings győződjön meg arról, hogy a vezérlő <xref:System.Windows.Forms.Control.Location%2A>tulajdonság a újratöltött beállítás megfelelően frissül.</xref:System.Windows.Forms.Control.Location%2A>"
  syntax:
    content: public void LoadComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.LoadComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings
  id: ResetComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: ResetComponentSettings()
  nameWithType: IPersistComponentSettings.ResetComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.ResetComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Alaphelyzetbe állítja a vezérlő alkalmazástulajdonságok beállításait az alapértékekre."
  remarks: "A ResetComponentSettings metódus végrehajtása általában meghívja a <xref:System.Configuration.ApplicationSettingsBase.Reset%2A>metódust egy alkalmazás-beállításokat tartalmaz osztály minden példánya.</xref:System.Configuration.ApplicationSettingsBase.Reset%2A>"
  syntax:
    content: public void ResetComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.ResetComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings
  id: SaveComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SaveComponentSettings()
  nameWithType: IPersistComponentSettings.SaveComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.SaveComponentSettings()
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Továbbra is fennáll, a vezérlő alkalmazástulajdonságok beállításait."
  remarks: "A SaveComponentSettings metódus ír a társított tárolót a vezérlő alkalmazástulajdonságok beállítások értékeit. A metódusnak adatokat tároló, a szerializálási technika határozza meg a társított minden egyes beállítások osztály keresztül a <xref:System.Configuration.SettingsProviderAttribute>.</xref:System.Configuration.SettingsProviderAttribute> szolgáltatója A választott beállítások szolgáltató használatával lehet felülbírálni a <xref:System.Configuration.ISettingsProviderService>felületet.</xref:System.Configuration.ISettingsProviderService>      > [!NOTE] > Ha a <xref:System.Configuration.IPersistComponentSettings.SaveSettings%2A>tulajdonság `true`, a vezérlő meg kell hívnia az SaveComponentSettings saját <xref:System.Windows.Forms.Control.Dispose%2A>metódust, hogy a vezérlőelem konfigurációs adatait az alkalmazás lejárta előtt automatikusan tárolódik.</xref:System.Windows.Forms.Control.Dispose%2A> </xref:System.Configuration.IPersistComponentSettings.SaveSettings%2A>"
  syntax:
    content: public void SaveComponentSettings ();
    parameters: []
  overload: System.Configuration.IPersistComponentSettings.SaveComponentSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SaveSettings
  id: SaveSettings
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
  fullName: System.Configuration.IPersistComponentSettings.SaveSettings
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely jelzi, hogy a vezérlő automatikusan kell megőrizni az alkalmazás beállításainak tulajdonságai."
  remarks: "Ha egy vezérlő konfigurációs adatokat tartalmaz, akkor általában megmaradnak explicit hívása válaszul ezeket az adatokat a <xref:System.Configuration.IPersistComponentSettings.SaveComponentSettings%2A>metódus vagy implicit módon néha amikor a vezérlő <xref:System.Windows.Forms.Control.Dispose%2A>metódus meghívja.</xref:System.Windows.Forms.Control.Dispose%2A> </xref:System.Configuration.IPersistComponentSettings.SaveComponentSettings%2A> A SaveSettings tulajdonság határozza meg, hogy a vezérlő automatikusan továbbra is fennáll a konfigurációs adatok azt eldobása során.       Az alapértelmezett érték SaveSettings a vezérlő függ. A vezérlő dokumentációjában kell jeleznie, hogy alkalmazás beállításait használja, milyen adatokat is megőrződjenek és a SaveSettings tulajdonság alapértelmezett értéke van."
  example:
  - "The following code example shows the proper way for a control to check the value of the SaveSettings property before it attempts to automatically persist its configuration data.  \n  \n `protected override void Dispose( bool disposing ) {`  \n  \n `if(disposing) {`  \n  \n `try {`  \n  \n `if (SaveSettings) {`  \n  \n `SaveComponentSettings();`  \n  \n `}`  \n  \n `}`  \n  \n `finally {`  \n  \n `//...`  \n  \n `}`  \n  \n `}`"
  syntax:
    content: public bool SaveSettings { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a vezérlő automatikusan kell megőrizni a állapotában; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Configuration.IPersistComponentSettings.SaveSettings*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IPersistComponentSettings.SettingsKey
  id: SettingsKey
  parent: System.Configuration.IPersistComponentSettings
  langs:
  - csharp
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
  fullName: System.Configuration.IPersistComponentSettings.SettingsKey
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi vagy beállítja az aktuális példány a vezérlő az alkalmazás beállításainak kulcsnak az értéke."
  remarks: "A SettingsKey tulajdonsággal elem egyértelműségének biztosításához alkalmazás tulajdonságai csoportját, amikor az ugyanazon burkoló osztály több példánya van. Például ha egy vezérlő tartalmaz egy társított burkoló osztályt, majd helyezi el ugyanarra a vezérlőre több példányát ugyanahhoz az alkalmazáshoz általában eredményez a burkoló osztály több példánya. A beállítások kulcsot meg kell adni csak akkor, ha a konfigurációs adatok eltér a egy példányonként; Ha például dinamikusan elhelyezett vezérlők helyét.       A következő általános szabályok vonatkoznak a SettingsKey használatát:-vezérlő, mint bármely osztály tartalmazhat nulla vagy több alkalmazás beállítások osztályok, <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> származik Egyes beállítások osztály tartalmazza a saját <xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>tulajdonság segítségével elem egyértelműségének biztosításához, hogy az osztály több példánya</xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>      -Vezérlőt kell külön a példány és a megosztott adatok különböző beállításokat osztályba.      -A vezérlőt bármely példányonkénti konfigurációs adatait a `get` SettingsKey tulajdonságának elérővel kell alapértelmezés szerint a a <xref:System.Windows.Forms.Control.Name%2A>a vezérlő.</xref:System.Windows.Forms.Control.Name%2A> A legtöbb esetben a vezérlő nevét az alkalmazáson belül egyedi lesz. Ha a vezérlő csak megosztott konfigurációs adatokat tartalmaz `get` az alapértelmezett kell `null`.      -A `set` ehhez a tulajdonsághoz tartozó elérő példány és a megosztott konfigurációs adatokat tartalmazó beállítások osztályok megkülönböztetésére kell végrehajtani. Egyes beállítások osztály példányonkénti adatokat tartalmazó `set` <xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName>a beállítások osztály tulajdonsága</xref:System.Configuration.ApplicationSettingsBase.SettingsKey%2A?displayProperty=fullName> csak áteresztő kell Megosztott adatokat tartalmazó beállítások osztályok `set` végre kell hajtania semmilyen műveletre vonatkozó beállításokat."
  syntax:
    content: public string SettingsKey { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>tartalmazó vezérlő aktuális példányát beállítások kulcsa.</xref:System.String>"
  overload: System.Configuration.IPersistComponentSettings.SettingsKey*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: LoadComponentSettings()
  nameWithType: IPersistComponentSettings.LoadComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.LoadComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: ResetComponentSettings()
  nameWithType: IPersistComponentSettings.ResetComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.ResetComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveComponentSettings()
  nameWithType: IPersistComponentSettings.SaveComponentSettings()
  fullName: System.Configuration.IPersistComponentSettings.SaveComponentSettings()
- uid: System.Configuration.IPersistComponentSettings.SaveSettings
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
  fullName: System.Configuration.IPersistComponentSettings.SaveSettings
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Configuration.IPersistComponentSettings.SettingsKey
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
  fullName: System.Configuration.IPersistComponentSettings.SettingsKey
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.IPersistComponentSettings.LoadComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: LoadComponentSettings
  nameWithType: IPersistComponentSettings.LoadComponentSettings
- uid: System.Configuration.IPersistComponentSettings.ResetComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: ResetComponentSettings
  nameWithType: IPersistComponentSettings.ResetComponentSettings
- uid: System.Configuration.IPersistComponentSettings.SaveComponentSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveComponentSettings
  nameWithType: IPersistComponentSettings.SaveComponentSettings
- uid: System.Configuration.IPersistComponentSettings.SaveSettings*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SaveSettings
  nameWithType: IPersistComponentSettings.SaveSettings
- uid: System.Configuration.IPersistComponentSettings.SettingsKey*
  parent: System.Configuration.IPersistComponentSettings
  isExternal: false
  name: SettingsKey
  nameWithType: IPersistComponentSettings.SettingsKey
