### YamlMime:ManagedReference
items:
- uid: System.Web.UI.Design.AppSettingsExpressionEditor
  id: AppSettingsExpressionEditor
  children:
  - System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  - System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  - System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  langs:
  - csharp
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor
  type: Class
  summary: "Tulajdonságokat és metódusokat biztosít értékelése és -szerkesztő alkalmazás beállítás kifejezés egy konfigurációs fájlban tervezési időben."
  remarks: "A AppSettingsExpressionEditor osztály származik a <xref:System.Web.UI.Design.ExpressionEditor>osztály és megvalósítását biztosít a kiértékelése, és egy alkalmazás-beállítás hivatkozási társít egy vezérlő tulajdonságának tervezési időben.</xref:System.Web.UI.Design.ExpressionEditor> Például egy vezérlő tulajdonságának kell kötni az alkalmazás-beállítás kifejezés `AppSettings:mySettingKeyName`, ami azt jelenti, hogy a vezérlőelem tulajdonságának értéke használata a `mySettingKeyName` értéket a `appSettings` a webes konfigurációs fájl részét.       A vizuális tervezőt működteti, például a [!INCLUDE[vsprvslong](~/add/includes/ajax-current-ext-md.md)], a AppSettingsExpressionEditor osztály használatával válassza ki az alkalmazás-beállítás a `appSettings` konfigurációs szakaszban, és ezután kiértékeli a kiválasztott kifejezés a tervezési idejű megjelenítés.       Ha megnyitja a a <xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A>tervezési idejű tulajdonságok rácsban vezérlőelem tulajdonságát, a vizuális tervezőt megjelenít egy párbeszédpanelt, amely a futásidejű értéket adjon meg egy vezérlő tulajdonságának beállítása kifejezésekre.</xref:System.Web.UI.Design.HtmlControlDesigner.Expressions%2A> A kifejezés előtagok listája alapján kifejezés típusának kiválasztása Ha bejelöli a **AppSettings** kifejezés-előtagot a listából, a vizuális Tervező fogadó használja a társított <xref:System.Web.UI.Design.ExpressionEditorSheet>tervezési idejű szerkesztési működésének biztosításához objektum `appSettings` kifejezések és felhasználási AppSettingsExpressionEditor módszerek kiértékeléséhez és konvertálni a kifejezés-karakterlánc alapján alkalmazás beállítás kifejezés szintaxisa.</xref:System.Web.UI.Design.ExpressionEditorSheet> A vizuális Tervező gazdagép hozzárendeléséhez vezérlő, amelyek megjelennek-e a tervezési felülethez a kiértékelt kifejezés eredménye használ.       A <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>AppSettingsExpressionEditor objektum tulajdonság a karakterláncot ad vissza, `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> A <xref:System.Web.Compilation.AppSettingsExpressionBuilder>osztály társítva a kifejezés-előtag `AppSettings` és AppSettingsExpressionEditor végrehajtása.</xref:System.Web.Compilation.AppSettingsExpressionBuilder>       A <xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A>metódus bemeneti alkalmazás beállítás kifejezés karakterláncra értékelődik ki.</xref:System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression%2A> A <xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>metódus értéket ad vissza a <xref:System.Web.UI.Design.ExpressionEditorSheet>beviteléhez és szerkesztéséhez alkalmazás beállítás kifejezések megvalósítási.</xref:System.Web.UI.Design.ExpressionEditorSheet> </xref:System.Web.UI.Design.ExpressionEditor.GetExpressionEditorSheet%2A>"
  example:
  - "The following code example demonstrates how to bind the <xref:System.Web.UI.WebControls.HyperLink.NavigateUrl%2A> property of a <xref:System.Web.UI.WebControls.HyperLink> control to an application setting expression using the AppSettingsExpressionEditor object.  \n  \n1.  In a Web Forms project, add `MyHyperLinkSetting` to the `<appSettings>` section of the web.config file.  \n  \n     [!code-xml[ControlsUsingExpressions#5](~/add/codesnippet/xml/t-system.web.ui.design.a_1.xml)]  \n  \n2.  On a Web Forms page, add a <xref:System.Web.UI.WebControls.HyperLink> control.  \n  \n3.  For the `Hyperlink` control, in Properties, click **Expressions**, and then click the ellipsis button (**...**).  \n  \n     The `<Hyperlinkname>`**Expression** dialog box appears.  \n  \n4.  Under **Bindable properties**, click **NavigateUrl**, in the **Expression type** list, click **AppSettings**, and then under **Expression properties**, in the **AppSetting** box, type **MyHyperLinkSetting**.  \n  \n The visual designer uses the AppSettingsExpressionEditor to assign the expression for the `NavigateUrl` property.  \n  \n The following aspx source shows an example of a property value set using an application setting expression.  \n  \n [!code-vb[ControlsUsingExpressions#2](~/add/codesnippet/visualbasic/t-system.web.ui.design.a_2.aspx)]\n [!code-cs[ControlsUsingExpressions#2](~/add/codesnippet/csharp/t-system.web.ui.design.a_2.aspx)]\n [!code-xml[ControlsUsingExpressions#2](~/add/codesnippet/xml/t-system.web.ui.design.a_2.xml)]"
  syntax:
    content: 'public class AppSettingsExpressionEditor : System.Web.UI.Design.ExpressionEditor'
  inheritance:
  - System.Object
  - System.Web.UI.Design.ExpressionEditor
  implements: []
  inheritedMembers:
  - System.Web.UI.Design.ExpressionEditor.ExpressionPrefix
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.String,System.IServiceProvider)
  - System.Web.UI.Design.ExpressionEditor.GetExpressionEditor(System.Type,System.IServiceProvider)
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  id: '#ctor'
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  type: Constructor
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Web.UI.Design.AppSettingsExpressionEditor&quot;> </xref> osztály."
  remarks: "Egy példányát a <xref:System.Web.UI.Design.AppSettingsExpressionEditor>osztály úgy van beállítva, a következő alaposztály együtt a <xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A>tulajdonsága `AppSettings`.</xref:System.Web.UI.Design.ExpressionEditor.ExpressionPrefix%2A> </xref:System.Web.UI.Design.AppSettingsExpressionEditor>"
  syntax:
    content: public AppSettingsExpressionEditor ();
    parameters: []
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  id: EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Alkalmazás-beállítás kifejezés karakterláncra értékelődik ki, és a tervezési idejű értéket ad meg egy vezérlő tulajdonság."
  remarks: "A EvaluateExpression módszer megkeresi az alkalmazás-beállítás által megadott `expression`, majd visszatér az Alkalmazásbeállítás értékét.       A vizuális tervező használatára a EvaluateExpression módszert használja, az alkalmazás-beállítás kifejezés kiértékelése és a tervezési idejű értéket adjon meg egy társított vezérlő tulajdonság. A vizuális tervező használatára a EvaluateExpression metódust hívja a kifejezés karakterlánccal, és a kiértékelt kifejezés eredményének használ, amelyek megjelennek-e a tervezési felülethez a vezérlő hozzárendelni.       Futásidőben, a lap elemző használja a <xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>és <xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A>módszerek a megfelelő <xref:System.Web.Compilation.AppSettingsExpressionBuilder>-kifejezés kiértékelése, valamint a futásidejű értéket adjon meg egy társított vezérlő tulajdonságának.</xref:System.Web.Compilation.AppSettingsExpressionBuilder> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.GetCodeExpression%2A> </xref:System.Web.Compilation.AppSettingsExpressionBuilder.EvaluateExpression%2A>"
  syntax:
    content: public override object EvaluateExpression (string expression, object parseTimeData, Type propertyType, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "Egy alkalmazás beállítás kifejezés karakterláncának kiértékeléséhez. `expression`nem tartalmazza a <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> kifejezés-előtagot."
    - id: parseTimeData
      type: System.Object
      description: "Egy objektum értékeléséhez további elemzési adatokat tartalmazó `expression`."
    - id: propertyType
      type: System.Type
      description: "A vezérlő tulajdonság típusa."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "A szolgáltatás szolgáltató általi megvalósítása a Tervező gazdagép, segítségével kéri le a további tervezési idejű szolgáltatások által biztosított."
    return:
      type: System.Object
      description: "Az objektum által hivatkozott <code> expression </code>, ha a kifejezés kiértékelése sikerült; ellenkező esetben <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  id: GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  langs:
  - csharp
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  type: Method
  assemblies:
  - System.Design
  namespace: System.Web.UI.Design
  summary: "Egy kifejezés szerkesztő lap az alkalmazás-beállítás kifejezést ad vissza."
  remarks: "A GetExpressionEditorSheet metódus visszaadja egy egyszerű szövegszerkesztőben lap végrehajtása, amely egyetlen bemeneti karakterláncot használó kifejezést kialakításához."
  syntax:
    content: public override System.Web.UI.Design.ExpressionEditorSheet GetExpressionEditorSheet (string expression, IServiceProvider serviceProvider);
    parameters:
    - id: expression
      type: System.String
      description: "A vezérlő tulajdonságnál, a kifejezés szerkesztő lap inicializáló kifejezés-karakterlánc. `expression`nem tartalmazza a <xref uid=&quot;langword_csharp_AppSettings&quot; name=&quot;AppSettings&quot; href=&quot;&quot;> </xref> kifejezés-előtagot."
    - id: serviceProvider
      type: System.IServiceProvider
      description: "A szolgáltatás szolgáltató általi megvalósítása a Tervező gazdagép, segítségével kéri le a további tervezési idejű szolgáltatások által biztosított."
    return:
      type: System.Web.UI.Design.ExpressionEditorSheet
      description: "Egy <xref href=&quot;System.Web.UI.Design.ExpressionEditorSheet&quot;> </xref> megvalósítása, amely az alkalmazás beállítás kifejezés tulajdonságainak meghatározása."
  overload: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.Design.ExpressionEditor
  isExternal: false
  name: System.Web.UI.Design.ExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor()
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor()
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.AppSettingsExpressionEditor()
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(System.String,System.Object,System.Type,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression(String,Object,Type,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression(String,Object,Type,IServiceProvider)
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.IServiceProvider
  parent: System
  isExternal: true
  name: IServiceProvider
  nameWithType: IServiceProvider
  fullName: System.IServiceProvider
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(System.String,System.IServiceProvider)
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet(String,IServiceProvider)
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
  fullName: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet(String,IServiceProvider)
- uid: System.Web.UI.Design.ExpressionEditorSheet
  parent: System.Web.UI.Design
  isExternal: false
  name: ExpressionEditorSheet
  nameWithType: ExpressionEditorSheet
  fullName: System.Web.UI.Design.ExpressionEditorSheet
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.#ctor*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: AppSettingsExpressionEditor
  nameWithType: AppSettingsExpressionEditor.AppSettingsExpressionEditor
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.EvaluateExpression*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: EvaluateExpression
  nameWithType: AppSettingsExpressionEditor.EvaluateExpression
- uid: System.Web.UI.Design.AppSettingsExpressionEditor.GetExpressionEditorSheet*
  parent: System.Web.UI.Design.AppSettingsExpressionEditor
  isExternal: false
  name: GetExpressionEditorSheet
  nameWithType: AppSettingsExpressionEditor.GetExpressionEditorSheet
