### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.CallbackDebugElement
  id: CallbackDebugElement
  children:
  - System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  - System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  - System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  - System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  - System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  - System.ServiceModel.Configuration.CallbackDebugElement.Properties
  langs:
  - csharp
  name: CallbackDebugElement
  nameWithType: CallbackDebugElement
  fullName: System.ServiceModel.Configuration.CallbackDebugElement
  type: Class
  summary: "Egy konfigurációs elem, amely meghatározza a kiszolgálóoldali hibakeresést egy Windows Communication Foundation (WCF) visszahívási objektumot jelöli. Ez az osztály nem örökölhető."
  remarks: "Ha a <xref:System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults%2A>tulajdonságot `true` programozott módon, engedélyezheti az ügyfél-visszahívás objektum vissza a szolgáltatás a hibakereséshez a felügyelt kivételek adatai áramlását.</xref:System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults%2A>      > [!CAUTION] > Ad vissza, az ügyfelek számára a felügyelt kivételek adatai egy biztonsági kockázatot jelenthet. Ennek az az oka a kivétel részletei teszi közzé a belső szolgáltatás végrehajtása nem engedélyezett az ügyfelek által használható kapcsolatos információkat."
  syntax:
    content: 'public sealed class CallbackDebugElement : System.ServiceModel.Configuration.BehaviorExtensionElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement
  - System.ServiceModel.Configuration.ServiceModelExtensionElement
  - System.ServiceModel.Configuration.BehaviorExtensionElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.ServiceModel.Configuration.ServiceModelConfigurationElement.SetPropertyValueIfNotDefaultValue``1(System.String,``0)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.ConfigurationElementName
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.IsModified
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.Reset(System.Configuration.ConfigurationElement)
  - System.ServiceModel.Configuration.ServiceModelExtensionElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CallbackDebugElement()
  nameWithType: CallbackDebugElement.CallbackDebugElement()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CallbackDebugElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.CallbackDebugElement&quot;> </xref> osztály."
  syntax:
    content: public CallbackDebugElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.CallbackDebugElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  id: BehaviorType
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Ez a viselkedés elem beolvasása."
  syntax:
    content: public override Type BehaviorType { get; }
    return:
      type: System.Type
      description: "A viselkedés elem típusa."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  id: CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Másolja a konfigurációs elem az adott konfigurációs elem tartalmát."
  syntax:
    content: public override void CopyFrom (System.ServiceModel.Configuration.ServiceModelExtensionElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.ServiceModelExtensionElement
      description: "A konfigurációs elem másolása."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  id: CreateBehavior
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: CreateBehavior()
  nameWithType: CallbackDebugElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior()
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override object CreateBehavior ();
    parameters: []
    return:
      type: System.Object
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  id: IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely megadja, hogy ügyfél visszahívási objektumok felügyelt kivételek adatai a SOAP-hibák vissza a szolgáltatás számára."
  syntax:
    content: public bool IncludeExceptionDetailInFaults { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a Windows Communication Foundation (WCF) adja vissza felügyelt visszahívás kivételt ügyfélinformációk megjelenjenek a SOAP hibákat duplex kommunikációt; a kiszolgálóoldali hibakeresés céljából Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  langs:
  - csharp
  name: Properties
  nameWithType: CallbackDebugElement.Properties
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.CallbackDebugElement.Properties*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ServiceModel.Configuration.BehaviorExtensionElement
  isExternal: false
  name: System.ServiceModel.Configuration.BehaviorExtensionElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CallbackDebugElement()
  nameWithType: CallbackDebugElement.CallbackDebugElement()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CallbackDebugElement()
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(System.ServiceModel.Configuration.ServiceModelExtensionElement)
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CopyFrom(ServiceModelExtensionElement)
  nameWithType: CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom(ServiceModelExtensionElement)
- uid: System.ServiceModel.Configuration.ServiceModelExtensionElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: ServiceModelExtensionElement
  nameWithType: ServiceModelExtensionElement
  fullName: System.ServiceModel.Configuration.ServiceModelExtensionElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CreateBehavior()
  nameWithType: CallbackDebugElement.CreateBehavior()
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior()
- uid: System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: Properties
  nameWithType: CallbackDebugElement.Properties
  fullName: System.ServiceModel.Configuration.CallbackDebugElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.CallbackDebugElement.#ctor*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CallbackDebugElement
  nameWithType: CallbackDebugElement.CallbackDebugElement
- uid: System.ServiceModel.Configuration.CallbackDebugElement.BehaviorType*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: BehaviorType
  nameWithType: CallbackDebugElement.BehaviorType
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CopyFrom*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CopyFrom
  nameWithType: CallbackDebugElement.CopyFrom
- uid: System.ServiceModel.Configuration.CallbackDebugElement.CreateBehavior*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: CreateBehavior
  nameWithType: CallbackDebugElement.CreateBehavior
- uid: System.ServiceModel.Configuration.CallbackDebugElement.IncludeExceptionDetailInFaults*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: IncludeExceptionDetailInFaults
  nameWithType: CallbackDebugElement.IncludeExceptionDetailInFaults
- uid: System.ServiceModel.Configuration.CallbackDebugElement.Properties*
  parent: System.ServiceModel.Configuration.CallbackDebugElement
  isExternal: false
  name: Properties
  nameWithType: CallbackDebugElement.Properties
