### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationLocation
  id: ConfigurationLocation
  children:
  - System.Configuration.ConfigurationLocation.OpenConfiguration
  - System.Configuration.ConfigurationLocation.Path
  langs:
  - csharp
  name: ConfigurationLocation
  nameWithType: ConfigurationLocation
  fullName: System.Configuration.ConfigurationLocation
  type: Class
  summary: "Jelöli egy <xref uid=&quot;langword_csharp_location&quot; name=&quot;location&quot; href=&quot;&quot;> </xref> elem konfigurációs fájlban."
  remarks: "A ConfigurationLocation osztály egy példányát jelenti az egyetlen `location` elemet a konfigurációs fájlban. Helyek segítségével adja meg, csak a megadott erőforrás, például egy adott oldal, a fájl vagy a alkönyvtárat, a webes alkalmazás vonatkozó konfigurációs beállításokat. A ConfigurationLocation osztály használatával szerezze be az elérési út és a <xref:System.Configuration.Configuration>objektum, amely a megadott erőforrás vonatkozik.</xref:System.Configuration.Configuration>"
  example:
  - "In the following code example, the Web configuration for the application `MySampleApp` is loaded, and then the locations defined in the configuration are displayed.  \n  \n [!code-vb[ConfigurationLocationCollection#1](~/add/codesnippet/visualbasic/t-system.configuration.c_22_1.vb)]\n [!code-cs[ConfigurationLocationCollection#1](~/add/codesnippet/csharp/t-system.configuration.c_22_1.cs)]"
  syntax:
    content: public class ConfigurationLocation
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  id: OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
  type: Method
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Létrehoz egy konfigurációs objektum egy példányát."
  syntax:
    content: public System.Configuration.Configuration OpenConfiguration ();
    parameters: []
    return:
      type: System.Configuration.Configuration
      description: "Egy konfigurációs objektumot."
  overload: System.Configuration.ConfigurationLocation.OpenConfiguration*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationLocation.Path
  id: Path
  parent: System.Configuration.ConfigurationLocation
  langs:
  - csharp
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
  type: Property
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Lekérdezi a relatív elérési út az erőforráshoz, amelynek konfigurációs beállításait jelölik ez <xref href=&quot;System.Configuration.ConfigurationLocation&quot;> </xref> objektum."
  remarks: "A Path tulajdonság által visszaadott elérési út a webhely gyökeréhez viszonyítva.      > [!NOTE] > Path tulajdonságot tartalmazhatnak, amelyre a konfigurációs beállítás csak az elérési utak vesszővel tagolt listáját."
  example:
  - "The following code example shows how to access the Path property and display the value returned to the console.  \n  \n [!code-vb[ConfigurationLocationCollection#2](~/add/codesnippet/visualbasic/p-system.configuration.c_38_1.vb)]\n [!code-cs[ConfigurationLocationCollection#2](~/add/codesnippet/csharp/p-system.configuration.c_38_1.cs)]"
  syntax:
    content: public string Path { get; }
    return:
      type: System.String
      description: "Az erőforrás, amelynek konfigurációs beállításait jelölik a relatív elérési útja <xref href=&quot;System.Configuration.ConfigurationLocation&quot;> </xref>."
  overload: System.Configuration.ConfigurationLocation.Path*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration()
  nameWithType: ConfigurationLocation.OpenConfiguration()
  fullName: System.Configuration.ConfigurationLocation.OpenConfiguration()
- uid: System.Configuration.Configuration
  parent: System.Configuration
  isExternal: false
  name: Configuration
  nameWithType: Configuration
  fullName: System.Configuration.Configuration
- uid: System.Configuration.ConfigurationLocation.Path
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
  fullName: System.Configuration.ConfigurationLocation.Path
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.ConfigurationLocation.OpenConfiguration*
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: OpenConfiguration
  nameWithType: ConfigurationLocation.OpenConfiguration
- uid: System.Configuration.ConfigurationLocation.Path*
  parent: System.Configuration.ConfigurationLocation
  isExternal: false
  name: Path
  nameWithType: ConfigurationLocation.Path
