### YamlMime:ManagedReference
items:
- uid: System.EnterpriseServices.Internal.ServerWebConfig
  id: ServerWebConfig
  children:
  - System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  - System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  - System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  langs:
  - csharp
  name: ServerWebConfig
  nameWithType: ServerWebConfig
  fullName: System.EnterpriseServices.Internal.ServerWebConfig
  type: Class
  summary: "Létrehoz egy SOAP-kompatibilis COM + alkalmazás Web.config fájlt. Összetevő-bejegyzések is adhat hozzá a fájlt az alkalmazás közzétett COM-felületek."
  remarks: "A ServerWebConfig osztály segítségével hozzon létre egy Web.config fájlt az Internet Information Services (IIS) 6.0 egy SOAP-kompatibilis COM + alkalmazás virtuális gyökérkönyvtár létrehozása során. Azt is adhat hozzá az XML-elemek a Web.config fájl az alkalmazáshoz hozzáadott összetevő-illesztőfelületei számára.       ServerWebConfig a .NET-keretrendszer belsőleg használja. Nem szeretné használni, azt közvetlenül a kódban."
  syntax:
    content: 'public class ServerWebConfig : System.EnterpriseServices.Internal.IServerWebConfig'
  inheritance:
  - System.Object
  implements:
  - System.EnterpriseServices.Internal.IServerWebConfig
  inheritedMembers: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  id: '#ctor'
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
  type: Constructor
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.EnterpriseServices.Internal.ServerWebConfig&quot;> </xref> osztály."
  syntax:
    content: public ServerWebConfig ();
    parameters: []
  overload: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  id: AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "XML-elemeket ad hozzá egy COM-illesztőfelület egy SOAP-kompatibilis COM + alkalmazás közzétett a Web.config fájlban."
  remarks: "A megadott típus esetében a AddElement metódus hozzáadja a Web.config fájlt a `<wellknown>` és `<activated>` elem gyermekeként a `<service>` elem a következő XPath: `/configuration/system.runtime.remoting/application/service` a `AssemblyName`, `TypeName`, `ProgId`, és `WkoMode` paraméterek be vannak építve az attribútumértékek két hozzáadott elem.       AddElement közvetlenül nem hívható. Ehelyett hívja a <xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>metódus.</xref:System.EnterpriseServices.Internal.Publish.ProcessServerTlb%2A>"
  syntax:
    content: public void AddElement (string FilePath, string AssemblyName, string TypeName, string ProgId, string WkoMode, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "A meglévő Web.config fájl elérési útját."
    - id: AssemblyName
      type: System.String
      description: "A hozzáadni kívánt típust tartalmazó szerelvény neve."
    - id: TypeName
      type: System.String
      description: "A hozzáadni kívánt típus neve."
    - id: ProgId
      type: System.String
      description: "A hozzáadni kívánt típusának programozott azonosítója."
    - id: WkoMode
      type: System.String
      description: "Egy karakterlánc-konstansra, amely a tag neve egyezik a <xref href=&quot;System.Runtime.Remoting.WellKnownObjectMode&quot;> </xref> számbavételi, amely megadja, hogy milyen jól ismert objektumok aktiválva van."
    - id: Error
      type: System.String
      description: "Egy karakterlánc, amelyre hibaüzenetet is beírhatók."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  exceptions: []
  platform:
  - net462
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  id: Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  langs:
  - csharp
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
  type: Method
  assemblies:
  - System.EnterpriseServices
  namespace: System.EnterpriseServices.Internal
  summary: "Létrehoz egy Web.config egy SOAP-kompatibilis COM + alkalmazás, hogy a fájl készen áll a COM-felületek közzétett hozzá az XML-elemek rendelkezik."
  remarks: "A Create metódussal hoz létre, amely tartalmazza a hierarchiát a következő XPath üres elem a Web.config fájlban: ```   /configuration/system.runtime.remoting/application/service   ``` példányának helyett egy <xref:System.EnterpriseServices.Internal.ServerWebConfig>objektum és a közvetlenül, létrehozás hívása történt a <xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A>metódus.</xref:System.EnterpriseServices.Internal.Publish.CreateVirtualRoot%2A> </xref:System.EnterpriseServices.Internal.ServerWebConfig>"
  syntax:
    content: public void Create (string FilePath, string FilePrefix, out string Error);
    parameters:
    - id: FilePath
      type: System.String
      description: "A mappa, amely a konfigurációs fájlban kell létrehozni."
    - id: FilePrefix
      type: System.String
      description: "A karakterlánc-érték &quot;Web&quot;, amelyre a konfigurációs kiterjesztés kerül."
    - id: Error
      type: System.String
      description: "Egy karakterlánc, amelyre hibaüzenetet is beírhatók."
  overload: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig()
  nameWithType: ServerWebConfig.ServerWebConfig()
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.ServerWebConfig()
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(System.String,System.String,System.String,System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement(String,String,String,String,String,String)
  nameWithType: ServerWebConfig.AddElement(String,String,String,String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.AddElement(String,String,String,String,String,String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create(System.String,System.String,System.String@)
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create(String,String,String)
  nameWithType: ServerWebConfig.Create(String,String,String)
  fullName: System.EnterpriseServices.Internal.ServerWebConfig.Create(String,String,String)
- uid: System.EnterpriseServices.Internal.ServerWebConfig.#ctor*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: ServerWebConfig
  nameWithType: ServerWebConfig.ServerWebConfig
- uid: System.EnterpriseServices.Internal.ServerWebConfig.AddElement*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: AddElement
  nameWithType: ServerWebConfig.AddElement
- uid: System.EnterpriseServices.Internal.ServerWebConfig.Create*
  parent: System.EnterpriseServices.Internal.ServerWebConfig
  isExternal: false
  name: Create
  nameWithType: ServerWebConfig.Create
