### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.ProcessModelLogLevel
  id: ProcessModelLogLevel
  children:
  - System.Web.Configuration.ProcessModelLogLevel.All
  - System.Web.Configuration.ProcessModelLogLevel.Errors
  - System.Web.Configuration.ProcessModelLogLevel.None
  langs:
  - csharp
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
  type: Enum
  summary: "Megadja a eseménytípusok az eseménynaplóba naplózni."
  remarks: "A ProcessModelLogLevel számbavétel telepítésekor használni kívánt értékeket tartalmazza a <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>tulajdonság.</xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A>       Az alapértelmezett érték: a hibák."
  example:
  - "The following code example shows how to set the <xref:System.Web.Configuration.ProcessModelSection.LogLevel%2A> property.  \n  \n [!code-cs[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/csharp/t-system.web.configurati_95_1.cs)]\n [!code-vb[System.Web.Configuration.ProcessModelSection#23](~/add/codesnippet/visualbasic/t-system.web.configurati_95_1.vb)]"
  syntax:
    content: public enum ProcessModelLogLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  id: All
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Rendszer minden eseményt naplóz. Ez a mező konstans értéke."
  remarks: "Használja ezt a beállítást, ha szeretné használni a lehetséges hibákat, az alkalmazás előfordulhat, hogy ki, szűrés nélkül. Ez a beállítás akkor hasznos, az épület és hibakeresés fázis során."
  syntax:
    content: All
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  id: Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Meghatározza, hogy csak a nem várt leállások, a memória-korlát leállítások és az holtpont leállítások kerüljenek. Ez a mező konstans értéke."
  remarks: "Ez az alapértelmezett beállítás."
  syntax:
    content: Errors
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  id: None
  parent: System.Web.Configuration.ProcessModelLogLevel
  langs:
  - csharp
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Meghatározza, hogy nincs naplózott esemény. Ez a mező konstans értéke."
  remarks: "Előfordulhat, hogy szeretné használni ezt a beállítást telepített és tesztelt alkalmazásokhoz."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.ProcessModelLogLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.ProcessModelLogLevel.All
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: All
  nameWithType: ProcessModelLogLevel.All
  fullName: System.Web.Configuration.ProcessModelLogLevel.All
- uid: System.Web.Configuration.ProcessModelLogLevel
  parent: System.Web.Configuration
  isExternal: false
  name: ProcessModelLogLevel
  nameWithType: ProcessModelLogLevel
  fullName: System.Web.Configuration.ProcessModelLogLevel
- uid: System.Web.Configuration.ProcessModelLogLevel.Errors
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: Errors
  nameWithType: ProcessModelLogLevel.Errors
  fullName: System.Web.Configuration.ProcessModelLogLevel.Errors
- uid: System.Web.Configuration.ProcessModelLogLevel.None
  parent: System.Web.Configuration.ProcessModelLogLevel
  isExternal: false
  name: None
  nameWithType: ProcessModelLogLevel.None
  fullName: System.Web.Configuration.ProcessModelLogLevel.None
