### YamlMime:ManagedReference
items:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  id: ITransformerConfigurationControl
  children:
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  - System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  langs:
  - csharp
  name: ITransformerConfigurationControl
  nameWithType: ITransformerConfigurationControl
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  type: Interface
  summary: "Határozza meg a szerződés egy vezérlő olyan konfiguráció-ellenőrzés a kijelzők kapcsolaton keresztül átalakítók nevében járhasson el."
  remarks: "A konfiguráció-ellenőrzés jeleníthető átalakítók felhasználónak konfigurálását. A konfigurációs vezérlője egy felhasználói felület (UI), amely lehetővé teszi a felhasználó számára melyik alakul. A kapcsolatok zónájában lévő jelenik meg. A <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>metódus visszaadja a konfigurációs.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A?displayProperty=fullName>       Ha szeretné felülbírálni az <xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A>metódust, ha a átalakító szükséges egy testre szabott felhasználói felület.</xref:System.Web.UI.WebControls.WebParts.WebPartTransformer.CreateConfigurationControl%2A> A konfiguráció-ellenőrzés meg kell valósítania a itransformerconfigurationcontrol felületet felületet, beleértve a <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled>és <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded>események.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded> </xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled> Ezek az események akkor történik, ha egy átalakító vezérlő lett konfigurálva vagy sikeresen, illetve konfigurálva."
  syntax:
    content: public interface ITransformerConfigurationControl
  implements: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  id: Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Átalakító konfigurációs nem befejezésekor következik be."
  remarks: "A kijelzők vezérlő, amely megvalósítja az <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>vet fel ezt az eseményt, amikor átalakító konfiguráció nem fejeződött be, mert a felhasználó megszakította a konfiguráció, vagy a konfiguráció nem hajtható végre.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Cancelled;
    return:
      type: System.EventHandler
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  id: Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  langs:
  - csharp
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  type: Event
  assemblies:
  - System.Web
  namespace: System.Web.UI.WebControls.WebParts
  summary: "Átalakító konfiguráció sikeres végrehajtása előtt következik be."
  remarks: "A kijelzők vezérlő, amely megvalósítja az <xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>vet fel az eseményt, amikor egy átalakító konfiguráció sikeresen befejeződött.</xref:System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl>"
  syntax:
    content: public event EventHandler Succeeded;
    return:
      type: System.EventHandler
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Cancelled
  nameWithType: ITransformerConfigurationControl.Cancelled
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Cancelled
- uid: System.EventHandler
  parent: System
  isExternal: true
  name: EventHandler
  nameWithType: EventHandler
  fullName: System.EventHandler
- uid: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
  parent: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl
  isExternal: false
  name: Succeeded
  nameWithType: ITransformerConfigurationControl.Succeeded
  fullName: System.Web.UI.WebControls.WebParts.ITransformerConfigurationControl.Succeeded
