### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.AuthenticationMode
  id: AuthenticationMode
  children:
  - System.Web.Configuration.AuthenticationMode.Forms
  - System.Web.Configuration.AuthenticationMode.None
  - System.Web.Configuration.AuthenticationMode.Passport
  - System.Web.Configuration.AuthenticationMode.Windows
  langs:
  - csharp
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: System.Web.Configuration.AuthenticationMode
  type: Enum
  summary: "Megadja a hitelesítési mód használata egy webalkalmazás."
  remarks: "A <xref:System.Web.Configuration.AuthenticationSection.Mode%2A>tulajdonság programozott módon konfigurálhatja a webes alkalmazás által használt hitelesítés típusa</xref:System.Web.Configuration.AuthenticationSection.Mode%2A>"
  example:
  - "The following code example shows how to access the <xref:System.Web.Configuration.AuthenticationSection.Mode%2A> property.  \n  \n [!code-cs[System.Web.Configuration.AuthenticationSection#4](~/add/codesnippet/csharp/t-system.web.configurati_43_1.cs)]\n [!code-vb[System.Web.Configuration.AuthenticationSection#4](~/add/codesnippet/visualbasic/t-system.web.configurati_43_1.vb)]"
  syntax:
    content: public enum AuthenticationMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationMode.Forms
  id: Forms
  parent: System.Web.Configuration.AuthenticationMode
  langs:
  - csharp
  name: Forms
  nameWithType: AuthenticationMode.Forms
  fullName: System.Web.Configuration.AuthenticationMode.Forms
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Adja meg a hitelesítési mód az ASP.NET űrlapos hitelesítését."
  syntax:
    content: Forms
    return:
      type: System.Web.Configuration.AuthenticationMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationMode.None
  id: None
  parent: System.Web.Configuration.AuthenticationMode
  langs:
  - csharp
  name: None
  nameWithType: AuthenticationMode.None
  fullName: System.Web.Configuration.AuthenticationMode.None
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Adja meg a hitelesítés."
  syntax:
    content: None
    return:
      type: System.Web.Configuration.AuthenticationMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationMode.Passport
  id: Passport
  parent: System.Web.Configuration.AuthenticationMode
  langs:
  - csharp
  name: Passport
  nameWithType: AuthenticationMode.Passport
  fullName: System.Web.Configuration.AuthenticationMode.Passport
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Adja meg a Microsoft Passport hitelesítési módot."
  syntax:
    content: Passport
    return:
      type: System.Web.Configuration.AuthenticationMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.AuthenticationMode.Windows
  id: Windows
  parent: System.Web.Configuration.AuthenticationMode
  langs:
  - csharp
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: System.Web.Configuration.AuthenticationMode.Windows
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Adja meg a Windows a hitelesítési módot. Ezt a módot alkalmazza, ha az Internet Information Services (IIS) hitelesítési módszerekkel Basic, Digest, integrált Windows-(NTLM/Kerberos), vagy tanúsítványokat."
  syntax:
    content: Windows
    return:
      type: System.Web.Configuration.AuthenticationMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.AuthenticationMode.Forms
  parent: System.Web.Configuration.AuthenticationMode
  isExternal: false
  name: Forms
  nameWithType: AuthenticationMode.Forms
  fullName: System.Web.Configuration.AuthenticationMode.Forms
- uid: System.Web.Configuration.AuthenticationMode
  parent: System.Web.Configuration
  isExternal: false
  name: AuthenticationMode
  nameWithType: AuthenticationMode
  fullName: System.Web.Configuration.AuthenticationMode
- uid: System.Web.Configuration.AuthenticationMode.None
  parent: System.Web.Configuration.AuthenticationMode
  isExternal: false
  name: None
  nameWithType: AuthenticationMode.None
  fullName: System.Web.Configuration.AuthenticationMode.None
- uid: System.Web.Configuration.AuthenticationMode.Passport
  parent: System.Web.Configuration.AuthenticationMode
  isExternal: false
  name: Passport
  nameWithType: AuthenticationMode.Passport
  fullName: System.Web.Configuration.AuthenticationMode.Passport
- uid: System.Web.Configuration.AuthenticationMode.Windows
  parent: System.Web.Configuration.AuthenticationMode
  isExternal: false
  name: Windows
  nameWithType: AuthenticationMode.Windows
  fullName: System.Web.Configuration.AuthenticationMode.Windows
