### YamlMime:ManagedReference
items:
- uid: System.Net.Configuration.SmtpSection
  id: SmtpSection
  children:
  - System.Net.Configuration.SmtpSection.#ctor
  - System.Net.Configuration.SmtpSection.DeliveryFormat
  - System.Net.Configuration.SmtpSection.DeliveryMethod
  - System.Net.Configuration.SmtpSection.From
  - System.Net.Configuration.SmtpSection.Network
  - System.Net.Configuration.SmtpSection.Properties
  - System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  langs:
  - csharp
  name: SmtpSection
  nameWithType: SmtpSection
  fullName: System.Net.Configuration.SmtpSection
  type: Class
  summary: "Az SMTP szakasz jelöli a <xref uid=&quot;langword_csharp_System.Net&quot; name=&quot;System.Net&quot; href=&quot;&quot;> </xref> konfigurációs fájlt."
  remarks: "Ez az osztály az SMTP-t támogató osztályok által használt konfigurációs fájlokban tárolt információk programozott hozzáférést biztosít a <xref:System.Net.Mail>névtér.</xref:System.Net.Mail>"
  syntax:
    content: 'public sealed class SmtpSection : System.Configuration.ConfigurationSection'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  - System.Configuration.ConfigurationSection
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.DeserializeSection(System.Xml.XmlReader)
  - System.Configuration.ConfigurationSection.GetRuntimeObject
  - System.Configuration.ConfigurationSection.IsModified
  - System.Configuration.ConfigurationSection.ResetModified
  - System.Configuration.ConfigurationSection.SectionInformation
  - System.Configuration.ConfigurationSection.SerializeSection(System.Configuration.ConfigurationElement,System.String,System.Configuration.ConfigurationSaveMode)
  - System.Configuration.ConfigurationSection.ShouldSerializeElementInTargetVersion(System.Configuration.ConfigurationElement,System.String,System.Runtime.Versioning.FrameworkName)
  - System.Configuration.ConfigurationSection.ShouldSerializePropertyInTargetVersion(System.Configuration.ConfigurationProperty,System.String,System.Runtime.Versioning.FrameworkName,System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationSection.ShouldSerializeSectionInTargetVersion(System.Runtime.Versioning.FrameworkName)
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.#ctor
  id: '#ctor'
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: SmtpSection()
  nameWithType: SmtpSection.SmtpSection()
  fullName: System.Net.Configuration.SmtpSection.SmtpSection()
  type: Constructor
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Net.Configuration.SmtpSection&quot;> </xref> osztály."
  syntax:
    content: public SmtpSection ();
    parameters: []
  overload: System.Net.Configuration.SmtpSection.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat
  id: DeliveryFormat
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
  fullName: System.Net.Configuration.SmtpSection.DeliveryFormat
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja a használatával a Simple Mail Transport Protocol (SMTP) kimenő e-mailek küldéséhez használt formátum."
  syntax:
    content: public System.Net.Mail.SmtpDeliveryFormat DeliveryFormat { get; set; }
    return:
      type: System.Net.Mail.SmtpDeliveryFormat
      description: "Returns <xref href=&quot;System.Net.Mail.SmtpDeliveryFormat&quot;></xref>.       A kimenő küldéséhez használt formátum e-mail küldése az SMTP használatával."
  overload: System.Net.Configuration.SmtpSection.DeliveryFormat*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod
  id: DeliveryMethod
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
  fullName: System.Net.Configuration.SmtpSection.DeliveryMethod
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja a Simple Mail Transport Protocol (SMTP) kézbesítési módszert. Az alapértelmezett kézbesítési módszer <xref href=&quot;System.Net.Mail.SmtpDeliveryMethod&quot;> </xref>."
  remarks: "Ez a tulajdonság értékek <xref:System.Net.Mail.SmtpDeliveryMethod>, <xref:System.Net.Mail.SmtpDeliveryMethod>, és <xref:System.Net.Mail.SmtpDeliveryMethod>.</xref:System.Net.Mail.SmtpDeliveryMethod> </xref:System.Net.Mail.SmtpDeliveryMethod> </xref:System.Net.Mail.SmtpDeliveryMethod> Ezek az értékek konfigurálható alárendelt elemet, és van egy megfelelő szakasz a `System.Net` konfigurációs fájlt. A szakaszok neveinél, a felhasználók felel meg a megfelelő szakaszneveket, a kézbesítési módszert."
  syntax:
    content: public System.Net.Mail.SmtpDeliveryMethod DeliveryMethod { get; set; }
    return:
      type: System.Net.Mail.SmtpDeliveryMethod
      description: "Az SMTP kézbesítési módszert jelölő karakterlánccá."
  overload: System.Net.Configuration.SmtpSection.DeliveryMethod*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.From
  id: From
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: From
  nameWithType: SmtpSection.From
  fullName: System.Net.Configuration.SmtpSection.From
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi vagy beállítja az alapértelmezett érték, amely azt jelzi, hogy az e-mail üzenetet."
  syntax:
    content: public string From { get; set; }
    return:
      type: System.String
      description: "Az alapértelmezett érték, amely jelzi, aki egy e-mail üzenetet a jelölő karakterlánccá."
  overload: System.Net.Configuration.SmtpSection.From*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.Network
  id: Network
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: Network
  nameWithType: SmtpSection.Network
  fullName: System.Net.Configuration.SmtpSection.Network
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi a konfigurációs elem, amely a szükséges hálózati beállításokat által a Simple Mail Transport Protocol (SMTP). fájl. <xref href=&quot;System.Net.Configuration.SmtpNetworkElement&quot;></xref>."
  syntax:
    content: public System.Net.Configuration.SmtpNetworkElement Network { get; }
    return:
      type: System.Net.Configuration.SmtpNetworkElement
      description: "A <xref href=&quot;System.Net.Configuration.SmtpNetworkElement&quot;></xref> object.       A konfigurációs elem, amely az SMTP által használt hálózati beállításokat."
  overload: System.Net.Configuration.SmtpSection.Network*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.Properties
  id: Properties
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: Properties
  nameWithType: SmtpSection.Properties
  fullName: System.Net.Configuration.SmtpSection.Properties
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.Net.Configuration.SmtpSection.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  id: SpecifiedPickupDirectory
  parent: System.Net.Configuration.SmtpSection
  langs:
  - csharp
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
  fullName: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  type: Property
  assemblies:
  - System
  namespace: System.Net.Configuration
  summary: "Lekérdezi a felvételi könyvtár SMPT-ügyfél által használandó."
  remarks: "Azt jelzi, hogy által megadott könyvtárban <xref:System.Net.Mail.SmtpClient.PickupDirectoryLocation%2A>fogja használni az SMTP-levélfelvételi könyvtár.</xref:System.Net.Mail.SmtpClient.PickupDirectoryLocation%2A> Ha az SMTP-ügyfelet nem lehet írni a felvételi könyvtár helyét egy i/o-kivétel történt <xref:System.Net.Mail.SmtpClient.Send%2A>.</xref:System.Net.Mail.SmtpClient.Send%2A> A könyvtár nem hozható létre, ha nem létezik. Az aktuálisan futó szál vagy egy másik folyamat hitelesítő adatait a könyvtár eléréséhez használható."
  syntax:
    content: public System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement SpecifiedPickupDirectory { get; }
    return:
      type: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
      description: "A <xref href=&quot;System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement&quot;> </xref> objektum, amely megadja, hogy a felvételi címtárban mappában."
  overload: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationSection
  isExternal: false
  name: System.Configuration.ConfigurationSection
- uid: System.Net.Configuration.SmtpSection.#ctor
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SmtpSection()
  nameWithType: SmtpSection.SmtpSection()
  fullName: System.Net.Configuration.SmtpSection.SmtpSection()
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
  fullName: System.Net.Configuration.SmtpSection.DeliveryFormat
- uid: System.Net.Mail.SmtpDeliveryFormat
  parent: System.Net.Mail
  isExternal: false
  name: SmtpDeliveryFormat
  nameWithType: SmtpDeliveryFormat
  fullName: System.Net.Mail.SmtpDeliveryFormat
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
  fullName: System.Net.Configuration.SmtpSection.DeliveryMethod
- uid: System.Net.Mail.SmtpDeliveryMethod
  parent: System.Net.Mail
  isExternal: false
  name: SmtpDeliveryMethod
  nameWithType: SmtpDeliveryMethod
  fullName: System.Net.Mail.SmtpDeliveryMethod
- uid: System.Net.Configuration.SmtpSection.From
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: From
  nameWithType: SmtpSection.From
  fullName: System.Net.Configuration.SmtpSection.From
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Net.Configuration.SmtpSection.Network
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Network
  nameWithType: SmtpSection.Network
  fullName: System.Net.Configuration.SmtpSection.Network
- uid: System.Net.Configuration.SmtpNetworkElement
  parent: System.Net.Configuration
  isExternal: false
  name: SmtpNetworkElement
  nameWithType: SmtpNetworkElement
  fullName: System.Net.Configuration.SmtpNetworkElement
- uid: System.Net.Configuration.SmtpSection.Properties
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Properties
  nameWithType: SmtpSection.Properties
  fullName: System.Net.Configuration.SmtpSection.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
  fullName: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory
- uid: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
  parent: System.Net.Configuration
  isExternal: false
  name: SmtpSpecifiedPickupDirectoryElement
  nameWithType: SmtpSpecifiedPickupDirectoryElement
  fullName: System.Net.Configuration.SmtpSpecifiedPickupDirectoryElement
- uid: System.Net.Configuration.SmtpSection.#ctor*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SmtpSection
  nameWithType: SmtpSection.SmtpSection
- uid: System.Net.Configuration.SmtpSection.DeliveryFormat*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryFormat
  nameWithType: SmtpSection.DeliveryFormat
- uid: System.Net.Configuration.SmtpSection.DeliveryMethod*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: DeliveryMethod
  nameWithType: SmtpSection.DeliveryMethod
- uid: System.Net.Configuration.SmtpSection.From*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: From
  nameWithType: SmtpSection.From
- uid: System.Net.Configuration.SmtpSection.Network*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Network
  nameWithType: SmtpSection.Network
- uid: System.Net.Configuration.SmtpSection.Properties*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: Properties
  nameWithType: SmtpSection.Properties
- uid: System.Net.Configuration.SmtpSection.SpecifiedPickupDirectory*
  parent: System.Net.Configuration.SmtpSection
  isExternal: false
  name: SpecifiedPickupDirectory
  nameWithType: SmtpSection.SpecifiedPickupDirectory
