### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.UpdateCheckInfo
  id: UpdateCheckInfo
  children:
  - System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  - System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  - System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  - System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  - System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  langs:
  - csharp
  name: UpdateCheckInfo
  nameWithType: UpdateCheckInfo
  fullName: System.Deployment.Application.UpdateCheckInfo
  type: Class
  summary: "Részletes frissítésekkel kapcsolatos információk <xref:System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate*>.</xref:System.Deployment.Application.ApplicationDeployment.CheckForDetailedUpdate*> hívásakor keresztül szerzett jelöli"
  remarks: "A UpdateCheckInfo dönthet úgy is, frissítsen a legújabb információk alapján ClickOnce alkalmazás-e. <xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A>jelzi, hogy van-e új frissítés minden logikai értéket ad eredményül.</xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A> A <xref:System.Deployment.Application.UpdateCheckInfo.AvailableVersion%2A>tulajdonság biztosítja az új verzió verziószáma közben <xref:System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion%2A>biztosít a legkorábbi verziót, amelyen telepítve van a felhasználó.</xref:System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion%2A> </xref:System.Deployment.Application.UpdateCheckInfo.AvailableVersion%2A> <xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A>fejezi ki, hogy a felhasználó szükség-e a legújabb frissítését.</xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A> Végezetül <xref:System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes%2A>fejezi ki a teljes mérete a frissítés.</xref:System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes%2A>      > [!NOTE] > Visual Studio hozzáadja a `<deploymentProvider>` elem a jegyzék csak akkor, ha az alkalmazáshoz be van állítva, a frissítések kereséséhez, vagy, hogy ellenőrizze, hogy **frissítések ellenőrizze az alkalmazás** , vagy adjon meg egy frissítési URL-CÍMÉT a **frissítési helyét** a a [alkalmazás frissítések párbeszédpanel](http://msdn.microsoft.com/en-us/8eca8743-8e68-4d04-bfd5-4dc0a9b2934f)."
  example:
  - "The following code example uses <xref:System.Deployment.Application.UpdateCheckInfo.UpdateAvailable%2A> to determine if there is a new application update, and <xref:System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired%2A> to determine whether to ask the user to install the update.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/t-system.deployment.appl_8_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public class UpdateCheckInfo
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  id: AvailableVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a verziószáma nem telepített legújabb verzióját."
  remarks: "AvailableVersion segítségével határozza meg, hogy telepítette a frissítést, a frissítés a súlyosság alapján. Például, ha csak a <xref:System.Version.Build%2A>vagy <xref:System.Version.Revision%2A>verzió tulajdonságai megváltoztak, az alkalmazás nem frissítésére lehet szükség amíg újra nem indítják a <xref:System.Version.Minor%2A>vagy <xref:System.Version.Major%2A>tulajdonságainak módosítása.</xref:System.Version.Major%2A> </xref:System.Version.Minor%2A> </xref:System.Version.Revision%2A> </xref:System.Version.Build%2A>"
  syntax:
    content: public Version AvailableVersion { get; }
    return:
      type: System.Version
      description: "A <xref:System.Version>kifejező, a fő- és alverzió és számát a legújabb verzióra.</xref:System.Version>"
  overload: System.Deployment.Application.UpdateCheckInfo.AvailableVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  id: IsUpdateRequired
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
  fullName: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy érték, amely jelzi, hogy a frissítés telepítve kell lekérdezi."
  remarks: "Amikor frissítést telepít a ClickOnce alkalmazáshoz, megjelölheti azt egy kötelező frissítés, mert jelzés az alkalmazáshoz, hogy azonnal kell frissíteni. Jelölje meg az alkalmazást, ha a legújabb verzióra olyan fontos frissítést tartalmaz, vagy nem kompatibilis a formátumok vagy a korábbi verziója által használt háttér-adatforrás esetén szeretné."
  example:
  - "The following code example uses IsUpdateRequired to determine whether to ask the user to install the update, or to install it without prompting.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_6_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public bool IsUpdateRequired { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a frissítés szükség; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  id: MinimumRequiredVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a felhasználó a számítógépen telepítve kell rendelkeznie a megengedett legrégebbi verzió."
  remarks: "Alkalmazások is teljesíti a szükséges frissítéseket, ha a felhasználó időt vesz igénybe az egy különös hozzárendelés vagy a számítógép el a hét és hónap. Minimumrequiredversion tulajdonság segítségével határozza meg, ha a felhasználó nem frissítette az alkalmazást egy kicsit, és hiányzik egy vagy több szükséges frissítéseket."
  example:
  - "The following code example demonstrates displaying the MinimumRequiredVersion property to the user when there is a required update available.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_1_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public Version MinimumRequiredVersion { get; }
    return:
      type: System.Version
      description: "A <xref:System.Version>kifejezése, amely a felhasználó telepíteni kell a legalább verzió.</xref:System.Version>"
  overload: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion*
  exceptions:
  - type: System.InvalidOperationException
    commentId: T:System.InvalidOperationException
    description: "Nem áll a telepítésre új verziója van."
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  id: UpdateAvailable
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi, hogy nem telepített frissítés érhető el."
  remarks: ''
  example:
  - "The following code example inspects UpdateAvailable to determine whether there is an update to install.  \n  \n [!code-cs[ClickOnceAPI#6](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#6)]\n [!code-cpp[ClickOnceAPI#6](~/add/codesnippet/cpp/p-system.deployment.appl_10_1.cpp)]\n [!code-vb[ClickOnceAPI#6](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#6)]"
  syntax:
    content: public bool UpdateAvailable { get; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha az alkalmazás új verziója érhető el; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  id: UpdateSizeBytes
  parent: System.Deployment.Application.UpdateCheckInfo
  langs:
  - csharp
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi az elérhető frissítésekkel méretét."
  syntax:
    content: public long UpdateSizeBytes { get; }
    return:
      type: System.Int64
      description: "Egy <xref:System.Int64>leíró méretét, bájtban az elérhető frissítésekkel.</xref:System.Int64> Ha a frissítés nem érhető el, a 0 értéket adja vissza."
  overload: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.InvalidOperationException
  isExternal: true
  name: System.InvalidOperationException
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.AvailableVersion
- uid: System.Version
  parent: System
  isExternal: true
  name: Version
  nameWithType: Version
  fullName: System.Version
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
  fullName: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
  fullName: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
  fullName: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.Deployment.Application.UpdateCheckInfo.AvailableVersion*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: AvailableVersion
  nameWithType: UpdateCheckInfo.AvailableVersion
- uid: System.Deployment.Application.UpdateCheckInfo.IsUpdateRequired*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: IsUpdateRequired
  nameWithType: UpdateCheckInfo.IsUpdateRequired
- uid: System.Deployment.Application.UpdateCheckInfo.MinimumRequiredVersion*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: MinimumRequiredVersion
  nameWithType: UpdateCheckInfo.MinimumRequiredVersion
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateAvailable*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateAvailable
  nameWithType: UpdateCheckInfo.UpdateAvailable
- uid: System.Deployment.Application.UpdateCheckInfo.UpdateSizeBytes*
  parent: System.Deployment.Application.UpdateCheckInfo
  isExternal: false
  name: UpdateSizeBytes
  nameWithType: UpdateCheckInfo.UpdateSizeBytes
