### YamlMime:ManagedReference
items:
- uid: System.Data.Services.IDataServiceConfiguration
  id: IDataServiceConfiguration
  children:
  - System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  - System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  - System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  - System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  - System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  - System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  - System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  - System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  - System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  langs:
  - csharp
  name: IDataServiceConfiguration
  nameWithType: IDataServiceConfiguration
  fullName: System.Data.Services.IDataServiceConfiguration
  type: Interface
  summary: "A IDataServiceConfiguration által használt [!INCLUDE[ssAstoria](~/add/includes/ssastoria-md.md)] jogosultságokkal a entitáskészletekben és szolgáltatási műveleteket, beleértve a szolgáltatás működésének beállításához korlátozza az engedélyezett kérelmek, alapértelmezés szerint, és az alapértelmezett részletességi a hibakezelés nem felderíthető típusok regisztrálása."
  remarks: "Ezt a típust <xref:System.Data.Services.DataService%601>statikus metódus végrehajtása a szolgáltatás konfigurálásához osztályok nevű InitializeService, vissza &quot;void&quot;, és egyetlen argumentuma IDataServiceConfiguration típusú véve.</xref:System.Data.Services.DataService%601> A konfigurációs objektum csak a szolgáltatás inicializálása hívása során használható."
  syntax:
    content: public interface IDataServiceConfiguration
  implements: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  id: MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Egy kötegben lekérdezi a kezelhető kérelmek maximális száma."
  syntax:
    content: public int MaxBatchCount { get; set; }
    return:
      type: System.Int32
      description: "Egész szám, amely jelzi a kötegben kezelhető kérelmek maximális száma."
  overload: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  id: MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Tudnak kezelni módosításkészletet maximális számának beolvasása kötegben."
  syntax:
    content: public int MaxChangesetCount { get; set; }
    return:
      type: System.Int32
      description: "Egész szám, amely azt jelzi, amely egy kötegelt kezelhető módosításkészletet maximális száma."
  overload: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  id: MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Lekérdezi vagy beállítja azt a maximális számát és a $ bővíthetők szegmensek bontsa ki a lekérdezés beállítás megadása a szolgáltatás minden kérelemhez."
  remarks: "Ha a meghaladja a korlátozást, 400 Hibás kérés állapotkód ad vissza. A megadott érték 0 között kell lennie, és `int.MaxValue`; ellenkező esetben egy `ArgumentOutOfRangeException` vált ki.       A következő lekérdezési karakterlánc minta két szegmensből áll:"
  syntax:
    content: public int MaxExpandCount { get; set; }
    return:
      type: System.Int32
      description: "Bontsa ki a szegmensek maximális számát."
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  id: MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Lekérdezi vagy beállítja azt az egyetlen támogatott szegmensek maximális számát `$expand` adatszolgáltatás összes kérelem elérési útját."
  remarks: "Ha a meghaladja a korlátozást, 400 Hibás kérés állapotkód ad vissza. A megadott érték 0 között kell lennie, és `int.MaxValue`; ellenkező esetben egy `ArgumentOutOfRangeException` vált ki.       A következő lekérdezési karakterlánc minta két szegmenst tartalmaz, az első `$expand` elérési utat és egy második `$expand` elérési útja:"
  syntax:
    content: public int MaxExpandDepth { get; set; }
    return:
      type: System.Int32
      description: "A maximális számát jelző egész számot támogatott szegmenseinek `$expand` elérési útja."
  overload: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  id: MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Lekérdezi vagy beállítja az egy kérelemhez lehet beszúrni objektumok maximális számát."
  syntax:
    content: public int MaxObjectCountOnInsert { get; set; }
    return:
      type: System.Int32
      description: "Az egész szám, amely tartalmazza az egy kérelemhez lehet beszúrni objektumok maximális számát."
  overload: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  id: MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Lekérdezi a gyűjteményenként eredmények maximális száma."
  syntax:
    content: public int MaxResultsPerCollection { get; set; }
    return:
      type: System.Int32
      description: "Az egész szám, amely jelzi a gyűjteményenként eredmények maximális száma."
  overload: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  id: RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "A data Service regisztrálja a használatra erőforrástípus."
  syntax:
    content: public void RegisterKnownType (Type type);
    parameters:
    - id: type
      type: System.Type
      description: "Az erőforrástípus regisztrálni."
  overload: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  id: SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Beállítja a megadott entitás hozzáférési szabályainak beállítása."
  remarks: "Az alapértelmezett konfigurálás az, hogy megtagadja a hozzáférést az erőforrásokhoz. A szolgáltatás inicializálásakor a hozzáférési jogok engedélyezve kell lennie."
  syntax:
    content: public void SetEntitySetAccessRule (string name, System.Data.Services.EntitySetRights rights);
    parameters:
    - id: name
      type: System.String
      description: "A beállított hozzáférés entitáskészlet neve."
    - id: rights
      type: System.Data.Services.EntitySetRights
      description: "A jogosultságok, a következő entitáskészlet engedélyezett."
  overload: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  id: SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  type: Method
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "A megadott műveletet hozzáférési szabályainak beállítása."
  remarks: "Az alapértelmezett konfigurálás az, hogy megtagadja a hozzáférést az erőforrásokhoz. A szolgáltatás inicializálásakor a hozzáférési jogok engedélyezve kell lennie."
  syntax:
    content: public void SetServiceOperationAccessRule (string name, System.Data.Services.ServiceOperationRights rights);
    parameters:
    - id: name
      type: System.String
      description: "A neve, amelyen beállítható a hozzáférési jogosultságokat a szolgáltatási művelet."
    - id: rights
      type: System.Data.Services.ServiceOperationRights
      description: "A jogok a következők szerint engedélyezett <xref href=&quot;System.Data.Services.ServiceOperationRights&quot;> </xref> enumerálása."
  overload: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  id: UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  langs:
  - csharp
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  type: Property
  assemblies:
  - System.Data.Services
  namespace: System.Data.Services
  summary: "Lekérdezi vagy beállítja, hogy részletes hibák esetén alapértelmezés szerint az adatszolgáltatás összes válaszát."
  remarks: "A megadott kérelem válaszára felülbírálhatják az adatok service fejlesztői felülbírálásával a `HandleException` metódust. Részletes hibák csak akkor engedélyezhető, nem éles környezetben, biztonsági okokból a fejlesztés során."
  syntax:
    content: public bool UseVerboseErrors { get; set; }
    return:
      type: System.Boolean
      description: "Logikai érték, amely jelzi, hogy részletes jelez hibát."
  overload: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxBatchCount
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
  fullName: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
  fullName: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
  fullName: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(System.Type)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType(Type)
  nameWithType: IDataServiceConfiguration.RegisterKnownType(Type)
  fullName: System.Data.Services.IDataServiceConfiguration.RegisterKnownType(Type)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(System.String,System.Data.Services.EntitySetRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule(String,EntitySetRights)
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule(String,EntitySetRights)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Services.EntitySetRights
  parent: System.Data.Services
  isExternal: false
  name: EntitySetRights
  nameWithType: EntitySetRights
  fullName: System.Data.Services.EntitySetRights
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(System.String,System.Data.Services.ServiceOperationRights)
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule(String,ServiceOperationRights)
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
  fullName: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule(String,ServiceOperationRights)
- uid: System.Data.Services.ServiceOperationRights
  parent: System.Data.Services
  isExternal: false
  name: ServiceOperationRights
  nameWithType: ServiceOperationRights
  fullName: System.Data.Services.ServiceOperationRights
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
  fullName: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.Data.Services.IDataServiceConfiguration.MaxBatchCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxBatchCount
  nameWithType: IDataServiceConfiguration.MaxBatchCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxChangesetCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxChangesetCount
  nameWithType: IDataServiceConfiguration.MaxChangesetCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandCount*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandCount
  nameWithType: IDataServiceConfiguration.MaxExpandCount
- uid: System.Data.Services.IDataServiceConfiguration.MaxExpandDepth*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxExpandDepth
  nameWithType: IDataServiceConfiguration.MaxExpandDepth
- uid: System.Data.Services.IDataServiceConfiguration.MaxObjectCountOnInsert*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxObjectCountOnInsert
  nameWithType: IDataServiceConfiguration.MaxObjectCountOnInsert
- uid: System.Data.Services.IDataServiceConfiguration.MaxResultsPerCollection*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: MaxResultsPerCollection
  nameWithType: IDataServiceConfiguration.MaxResultsPerCollection
- uid: System.Data.Services.IDataServiceConfiguration.RegisterKnownType*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: RegisterKnownType
  nameWithType: IDataServiceConfiguration.RegisterKnownType
- uid: System.Data.Services.IDataServiceConfiguration.SetEntitySetAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetEntitySetAccessRule
  nameWithType: IDataServiceConfiguration.SetEntitySetAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.SetServiceOperationAccessRule*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: SetServiceOperationAccessRule
  nameWithType: IDataServiceConfiguration.SetServiceOperationAccessRule
- uid: System.Data.Services.IDataServiceConfiguration.UseVerboseErrors*
  parent: System.Data.Services.IDataServiceConfiguration
  isExternal: false
  name: UseVerboseErrors
  nameWithType: IDataServiceConfiguration.UseVerboseErrors
