### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DeploymentDownloadException
  id: DeploymentDownloadException
  children:
  - System.Deployment.Application.DeploymentDownloadException.#ctor
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: DeploymentDownloadException
  nameWithType: DeploymentDownloadException
  fullName: System.Deployment.Application.DeploymentDownloadException
  type: Class
  summary: "Azt jelzi, hogy letöltése vagy hiba történt a [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] jegyzékfájlokban vagy a telepítési fájlok az ügyfélszámítógépen."
  remarks: "Egy DeploymentDownloadException arra utal, hogy számos probléma történt, amikor a felhasználó megpróbálta letölteni egy [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] alkalmazás frissítése:-az ügyfél számítógépének hálózati kapcsolat nem működik.      -A webkiszolgálón, FTP-kiszolgáló vagy a frissítés üzemeltető fájlmegosztás nem érhető el.      -Egy vagy több, a fájl a [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] központi telepítés nem található.       Kapcsolatos kivétel hibával kapcsolatos részletes információk beszerzéséhez olvassa el a [!INCLUDE[ndptecclick](~/add/includes/ndptecclick-md.md)] hibanaplóját. További információkért lásd: [hibaelhárítási ClickOnce telepítések](~/add/includes/ajax-current-ext-md.md)."
  example:
  - "The following code example installs an application update synchronously, and reports to the user if there was a problem downloading either the manifests or the deployment's files.  \n  \n [!code-cs[ClickOnceAPI#5](~/add/codesnippet/csharp/ClickOnceAPI/Form1.cs#5)]\n [!code-cpp[ClickOnceAPI#5](~/add/codesnippet/cpp/t-system.deployment.appl_2_1.cpp)]\n [!code-vb[ClickOnceAPI#5](~/add/codesnippet/visualbasic/ClickOnceAPIVB/Form1.vb#5)]"
  syntax:
    content: 'public class DeploymentDownloadException : System.Deployment.Application.DeploymentException'
  inheritance:
  - System.Exception
  - System.SystemException
  - System.Deployment.Application.DeploymentException
  implements: []
  inheritedMembers:
  - System.Deployment.Application.DeploymentException.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor
  id: '#ctor'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException()
  nameWithType: DeploymentDownloadException.DeploymentDownloadException()
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException()
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref> osztály."
  syntax:
    content: public DeploymentDownloadException ();
    parameters: []
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(String)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref> osztály, amely leírja a kivétel üzenetet."
  syntax:
    content: public DeploymentDownloadException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref> osztály."
  syntax:
    content: protected DeploymentDownloadException (System.Runtime.Serialization.SerializationInfo serializationInfo, System.Runtime.Serialization.StreamingContext streamingContext);
    parameters:
    - id: serializationInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "A szerializált objektum adatokat tartalmazó objektum."
    - id: streamingContext
      type: System.Runtime.Serialization.StreamingContext
      description: "A cél- és környezeti információt."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Deployment.Application.DeploymentDownloadException
  langs:
  - csharp
  name: DeploymentDownloadException(String,Exception)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  type: Constructor
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Deployment.Application.DeploymentDownloadException&quot;> </xref> osztály."
  syntax:
    content: public DeploymentDownloadException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A kivétel leíró üzenet. Ez a konstruktor védőfalkezelőbe annak érdekében szükség, hogy ez a karakterlánc a jelenlegi rendszer kulturális környezethez tartozó honosított."
    - id: innerException
      type: System.Exception
      description: "A kivétellel, hogy a jelenlegi kivétel okozza. Ha a `innerException` paraméter nem <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a jelenlegi kivétel a következik be egy <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> blokk, amely kezeli a belső kivételben találhatók."
  overload: System.Deployment.Application.DeploymentDownloadException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Deployment.Application.DeploymentException
  isExternal: false
  name: System.Deployment.Application.DeploymentException
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException()
  nameWithType: DeploymentDownloadException.DeploymentDownloadException()
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException()
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(String)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(SerializationInfo,StreamingContext)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor(System.String,System.Exception)
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException(String,Exception)
  nameWithType: DeploymentDownloadException.DeploymentDownloadException(String,Exception)
  fullName: System.Deployment.Application.DeploymentDownloadException.DeploymentDownloadException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Deployment.Application.DeploymentDownloadException.#ctor*
  parent: System.Deployment.Application.DeploymentDownloadException
  isExternal: false
  name: DeploymentDownloadException
  nameWithType: DeploymentDownloadException.DeploymentDownloadException
