### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.Configuration.FilterType
  id: FilterType
  children:
  - System.ServiceModel.Routing.Configuration.FilterType.Action
  - System.ServiceModel.Routing.Configuration.FilterType.And
  - System.ServiceModel.Routing.Configuration.FilterType.Custom
  - System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
  - System.ServiceModel.Routing.Configuration.FilterType.EndpointName
  - System.ServiceModel.Routing.Configuration.FilterType.MatchAll
  - System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
  - System.ServiceModel.Routing.Configuration.FilterType.XPath
  langs:
  - csharp
  name: FilterType
  nameWithType: FilterType
  fullName: System.ServiceModel.Routing.Configuration.FilterType
  type: Enum
  summary: "Határozza meg a szűrő üzenetek útválasztási használandó."
  remarks: '[!INCLUDE[crabout](~/add/includes/ajax-current-ext-md.md)]<xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterData%2A>.</xref:System.ServiceModel.Routing.Configuration.FilterElement.FilterData%2A> FilterType használatával, lásd:'
  syntax:
    content: public enum FilterType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterType.Action
  id: Action
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: Action
  nameWithType: FilterType.Action
  fullName: System.ServiceModel.Routing.Configuration.FilterType.Action
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Használjon <xref href=&quot;System.ServiceModel.Dispatcher.ActionMessageFilter&quot;> </xref> szűrési művelet."
  syntax:
    content: Action
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterType.And
  id: And
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: And
  nameWithType: FilterType.And
  fullName: System.ServiceModel.Routing.Configuration.FilterType.And
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Használjon <xref href=&quot;System.ServiceModel.Dispatcher.StrictAndMessageFilter&quot;> </xref> együtt szűréshez két üzenet szűrőt, a műveletet."
  syntax:
    content: And
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterType.Custom
  id: Custom
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: Custom
  nameWithType: FilterType.Custom
  fullName: System.ServiceModel.Routing.Configuration.FilterType.Custom
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Felhasználó által definiált szűrő használata."
  syntax:
    content: Custom
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
  id: EndpointAddress
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: EndpointAddress
  nameWithType: FilterType.EndpointAddress
  fullName: System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Használjon <xref href=&quot;System.ServiceModel.Dispatcher.EndpointAddressMessageFilter&quot;> </xref> a <> </> *> beállítása * *hamis** szűrése a címe."
  syntax:
    content: EndpointAddress
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterType.EndpointName
  id: EndpointName
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: EndpointName
  nameWithType: FilterType.EndpointName
  fullName: System.ServiceModel.Routing.Configuration.FilterType.EndpointName
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Használja a <xref href=&quot;System.ServiceModel.Dispatcher.EndpointNameMessageFilter&quot;> </xref> szűrése a szolgáltatásvégpont neve."
  syntax:
    content: EndpointName
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterType.MatchAll
  id: MatchAll
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: MatchAll
  nameWithType: FilterType.MatchAll
  fullName: System.ServiceModel.Routing.Configuration.FilterType.MatchAll
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Használja a <xref href=&quot;System.ServiceModel.Dispatcher.MatchAllMessageFilter&quot;> </xref> összes üzenet kereséséhez."
  syntax:
    content: MatchAll
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
  id: PrefixEndpointAddress
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: PrefixEndpointAddress
  nameWithType: FilterType.PrefixEndpointAddress
  fullName: System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Használjon <xref href=&quot;System.ServiceModel.Dispatcher.PrefixEndpointAddressMessageFilter&quot;> </xref> a <> </> *> beállítása * *hamis** előtag-megfeleltetéssel leghosszabb cím szűréshez."
  syntax:
    content: PrefixEndpointAddress
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.Configuration.FilterType.XPath
  id: XPath
  parent: System.ServiceModel.Routing.Configuration.FilterType
  langs:
  - csharp
  name: XPath
  nameWithType: FilterType.XPath
  fullName: System.ServiceModel.Routing.Configuration.FilterType.XPath
  type: Field
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing.Configuration
  summary: "Használja a <xref href=&quot;System.ServiceModel.Dispatcher.XPathMessageFilter&quot;> </xref> szűrése XPath kifejezés."
  syntax:
    content: XPath
    return:
      type: System.ServiceModel.Routing.Configuration.FilterType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.ServiceModel.Routing.Configuration.FilterType.Action
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: Action
  nameWithType: FilterType.Action
  fullName: System.ServiceModel.Routing.Configuration.FilterType.Action
- uid: System.ServiceModel.Routing.Configuration.FilterType
  parent: System.ServiceModel.Routing.Configuration
  isExternal: false
  name: FilterType
  nameWithType: FilterType
  fullName: System.ServiceModel.Routing.Configuration.FilterType
- uid: System.ServiceModel.Routing.Configuration.FilterType.And
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: And
  nameWithType: FilterType.And
  fullName: System.ServiceModel.Routing.Configuration.FilterType.And
- uid: System.ServiceModel.Routing.Configuration.FilterType.Custom
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: Custom
  nameWithType: FilterType.Custom
  fullName: System.ServiceModel.Routing.Configuration.FilterType.Custom
- uid: System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: EndpointAddress
  nameWithType: FilterType.EndpointAddress
  fullName: System.ServiceModel.Routing.Configuration.FilterType.EndpointAddress
- uid: System.ServiceModel.Routing.Configuration.FilterType.EndpointName
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: EndpointName
  nameWithType: FilterType.EndpointName
  fullName: System.ServiceModel.Routing.Configuration.FilterType.EndpointName
- uid: System.ServiceModel.Routing.Configuration.FilterType.MatchAll
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: MatchAll
  nameWithType: FilterType.MatchAll
  fullName: System.ServiceModel.Routing.Configuration.FilterType.MatchAll
- uid: System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: PrefixEndpointAddress
  nameWithType: FilterType.PrefixEndpointAddress
  fullName: System.ServiceModel.Routing.Configuration.FilterType.PrefixEndpointAddress
- uid: System.ServiceModel.Routing.Configuration.FilterType.XPath
  parent: System.ServiceModel.Routing.Configuration.FilterType
  isExternal: false
  name: XPath
  nameWithType: FilterType.XPath
  fullName: System.ServiceModel.Routing.Configuration.FilterType.XPath
