### YamlMime:ManagedReference
items:
- uid: System.Configuration.NameValueFileSectionHandler
  id: NameValueFileSectionHandler
  children:
  - System.Configuration.NameValueFileSectionHandler.#ctor
  - System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  langs:
  - csharp
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler
  fullName: System.Configuration.NameValueFileSectionHandler
  type: Class
  summary: "Egy konfigurációs fájl hozzáférést biztosít. Ez a típus a .NET-keretrendszer konfigurációs infrastruktúrája támogatja, és nem javasolt közvetlenül a kódból használni."
  remarks: "A `file` attribútuma a `<appSettings>` szakasz elérési útja relatív egy külső, egyéni alkalmazás-konfigurációs beállításokat tartalmazó fájl. A fájlban megadott adatok működjön, és egy `<appSettings>` szakasz a konfigurációs fájlban. A fájl a NameValueFileSectionHandler osztály használatával érhető el. A fájl gyökérelemnek meg kell egyeznie a szakasz az arra való hivatkozás."
  syntax:
    content: 'public class NameValueFileSectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.NameValueFileSectionHandler&quot;> </xref> osztály."
  syntax:
    content: public NameValueFileSectionHandler ();
    parameters: []
  overload: System.Configuration.NameValueFileSectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Létrehoz egy új konfigurációs kezelője, és hozzáadja azt a szakasz-kezelőjének gyűjtemény a megadott paraméterek alapján."
  remarks: "A `parent` objektumparaméterek úgy működik, mint a konfigurációs beállításokat a megfelelő szülő konfigurációs szakaszban. A `configContext` objektum paraméter értéke, amelynek a konfigurációs szakasz kezelőjének kiszámítja a konfigurációs értékek virtuális elérési utat. Általában ez a paraméter fenntartva, és van `null`. A `section` paraméter a <xref:System.Xml.XmlNode>kezelni kívánt konfigurációs információkat tartalmazza, amelyek.</xref:System.Xml.XmlNode> A `section` paramétert a konfigurációs szakasz az XML-tartalmának közvetlen hozzáférést biztosít."
  syntax:
    content: public object Create (object parent, object configContext, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "A szülői objektumon."
    - id: configContext
      type: System.Object
      description: "A konfigurációs környezeti objektumot."
    - id: section
      type: System.Xml.XmlNode
      description: "A szakasz XML-csomópontot."
    return:
      type: System.Object
      description: "Egy konfigurációs objektumot."
  overload: System.Configuration.NameValueFileSectionHandler.Create*
  exceptions:
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "The file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute of <code>section</code> exists but cannot be loaded.  \n  \n \\- or -  \n  \n The <xref uid=\"langword_csharp_name\" name=\"name\" href=\"\"></xref> attribute of <code>section</code> does not match the root element of the file specified in the <xref uid=\"langword_csharp_file\" name=\"file\" href=\"\"></xref> attribute."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.Configuration.NameValueFileSectionHandler.#ctor
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler()
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler()
  fullName: System.Configuration.NameValueFileSectionHandler.NameValueFileSectionHandler()
- uid: System.Configuration.NameValueFileSectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: NameValueFileSectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.NameValueFileSectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.NameValueFileSectionHandler.#ctor*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: NameValueFileSectionHandler
  nameWithType: NameValueFileSectionHandler.NameValueFileSectionHandler
- uid: System.Configuration.NameValueFileSectionHandler.Create*
  parent: System.Configuration.NameValueFileSectionHandler
  isExternal: false
  name: Create
  nameWithType: NameValueFileSectionHandler.Create
