### YamlMime:ManagedReference
items:
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  id: DownloadApplicationCompletedEventArgs
  children:
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  - System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  langs:
  - csharp
  name: DownloadApplicationCompletedEventArgs
  nameWithType: DownloadApplicationCompletedEventArgs
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  type: Class
  summary: "Adja meg az adatait a <xref href=&quot;System.Deployment.Application.InPlaceHostingManager.DownloadApplicationCompleted&quot;> </xref> esemény."
  syntax:
    content: 'public class DownloadApplicationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs'
  inheritance:
  - System.ComponentModel.AsyncCompletedEventArgs
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  id: LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a ClickOnce naplófájl elérési útját."
  syntax:
    content: public string LogFilePath { get; }
    return:
      type: System.String
      description: "A ClickOnce naplófájl elérési útja."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  exceptions: []
  platform:
  - net462
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  id: ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  langs:
  - csharp
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  type: Property
  assemblies:
  - System.Deployment
  namespace: System.Deployment.Application
  summary: "Lekérdezi a tartalmát egy .appref-ms-fájl, amely a ClickOnce alkalmazáshoz is elindíthatja."
  remarks: 'Ez a tulajdonság a szöveget tartalmaz egy egyéni telepítő írhat a ClickOnce alkalmazás futtatására tett .appref-ms-fájlba. ClickOnce által létrehozott indítsa el az Ön olyan ClickOnce alkalmazásokhoz, kapcsolat nélkül is elérhető, kivéve, amely tartalmazza az alkalmazások telepítése során a `<customUX>` elemet. Egy egyéni telepítő hozhat létre egy parancsikont a ClickOnce-alkalmazást, amely tartalmaz egy `<customUX>` elem írásával a szöveg ebben a tulajdonságban egy új .appref-ms-fájl Unicode formátumú. További információkért lásd: [ \&lt; entryPoint\&gt; Elem](../Topic/%3CentryPoint%3E%20Element%20\(ClickOnce%20Application\).md) és [forgatókönyv: Egyéni telepítőt ClickOnce alkalmazáshoz létrehozása](~/add/includes/ajax-current-ext-md.md).'
  syntax:
    content: public string ShortcutAppId { get; }
    return:
      type: System.String
      description: "Egy .appref-ms-fájl tartalmát."
  overload: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ComponentModel.AsyncCompletedEventArgs
  isExternal: false
  name: System.ComponentModel.AsyncCompletedEventArgs
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
  fullName: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.LogFilePath*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: LogFilePath
  nameWithType: DownloadApplicationCompletedEventArgs.LogFilePath
- uid: System.Deployment.Application.DownloadApplicationCompletedEventArgs.ShortcutAppId*
  parent: System.Deployment.Application.DownloadApplicationCompletedEventArgs
  isExternal: false
  name: ShortcutAppId
  nameWithType: DownloadApplicationCompletedEventArgs.ShortcutAppId
