### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Routing.RoutingConfiguration
  id: RoutingConfiguration
  children:
  - System.ServiceModel.Routing.RoutingConfiguration.#ctor
  - System.ServiceModel.Routing.RoutingConfiguration.#ctor(System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}},System.Boolean)
  - System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
  - System.ServiceModel.Routing.RoutingConfiguration.FilterTable
  - System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
  - System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
  langs:
  - csharp
  name: RoutingConfiguration
  nameWithType: RoutingConfiguration
  fullName: System.ServiceModel.Routing.RoutingConfiguration
  type: Class
  summary: "Meghatározza a által használt konfigurációs információk <xref href=&quot;System.ServiceModel.Routing.RoutingExtension&quot;> </xref>."
  syntax:
    content: public sealed class RoutingConfiguration
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: RoutingConfiguration()
  nameWithType: RoutingConfiguration.RoutingConfiguration()
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RoutingConfiguration()
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.ServiceModel.Routing.RoutingConfiguration&quot;> </xref> osztály."
  syntax:
    content: public RoutingConfiguration ();
    parameters: []
  overload: System.ServiceModel.Routing.RoutingConfiguration.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor(System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}},System.Boolean)
  id: '#ctor(System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}},System.Boolean)'
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  nameWithType: RoutingConfiguration.RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  type: Constructor
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Létrehoz egy új példányt a <xref href=&quot;System.ServiceModel.Routing.RoutingConfiguration&quot;> </xref> használata a megadott osztály &lt;xref:System.ServiceModel.Dispatcher.MessageFilterTable%601&gt; és routeOnHeadersOnly paraméter."
  syntax:
    content: public RoutingConfiguration (System.ServiceModel.Dispatcher.MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>> filterTable, bool routeOnHeadersOnly);
    parameters:
    - id: filterTable
      type: System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}}
      description: "Az üzenet szűrőtáblában ehhez a konfigurációhoz használni."
    - id: routeOnHeadersOnly
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a &lt;xref:System.ServiceModel.Dispatcher.MessageFilterTable%601&gt; csak ellenőrizheti üzenetfejlécek; ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Routing.RoutingConfiguration.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
  id: EnsureOrderedDispatch
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: EnsureOrderedDispatch
  nameWithType: RoutingConfiguration.EnsureOrderedDispatch
  fullName: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Egy érték, amely azt jelzi, hogy üzenetek küldés sorrendjében küldik lekérdezi."
  syntax:
    content: public bool EnsureOrderedDispatch { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha üzenetek sorrendben történő küldés; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.RoutingConfiguration.FilterTable
  id: FilterTable
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: FilterTable
  nameWithType: RoutingConfiguration.FilterTable
  fullName: System.ServiceModel.Routing.RoutingConfiguration.FilterTable
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Lekérdezi vagy beállítja a &lt;xref:System.ServiceModel.Dispatcher.MessageFilterTable%601&gt; használják ezt a konfigurációt."
  syntax:
    content: public System.ServiceModel.Dispatcher.MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>> FilterTable { get; }
    return:
      type: System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}}
      description: "Az üzenet szűrőtáblában."
  overload: System.ServiceModel.Routing.RoutingConfiguration.FilterTable*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
  id: RouteOnHeadersOnly
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: RouteOnHeadersOnly
  nameWithType: RoutingConfiguration.RouteOnHeadersOnly
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Lekérdezi vagy beállítja egy érték, amely azt jelzi, hogy a szűrő ellenőrizheti az üzenet törzse."
  syntax:
    content: public bool RouteOnHeadersOnly { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha a szűrő csak ellenőrizheti üzenetfejlécek; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték **igaz**."
  overload: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
  id: SoapProcessingEnabled
  parent: System.ServiceModel.Routing.RoutingConfiguration
  langs:
  - csharp
  name: SoapProcessingEnabled
  nameWithType: RoutingConfiguration.SoapProcessingEnabled
  fullName: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
  type: Property
  assemblies:
  - System.ServiceModel.Routing
  namespace: System.ServiceModel.Routing
  summary: "Lekérdez vagy beállít egy értéket, amely jelzi, hogy üzenetek fel kell dolgozni között SOAP <xref:System.ServiceModel.Channels.MessageVersion>használatát.</xref:System.ServiceModel.Channels.MessageVersion>"
  remarks: "SOAP-feldolgozás az a folyamat, ahol alakítja a üzenetek között SOAP <xref:System.ServiceModel.Channels.MessageVersion>használatát.</xref:System.ServiceModel.Channels.MessageVersion>       Az érték `false` azt jelzi, hogy a <xref:System.ServiceModel.Routing.RoutingBehavior>ne telepítse a <xref:System.ServiceModel.Routing.SoapProcessingBehavior>az ügyfél végpontokon.</xref:System.ServiceModel.Routing.SoapProcessingBehavior> </xref:System.ServiceModel.Routing.RoutingBehavior> Ha beállítása `false`, hozzá kell adnia a saját üzenet inspector vagy más kód üzenetek az egyes funkcióit kezelésére megkövetelése azok elküldéséhez. Akkor is SOAP-feldolgozás esetén a végpontok letiltása. [!INCLUDE[crdefault](~/add/includes/ajax-current-ext-md.md)]az <xref:System.ServiceModel.Routing.SoapProcessingBehavior>osztályhoz.</xref:System.ServiceModel.Routing.SoapProcessingBehavior>       Alapértelmezés szerint a <xref:System.ServiceModel.Routing.RoutingBehavior>hoz létre, és csatolja új <xref:System.ServiceModel.Routing.SoapProcessingBehavior>rendelkező <xref:System.ServiceModel.Routing.SoapProcessingBehavior.ProcessMessages%2A>beállítása `true` ügyfél végpontok.</xref:System.ServiceModel.Routing.SoapProcessingBehavior.ProcessMessages%2A> </xref:System.ServiceModel.Routing.SoapProcessingBehavior> </xref:System.ServiceModel.Routing.RoutingBehavior> Ha nem szeretné használni a <xref:System.ServiceModel.Routing.SoapProcessingBehavior>egy különös végpontot, hozzon létre egy új <xref:System.ServiceModel.Routing.SoapProcessingBehavior>ezen érték `false` majd csatolja a végponthoz, amelyeken nem szeretné, hogy feldolgozása megtörténik.</xref:System.ServiceModel.Routing.SoapProcessingBehavior> </xref:System.ServiceModel.Routing.SoapProcessingBehavior> Ha a <xref:System.ServiceModel.Routing.RoutingBehavior>figyelembe veszi, hogy az ügyfél már rendelkezik egy <xref:System.ServiceModel.Routing.SoapProcessingBehavior>, próbáljon csatlakoztatni egy másik.</xref:System.ServiceModel.Routing.SoapProcessingBehavior> </xref:System.ServiceModel.Routing.RoutingBehavior>       <xref:System.ServiceModel.Routing.SoapProcessingBehavior>A tetszőleges végpontot, tiltsa le a SOAP-feldolgozás <xref:System.ServiceModel.Routing.RoutingBehavior>és a <xref:System.ServiceModel.Routing.RoutingConfiguration>.</xref:System.ServiceModel.Routing.RoutingConfiguration> </xref:System.ServiceModel.Routing.RoutingBehavior> </xref:System.ServiceModel.Routing.SoapProcessingBehavior> alkalmazásának letiltása       Ha SoapProcessingEnabled `true`, a <xref:System.ServiceModel.Routing.SoapProcessingBehavior>hozzáadódik az ügyfél végpont <xref:System.ServiceModel.Description.ServiceEndpoint.Behaviors%2A>gyűjtemény.</xref:System.ServiceModel.Description.ServiceEndpoint.Behaviors%2A> </xref:System.ServiceModel.Routing.SoapProcessingBehavior>"
  syntax:
    content: public bool SoapProcessingEnabled { get; set; }
    return:
      type: System.Boolean
      description: "<xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;></xref>Ha üzenetek fel kell dolgozni; Ellenkező esetben <xref uid=&quot;langword_csharp_false&quot; name=&quot;false&quot; href=&quot;&quot;> </xref>. Az alapértelmezett érték <xref uid=&quot;langword_csharp_true&quot; name=&quot;true&quot; href=&quot;&quot;> </xref>."
  overload: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RoutingConfiguration()
  nameWithType: RoutingConfiguration.RoutingConfiguration()
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RoutingConfiguration()
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor(System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}},System.Boolean)
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  nameWithType: RoutingConfiguration.RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RoutingConfiguration(MessageFilterTable<IEnumerable<ServiceEndpoint>>,Boolean)
- uid: System.ServiceModel.Dispatcher.MessageFilterTable{System.Collections.Generic.IEnumerable{System.ServiceModel.Description.ServiceEndpoint}}
  parent: System.ServiceModel.Dispatcher
  isExternal: false
  name: MessageFilterTable<IEnumerable<ServiceEndpoint>>
  nameWithType: MessageFilterTable<IEnumerable<ServiceEndpoint>>
  fullName: System.ServiceModel.Dispatcher.MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>>
  spec.csharp:
  - uid: System.ServiceModel.Dispatcher.MessageFilterTable`1
    name: MessageFilterTable
    nameWithType: MessageFilterTable
    fullName: MessageFilterTable<System.Collections.Generic.IEnumerable<System.ServiceModel.Description.ServiceEndpoint>>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.Collections.Generic.IEnumerable`1
    name: IEnumerable
    nameWithType: IEnumerable
    fullName: IEnumerable<System.ServiceModel.Description.ServiceEndpoint>
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.ServiceModel.Description.ServiceEndpoint
    name: ServiceEndpoint
    nameWithType: ServiceEndpoint
    fullName: ServiceEndpoint
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  - name: '>'
    nameWithType: '>'
    fullName: '>'
- uid: System.Boolean
  parent: System
  isExternal: true
  name: Boolean
  nameWithType: Boolean
  fullName: System.Boolean
- uid: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: EnsureOrderedDispatch
  nameWithType: RoutingConfiguration.EnsureOrderedDispatch
  fullName: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch
- uid: System.ServiceModel.Routing.RoutingConfiguration.FilterTable
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: FilterTable
  nameWithType: RoutingConfiguration.FilterTable
  fullName: System.ServiceModel.Routing.RoutingConfiguration.FilterTable
- uid: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RouteOnHeadersOnly
  nameWithType: RoutingConfiguration.RouteOnHeadersOnly
  fullName: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly
- uid: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: SoapProcessingEnabled
  nameWithType: RoutingConfiguration.SoapProcessingEnabled
  fullName: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled
- uid: System.ServiceModel.Routing.RoutingConfiguration.#ctor*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RoutingConfiguration
  nameWithType: RoutingConfiguration.RoutingConfiguration
- uid: System.ServiceModel.Routing.RoutingConfiguration.EnsureOrderedDispatch*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: EnsureOrderedDispatch
  nameWithType: RoutingConfiguration.EnsureOrderedDispatch
- uid: System.ServiceModel.Routing.RoutingConfiguration.FilterTable*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: FilterTable
  nameWithType: RoutingConfiguration.FilterTable
- uid: System.ServiceModel.Routing.RoutingConfiguration.RouteOnHeadersOnly*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: RouteOnHeadersOnly
  nameWithType: RoutingConfiguration.RouteOnHeadersOnly
- uid: System.ServiceModel.Routing.RoutingConfiguration.SoapProcessingEnabled*
  parent: System.ServiceModel.Routing.RoutingConfiguration
  isExternal: false
  name: SoapProcessingEnabled
  nameWithType: RoutingConfiguration.SoapProcessingEnabled
