### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  id: X509ClientCertificateCredentialsElement
  children:
  - System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.#ctor
  - System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Copy(System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement)
  - System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue
  - System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Properties
  - System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreLocation
  - System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreName
  - System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType
  langs:
  - csharp
  name: X509ClientCertificateCredentialsElement
  nameWithType: X509ClientCertificateCredentialsElement
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  type: Class
  summary: "Egy konfigurációs elem, amely meghatározza egy ügyfél által használt tanúsítvány jelöli. Ez az osztály nem örökölhető."
  syntax:
    content: 'public sealed class X509ClientCertificateCredentialsElement : System.Configuration.ConfigurationElement'
  inheritance:
  - System.Object
  - System.Configuration.ConfigurationElement
  implements: []
  inheritedMembers:
  - System.Configuration.ConfigurationElement.CurrentConfiguration
  - System.Configuration.ConfigurationElement.DeserializeElement(System.Xml.XmlReader,System.Boolean)
  - System.Configuration.ConfigurationElement.ElementInformation
  - System.Configuration.ConfigurationElement.ElementProperty
  - System.Configuration.ConfigurationElement.Equals(System.Object)
  - System.Configuration.ConfigurationElement.EvaluationContext
  - System.Configuration.ConfigurationElement.GetHashCode
  - System.Configuration.ConfigurationElement.GetTransformedAssemblyString(System.String)
  - System.Configuration.ConfigurationElement.GetTransformedTypeString(System.String)
  - System.Configuration.ConfigurationElement.HasContext
  - System.Configuration.ConfigurationElement.Init
  - System.Configuration.ConfigurationElement.InitializeDefault
  - System.Configuration.ConfigurationElement.IsModified
  - System.Configuration.ConfigurationElement.IsReadOnly
  - System.Configuration.ConfigurationElement.Item(System.Configuration.ConfigurationProperty)
  - System.Configuration.ConfigurationElement.Item(System.String)
  - System.Configuration.ConfigurationElement.ListErrors(System.Collections.IList)
  - System.Configuration.ConfigurationElement.LockAllAttributesExcept
  - System.Configuration.ConfigurationElement.LockAllElementsExcept
  - System.Configuration.ConfigurationElement.LockAttributes
  - System.Configuration.ConfigurationElement.LockElements
  - System.Configuration.ConfigurationElement.LockItem
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedAttribute(System.String,System.String)
  - System.Configuration.ConfigurationElement.OnDeserializeUnrecognizedElement(System.String,System.Xml.XmlReader)
  - System.Configuration.ConfigurationElement.OnRequiredPropertyNotFound(System.String)
  - System.Configuration.ConfigurationElement.PostDeserialize
  - System.Configuration.ConfigurationElement.PreSerialize(System.Xml.XmlWriter)
  - System.Configuration.ConfigurationElement.Reset(System.Configuration.ConfigurationElement)
  - System.Configuration.ConfigurationElement.ResetModified
  - System.Configuration.ConfigurationElement.SerializeElement(System.Xml.XmlWriter,System.Boolean)
  - System.Configuration.ConfigurationElement.SerializeToXmlElement(System.Xml.XmlWriter,System.String)
  - System.Configuration.ConfigurationElement.SetPropertyValue(System.Configuration.ConfigurationProperty,System.Object,System.Boolean)
  - System.Configuration.ConfigurationElement.SetReadOnly
  - System.Configuration.ConfigurationElement.Unmerge(System.Configuration.ConfigurationElement,System.Configuration.ConfigurationElement,System.Configuration.ConfigurationSaveMode)
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.#ctor
  id: '#ctor'
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  langs:
  - csharp
  name: X509ClientCertificateCredentialsElement()
  nameWithType: X509ClientCertificateCredentialsElement.X509ClientCertificateCredentialsElement()
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509ClientCertificateCredentialsElement()
  type: Constructor
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement&quot;> </xref> osztály."
  syntax:
    content: public X509ClientCertificateCredentialsElement ();
    parameters: []
  overload: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Copy(System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement)
  id: Copy(System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement)
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  langs:
  - csharp
  name: Copy(X509ClientCertificateCredentialsElement)
  nameWithType: X509ClientCertificateCredentialsElement.Copy(X509ClientCertificateCredentialsElement)
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Copy(X509ClientCertificateCredentialsElement)
  type: Method
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Másolja a konfigurációs elem az adott konfigurációs elem tartalmát."
  syntax:
    content: public void Copy (System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement from);
    parameters:
    - id: from
      type: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
      description: "A konfigurációs elem másolása."
  overload: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Copy*
  exceptions:
  - type: System.ArgumentNullException
    commentId: T:System.ArgumentNullException
    description: "<code>from</code>is <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;></xref>."
  - type: System.Configuration.ConfigurationErrorsException
    commentId: T:System.Configuration.ConfigurationErrorsException
    description: "A konfigurációs fájl csak olvasható."
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue
  id: FindValue
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  langs:
  - csharp
  name: FindValue
  nameWithType: X509ClientCertificateCredentialsElement.FindValue
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a található X.509 tanúsítvány keresendő értéket meghatározó karakterlánc."
  remarks: "Az ebben a tulajdonságban tárolt meg kell felelnie a megadott követelményeinek <xref:System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType%2A>érték.</xref:System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType%2A> Az alapértelmezett érték egy üres karakterlánc."
  syntax:
    content: public string FindValue { get; set; }
    return:
      type: System.String
      description: "Az X.509 tanúsítvány tárolójában keresendő értéket."
  overload: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Properties
  id: Properties
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  langs:
  - csharp
  name: Properties
  nameWithType: X509ClientCertificateCredentialsElement.Properties
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Properties
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  syntax:
    content: protected override System.Configuration.ConfigurationPropertyCollection Properties { get; }
    return:
      type: System.Configuration.ConfigurationPropertyCollection
      description: "Fel kell venni a párbeszédpanelre."
  overload: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Properties*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreLocation
  id: StoreLocation
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  langs:
  - csharp
  name: StoreLocation
  nameWithType: X509ClientCertificateCredentialsElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreLocation
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja egy érték, amely meghatározza a helyét, a szolgáltatás segítségével ellenőrizze az ügyféltanúsítvány a tanúsítványtárolóból."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreLocation StoreLocation { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreLocation
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;></xref>. Az alapértelmezett érték <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreLocation&quot;> </xref>."
  overload: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreLocation*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreName
  id: StoreName
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  langs:
  - csharp
  name: StoreName
  nameWithType: X509ClientCertificateCredentialsElement.StoreName
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreName
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a nevét, az X.509 tanúsítvány tároló megnyitása."
  syntax:
    content: public System.Security.Cryptography.X509Certificates.StoreName StoreName { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.StoreName
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.StoreName&quot;> </xref> , amely az X.509 tanúsítvány áruházból, nyissa meg a nevét tartalmazza."
  overload: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreName*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType
  id: X509FindType
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  langs:
  - csharp
  name: X509FindType
  nameWithType: X509ClientCertificateCredentialsElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType
  type: Property
  assemblies:
  - System.ServiceModel
  namespace: System.ServiceModel.Configuration
  summary: "Lekérdezi vagy beállítja a típusú X.509 keresés hajthatnak végre."
  remarks: "A típus szereplő <xref:System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue%2A>meg kell felelniük a ennek a tulajdonságnak.</xref:System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue%2A>"
  syntax:
    content: public System.Security.Cryptography.X509Certificates.X509FindType X509FindType { get; set; }
    return:
      type: System.Security.Cryptography.X509Certificates.X509FindType
      description: "A <xref href=&quot;System.Security.Cryptography.X509Certificates.X509FindType&quot;> </xref> , amely megadja, hogy a típusú X.509 keresés hajthatnak végre."
  overload: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.ConfigurationElement
  isExternal: false
  name: System.Configuration.ConfigurationElement
- uid: System.ArgumentNullException
  isExternal: true
  name: System.ArgumentNullException
- uid: System.Configuration.ConfigurationErrorsException
  parent: System.Configuration
  isExternal: false
  name: ConfigurationErrorsException
  nameWithType: ConfigurationErrorsException
  fullName: System.Configuration.ConfigurationErrorsException
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.#ctor
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: X509ClientCertificateCredentialsElement()
  nameWithType: X509ClientCertificateCredentialsElement.X509ClientCertificateCredentialsElement()
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509ClientCertificateCredentialsElement()
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Copy(System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement)
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: Copy(X509ClientCertificateCredentialsElement)
  nameWithType: X509ClientCertificateCredentialsElement.Copy(X509ClientCertificateCredentialsElement)
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Copy(X509ClientCertificateCredentialsElement)
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  parent: System.ServiceModel.Configuration
  isExternal: false
  name: X509ClientCertificateCredentialsElement
  nameWithType: X509ClientCertificateCredentialsElement
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: FindValue
  nameWithType: X509ClientCertificateCredentialsElement.FindValue
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Properties
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: Properties
  nameWithType: X509ClientCertificateCredentialsElement.Properties
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Properties
- uid: System.Configuration.ConfigurationPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: ConfigurationPropertyCollection
  nameWithType: ConfigurationPropertyCollection
  fullName: System.Configuration.ConfigurationPropertyCollection
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreLocation
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509ClientCertificateCredentialsElement.StoreLocation
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreLocation
- uid: System.Security.Cryptography.X509Certificates.StoreLocation
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreLocation
  nameWithType: StoreLocation
  fullName: System.Security.Cryptography.X509Certificates.StoreLocation
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreName
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: StoreName
  nameWithType: X509ClientCertificateCredentialsElement.StoreName
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreName
- uid: System.Security.Cryptography.X509Certificates.StoreName
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: StoreName
  nameWithType: StoreName
  fullName: System.Security.Cryptography.X509Certificates.StoreName
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: X509FindType
  nameWithType: X509ClientCertificateCredentialsElement.X509FindType
  fullName: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType
- uid: System.Security.Cryptography.X509Certificates.X509FindType
  parent: System.Security.Cryptography.X509Certificates
  isExternal: false
  name: X509FindType
  nameWithType: X509FindType
  fullName: System.Security.Cryptography.X509Certificates.X509FindType
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.#ctor*
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: X509ClientCertificateCredentialsElement
  nameWithType: X509ClientCertificateCredentialsElement.X509ClientCertificateCredentialsElement
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Copy*
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: Copy
  nameWithType: X509ClientCertificateCredentialsElement.Copy
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.FindValue*
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: FindValue
  nameWithType: X509ClientCertificateCredentialsElement.FindValue
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.Properties*
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: Properties
  nameWithType: X509ClientCertificateCredentialsElement.Properties
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreLocation*
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: StoreLocation
  nameWithType: X509ClientCertificateCredentialsElement.StoreLocation
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.StoreName*
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: StoreName
  nameWithType: X509ClientCertificateCredentialsElement.StoreName
- uid: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement.X509FindType*
  parent: System.ServiceModel.Configuration.X509ClientCertificateCredentialsElement
  isExternal: false
  name: X509FindType
  nameWithType: X509ClientCertificateCredentialsElement.X509FindType
