### YamlMime:ManagedReference
items:
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  id: RibbonApplicationMenuItemLevel
  children:
  - System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
  - System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
  - System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
  langs:
  - csharp
  name: RibbonApplicationMenuItemLevel
  nameWithType: RibbonApplicationMenuItemLevel
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  type: Enum
  summary: "A menüpontok jelenik meg a menüszalagon alkalmazás menü szint állandókat határozza meg."
  remarks: "Ez az enumerálás használják a <xref:System.Windows.Controls.Ribbon.RibbonApplicationMenuItem.Level%2A>tulajdonság.</xref:System.Windows.Controls.Ribbon.RibbonApplicationMenuItem.Level%2A>"
  syntax:
    content: public enum RibbonApplicationMenuItemLevel
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
  id: Middle
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  langs:
  - csharp
  name: Middle
  nameWithType: RibbonApplicationMenuItemLevel.Middle
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
  type: Field
  assemblies:
  - System.Windows.Controls.Ribbon
  namespace: System.Windows.Controls.Ribbon
  summary: "A menüpont a középső szint jelenik meg."
  syntax:
    content: Middle
    return:
      type: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
  id: Sub
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  langs:
  - csharp
  name: Sub
  nameWithType: RibbonApplicationMenuItemLevel.Sub
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
  type: Field
  assemblies:
  - System.Windows.Controls.Ribbon
  namespace: System.Windows.Controls.Ribbon
  summary: "A menüpont a legalacsonyabb jelenik meg."
  syntax:
    content: Sub
    return:
      type: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
  id: Top
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  langs:
  - csharp
  name: Top
  nameWithType: RibbonApplicationMenuItemLevel.Top
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
  type: Field
  assemblies:
  - System.Windows.Controls.Ribbon
  namespace: System.Windows.Controls.Ribbon
  summary: "A menüpont a legfelső szinten jelenik meg."
  syntax:
    content: Top
    return:
      type: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  isExternal: false
  name: Middle
  nameWithType: RibbonApplicationMenuItemLevel.Middle
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Middle
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  parent: System.Windows.Controls.Ribbon
  isExternal: false
  name: RibbonApplicationMenuItemLevel
  nameWithType: RibbonApplicationMenuItemLevel
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  isExternal: false
  name: Sub
  nameWithType: RibbonApplicationMenuItemLevel.Sub
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Sub
- uid: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
  parent: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel
  isExternal: false
  name: Top
  nameWithType: RibbonApplicationMenuItemLevel.Top
  fullName: System.Windows.Controls.Ribbon.RibbonApplicationMenuItemLevel.Top
