### YamlMime:ManagedReference
items:
- uid: System.Configuration.DictionarySectionHandler
  id: DictionarySectionHandler
  children:
  - System.Configuration.DictionarySectionHandler.#ctor
  - System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  - System.Configuration.DictionarySectionHandler.KeyAttributeName
  - System.Configuration.DictionarySectionHandler.ValueAttributeName
  langs:
  - csharp
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler
  fullName: System.Configuration.DictionarySectionHandler
  type: Class
  summary: "Kulcs/érték pár a konfigurációs szakasz konfigurációs információkat nyújt."
  remarks: "Ez az osztály megvalósítja az `IConfigSectionHandler` felületet. A DictionarySectionHandler XML-konfigurációs szakaszban kezelésére szolgáló szabályokat határozza meg."
  syntax:
    content: 'public class DictionarySectionHandler : System.Configuration.IConfigurationSectionHandler'
  inheritance:
  - System.Object
  implements:
  - System.Configuration.IConfigurationSectionHandler
  inheritedMembers: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.#ctor
  id: '#ctor'
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.DictionarySectionHandler&quot;> </xref> osztály."
  syntax:
    content: public DictionarySectionHandler ();
    parameters: []
  overload: System.Configuration.DictionarySectionHandler.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  id: Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: Create(Object,Object,XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object,Object,XmlNode)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Létrehoz egy új konfigurációs kezelője, és hozzáadja azt a szakasz-kezelőjének gyűjtemény a megadott paraméterek alapján."
  remarks: "A `parent` objektumparaméterek úgy működik, mint a konfigurációs beállításokat a megfelelő szülő konfigurációs szakaszban. A `context` objektum paraméter értéke, amelynek a konfigurációs szakasz kezelőjének kiszámítja a konfigurációs értékek virtuális elérési utat. Általában ez a paraméter fenntartva, és van `null`.  A `section` paraméter a <xref:System.Xml.XmlNode>kezelni kívánt konfigurációs információkat tartalmazza, amelyek.</xref:System.Xml.XmlNode> A `section` paramétert a konfigurációs szakasz az XML-tartalmának közvetlen hozzáférést biztosít."
  syntax:
    content: public virtual object Create (object parent, object context, System.Xml.XmlNode section);
    parameters:
    - id: parent
      type: System.Object
      description: "Szülői objektumon."
    - id: context
      type: System.Object
      description: "Konfigurációs környezeti objektumot."
    - id: section
      type: System.Xml.XmlNode
      description: "A szakasz XML-csomópont."
    return:
      type: System.Object
      description: "Egy konfigurációs objektumot."
  overload: System.Configuration.DictionarySectionHandler.Create*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  id: KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi az XML-attribútumnév egy kulcs/érték pár kulcsként használja."
  syntax:
    content: protected virtual string KeyAttributeName { get; }
    return:
      type: System.String
      description: "A kulcs nevét tartalmazó karakterlánc-érték."
  overload: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  id: ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  langs:
  - csharp
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
  type: Property
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Lekérdezi az XML-attribútumnév használja egy kulcs-érték párokban szereplő értékkel."
  syntax:
    content: protected virtual string ValueAttributeName { get; }
    return:
      type: System.String
      description: "A value attribútumként nevét tartalmazó karakterlánc-érték."
  overload: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.Configuration.DictionarySectionHandler.#ctor
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler()
  nameWithType: DictionarySectionHandler.DictionarySectionHandler()
  fullName: System.Configuration.DictionarySectionHandler.DictionarySectionHandler()
- uid: System.Configuration.DictionarySectionHandler.Create(System.Object,System.Object,System.Xml.XmlNode)
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create(Object,Object,XmlNode)
  nameWithType: DictionarySectionHandler.Create(Object,Object,XmlNode)
  fullName: System.Configuration.DictionarySectionHandler.Create(Object,Object,XmlNode)
- uid: System.Xml.XmlNode
  parent: System.Xml
  isExternal: false
  name: XmlNode
  nameWithType: XmlNode
  fullName: System.Xml.XmlNode
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
  fullName: System.Configuration.DictionarySectionHandler.KeyAttributeName
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
  fullName: System.Configuration.DictionarySectionHandler.ValueAttributeName
- uid: System.Configuration.DictionarySectionHandler.#ctor*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: DictionarySectionHandler
  nameWithType: DictionarySectionHandler.DictionarySectionHandler
- uid: System.Configuration.DictionarySectionHandler.Create*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: Create
  nameWithType: DictionarySectionHandler.Create
- uid: System.Configuration.DictionarySectionHandler.KeyAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: KeyAttributeName
  nameWithType: DictionarySectionHandler.KeyAttributeName
- uid: System.Configuration.DictionarySectionHandler.ValueAttributeName*
  parent: System.Configuration.DictionarySectionHandler
  isExternal: false
  name: ValueAttributeName
  nameWithType: DictionarySectionHandler.ValueAttributeName
