### YamlMime:ManagedReference
items:
- uid: System.Web.Hosting.ApplicationHost
  id: ApplicationHost
  children:
  - System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  langs:
  - csharp
  name: ApplicationHost
  nameWithType: ApplicationHost
  fullName: System.Web.Hosting.ApplicationHost
  type: Class
  summary: "Lehetővé teszi, hogy az ASP.NET-lapok az Internet Information Services (IIS) alkalmazáson kívül üzemeltetéséhez. Ez az osztály lehetővé teszi, hogy a gazdagép alkalmazástartományok ASP.NET-kérelmek feldolgozásának létrehozásához."
  remarks: "Alkalmazásgazdáról megjelent a .NET-keretrendszer 3.5-ös verziója.  További információkért lásd: [verziója és a függőségek](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public sealed class ApplicationHost
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  id: CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  langs:
  - csharp
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
  type: Method
  assemblies:
  - System.Web
  namespace: System.Web.Hosting
  summary: "Hoz létre, és beállítja egy alkalmazástartomány ASP.NET üzemeltetéséhez."
  syntax:
    content: public static object CreateApplicationHost (Type hostType, string virtualDir, string physicalDir);
    parameters:
    - id: hostType
      type: System.Type
      description: "Az új alkalmazás tartományon belül létrehozható egy felhasználó által megadott osztály nevét."
    - id: virtualDir
      type: System.String
      description: "A virtuális könyvtárat az alkalmazás tartomány; például/MyApp."
    - id: physicalDir
      type: System.String
      description: "A fizikai könyvtárat az alkalmazástartományt, amelyben ASP.NET-lapok találhatók; például c:\\mypages."
    return:
      type: System.Object
      description: "Az újonnan létrehozott alkalmazás tartományába hívások átadásra való előkészítéséhez használt felhasználó által megadott osztály egy példányát."
  overload: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  exceptions:
  - type: System.PlatformNotSupportedException
    commentId: T:System.PlatformNotSupportedException
    description: "A webes állomás számítógépen nem fut a Windows NT platform vagy Coriolis környezetben."
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.PlatformNotSupportedException
  isExternal: true
  name: System.PlatformNotSupportedException
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost(System.Type,System.String,System.String)
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost(Type,String,String)
  nameWithType: ApplicationHost.CreateApplicationHost(Type,String,String)
  fullName: System.Web.Hosting.ApplicationHost.CreateApplicationHost(Type,String,String)
- uid: System.Type
  parent: System
  isExternal: true
  name: Type
  nameWithType: Type
  fullName: System.Type
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Web.Hosting.ApplicationHost.CreateApplicationHost*
  parent: System.Web.Hosting.ApplicationHost
  isExternal: false
  name: CreateApplicationHost
  nameWithType: ApplicationHost.CreateApplicationHost
