### YamlMime:ManagedReference
items:
- uid: System.Configuration.SettingsContext
  id: SettingsContext
  children:
  - System.Configuration.SettingsContext.#ctor
  langs:
  - csharp
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
  type: Class
  summary: "A szolgáltató használhatja, ha a beállítások megőrzése környezetfüggő információkat biztosít."
  remarks: "A SettingsContext osztály az alaposztály alkalmazások segítségével adja meg a környezetfüggő adatokat a beállítások szolgáltató. Bár az osztály nem absztrakt, hozzon létre egy speciális osztályt SettingsContext osztály örökli és további információkat a szolgáltatók adott típusú kérelmet választhat. A szolgáltató majd ellenőrizheti környezetfüggő beállítások tulajdonságok írása közben.       Az elsődleges SettingsContext osztály célja használó szolgáltatások a <xref:System.Configuration.SettingsBase>osztály és a kapcsolódó infrastruktúrát.</xref:System.Configuration.SettingsBase> A SettingsContext osztály szolgáltatásspecifikus környezetfüggő adatokról bővebb tájékoztatás a tulajdonság által tárolt biztosít a <xref:System.Configuration.SettingsBase>példány.</xref:System.Configuration.SettingsBase> Ezért rendkívül egyszerű SettingsContext osztály további információk tárolására, (vagy egyéb beállítások * osztályoktól) nélkül, további szolgáltatásspecifikus kontextusadatok támogatásához.       Például az ASP.NET használja a SettingsContext osztály által kezelt adatok társított felhasználónév adják át a <xref:System.Configuration.SettingsBase>példány, valamint egy tulajdonság, amely azt jelzi, hogy a felhasználó akkor tekinthető, hitelesített.</xref:System.Configuration.SettingsBase> Ily módon ASP.NET használja a SettingsContext osztály azonosítására és a névtelen profil hitelesítése."
  syntax:
    content: 'public class SettingsContext : System.Collections.Hashtable'
  inheritance:
  - System.Object
  - System.Collections.Hashtable
  implements: []
  inheritedMembers:
  - System.Collections.Hashtable.Add(System.Object,System.Object)
  - System.Collections.Hashtable.Clear
  - System.Collections.Hashtable.Clone
  - System.Collections.Hashtable.comparer
  - System.Collections.Hashtable.Contains(System.Object)
  - System.Collections.Hashtable.ContainsKey(System.Object)
  - System.Collections.Hashtable.ContainsValue(System.Object)
  - System.Collections.Hashtable.CopyTo(System.Array,System.Int32)
  - System.Collections.Hashtable.Count
  - System.Collections.Hashtable.EqualityComparer
  - System.Collections.Hashtable.GetEnumerator
  - System.Collections.Hashtable.GetHash(System.Object)
  - System.Collections.Hashtable.GetObjectData(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Collections.Hashtable.hcp
  - System.Collections.Hashtable.IsFixedSize
  - System.Collections.Hashtable.IsReadOnly
  - System.Collections.Hashtable.IsSynchronized
  - System.Collections.Hashtable.Item(System.Object)
  - System.Collections.Hashtable.KeyEquals(System.Object,System.Object)
  - System.Collections.Hashtable.Keys
  - System.Collections.Hashtable.OnDeserialization(System.Object)
  - System.Collections.Hashtable.Remove(System.Object)
  - System.Collections.Hashtable.Synchronized(System.Collections.Hashtable)
  - System.Collections.Hashtable.SyncRoot
  - System.Collections.Hashtable.System#Collections#IEnumerable#GetEnumerator
  - System.Collections.Hashtable.Values
  platform:
  - net462
- uid: System.Configuration.SettingsContext.#ctor
  id: '#ctor'
  parent: System.Configuration.SettingsContext
  langs:
  - csharp
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
  type: Constructor
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Egy új példányát inicializálja a <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> osztály."
  syntax:
    content: public SettingsContext ();
    parameters: []
  overload: System.Configuration.SettingsContext.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Collections.Hashtable
  isExternal: false
  name: System.Collections.Hashtable
- uid: System.Configuration.SettingsContext.#ctor
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext()
  nameWithType: SettingsContext.SettingsContext()
  fullName: System.Configuration.SettingsContext.SettingsContext()
- uid: System.Configuration.SettingsContext.#ctor*
  parent: System.Configuration.SettingsContext
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext.SettingsContext
