### YamlMime:ManagedReference
items:
- uid: System.ServiceModel.Discovery.UdpTransportSettings
  id: UdpTransportSettings
  children:
  - System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  - System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  - System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  - System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  - System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  langs:
  - csharp
  name: UdpTransportSettings
  nameWithType: UdpTransportSettings
  fullName: System.ServiceModel.Discovery.UdpTransportSettings
  type: Class
  summary: "Lehetővé teszi az UDP-átvitel beállításainak megadása."
  syntax:
    content: public class UdpTransportSettings
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  id: DuplicateMessageHistoryLength
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja egy érték, amely meghatározza az átvitel alapján azonosítja a duplikált üzenetek használt üzenetkivonatokkal maximális számát."
  remarks: "Ez a tulajdonság lehetőséget nyújt a rendszergazdák és fejlesztők kikapcsolása a duplikált üzenetek észlelésének algoritmusok. 0 érték megadása letiltja a duplikált üzenetek észlelésének. Az alapértelmezett érték: 4112."
  syntax:
    content: public int DuplicateMessageHistoryLength { get; set; }
    return:
      type: System.Int32
      description: "A használandó üzenetkivonatokkal maximális száma."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  id: MaxBufferPoolSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja a maximális méretet, bármely az átvitel használt puffer gyűjtők száma."
  syntax:
    content: public long MaxBufferPoolSize { get; set; }
    return:
      type: System.Int64
      description: "A pufferkészlet maximális mérete."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  id: MaxMulticastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja a csoportos küldésű üzenet kell újraküldött, (az első küldése) mellett a maximálisan megengedett számú meghatározó érték."
  remarks: "Az alapértelmezett érték 2."
  syntax:
    content: public int MaxMulticastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "A csoportos küldésű üzenet van újraküldött hányszor maximális száma."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  id: MaxPendingMessageCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja egy érték, amely megadja a beérkezett, de még nincs egy csatornát példány bemeneti várólistából való eltávolításának üzenetek maximális számát."
  remarks: "Ha a bemeneti várólistára elérte a függőben lévő üzenetek maximális száma, a rendszer eldobja az üzenetet. Az alapértelmezett érték: 32."
  syntax:
    content: public int MaxPendingMessageCount { get; set; }
    return:
      type: System.Int32
      description: "Az üzenetek száma."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  id: MaxReceivedMessageSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja a maximális méretet, egy üzenet, amely a kötés által dolgozhatók bájtokban."
  remarks: "Az alapértelmezett érték: 65507."
  syntax:
    content: public long MaxReceivedMessageSize { get; set; }
    return:
      type: System.Int64
      description: "Egy üzenet maximális mérete."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  id: MaxUnicastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja az egyedi küldésű üzenet kell újraküldött, (az első küldése) mellett a maximálisan megengedett számú értéke."
  remarks: "Az alapértelmezett érték az 1."
  syntax:
    content: public int MaxUnicastRetransmitCount { get; set; }
    return:
      type: System.Int32
      description: "Egyedi küldésű üzenet van újraküldött hányszor maximális száma."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  id: MulticastInterfaceId
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja egy érték, amely egyedileg azonosítja a hálózati adapter esetén használt csoportos küldésű üzenetek küldése és fogadása."
  remarks: "Futásidőben, az átvitel ezt az értéket használja majd beállítására használatos kapcsolatindexét megkeresheti a `IP_MULTICAST_IF` és `IPV6_MULTICAST_IF` szoftvercsatorna-beállítások. Az azonos kapcsolatindexét akkor használatos, ha a csoportos küldési csoporthoz való csatlakozásra. Az alapértelmezett érték `null`."
  syntax:
    content: public string MulticastInterfaceId { get; set; }
    return:
      type: System.String
      description: "A hálózati adapter azonosítója."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  id: SocketReceiveBufferSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja a fogadási pufferek méretét a mögöttes WinSock-szoftvercsatorna."
  remarks: "A felhasználó fogadó csatorna segítségével ezt az értéket a Binding adatainak fogadásakor a rendszer viselkedését szabályozza. Például adott alkalmazás fér hozzá a bejövő [!INCLUDE[indigo2](~/add/includes/ajax-current-ext-md.md)] üzenetekben a maximális küszöbértéket, a nagyobb érték használata révén a WinSock pufferben miközben a rendszer az alkalmazás dolgozza fel őket a verem üzeneteket. Ugyanez a helyzet alacsonyabb érték használata megszakad üzenetek eredményezne. Ez a tulajdonság mutatja meg az alapul szolgáló WinSock `SO_RCVBUF` szoftvercsatorna-beállítás. Ez a tulajdonság értéke legalább <xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>.</xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A> méretűnek kell lennie Beállítás értéke kisebb, mint a <xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A>futásidejű kivételt eredményezi.</xref:System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize%2A> Az alapértelmezett érték 65536."
  syntax:
    content: public int SocketReceiveBufferSize { get; set; }
    return:
      type: System.Int32
      description: "A fogadási pufferek méretét."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize*
  exceptions: []
  platform:
  - net462
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  id: TimeToLive
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  langs:
  - csharp
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  type: Property
  assemblies:
  - System.ServiceModel.Discovery
  namespace: System.ServiceModel.Discovery
  summary: "Lekérdezi vagy beállítja egy érték, amely a csoportos küldésű csomagok áthaladó hálózati szegmens ugrások számát adja meg."
  remarks: "Ez a tulajdonság mutatja meg a társított funkciót a `IP_MULTICAST_TTL` és `IP_TTL` szoftvercsatorna-beállítások. Az alapértelmezett érték az 1."
  syntax:
    content: public int TimeToLive { get; set; }
    return:
      type: System.Int32
      description: "Az hálózati szegmensek ugrások száma."
  overload: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize
- uid: System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
  fullName: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive
- uid: System.ServiceModel.Discovery.UdpTransportSettings.DuplicateMessageHistoryLength*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: DuplicateMessageHistoryLength
  nameWithType: UdpTransportSettings.DuplicateMessageHistoryLength
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxBufferPoolSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxBufferPoolSize
  nameWithType: UdpTransportSettings.MaxBufferPoolSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxMulticastRetransmitCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxMulticastRetransmitCount
  nameWithType: UdpTransportSettings.MaxMulticastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxPendingMessageCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxPendingMessageCount
  nameWithType: UdpTransportSettings.MaxPendingMessageCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxReceivedMessageSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxReceivedMessageSize
  nameWithType: UdpTransportSettings.MaxReceivedMessageSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MaxUnicastRetransmitCount*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MaxUnicastRetransmitCount
  nameWithType: UdpTransportSettings.MaxUnicastRetransmitCount
- uid: System.ServiceModel.Discovery.UdpTransportSettings.MulticastInterfaceId*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: MulticastInterfaceId
  nameWithType: UdpTransportSettings.MulticastInterfaceId
- uid: System.ServiceModel.Discovery.UdpTransportSettings.SocketReceiveBufferSize*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: SocketReceiveBufferSize
  nameWithType: UdpTransportSettings.SocketReceiveBufferSize
- uid: System.ServiceModel.Discovery.UdpTransportSettings.TimeToLive*
  parent: System.ServiceModel.Discovery.UdpTransportSettings
  isExternal: false
  name: TimeToLive
  nameWithType: UdpTransportSettings.TimeToLive
