### YamlMime:ManagedReference
items:
- uid: System.Configuration.IApplicationSettingsProvider
  id: IApplicationSettingsProvider
  children:
  - System.Configuration.IApplicationSettingsProvider.GetPreviousVersion(System.Configuration.SettingsContext,System.Configuration.SettingsProperty)
  - System.Configuration.IApplicationSettingsProvider.Reset(System.Configuration.SettingsContext)
  - System.Configuration.IApplicationSettingsProvider.Upgrade(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  langs:
  - csharp
  name: IApplicationSettingsProvider
  nameWithType: IApplicationSettingsProvider
  fullName: System.Configuration.IApplicationSettingsProvider
  type: Interface
  summary: "Az alkalmazás ügyfél-alapú beállítások szolgáltatók határozza meg a kiterjesztett képességeit."
  remarks: "Az alkalmazás beállításainak architektúra lehetővé teszi, hogy adja meg egy egyéni tárolási mechanizmus az alkalmazásbeállítások hozzon létre egy egyéni beállítások szolgáltatót, amely <xref:System.Configuration.SettingsProvider>.</xref:System.Configuration.SettingsProvider> -ból származtatott osztályt Az ilyen osztály tárolásához és a Tulajdonságok beolvasása alapvető funkcióit tartalmazza. Azonban további szabványos funkciókat is hozzáadhat a IApplicationSettingsProvider felületet valósít meg az egyéni beállítások szolgáltató. Ez az interfész tartalmazza, amelyek elsődlegesen lehetővé teszik a beállítások szolgáltatót, amelyet ezután több leíró alkalmazás megváltozik a verzió három módszert. Általában a beállításszolgáltató fogja tárolja az alkalmazásbeállításokat az külön-külön várhatóan a következő esetekben az alkalmazások különböző verzióihoz:-az alkalmazás különböző verzióinak egymás melletti végrehajtását.      -Alkalmazásbeállítások megőrzése a alkalmazás verzióra.      -Az alkalmazás beállításainak visszaállítása az alapértelmezett értékekre a jelenleg használt verzió.       A <xref:System.Configuration.LocalFileSettingsProvider>osztály megvalósítja az IApplicationSettingsProvider felületet.</xref:System.Configuration.LocalFileSettingsProvider> Ugyanazokat a módszereket IApplicationSettingsProvider által tartalmazott is megtalálható a <xref:System.Configuration.ApplicationSettingsBase>osztály, amelyek lehetővé teszik az alkalmazás beállításainak burkoló és a beállítások szolgáltató közötti előre definiált kommunikációs csatorna.</xref:System.Configuration.ApplicationSettingsBase>      > [!NOTE] > Ez az interfész nem kötelező megadni. A szolgáltató nem valósítja meg az illesztő, ha a beállítások infrastruktúra értesítés nélküli meghiúsul, ha megkísérli elérni a módszerekkel, ez az interfész által meghatározott."
  syntax:
    content: public interface IApplicationSettingsProvider
  implements: []
  platform:
  - net462
- uid: System.Configuration.IApplicationSettingsProvider.GetPreviousVersion(System.Configuration.SettingsContext,System.Configuration.SettingsProperty)
  id: GetPreviousVersion(System.Configuration.SettingsContext,System.Configuration.SettingsProperty)
  parent: System.Configuration.IApplicationSettingsProvider
  langs:
  - csharp
  name: GetPreviousVersion(SettingsContext,SettingsProperty)
  nameWithType: IApplicationSettingsProvider.GetPreviousVersion(SettingsContext,SettingsProperty)
  fullName: System.Configuration.IApplicationSettingsProvider.GetPreviousVersion(SettingsContext,SettingsProperty)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A régebbi ugyanahhoz az alkalmazáshoz megadott beállítások tulajdonságának értékét adja vissza."
  remarks: "A GetPreviousVersion módszer használható együtt a <xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A>metódus alkalmazás-beállításainak áttelepítése során, vagy egy alkalmazás új verziójának telepítése után.</xref:System.Configuration.IApplicationSettingsProvider.Upgrade%2A>"
  syntax:
    content: public System.Configuration.SettingsPropertyValue GetPreviousVersion (System.Configuration.SettingsContext context, System.Configuration.SettingsProperty property);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "A <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> az aktuális alkalmazás használati leíró."
    - id: property
      type: System.Configuration.SettingsProperty
      description: "A <xref href=&quot;System.Configuration.SettingsProperty&quot;> </xref> visszaadandó értéke."
    return:
      type: System.Configuration.SettingsPropertyValue
      description: "A <xref href=&quot;System.Configuration.SettingsPropertyValue&quot;> </xref> utolsó állították be az alkalmazás; előző verzióját a megadott tulajdonság beállítás értékét tartalmazó vagy <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref> Ha a beállítás nem található."
  overload: System.Configuration.IApplicationSettingsProvider.GetPreviousVersion*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IApplicationSettingsProvider.Reset(System.Configuration.SettingsContext)
  id: Reset(System.Configuration.SettingsContext)
  parent: System.Configuration.IApplicationSettingsProvider
  langs:
  - csharp
  name: Reset(SettingsContext)
  nameWithType: IApplicationSettingsProvider.Reset(SettingsContext)
  fullName: System.Configuration.IApplicationSettingsProvider.Reset(SettingsContext)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "Az alkalmazás beállításait az alapértékekre az adott alkalmazáshoz kapcsolódó visszaállítja."
  remarks: "A visszaállítási metódus újrainicializálja a megadott beállítások alkalmazáscsoport tárolt értékeit. Ezzel szemben <xref:System.Configuration.DefaultSettingValueAttribute>választékát kínálja egy egyetlen beállítások tulajdonság alapértelmezett értékét tulajdonság az inicializálás során, ha nincs tárolt értékkel rendelkezik.</xref:System.Configuration.DefaultSettingValueAttribute>       A beállítások szolgáltató meghatározza, hogy ésszerű alapértelmezett Mik az alkalmazásbeállítások meghatározott csoportjára. Például a megvalósítást <xref:System.Configuration.LocalFileSettingsProvider>alaphelyzetbe állítja a felhasználó által megadott hatókörű beállításokat a megosztott értékeinek a `application.exe.config` ellentétben az hagyja változatlanul alkalmazásokra kiterjedő hatókörű beállítások; fájlt.</xref:System.Configuration.LocalFileSettingsProvider>"
  syntax:
    content: public void Reset (System.Configuration.SettingsContext context);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "A <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> az aktuális alkalmazás használati leíró."
  overload: System.Configuration.IApplicationSettingsProvider.Reset*
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.IApplicationSettingsProvider.Upgrade(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  id: Upgrade(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  parent: System.Configuration.IApplicationSettingsProvider
  langs:
  - csharp
  name: Upgrade(SettingsContext,SettingsPropertyCollection)
  nameWithType: IApplicationSettingsProvider.Upgrade(SettingsContext,SettingsPropertyCollection)
  fullName: System.Configuration.IApplicationSettingsProvider.Upgrade(SettingsContext,SettingsPropertyCollection)
  type: Method
  assemblies:
  - System
  namespace: System.Configuration
  summary: "A szolgáltató jelzi, hogy az alkalmazás frissítve lett. Ez lehetővé teszi, hogy a szolgáltató a megfelelő tárolt beállítások frissítéséhez."
  remarks: "A .NET-keretrendszer lehetővé teszi, hogy egymás melletti telepítéséhez és futtatásához a az alkalmazás különböző verzióit. Az alkalmazás szolgáltatója tárolja az alkalmazás beállításait minden verzió esetében külön-külön az alkalmazás-elszigetelés érdekében. Azonban érdemes beállítások áttelepítése egy alkalmazást a jelenlegi egy korábbi verziója. Adja meg ezt a funkciót, használja a frissítési módszert, <xref:System.Configuration.SettingsProvider>.</xref:System.Configuration.SettingsProvider> -ból származtatott osztályt megvalósítva       A frissítési módszer használható együtt a <xref:System.Configuration.IApplicationSettingsProvider.GetPreviousVersion%2A>metódus alkalmazás-beállításainak áttelepítése során, vagy egy alkalmazás új verziójának telepítése után.</xref:System.Configuration.IApplicationSettingsProvider.GetPreviousVersion%2A>       Ezzel a módszerrel el kell rejteni minden Alkalmazásbeállítás, amely rendelkezik a <xref:System.Configuration.NoSettingsVersionUpgradeAttribute>van, vagy a teljes beállítások burkoló osztály, <xref:System.Configuration.ApplicationSettingsBase>.</xref:System.Configuration.ApplicationSettingsBase> származik</xref:System.Configuration.NoSettingsVersionUpgradeAttribute>"
  syntax:
    content: public void Upgrade (System.Configuration.SettingsContext context, System.Configuration.SettingsPropertyCollection properties);
    parameters:
    - id: context
      type: System.Configuration.SettingsContext
      description: "A <xref href=&quot;System.Configuration.SettingsContext&quot;> </xref> az aktuális alkalmazás használati leíró."
    - id: properties
      type: System.Configuration.SettingsPropertyCollection
      description: "A <xref href=&quot;System.Configuration.SettingsPropertyCollection&quot;> </xref> tartalmazó a beállítások tulajdonságcsoport, amelynek értékei kérhető."
  overload: System.Configuration.IApplicationSettingsProvider.Upgrade*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Configuration.IApplicationSettingsProvider.GetPreviousVersion(System.Configuration.SettingsContext,System.Configuration.SettingsProperty)
  parent: System.Configuration.IApplicationSettingsProvider
  isExternal: false
  name: GetPreviousVersion(SettingsContext,SettingsProperty)
  nameWithType: IApplicationSettingsProvider.GetPreviousVersion(SettingsContext,SettingsProperty)
  fullName: System.Configuration.IApplicationSettingsProvider.GetPreviousVersion(SettingsContext,SettingsProperty)
- uid: System.Configuration.SettingsPropertyValue
  parent: System.Configuration
  isExternal: false
  name: SettingsPropertyValue
  nameWithType: SettingsPropertyValue
  fullName: System.Configuration.SettingsPropertyValue
- uid: System.Configuration.SettingsContext
  parent: System.Configuration
  isExternal: false
  name: SettingsContext
  nameWithType: SettingsContext
  fullName: System.Configuration.SettingsContext
- uid: System.Configuration.SettingsProperty
  parent: System.Configuration
  isExternal: false
  name: SettingsProperty
  nameWithType: SettingsProperty
  fullName: System.Configuration.SettingsProperty
- uid: System.Configuration.IApplicationSettingsProvider.Reset(System.Configuration.SettingsContext)
  parent: System.Configuration.IApplicationSettingsProvider
  isExternal: false
  name: Reset(SettingsContext)
  nameWithType: IApplicationSettingsProvider.Reset(SettingsContext)
  fullName: System.Configuration.IApplicationSettingsProvider.Reset(SettingsContext)
- uid: System.Configuration.IApplicationSettingsProvider.Upgrade(System.Configuration.SettingsContext,System.Configuration.SettingsPropertyCollection)
  parent: System.Configuration.IApplicationSettingsProvider
  isExternal: false
  name: Upgrade(SettingsContext,SettingsPropertyCollection)
  nameWithType: IApplicationSettingsProvider.Upgrade(SettingsContext,SettingsPropertyCollection)
  fullName: System.Configuration.IApplicationSettingsProvider.Upgrade(SettingsContext,SettingsPropertyCollection)
- uid: System.Configuration.SettingsPropertyCollection
  parent: System.Configuration
  isExternal: false
  name: SettingsPropertyCollection
  nameWithType: SettingsPropertyCollection
  fullName: System.Configuration.SettingsPropertyCollection
- uid: System.Configuration.IApplicationSettingsProvider.GetPreviousVersion*
  parent: System.Configuration.IApplicationSettingsProvider
  isExternal: false
  name: GetPreviousVersion
  nameWithType: IApplicationSettingsProvider.GetPreviousVersion
- uid: System.Configuration.IApplicationSettingsProvider.Reset*
  parent: System.Configuration.IApplicationSettingsProvider
  isExternal: false
  name: Reset
  nameWithType: IApplicationSettingsProvider.Reset
- uid: System.Configuration.IApplicationSettingsProvider.Upgrade*
  parent: System.Configuration.IApplicationSettingsProvider
  isExternal: false
  name: Upgrade
  nameWithType: IApplicationSettingsProvider.Upgrade
