### YamlMime:ManagedReference
items:
- uid: System.Web.Configuration.XhtmlConformanceMode
  id: XhtmlConformanceMode
  children:
  - System.Web.Configuration.XhtmlConformanceMode.Legacy
  - System.Web.Configuration.XhtmlConformanceMode.Strict
  - System.Web.Configuration.XhtmlConformanceMode.Transitional
  langs:
  - csharp
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
  type: Enum
  summary: "Megadja a hitelesítési mód használata egy webalkalmazás."
  remarks: "A XhtmlConformanceMode számbavétel vonatkozik a `mode` attribútumnak a `xhtmlConformance` címke. Megadja egy ASP.NET alkalmazás XHTML megjelenítési módját. A módban a következő értékeket veheti fel. Az alapértelmezett érték `Transitional` (XHTML 1.0 átmeneti)."
  syntax:
    content: public enum XhtmlConformanceMode
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceMode.Legacy
  id: Legacy
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Legacy
  nameWithType: XhtmlConformanceMode.Legacy
  fullName: System.Web.Configuration.XhtmlConformanceMode.Legacy
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "XHTML 1.0 átmeneti"
  syntax:
    content: Legacy
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceMode.Strict
  id: Strict
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Strict
  nameWithType: XhtmlConformanceMode.Strict
  fullName: System.Web.Configuration.XhtmlConformanceMode.Strict
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "XHTML 1.0 szigorú megfelelés"
  syntax:
    content: Strict
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Web.Configuration.XhtmlConformanceMode.Transitional
  id: Transitional
  parent: System.Web.Configuration.XhtmlConformanceMode
  langs:
  - csharp
  name: Transitional
  nameWithType: XhtmlConformanceMode.Transitional
  fullName: System.Web.Configuration.XhtmlConformanceMode.Transitional
  type: Field
  assemblies:
  - System.Web
  namespace: System.Web.Configuration
  summary: "Megjelenítés a érintő módosítások v1.1 megjelenítési viselkedésének megfelelési számos helyreállítja."
  syntax:
    content: Transitional
    return:
      type: System.Web.Configuration.XhtmlConformanceMode
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Web.Configuration.XhtmlConformanceMode.Legacy
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Legacy
  nameWithType: XhtmlConformanceMode.Legacy
  fullName: System.Web.Configuration.XhtmlConformanceMode.Legacy
- uid: System.Web.Configuration.XhtmlConformanceMode
  parent: System.Web.Configuration
  isExternal: false
  name: XhtmlConformanceMode
  nameWithType: XhtmlConformanceMode
  fullName: System.Web.Configuration.XhtmlConformanceMode
- uid: System.Web.Configuration.XhtmlConformanceMode.Strict
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Strict
  nameWithType: XhtmlConformanceMode.Strict
  fullName: System.Web.Configuration.XhtmlConformanceMode.Strict
- uid: System.Web.Configuration.XhtmlConformanceMode.Transitional
  parent: System.Web.Configuration.XhtmlConformanceMode
  isExternal: false
  name: Transitional
  nameWithType: XhtmlConformanceMode.Transitional
  fullName: System.Web.Configuration.XhtmlConformanceMode.Transitional
