### YamlMime:ManagedReference
items:
- uid: System.Configuration.ConfigurationElementCollectionType
  id: ConfigurationElementCollectionType
  children:
  - System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  - System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  - System.Configuration.ConfigurationElementCollectionType.BasicMap
  - System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  langs:
  - csharp
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
  type: Enum
  summary: "Adja meg a ConfigurationElementCollectionType objektum."
  remarks: "Ez az enumerálás tartalmaz minden lehetséges visszatérési értékei a <xref:System.Configuration.ConfigurationElementCollection.CollectionType%2A>tulajdonság.</xref:System.Configuration.ConfigurationElementCollection.CollectionType%2A> Segítségével a konfigurációs rendszer futásidőben megfelelően egyesítse a konfigurációs beállításokat. Ha egyéni osztály létrehozása, amely kiterjeszti a <xref:System.Configuration.ConfigurationElementCollection>.</xref:System.Configuration.ConfigurationElementCollection> is használja       Alapértelmezés szerint a típusú egy <xref:System.Configuration.ConfigurationElementCollection>objektum AddRemoveClearMap.</xref:System.Configuration.ConfigurationElementCollection> Ha egy BasicMap szükséges, bírálja felül a ConfigurationElementCollectionType tulajdonságot <xref:System.Configuration.ConfigurationElementCollection>.</xref:System.Configuration.ConfigurationElementCollection> bővítésekor"
  syntax:
    content: public enum ConfigurationElementCollectionType
  inheritance:
  - System.Enum
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  id: AddRemoveClearMap
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: AddRemoveClearMap
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMap
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Az alapértelmezett típusa <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref>. Az ilyen típusú gyűjtemények között a hierarchiában a konfigurációs fájlok egyesíthető elemek tartalmaznak. A hierarchián belül bármely adott szinten <xref uid=&quot;langword_csharp_add&quot; name=&quot;add&quot; href=&quot;&quot;> </xref>, <xref uid=&quot;langword_csharp_remove&quot; name=&quot;remove&quot; href=&quot;&quot;> </xref>, és <xref uid=&quot;langword_csharp_clear&quot; name=&quot;clear&quot; href=&quot;&quot;> </xref> irányelvek segítségével módosítsa a örökölt tulajdonságokat, és adja meg újakat."
  syntax:
    content: AddRemoveClearMap
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  id: AddRemoveClearMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: AddRemoveClearMapAlternate
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ugyanaz, mint a AddRemoveClearMap, azzal a különbséggel, hogy ilyen típusú hatására a <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref> objektum rendezéséhez tartalmát úgy, hogy az örökölt elemek utolsó szerepelnek."
  syntax:
    content: AddRemoveClearMapAlternate
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMap
  id: BasicMap
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: BasicMap
  nameWithType: ConfigurationElementCollectionType.BasicMap
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMap
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Az ilyen típusú gyűjtemények elemeit tartalmazza, amely azokat a szintre, és az összes alárendelt szint tartalmaznak. A gyermek szint nem módosítható egy ilyen típusú szülő elem által meghatározott tulajdonságait."
  syntax:
    content: BasicMap
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  id: BasicMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  langs:
  - csharp
  name: BasicMapAlternate
  nameWithType: ConfigurationElementCollectionType.BasicMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  type: Field
  assemblies:
  - System.Configuration
  namespace: System.Configuration
  summary: "Ugyanaz, mint a BasicMap, azzal a különbséggel, hogy ilyen típusú hatására a <xref href=&quot;System.Configuration.ConfigurationElementCollection&quot;> </xref> objektum tartalmának rendezése úgy, hogy az örökölt elemek utolsó szerepelnek."
  syntax:
    content: BasicMapAlternate
    return:
      type: System.Configuration.ConfigurationElementCollectionType
      description: "Fel kell venni a párbeszédpanelre."
  exceptions: []
  platform:
  - net462
references:
- uid: System.Enum
  isExternal: false
  name: System.Enum
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: AddRemoveClearMap
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMap
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMap
- uid: System.Configuration.ConfigurationElementCollectionType
  parent: System.Configuration
  isExternal: false
  name: ConfigurationElementCollectionType
  nameWithType: ConfigurationElementCollectionType
  fullName: System.Configuration.ConfigurationElementCollectionType
- uid: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: AddRemoveClearMapAlternate
  nameWithType: ConfigurationElementCollectionType.AddRemoveClearMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.AddRemoveClearMapAlternate
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMap
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: BasicMap
  nameWithType: ConfigurationElementCollectionType.BasicMap
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMap
- uid: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
  parent: System.Configuration.ConfigurationElementCollectionType
  isExternal: false
  name: BasicMapAlternate
  nameWithType: ConfigurationElementCollectionType.BasicMapAlternate
  fullName: System.Configuration.ConfigurationElementCollectionType.BasicMapAlternate
