### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  id: FileReferenceCollection
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Clear
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Count
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.FindTargetPath(System.String)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.GetEnumerator
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Item(System.Int32)
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Remove(Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference)
  langs:
  - csharp
  name: FileReferenceCollection
  nameWithType: FileReferenceCollection
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  type: Class
  summary: "Jegyzékfájl hivatkozások gyűjteményét képviseli."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class FileReferenceCollection : System.Collections.IEnumerable
  inheritance:
  - System.Object
  implements:
  - System.Collections.IEnumerable
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference)
  id: Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  langs:
  - csharp
  name: Add(FileReference)
  nameWithType: FileReferenceCollection.Add(FileReference)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(FileReference)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Hozzáadja a megadott fájl hivatkozás a gyűjteményhez."
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference Add (Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference file);
    parameters:
    - id: file
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
      description: "A megadott fájl hivatkozás hozzáadása."
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
      description: "A hozzáadott fájl hivatkozás objektum beállítása/beolvasása."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(System.String)
  id: Add(System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  langs:
  - csharp
  name: Add(String)
  nameWithType: FileReferenceCollection.Add(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(String)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Hozzáadja a megadott fájl hivatkozás a gyűjteményhez."
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference Add (string path);
    parameters:
    - id: path
      type: System.String
      description: "A megadott fájl hivatkozás hozzáadása elérési útját."
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
      description: "A hozzáadott fájl hivatkozás objektum beállítása/beolvasása."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Clear
  id: Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  langs:
  - csharp
  name: Clear()
  nameWithType: FileReferenceCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Clear()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Eltávolítja az összes objektum a gyűjteményből."
  syntax:
    content: public void Clear ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Clear*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Count
  id: Count
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  langs:
  - csharp
  name: Count
  nameWithType: FileReferenceCollection.Count
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Count
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "A gyűjteményben szereplő objektumokat számát adja vissza."
  syntax:
    content: public int Count { get; }
    return:
      type: System.Int32
      description: "a gyűjteményben található objektumok száma."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Count*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.FindTargetPath(System.String)
  id: FindTargetPath(System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  langs:
  - csharp
  name: FindTargetPath(String)
  nameWithType: FileReferenceCollection.FindTargetPath(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.FindTargetPath(String)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "A gyűjtemény úgy egy hivatkozást a megadott cél elérési út."
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference FindTargetPath (string targetPath);
    parameters:
    - id: targetPath
      type: System.String
      description: "A megadott cél elérési út."
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
      description: "A tényleges fájlra mutató hivatkozást ad vissza."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.FindTargetPath*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.GetEnumerator
  id: GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  langs:
  - csharp
  name: GetEnumerator()
  nameWithType: FileReferenceCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.GetEnumerator()
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Adja vissza, amely a gyűjtemény is iterációt számbevevőre."
  syntax:
    content: public System.Collections.IEnumerator GetEnumerator ();
    parameters: []
    return:
      type: System.Collections.IEnumerator
      description: "Egy <xref:System.Collections.IEnumerator>felület, amely a gyűjtemény is iterációt számbavevő képviselő.</xref:System.Collections.IEnumerator>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.GetEnumerator*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Item(System.Int32)
  id: Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  langs:
  - csharp
  name: Item(Int32)
  nameWithType: FileReferenceCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Item(Int32)
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "A megadott index az elem beolvasása."
  syntax:
    content: public Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference this[int index] { get; }
    parameters:
    - id: index
      type: System.Int32
      description: "A bejegyzés a beolvasandó nulla alapú indexét."
    return:
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
      description: "A fájl hivatkozás objektum beállítása/beolvasása."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Item*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Remove(Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference)
  id: Remove(Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  langs:
  - csharp
  name: Remove(FileReference)
  nameWithType: FileReferenceCollection.Remove(FileReference)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Remove(FileReference)
  type: Method
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Eltávolítja a megadott fájl hivatkozás a gyűjteményből."
  syntax:
    content: public void Remove (Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference file);
    parameters:
    - id: file
      type: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
      description: "A megadott fájl hivatkozás eltávolítása."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Remove*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Add(FileReference)
  nameWithType: FileReferenceCollection.Add(FileReference)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(FileReference)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  isExternal: false
  name: FileReference
  nameWithType: FileReference
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Add(String)
  nameWithType: FileReferenceCollection.Add(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Clear
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Clear()
  nameWithType: FileReferenceCollection.Clear()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Clear()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Count
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Count
  nameWithType: FileReferenceCollection.Count
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Count
- uid: System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.FindTargetPath(System.String)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: FindTargetPath(String)
  nameWithType: FileReferenceCollection.FindTargetPath(String)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.FindTargetPath(String)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.GetEnumerator
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: GetEnumerator()
  nameWithType: FileReferenceCollection.GetEnumerator()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.GetEnumerator()
- uid: System.Collections.IEnumerator
  parent: System.Collections
  isExternal: true
  name: IEnumerator
  nameWithType: IEnumerator
  fullName: System.Collections.IEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Item(System.Int32)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Item(Int32)
  nameWithType: FileReferenceCollection.Item(Int32)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Item(Int32)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Remove(Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReference)
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Remove(FileReference)
  nameWithType: FileReferenceCollection.Remove(FileReference)
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Remove(FileReference)
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Add*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Add
  nameWithType: FileReferenceCollection.Add
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Clear*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Clear
  nameWithType: FileReferenceCollection.Clear
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Count*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Count
  nameWithType: FileReferenceCollection.Count
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.FindTargetPath*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: FindTargetPath
  nameWithType: FileReferenceCollection.FindTargetPath
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.GetEnumerator*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: GetEnumerator
  nameWithType: FileReferenceCollection.GetEnumerator
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Item*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Item
  nameWithType: FileReferenceCollection.Item
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection.Remove*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.FileReferenceCollection
  isExternal: false
  name: Remove
  nameWithType: FileReferenceCollection.Remove
