### YamlMime:ManagedReference
items:
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  id: CompatibleFramework
  children:
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  - Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  langs:
  - csharp
  name: CompatibleFramework
  nameWithType: CompatibleFramework
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  type: Class
  summary: "Ismerteti, hogy az alkalmazás futtatható a .NET-keretrendszer verziója."
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(false)]

      public sealed class CompatibleFramework
  inheritance:
  - System.Object
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  id: '#ctor'
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: CompatibleFramework()
  nameWithType: CompatibleFramework.CompatibleFramework()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.CompatibleFramework()
  type: Constructor
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Egy új példányát inicializálja a <xref href=&quot;Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework&quot;> </xref> osztály."
  syntax:
    content: public CompatibleFramework ();
    parameters: []
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  id: Profile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "A profil a megfelelő .NET-keretrendszer jelöli."
  remarks: "A profil része a teljes .NET-keretrendszer. Például a [!INCLUDE[net_client_v35_long](~/add/includes/net-client-v35-long-md.md)] részhalmaza a [!INCLUDE[net_v35SP1_long](~/add/includes/net-v35sp1-long-md.md)], és a [!INCLUDE[net_client_v40_long](~/add/includes/net-client-v40-long-md.md)] részhalmaza a [!INCLUDE[net_v45](~/add/includes/ajax-current-ext-md.md)]. További információkért lásd: [.NET keretrendszer Ügyfélprofiljával](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: public string Profile { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>a.NET Framework profiljában képviselő objektum.</xref:System.String>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  id: SupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Lekérdezi vagy beállítja a keretrendszer támogatott futásidejű."
  syntax:
    content: public string SupportedRuntime { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>objektum, amely a megfelelő .NET-keretrendszer futásidejű verzióját jeleníti meg.</xref:System.String>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  id: Version
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: Version
  nameWithType: CompatibleFramework.Version
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Lekérdezi vagy beállítja a keretrendszer verzióját."
  syntax:
    content: public string Version { get; set; }
    return:
      type: System.String
      description: "A <xref:System.String>egy .NET-keretrendszer verzióját képviselő objektum.</xref:System.String>"
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  id: XmlProfile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlProfile
  nameWithType: CompatibleFramework.XmlProfile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Lekérdezi vagy beállítja a keretrendszer XML verzióját."
  syntax:
    content: public string XmlProfile { get; set; }
    return:
      type: System.String
      description: "XML-elemek képviselő tömböt a.NET Framework profiljában."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  id: XmlSupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlSupportedRuntime
  nameWithType: CompatibleFramework.XmlSupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Lekérdezi vagy beállítja a támogatott XML-futtatókörnyezet a keretrendszer."
  syntax:
    content: public string XmlSupportedRuntime { get; set; }
    return:
      type: System.String
      description: "XML-elemek képviselő tömböt a megfelelő .NET-keretrendszer futásidejű verzióját."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime*
  exceptions: []
  platform:
  - net462
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  id: XmlVersion
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  langs:
  - csharp
  name: XmlVersion
  nameWithType: CompatibleFramework.XmlVersion
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  type: Property
  assemblies:
  - Microsoft.Build.Tasks.v4.0
  namespace: Microsoft.Build.Tasks.Deployment.ManifestUtilities
  summary: "Lekérdezi vagy beállítja a keretrendszer verzióját."
  syntax:
    content: public string XmlVersion { get; set; }
    return:
      type: System.String
      description: "XML-elemek képviselő tömböt egy .NET-keretrendszer verzióját."
  overload: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Object
  isExternal: false
  name: System.Object
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: CompatibleFramework()
  nameWithType: CompatibleFramework.CompatibleFramework()
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.CompatibleFramework()
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Version
  nameWithType: CompatibleFramework.Version
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlProfile
  nameWithType: CompatibleFramework.XmlProfile
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlSupportedRuntime
  nameWithType: CompatibleFramework.XmlSupportedRuntime
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlVersion
  nameWithType: CompatibleFramework.XmlVersion
  fullName: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.#ctor*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: CompatibleFramework
  nameWithType: CompatibleFramework.CompatibleFramework
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Profile*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Profile
  nameWithType: CompatibleFramework.Profile
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.SupportedRuntime*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: SupportedRuntime
  nameWithType: CompatibleFramework.SupportedRuntime
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.Version*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: Version
  nameWithType: CompatibleFramework.Version
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlProfile*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlProfile
  nameWithType: CompatibleFramework.XmlProfile
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlSupportedRuntime*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlSupportedRuntime
  nameWithType: CompatibleFramework.XmlSupportedRuntime
- uid: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework.XmlVersion*
  parent: Microsoft.Build.Tasks.Deployment.ManifestUtilities.CompatibleFramework
  isExternal: false
  name: XmlVersion
  nameWithType: CompatibleFramework.XmlVersion
